### ISSUE TITLE
[Table] EnhancedTable在树场景下的问题

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#1001]
### tdesign-react 版本

0.36.1

### 重现链接

1. https://codesandbox.io/s/tdesign-react-demo-forked-5kzhe7?file=/src/demo.jsx:50-63

2. https://codesandbox.io/s/tdesign-react-demo-forked-tt5b3t

### 重现步骤

1.  EnhancedTable的树状渲染是否应该通过配置项选择是否开启？如示例1情况下，没有传tree，选择将会报错。数据里面有字段是数组 不一定代表当前就是树表格
2. 部分时候，如示例2选择按钮无法正常渲染

### 框架版本

React 16.x

**Comment by chaishi** [comment]
好奇，如果不是树形结构，使用 `EnhancedTable` 的场景是？

**Comment by chaishi** [comment]
> 部分时候，如示例2选择按钮无法正常渲染

这句话的问题没有看明白，点链接，也没看到哪里有明显的问题

**Comment by chaishi** [comment]
resolved in a49ac53a

已在树形结构结构中支持 非树状结构 的行选中，待发布

https://user-images.githubusercontent.com/11605702/177024326-7eadb093-865a-4a3f-a393-324674e48422.mov

**Comment by HQ-Lin** [comment]
0.36.2 fixed
