### ISSUE TITLE
[Tree] disableCheck 方法的参数 TreeNodeModel 没有传入 T 型

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#1005]
### tdesign-react 版本

0.36.1

### 重现步骤

disableCheck 麻烦把范型传入进去
![企业微信截图_e8846ab6-7e0c-4237-8fb1-81ba21bfe0f2](https://user-images.githubusercontent.com/29194619/176384211-157de4be-21fa-41cb-8005-3613defdf81b.png)
![企业微信截图_023ab05a-9eca-48af-b005-9705de153682](https://user-images.githubusercontent.com/29194619/176384232-da7daef8-3a04-4cd2-9df3-08133a431b62.png)
![企业微信截图_14500ecb-05f7-493b-ab87-a9f7d31389cc](https://user-images.githubusercontent.com/29194619/176384326-a6d0bec5-ad97-4ff5-a97f-ecd240b90b0c.png)

错误的结果：
![企业微信截图_d9e43a8a-98ef-4c94-b35c-2e32a343243c](https://user-images.githubusercontent.com/29194619/176384335-9151de27-2749-4c32-8c16-13b0a77bf860.png)

正确的结果：
![企业微信截图_8d1225f8-9a52-426d-8eb9-82417d70a7b3](https://user-images.githubusercontent.com/29194619/176384344-cfa59353-33cc-4176-8009-ca25237d191c.png)

**Comment by HQ-Lin** [comment]
0.36.2 fixed
