### ISSUE TITLE
[Table] Table 的rowkey应该支持函数

### ISSUE THREAD

**Issue by zFitness** [Tencent/tdesign-react#1022]
### 这个功能解决了什么问题

数据没有唯一的key值

### 你建议的方案是什么

支持 rowKey 为一个函数

**Comment by chaishi** [comment]
不支持函数。

如果数据没有唯一的 key 值，可以设置  `data = data.map((item, index)=> ({ ...item, id: item.a + item.b + index }))` 来设置 唯一 key。一行代码就解决问题。

**Comment by zFitness** [comment]
暂时先这么搞吧，但是得提供一个必填属性，让用户手动制定这个key的名字例如id。
