### ISSUE TITLE
[Table] 官网固定列失效（文档问题，组件本身正常）Space 组件引入的问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#1031]
### tdesign-react 版本

0.36.1

### 重现步骤

0.35.x 正常

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/11605702/177047403-ad465f75-2e49-420f-a29f-1d4e666c056a.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1030

**Comment by HQ-Lin** [comment]
0.36.2 fixed
