### ISSUE TITLE
[upload] 添加disabled属性，设置默认图片，图片能够被删除

### ISSUE THREAD

**Issue by zhushibo** [Tencent/tdesign-react#1034]
### tdesign-react 版本

0.36。1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-u4x46b?file=/src/demo.jsx

### 重现步骤

设置组件熟悉 disabled
hover Upload组件，点击删除

### 期望结果

不显示删除图标

### 实际结果

显示删除，且能被电击

### 框架版本

react(17.0.2)

### 浏览器版本

Chrome 100

### 系统版本

MacOS

**Comment by HQ-Lin** [comment]
0.36.2 fixed
