### ISSUE TITLE
[steps] 文案长短不一至，导致步骤条的横线长短不一致

### ISSUE THREAD

**Issue by zhushibo** [Tencent/tdesign-react#1035]
### tdesign-react 版本

0.36.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-21hct2?file=/src/demo.jsx

### 重现步骤

步骤条给一个文案长一点的

### 期望结果

横线被均分

### 实际结果

长短不一至

### 框架版本

react(17.0.2)

### 浏览器版本

Chrome 100

### 系统版本

MacOS

**Comment by HQ-Lin** [comment]
这里已经是自适应展示每个 stepItem了，均等分不管是按照最长的来分还是按照最短的来分都会有问题
按照最长的那么短的item就会留空白，按照最短的那么最长的就会换行，如果一定要均等分你可以手动控制每个title的长度保持一致
