### ISSUE TITLE
[select] 多选时一直可筛选，不可控制；有选项存在时样式也有问题

### ISSUE THREAD

**Issue by zhaosqgit** [Tencent/tdesign-react#1038]
### tdesign-react 版本

0.36.1，0.36.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-yr7rjq?file=/src/demo.jsx

### 重现步骤

1、multiple为true时，一直可筛选，filterable不起作用；
2、使用valueDisplay时自定义已选择选项面板时，有多个选择项超出选择器长度时，样式存在问题；

### 期望结果

以上问题修复

### 框架版本

react

**Comment by uyarn** [comment]
fixed in 0.36.3
