### ISSUE TITLE
[Collapse] 自定义Panel组件，无法正常渲染

### ISSUE THREAD

**Issue by lazybonee** [Tencent/tdesign-react#1041]
### tdesign-react 版本

0.36.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-gjonft?file=/src/demo.jsx

### 期望结果

![image](https://user-images.githubusercontent.com/11715201/177159396-c2e1144a-58f7-45e0-b72a-423b1982ad83.png)
【自定义Panel组件函数调用】与【直接编写Panel】都应该正常渲染出折叠面板

### 实际结果

【自定义Panel组件函数调用】无法渲染出折叠面板，并且渲染函数并未执行
console语句没有打印

### 框架版本

React(17.0.2)

### 浏览器版本

Chorme(102.0.5005.115)

### 系统版本

MacOs

**Comment by southorange1228** [comment]
什么场景需要自定义`Panel`组件呢？按理说都是要被`Collapse.Panel`包裹一层 @lazybonee

**Comment by HQ-Lin** [comment]
Collapse 在渲染子节点的时候会过滤非 panel 元素，总不能塞个table也要渲染出来吧，自定义内容完全可以在panel里面渲染，确实想不到什么场景需要自定义组件里面再去渲染panel

**Comment by haishancai** [comment]
自定义组件建议改成这样https://codesandbox.io/s/tdesign-react-demo-forked-uv6gd6?file=/src/demo.jsx

**Comment by lazybonee** [comment]
ok～了解，感觉这样写有点限制，如果能识别自定义组件返回的是Collapse.Panel实例就更智能一点

> 自定义组件建议改成这样https://codesandbox.io/s/tdesign-react-demo-forked-uv6gd6?file=/src/demo.jsx
