### ISSUE TITLE
[table] 可编辑功能的官方例子中，清除 select 会报错白屏

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#1043]
### tdesign-react 版本

0.36.2

### 重现链接

https://tdesign.tencent.com/react/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

点击 select 的 x 号清除时白屏

**Comment by chaishi** [comment]
我晚上看下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1046

**Comment by HQ-Lin** [comment]
0.36.4 fixed
