### ISSUE TITLE
[Space] 文档类型错误

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#1049]
### tdesign-react 版本

0.36.1

### 重现步骤

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/32590310/177539895-0fbcbc84-6429-453b-a4ce-1474c460fc6c.png">

不应该有`SpaceSize[]`类型？

**Comment by HQ-Lin** [comment]
这里没问题的，size支持传入数组，数组是可以控制横向和纵向的间距

**Comment by southorange1228** [comment]
了解...是我理解错误了
