### ISSUE TITLE
[DialogPlugin] visible 与 descroyOnClose 不生效

### ISSUE THREAD

**Issue by jsonz1993** [Tencent/tdesign-react#1052]
### tdesign-react 版本

0.36.3

### 重现链接

https://stackblitz.com/edit/react-fcsekz?file=src/demo.jsx

### 重现步骤

点击create按钮，输入信息，隐藏之后重新展示，数据丢失。

### 期望结果

可以控制 visible 与 destroy

### 框架版本

React(18.x)

**Comment by HQ-Lin** [comment]
你是希望弹窗是单例模式吧，插件模式下弹窗没办法做成单例模式，每次创建都是新的dom关闭就销毁，希望保持一个dom那就自己定义 Dialog 在下面控制visible

**Comment by jsonz1993** [comment]
所以插件模式，是一创建必定会展示 && 一关闭就销毁是吗，不能配置

**Comment by HQ-Lin** [comment]
目前不支持，一般插件模式就是比较快捷的使用场景，如果还要保留上一次的内容变化为什么不自己写dialog维护呢

**Comment by jsonz1993** [comment]
那我自己业务封装个函数式调用吧，不过建议 DialogPlugin Type 更新下，避免误导
