### ISSUE TITLE
[Radio] 样式问题

### ISSUE THREAD

**Issue by bemzhao** [Tencent/tdesign-react#1054]
### tdesign-react 版本

0.36.3

### 重现链接

https://tdesign.tencent.com/react/components/radio#%E4%B8%8D%E5%90%8C%E5%B0%BA%E5%AF%B8%E7%9A%84%E6%8C%89%E9%92%AE%E5%8D%95%E9%80%89%E6%A1%86

### 重现步骤

文档上放大看可以看到问题

<img width="2180" alt="image" src="https://user-images.githubusercontent.com/27409590/177767303-13838df3-25c2-4990-a789-b8b7cb3f8616.png">

### 期望结果

.t-radio-group__outline 下的 Radio 选中状态看起来和伪元素没什么关系，是不是没什么存在的必要

**Comment by bemzhao** [comment]
看起来是多余的样式，本地开发的时候去掉了看起来也没有影响到其他

![image](https://user-images.githubusercontent.com/27409590/177798627-fb4219a7-82fd-4964-9ee1-fea99e755514.png)

![image](https://user-images.githubusercontent.com/27409590/177799001-04580ee5-7f5e-43a4-91a1-7b4facea5e61.png)

顺便请教一下，我使用的是 sourcetree，是不是在 _common 下提交了之后还需要到主仓库去再提交一次呢？

![image](https://user-images.githubusercontent.com/27409590/177806429-4d1e4120-2480-4a35-8e3e-3f614dc51c86.png)

**Comment by bemzhao** [comment]
提了个 PR：https://github.com/Tencent/tdesign-react/pull/1055

之前没有用过子仓库也没有贡献过，如果有什么不正确的地方希望可以指出，感谢

**Comment by HQ-Lin** [comment]
我看看，这里确实样式有点问题

**Comment by HQ-Lin** [comment]
> 提了个 PR：#1055
> 
> 之前没有用过子仓库也没有贡献过，如果有什么不正确的地方希望可以指出，感谢

子仓库对于主仓库来说就是一个存放hash的文件夹，要修改子仓库的代码你得去子仓库下面提交pr，你就当成两个git仓库，代码记录都是隔离的就好了

**Comment by HQ-Lin** [comment]
> 看起来是多余的样式，本地开发的时候去掉了看起来也没有影响到其他
> 
> ![image](https://user-images.githubusercontent.com/27409590/177798627-fb4219a7-82fd-4964-9ee1-fea99e755514.png)
> 
> ![image](https://user-images.githubusercontent.com/27409590/177799001-04580ee5-7f5e-43a4-91a1-7b4facea5e61.png)
> 
> 顺便请教一下，我使用的是 sourcetree，是不是在 _common 下提交了之后还需要到主仓库去再提交一次呢？
> 
> ![image](https://user-images.githubusercontent.com/27409590/177806429-4d1e4120-2480-4a35-8e3e-3f614dc51c86.png)

这里是后来加上的样式，主要是处理换行的时候缺少了左侧的竖线，但是漏了最后一个子节点的圆角问题，我处理下吧

**Comment by HQ-Lin** [comment]
这个我来改吧，之前应该是没改好
https://github.com/Tencent/tdesign-common/pull/628

**Comment by bemzhao** [comment]
> > 提了个 PR：#1055
> > 之前没有用过子仓库也没有贡献过，如果有什么不正确的地方希望可以指出，感谢
> 
> 子仓库对于主仓库来说就是一个存放hash的文件夹，要修改子仓库的代码你得去子仓库下面提交pr，你就当成两个git仓库，代码记录都是隔离的就好了

👌 明白了，我自己建个仓库试试

**Comment by HQ-Lin** [comment]
0.36.4 fixed
