### ISSUE TITLE
[Button] content为空的时候icon不居中

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1060]
### tdesign-react 版本

0.36.3

### 重现链接

https://rhvtaz--run.stackblitz.io

### 重现步骤

![2](https://user-images.githubusercontent.com/108825798/178104329-14a11d53-9d95-495b-a32d-21eaf812fbdd.png)

### 期望结果

在按钮content为空的时候icon自动居中（代码里不在出现content的span标签）

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

**Comment by HQ-Lin** [comment]
确实不该表现成这样，我优化下

**Comment by HQ-Lin** [comment]
0.36.4 fixed
