### ISSUE TITLE
[Tree] transition animation  数据展示切换存在体验问题

### ISSUE THREAD

**Issue by suyingda** [Tencent/tdesign-react#1065]
### 你建议的方案是什么
API: transition 状态是默认开启 ，自定义关闭后数据展示会闪烁一下
transition | Boolean | false | 节点展开折叠时默认不使用过渡动画
https://user-images.githubusercontent.com/25656537/178192252-c4da6537-173e-43dd-af88-1d8741f7c6dc.mov

**Comment by CodingOnStar** [comment]
能给个在线demo的地址吗

> ### 你建议的方案是什么
> API: transition 状态是默认开启 ，自定义关闭后数据展示会闪烁一下 transition | Boolean | false | 节点展开折叠时默认不使用过渡动画 https://user-images.githubusercontent.com/25656537/178192252-c4da6537-173e-43dd-af88-1d8741f7c6dc.mov
