### ISSUE TITLE
[Form 校验] 支持根据 trigger 来定义特殊的校验规则

### ISSUE THREAD

**Issue by feibinyang** [Tencent/tdesign-react#1068]
### 这个功能解决了什么问题

现在的表单校验只支持 `change/blur` 两种 trigger，有些场景下不满足需求。比如手机号码校验，产品期望的是没输入到 11 位数字时，不校验报错信息（但是 `submit` 的话还是要校验），只有输入非数字或者超过 11 位时才实时显示校验信息。这个时候好像没办法实现，如果在 rule 里直接写这个校验逻辑的话，那 `submit` 时会校验不对。

我这边想的是如果在 rule 校验函数参数里增加 `trigger` 的话，校验函数可以根据 `trigger` 来源不同写不同的校验逻辑。

### 你建议的方案是什么

期望在 rule 校验函数里增加参数，把当前触发校验的 `trigger` 来源传给函数，函数可以根据 `trigger` 不同写不同的校验逻辑。

**Comment by chaishi** [comment]
OK
