### ISSUE TITLE
官网组件展示页，面包屑相关问题

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#107]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
[breadcrumb doc](https://tdesign.tencent.com/react/components/breadcrumb) 基础面包屑示例文案错误，「页面2」和「页面3」有多次重复
不知道这个重复的文字算不算有意而为之，如果我理解错的话，烦请关闭这个 issue。多谢！

**Additional context**
![image](https://user-images.githubusercontent.com/43896664/147535585-fb2282a9-0ef7-4622-900a-b8024cc6faf1.png)

**Comment by vision-yip** [comment]
应该是故意为之的, 目的是展示在不同maxItemWidth的展示方式, 只是150跟160的区别不大, 觉得可以调整下

**Comment by Yilun-Sun** [comment]
![image](https://user-images.githubusercontent.com/43896664/147545429-91830edc-a9f9-4fc1-b720-ec31debb3bf3.png)

BreadcrumbItems Prop Typo

**Comment by Yilun-Sun** [comment]
> **Describe Framework**
> 
> * [x]  tdesign-react
> 
> **Describe Environment**
> 
> Add browser version here
> 
> **Describe the bug** [breadcrumb doc](https://tdesign.tencent.com/react/components/breadcrumb) 基础面包屑示例文案错误，「页面2」和「页面3」有多次重复 不知道这个重复的文字算不算有意而为之，如果我理解错的话，烦请关闭这个 issue。多谢！
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/43896664/147535585-fb2282a9-0ef7-4622-900a-b8024cc6faf1.png)

经确认，这个不是文案错误。但是这么写并不清晰，准备拆分对最大宽度的展示，新增 `width.jsx` 来说明。在 `base.jsx` 中去掉所有和最大宽度相关参数，变为最基础实现。

**Comment by Athenaqin** [comment]
<img width="1149" alt="截屏2021-12-28 下午5 18 24" src="https://user-images.githubusercontent.com/88708041/147550500-359a4776-5477-47b4-92e4-99a6a46d48e8.png">

**Comment by Athenaqin** [comment]
<img width="1149" alt="截屏2021-12-28 下午5 18 24" src="https://user-images.githubusercontent.com/88708041/147550577-1bd5f147-bce6-4d28-a498-9d301be22c73.png">

Vue的文案内容是想要表达的效果，React的文案正在更换进行中，很快就会同步刷新

**Comment by Yilun-Sun** [comment]
非 `options` 模式下，`maxItemWidth` 没有传给子组件 ``

**Comment by Yilun-Sun** [comment]
`option` -> `options`

**Comment by Yilun-Sun** [comment]
`maxWith` typo
