### ISSUE TITLE
[form] react18下的重复渲染

### ISSUE THREAD

**Issue by nieoding** [Tencent/tdesign-react#1072]
### tdesign-react 版本

latest

### 重现步骤

form的validate在react18的strictmode模式下，初始化的时候就会触发验证。
例如： 表现出来最简单的登录页面，页面打开就显示“请输入用户名”，“请输入密码”

### 期望结果

目前临时是把strictmode关闭，但不是长久之计

### 框架版本

react18

**Comment by HQ-Lin** [comment]
因为 React 18在development + strict mode 下就是让useEffect执行了两次，导致了我没办法区分到底组件初始化完成了没有

**Comment by HQ-Lin** [comment]
这个问题很早也有人反馈过了 #850

**Comment by nieoding** [comment]
有可能tdesign适配strictmode不？

**Comment by HQ-Lin** [comment]
> 有可能tdesign适配strictmode不？

我看看能不能调整下逻辑不依赖于初始化判断吧，应该可以做到

**Comment by HQ-Lin** [comment]
统一到这里讨论吧 https://github.com/Tencent/tdesign-react/issues/850
