### ISSUE TITLE
[MessagePlugin] React 18 会报错

### ISSUE THREAD

**Issue by JX-Zhuang** [Tencent/tdesign-react#1074]
### tdesign-react 版本

0.36.4

### 重现步骤

```
import { MessagePlugin } from 'tdesign-react';
MessagePlugin.error('error')
```

### 期望结果

控制台不报错

### 实际结果

![image](https://user-images.githubusercontent.com/8744030/178459981-d70ae2c2-3f66-4d4a-9e21-21b620848407.png)

### 框架版本

React 18.0.15

**Comment by HQ-Lin** [comment]
duplicate https://github.com/Tencent/tdesign-react/issues/952
