### ISSUE TITLE
[ColorPicker ] 渐变色选择器 点击第二个颜色点没有反应

### ISSUE THREAD

**Issue by 544751779** [Tencent/tdesign-react#1078]
### tdesign-react 版本

last

### 重现链接

https://tdesign.tencent.com/react/components/color-picker

**Comment by insekkei** [comment]
「点击第二个颜色」指的是渐变模式下最上面那个滑杆上的圆点吗？ @544751779

**Comment by 544751779** [comment]
> 「点击第二个颜色那个」指的是颜色模式下最那个滑杆上的圆点吗？@544751779

是的 是滑竿上的第二个点 无法点击设置颜色 vue版本是可以的

**Comment by insekkei** [comment]
ok，我看看

**Comment by HQ-Lin** [comment]
0.37.0 fixed
