### ISSUE TITLE
[table] 编辑表格单元格后，使用enter键回车退出编辑状态时，没有触发单元格的column.edit.onEdited 事件

### ISSUE THREAD

**Issue by zhuchao666** [Tencent/tdesign-react#1084]
### tdesign-react 版本

0.36.4

### 重现链接

https://stackblitz.com/edit/react-vsxz6p?file=src%2Fdemo.jsx 

### 重现步骤

编辑单元格后按回车键退出编辑状态

### 期望结果

能够正常触发onEdited事件

### 实际结果

没有触发onEdited事件

### 框架版本

React（17.0.2）

### 浏览器版本

103.0.5060.114

### 系统版本

MacOS（11.4）

### Node版本

node V16.14.0

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1108

**Comment by HQ-Lin** [comment]
0.37.0 fixed
