### ISSUE TITLE
[Watermark]  子组件高度乱了

### ISSUE THREAD

**Issue by xiangyouyu** [Tencent/tdesign-react#1085]
### tdesign 版本

tdesign-react:0.36.3

### 重现步骤

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/73029343/178141175-882f7ef4-3edb-42b4-b023-ada37eb18163.png">

### 期望结果

高度正常

### 实际结果

高速正常

### 框架版本

react

**Comment by carolin913** [comment]
<img width="1158" alt="wecom-temp-5c999febe88c1a5743d4383280317938" src="https://user-images.githubusercontent.com/2638568/178695510-4dca0220-a8e4-486d-8eb7-6c71dcb60bbd.png">
这个需要改一下starter layout这里的样式

**Comment by uyarn** [comment]
@xiangyouyu 麻烦参考一下回复改动 如果用水印的话
