### ISSUE TITLE
[Form] Form 没有initialData 属性

### ISSUE THREAD

**Issue by genyuMPj** [Tencent/tdesign-react#1087]
### 这个功能解决了什么问题

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/50562327/178711576-dc77a7e2-29d9-4a81-bf38-57509db979ec.png">
文档中，写了formlist 可以指定initialData，如果与form 中的initialData 冲突，则以form为准。但是form props 中并没有定义 initialData 属性，只有formItem 中可以对item 指定初始值。 因此，这里是文档描述有问题，还是form 的initialData 属性暂时没加上，后续会加？

### 你建议的方案是什么

1、 给form提供整个表单的initialData 属性 2、若没有这个计划，则修改组件文档，容易引起歧义。

**Comment by HQ-Lin** [comment]
这里应该是 FormItem😂，我改下

**Comment by genyuMPj** [comment]
> 这里应该是 FormItem😂，我改下

但其实，form 的initialData 也是有这个使用场景的
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/50562327/178715295-63ddfdf6-cf82-41f5-9542-cec990cc8c9a.png">
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/50562327/178715434-8e6811a6-3b80-467d-9799-1a6c6cdcdae4.png">
参考antd4 的设计。

**Comment by HQ-Lin** [comment]
emm 我反而觉得就近原则是比较合理的，哪个属性具体实际生效的地方更近，说明用户设置成本越高，更应该是用户真正想要的数据，全局配置api的逻辑也是这么定义的，全局配置文件始终比不上组件设置的props，当然这里只要自圆其说谁优先级高都是可以。
不过这里并没有实现 form 的 initialData 算是遗漏把，但好像没什么人反馈，大家似乎都能接受 formItem 设置的样子

**Comment by HQ-Lin** [comment]
> > > 这里应该是 FormItem😂，我改下
> > 
> > 
> > 但其实，form 的initialData 也是有这个使用场景的 <img alt="image" width="1339" src="https://user-images.githubusercontent.com/50562327/178715295-63ddfdf6-cf82-41f5-9542-cec990cc8c9a.png"> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/50562327/178715434-8e6811a6-3b80-467d-9799-1a6c6cdcdae4.png"> 参考antd4 的设计。
> 
> antd4 其实form.list 和item以及form 本身都有intialValue 或者intialValues 的属性， 然后优先级是： form > form.list > form.item.
> 
> 我想表达一下我认为的使用场景以及这里的优先级逻辑哈： 1、 form 里面的initialData 可以用于，异步请求后或其他场景下，给整个表单赋予初始值。用于，用户在修改表单的场景下，需要点击重置恢复表单值为初始值。这个时候，只依赖于formitem 的初始值，就不太灵活，需要给每个item 都定义初始值。 2、 优先级

不过你说的第一点也有道理，都让用户在 formItem 设置当表单项多的时候某些场景也不方便，一个地方统一设置会快捷很多，我找个时间补一下吧

**Comment by genyuMPj** [comment]
> emm 我反而觉得就近原则是比较合理的，哪个属性具体实际生效的地方更近，说明用户设置成本越高，更应该是用户真正想要的数据，全局配置api的逻辑也是这么定义的，全局配置文件始终比不上组件设置的props，当然这里只要自圆其说谁优先级高都是可以。 不过这里并没有实现 form 的 initialData 算是遗漏把，但好像没什么人反馈，大家似乎都能接受 formItem 设置的样子

是的，一般情况下，都是就近原则的。但是antd 的 逻辑是反的，我也能理解antd 反着设计的目的，就是认为用户可能要修改initialData 时，使用form 更方便修改。不过就近原则也可以，虽然不能用form 的initialData 覆盖item 的，但也无伤大雅，若需要批量去设置或者修改initialData ，就可以统一使用 form 的intialData 。

**Comment by genyuMPj** [comment]
> > > > 这里应该是 FormItem😂，我改下
> > > 
> > > 
> > > 但其实，form 的initialData 也是有这个使用场景的 <img alt="image" width="1339" src="https://user-images.githubusercontent.com/50562327/178715295-63ddfdf6-cf82-41f5-9542-cec990cc8c9a.png"> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/50562327/178715434-8e6811a6-3b80-467d-9799-1a6c6cdcdae4.png"> 参考antd4 的设计。
> > 
> > 
> > antd4 其实form.list 和item以及form 本身都有intialValue 或者intialValues 的属性， 然后优先级是： form > form.list > form.item.
> > 我想表达一下我认为的使用场景以及这里的优先级逻辑哈： 1、 form 里面的initialData 可以用于，异步请求后或其他场景下，给整个表单赋予初始值。用于，用户在修改表单的场景下，需要点击重置恢复表单值为初始值。这个时候，只依赖于formitem 的初始值，就不太灵活，需要给每个item 都定义初始值。 2、 优先级
> 
> 不过你说的第一点也有道理，都让用户在 formItem 设置当表单项多的时候某些场景也不方便，一个地方统一设置会快捷很多，我找个时间补一下吧

给力~ 补了会更好，我们目前业务中，迁移使用tdesign form，感觉没有form.initialValues 还是挺不方便的。目前暂时是自己封装了一层实现这个能力，官方支持会更好~

**Comment by genyuMPj** [comment]
> > > > 这里应该是 FormItem😂，我改下
> > > 
> > > 
> > > 但其实，form 的initialData 也是有这个使用场景的 <img alt="image" width="1339" src="https://user-images.githubusercontent.com/50562327/178715295-63ddfdf6-cf82-41f5-9542-cec990cc8c9a.png"> <img alt="image" width="1335" src="https://user-images.githubusercontent.com/50562327/178715434-8e6811a6-3b80-467d-9799-1a6c6cdcdae4.png"> 参考antd4 的设计。
> > 
> > 
> > antd4 其实form.list 和item以及form 本身都有intialValue 或者intialValues 的属性， 然后优先级是： form > form.list > form.item.
> > 我想表达一下我认为的使用场景以及这里的优先级逻辑哈： 1、 form 里面的initialData 可以用于，异步请求后或其他场景下，给整个表单赋予初始值。用于，用户在修改表单的场景下，需要点击重置恢复表单值为初始值。这个时候，只依赖于formitem 的初始值，就不太灵活，需要给每个item 都定义初始值。 2、 优先级
> 
> 不过你说的第一点也有道理，都让用户在 formItem 设置当表单项多的时候某些场景也不方便，一个地方统一设置会快捷很多，我找个时间补一下吧

请问这个大概什么时候能加上呢？

**Comment by HQ-Lin** [comment]
> 

这周吧，还是有一点复杂的，主要在嵌套数据结构场景处理起来比较麻烦

**Comment by HQ-Lin** [comment]
0.40.5 fixed
