### ISSUE TITLE
[Dialog] Cascader 在 dialog 中，placeholder 不显示

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#1091]
### tdesign-react 版本

0.36.4

### 重现步骤

<img width="977" alt="企业微信截图_71603c52-8c6e-4d9c-b454-3902c1ec9587" src="https://user-images.githubusercontent.com/29194619/178744176-89e3a6cc-ed94-4c65-ba61-35cee083845b.png">

**Comment by HQ-Lin** [comment]
大哥顺便给个codesanbox 链接啊。

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/react-tz4wpn?file=src%2Fdemo.jsx
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/24469546/178927246-e1f8737d-c968-4ba8-a64d-ec2e7be3361b.png">
没毛病啊

**Comment by PBK-B** [comment]
@HQ-Lin 目前看起来是受 `multiple` 属性影响

**Comment by HQ-Lin** [comment]
0.38 fixed
