### ISSUE TITLE
[Space] direction='vertical' 时候，.t-space 使用了错误的 inline-flex

### ISSUE THREAD

**Issue by libo1106** [Tencent/tdesign-react#1098]
### tdesign-react 版本

0.36.4

### 重现步骤

```tsx
<div>
<Space direction='vertical'>
  <div style={{backgroundColor: 'red'}}>红</div>
  <div style={{backgroundColor: 'yellow'}}>黄</div>
  <div style={{backgroundColor: 'green'}}>黄</div>
</Space>
</div>
```

![image](https://user-images.githubusercontent.com/793007/178984195-c751d26e-c7c4-430c-a960-8f1a3f0ac12c.png)

### 期望结果

`direction='vertical'` 的时候，Space 内每个元素的表现依旧是如 Block 一样

### 实际结果

div 不再是 Block 元素撑满宽度

### 框架版本

React(17)

### 浏览器版本

Chrome(103)

**Comment by HQ-Lin** [comment]
看起来 flex 布局可能更符合大多数人的预期，之前使用inline-flex 布局是有考虑到用户使用多个 space 并排但又不想换行，但现在感觉期望换行才是多数

**Comment by HQ-Lin** [comment]
这里还是手动改一下 style 吧
```
<Space direction='vertical' style={{ display: 'flex' }}>
  <div style={{backgroundColor: 'red'}}>红</div>
  <div style={{backgroundColor: 'yellow'}}>黄</div>
  <div style={{backgroundColor: 'green'}}>黄</div>
</Space>
```
默认使用 inline-flex 有个很重要的点是不希望破坏 space 的兄弟行内节点的展示，改成flex就强制占据一行了，需要手动修改成 inline-flex才能并排，更改成本跟目前的行内改块级是一样的都不麻烦
