### ISSUE TITLE
[Popconfirm] children 传入没有 ref 的函数组件时报错Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#1100]
### tdesign-react 版本

0.35.1

### 重现步骤

popConfirm 组件 children 使用没有 ref 的函数组件时报错  Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### 期望结果

期望能够做个兼容，支持非 ref 组件使用

### 框架版本

react@17.0.2

**Comment by HQ-Lin** [comment]
popup 依赖ref获取dom元素导致的，这周重构一下换一种实现思路吧，很多function component 并没有处理 forwardRef 逻辑

**Comment by fangxiezhen** [comment]
> popup 依赖ref获取dom元素导致的，这周重构一下换一种实现思路吧，很多function component 并没有处理 forwardRef 逻辑

是的，必须依赖 ref 这种方式实在太过不优雅，期待优化

**Comment by HQ-Lin** [comment]
0.40.0 fixed
