### ISSUE TITLE
[Select] 多选时，选中值下拉菜单可配置是否收起

### ISSUE THREAD

**Issue by genyuMPj** [Tencent/tdesign-react#1102]
### 这个功能解决了什么问题

[Select] 多选时，选中值下拉菜单可配置是否收起， 如题，目前select 在多选时，下拉选框不会收起，也不支持配置，实际使用中，有些情况我们是期望下拉选框能在选择后收起。
希望可以能提供可配置项或者其他实现方式，方便用户自定义多选时，选中值后，下拉面板是否收起

### 你建议的方案是什么

[Select] 多选时，选中值下拉菜单可配置是否收起， 如题，目前select 在多选时，下拉选框不会收起，也不支持配置，实际使用中，有些情况我们是期望下拉选框能在选择后收起。
希望可以能提供可配置项或者其他实现方式，方便用户自定义多选时，选中值后，下拉面板是否收起

**Comment by HQ-Lin** [comment]
你这个场景属于定制select的默认行为了，也是可以手动控制select 的popupVisible的。但目前popupVisible 实现的有点问题，我让开发者跟进下
https://stackblitz.com/edit/react-5bbt4n?file=src%2Fdemo.jsx

**Comment by southorange1228** [comment]
关联PR中同步修复 受控popupVisible问题

**Comment by southorange1228** [comment]
https://stackblitz.com/edit/react-5bbt4n-ap1anw?file=src%2Fdemo.jsx
patch版本发布之后。可参考示例代码 走受控逻辑实现

**Comment by HQ-Lin** [comment]
0.38.0 已修复，参考这个demo
https://stackblitz.com/edit/react-5bbt4n-lcb5ij?file=src%2Fdemo.jsx
