### ISSUE TITLE
[Radio] Argument of type 'RadioValue' is not assignable to parameter of type 'SetStateAction<string>'

### ISSUE THREAD

**Issue by NWYLZW** [Tencent/tdesign-react#1104]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-hwf05v?file=/src/demo.tsx

### 重现步骤
使用 tsx
typescript 会提示类型不匹配

### 期望结果
应该匹配到对应的类型

### 实际结果
![0F2F5D46-C0FF-4904-A467-2D5799659BFF](https://user-images.githubusercontent.com/51358815/179189267-92a07fba-104d-4d3b-8a34-f76aab3b4e61.png)

| Environment | Info |
|---|---|
| 相关版本 | 0.36.4 |
| 框架版本 / 基础库版本 | React(16.13.1) |
| 系统、浏览器 | Chrome(103.0.5060.114) |
| Node版本 |  |

**Comment by chaishi** [comment]
#### 可以先这样处理，不会报错了

<img width="859" alt="image" src="https://user-images.githubusercontent.com/11605702/179336312-d423d7ff-9c81-43c6-932b-c76b3fac0f44.png">

**Comment by NWYLZW** [comment]
> #### 可以这样处理，不会报错了
> 组件是什么类型，最好变量就是什么类型
> 
> 我们缺少一个范型，用于指定 RadioValue 的具体类型，后面可以补一下
> 
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/11605702/179336312-d423d7ff-9c81-43c6-932b-c76b3fac0f44.png">



> #### 可以这样处理，不会报错了
> 组件是什么类型，最好变量就是什么类型
> 
> 我们缺少一个范型，用于指定 RadioValue 的具体类型，后面可以补一下
> 
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/11605702/179336312-d423d7ff-9c81-43c6-932b-c76b3fac0f44.png">

是，其实我倒是知道这样子修复
提出 issue 的目的其实是想要一个好一点的泛型支持

除了上面的修复方式，其实还有一种就是 onChange 的时候 String(value)
