### ISSUE TITLE
[Table] column.edit.props 透传 panelBottomContent 

### ISSUE THREAD

**Issue by liuxiang53** [Tencent/tdesign-react#1109]
### tdesign-react 版本

0.36.4

### 重现链接

https://codesandbox.io/s/90bg3i?file=/src/demo.jsx

### 重现步骤

```javascript
// 行号 58
edit: {
  component: Select,
  // props, 透传全部属性到 Select 组件
  props: {
    clearable: true,
    options: [
      { label: 'Vue', value: 'Vue' },
      { label: 'React', value: 'React' },
      { label: 'Miniprogram', value: 'Miniprogram' },
      { label: 'Flutter', value: 'Flutter' },
    ],
  panelBottomContent:<div>123</div>
  },
}
```

### 期望结果

123

### 实际结果

TypeError
Converting circular structure to JSON
    --> starting at object with constructor 'FiberRootNode'
    |     property 'containerInfo' -> object with constructor 'HTMLDivElement'
    |     property '__reactContainer$iahu9n5flqq' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle

### 框架版本

React

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1108

**Comment by uyarn** [comment]
0.37.0 fixed
