### ISSUE TITLE
[Table] 对数据的范型支持

### ISSUE THREAD

**Issue by NWYLZW** [Tencent/tdesign-react#1110]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-iweby5?file=/src/demo.tsx

### 重现步骤
* 使用 Table 组件的 columns 属性
* 设置其元素的单个属性的 cell
* 在其中调用 row 参数的属性配置，会发现所有的属性都丢失了

### 期望结果
应当推断出对应 data 中的类型，再传递给 cell 函数，从而实现类型推断

### 实际结果
<img width="481" alt="企业微信截图_a890d799-e586-4300-a5a7-130bf5d54d0f" src="https://user-images.githubusercontent.com/51358815/179341724-d956a398-3574-4650-9d63-37daa7d675f9.png">

### 补充说明
上述是简化了的过程，实际遇到的问题我在下方补充一份新的 codesandbox

| Environment | Info |
|---|---|
| 相关版本 | 0.36.4 |
| 框架版本 / 基础库版本 | React(16.13.1) |
| 系统、浏览器 | Chrome(103.0.5060.114) |
| Node版本 |  |

**Comment by NWYLZW** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-sbmumj?file=/src/demo.tsx
补充出现问题的实际场景

该问题能在关闭了 tsconfig 的 strict 配置后解决
但是我觉得组件确实也应该提供对应 table data 属性中的类型信息
实现对类型安全保障

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-react/blob/develop/src/table/type.ts
很多地方都有数据类型的范型

<img width="879" alt="image" src="https://user-images.githubusercontent.com/11605702/179356635-57a1537a-0db8-45e1-937e-7bdbdfe47df0.png">

**Comment by NWYLZW** [comment]
> 

不，我知道
这里是有泛型，但是不支持
没有在 table 组件中体现

**Comment by NWYLZW** [comment]
另外我觉得可以提供类型的地方是
`rowKey` 的类型设置为 `keyof T`，这样子可以在 ide 重构 T 的属性的时候支持索引到该属性对其进行同步修改
比如后端将 T 的 id 修改为了 uuid，这种情况使用 ide 的重命名能索引到该属性

**Comment by NWYLZW** [comment]
0.37.2-alpha.2
看起来是没有这个 bug 了

**Comment by NWYLZW** [comment]
0.40.3
再次出现了该问题
