### ISSUE TITLE
[ColorPicker] 选中渐变色的时候无法取消其中其他选中的中间渐变色，以及无法选中原有的进行换色拖动，而是会新增一个区间拖动按钮

### ISSUE THREAD

**Issue by juzhiqiang** [Tencent/tdesign-react#1117]
### tdesign-react 版本

0.36.4

### 重现链接

https://tdesign.tencent.com/react/components/color-picker

### 重现步骤

1. 打开渐变色
2. 选中其中一个选色，再在其他位置选中选色
3. 去点之前的选色按钮，拖动会生成一个新的

### 期望结果

1. 点之前的就选中之前的
2. 可以删除任意一个新增按钮

### 实际结果

1. 无法选中 且新增了

### 框架版本

官网示例

### 系统版本

window 10

**Comment by carolin913** [comment]
同 #1078 ，已解决待发布

**Comment by uyarn** [comment]
0.37.0 fixed
