### ISSUE TITLE
[ColorPicker] 渐变色新增的中间色渐变按钮可以删除吗

### ISSUE THREAD

**Issue by juzhiqiang** [Tencent/tdesign-react#1136]
### 这个功能解决了什么问题

当某些场景选中过度色后，之后更改需要减少中间过渡色，期望可以有一个删除新增的过度色按钮，

### 你建议的方案是什么

可以选中删除
![image](https://user-images.githubusercontent.com/25214312/179734848-5eb23b66-fced-4b62-ac4e-9bbada1170d0.png)
k

**Comment by carolin913** [comment]
这里是可以删除的哈，目前是通过键盘回退键，可以试一下
