### ISSUE TITLE
[Message] MessagePlugin 缺少 config() 方法

### ISSUE THREAD

**Issue by mathewzhai** [Tencent/tdesign-react#1137]
### tdesign-react 版本

0.37.0

### 期望结果

期望补充 MessagePlugin.config()

### 实际结果

官网 API 有 MessagePlugin.config() 的说明
<img width="893" alt="image" src="https://user-images.githubusercontent.com/106570404/179946439-ae162fa0-ae7f-4d25-9c34-3676228609ee.png">

但源码中没有此方法
<img width="614" alt="image" src="https://user-images.githubusercontent.com/106570404/179946613-6be863ed-ad8c-45c0-bb7a-2832799967c9.png">
![image](https://user-images.githubusercontent.com/106570404/179946736-a9f2cad6-f43a-454a-ad4c-b011816de6ef.png)

**Comment by HQ-Lin** [comment]
0.40.0 fixed
