### ISSUE TITLE
[Divider 分割线] 在content为空，且没有children的时候也会渲染出个span标签，导致分割线断开（中间有空）

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1141]
### tdesign-react 版本

0.36.3

### 重现链接

在第三方系统里使用，截图重现

### 重现步骤

![111](https://user-images.githubusercontent.com/108825798/180130904-891fbcdc-a8f0-4116-9d3a-94064a117bb2.png)

![000](https://user-images.githubusercontent.com/108825798/180130941-9dc70320-3582-49d8-a1c5-4fb630a204d3.png)

麻烦看图，jsx里代码如图1

在content为空，且没有children子元素的时候也会渲染出个<span class="t-divider__inner-text"></span>标签，导致分割线断开（中间有空）（如图2）

### 期望结果

在content为空，且没有children子元素的时候分隔线呈现一条直线，不断开（没有中间的空）

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

### 补充说明

因在第三方系统里使用，不知道该怎么在CodePen里重现，也不确定是第三方系统的bug 还 是tdesing的bug

**Comment by HQ-Lin** [comment]
这里这么写在react渲染时会变成 ['', '']导致误以为有子节点，我这周优化下

**Comment by HQ-Lin** [comment]
0.37.1 fixed

**Comment by HQ-Lin** [comment]
怎么里面又套了一个span。下次还是给个demo链接效率更高点，截图还要猜业务场景容易遗漏

**Comment by HQ-Lin** [comment]
这里自己判断一下如果都是空字符串就不要渲染 span 标签了，这里的 padding 是希望当有内容的时候与横线隔开增加美观，本来文本可以直接判断，你增加了 span 标签没办法通过 css 判断了
