### ISSUE TITLE
[Select] 使用filter api，无法选择其他选项

### ISSUE THREAD

**Issue by gl4523** [Tencent/tdesign-react#1143]
### tdesign-react 版本

0.37.0

### 重现链接

https://tdesign.woa.com/react/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

先选择一个选项，选项列表中就没有其他选项了

### 框架版本

React18

**Comment by southorange1228** [comment]
辛苦给个操作示意图？没看懂

**Comment by southorange1228** [comment]
> 辛苦给个操作示意图？没看懂

单选的 已了解问题

**Comment by lazybonee** [comment]
请问这个问题是否已解决呢，在最新版本0.37.2-alpha.2中仍然存在

**Comment by HQ-Lin** [comment]
> 请问这个问题是否已解决呢，在最新版本0.37.2-alpha.2中仍然存在
刚才又发了个alpha包，试一下 0.37.2-alpha.3
https://stackblitz.com/edit/react-jdzguy?file=src%2Fdemo.jsx

**Comment by HQ-Lin** [comment]
0.38 fixed
