### ISSUE TITLE
[Button] 按钮左侧icon和右侧suffix的高度不一致

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1154]
### tdesign-react 版本

0.37.0

### 重现链接

https://xv1jwu--run.stackblitz.io/

### 重现步骤

![1](https://user-images.githubusercontent.com/108825798/180631171-5e1e3cd9-69c0-4304-bd9d-09e5ec13445f.png)
![2](https://user-images.githubusercontent.com/108825798/180631174-784c5cb8-99bb-4e0a-b434-0793fc04eb05.png)
![3](https://user-images.githubusercontent.com/108825798/180631177-70155d97-e136-41c8-ac13-b76ed78b4698.png)

### 期望结果

希望按钮左侧icon和右侧suffix的高度一致

### 实际结果

按钮左侧icon和右侧suffix的高度不一致

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

### 补充说明

其实没必要加suffix属性，想把图标放右侧直接写slot里或者用children就可以啦，不过，既然已经加上了，就得让它左右大小一致吧

**Comment by szqyqxgs** [comment]
乍一看，2个图标一高一低；仔细看，原来是icon属性和suffix属性的尺寸不同

**Comment by HQ-Lin** [comment]
0.37.1 fixed
