### ISSUE TITLE
[Select] 过滤时，inputValue 为空的时候，未显示全部选项

### ISSUE THREAD

**Issue by Blackn-L** [Tencent/tdesign-react#1155]
### tdesign-react 版本

0.37.0

### 重现链接

https://tdesign.tencent.com/react/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

官方 Demo 即可复现，见 Demo [可过滤的选择器](https://tdesign.tencent.com/react/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8)
步骤如图所示
1、第一个输入框，输入 `w`，下拉框为空
2、删除 `w`，下拉框还是为空
3、正常表现：删除 `w` 后，应该显示全部结果
![Select-1](https://user-images.githubusercontent.com/36040004/180652108-ce390ed0-7a08-4d23-a1ad-016ae9d317ea.png)
![Select-2](https://user-images.githubusercontent.com/36040004/180652119-ca7420b4-e69b-4ab3-bfd3-c6b486a884c2.png)
![Select-3](https://user-images.githubusercontent.com/36040004/180652123-bef46adb-cfab-4eeb-a178-aa20d2bd67d4.png)

### 期望结果

1、第一个输入框，输入 `w`，下拉框为空
2、删除 `w`后，应显示全部结果

### 实际结果

1、第一个输入框，输入 `w`，下拉框为空
2、删除 `w`，下拉框还是为空

### 框架版本

React 0.37.0

### 补充说明

应该是这个 PR 导致的 https://github.com/Tencent/tdesign-react/pull/1105
``` JavaScript
handleFilter(String(inputValue))
// inputValue 为 undefined 时，会转为 'undefined':string
// 导致去搜索 label 为 'undefined'的选项
```

**Comment by HQ-Lin** [comment]
0.38 fixed
