### ISSUE TITLE
[SelectInput] popupVisible为false allowInput为true 输入不了内容

### ISSUE THREAD

**Issue by zc422** [Tencent/tdesign-react#1169]
### tdesign-react 版本

0.37.1

**Comment by CodingOnStar** [comment]
提了一个fix试了试，想到一个问题，popup如果没有的话，为啥不直接input框呢

**Comment by HQ-Lin** [comment]
> 提了一个fix试了试，想到一个问题，popup如果没有的话，为啥不直接input框呢

可以提 pr 看看，我看你只是推到了自己fork的仓库而已

**Comment by CodingOnStar** [comment]
> > 提了一个fix试了试，想到一个问题，popup如果没有的话，为啥不直接input框呢
> 
> 可以提 pr 看看，我看你只是推到了自己fork的仓库而已

想了想，感觉这里好像没有必要修改。作为筛选器输入框的话，如果popupVisible是false，也就是看不到筛选项了，那这个时候allowInput的话，确实就是一个Input输入框的作用，起不到筛选作用，所以貌似没必要修改
