### ISSUE TITLE
[SelectInput] 当父级的上一个同级元素有margin，clearable 的icon会偏移

### ISSUE THREAD

**Issue by zc422** [Tencent/tdesign-react#1173]
### tdesign-react 版本

0.37.1

### 补充说明

![image](https://user-images.githubusercontent.com/28388644/180941434-f5aeee5d-f8b7-42b5-b91e-e8c824872b62.png)
![image](https://user-images.githubusercontent.com/28388644/180941489-ceaade9e-0b66-4360-b6f2-652c5757719d.png)

**Comment by HQ-Lin** [comment]
能给个复现的demo地址方便排查下么

**Comment by zc422** [comment]
![image](https://user-images.githubusercontent.com/28388644/180980198-85926feb-1bbc-4a80-b50d-15184a0adfb9.png)
线上的地址不好弄到。代码片段是这样。当span和SelectInput有外边距时候就会出现偏移的情况
