### ISSUE TITLE
[button按钮] icon在左 content在中 suffix在右，他们应该是一体的，假如再有个children，应该放他们的上下左右边，而不是插他们里面去

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1179]
### tdesign-react 版本

0.37.1

### 重现链接

https://4uj9wo--run.stackblitz.io

### 重现步骤

链接已重现

### 期望结果

 icon在左 content在中 suffix在右，他们是按钮的三要素，应该是一体的，假如再有个children（虽然不太可能4个同时出现），应该放他们的上下左右边，而不是插他们里面去

### 实际结果

建议 children 自动放 suffix 的右边去

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

### 补充说明

虽然不太可能在按钮里出现这么多属性和子组件，但我觉得子组件不应该插入到父组件的多个元素中间去吧

**Comment by chaishi** [comment]
TDesign React 中 `children` 和 `content` 永久保持一致，如果有哪个组件不一致的可以提出来。

`children` 即是 `content`，两者一致，永久保持为 Button 组件最中间的内容

**Comment by chaishi** [comment]
content/children + icon + suffix，已经满足很多场景了，如果这些还无法满足你的需求，辛苦使用 content 完全自行定义自己想要的任何内容或样式
