### ISSUE TITLE
[Input] clearable设置成true会有两个关闭按钮

### ISSUE THREAD

**Issue by lazybonee** [Tencent/tdesign-react#1182]
### tdesign-react 版本

0.37.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-khpwkm

### 期望结果

<img width="618" alt="image" src="https://user-images.githubusercontent.com/11715201/181465648-feb409d4-9bcd-4234-ade1-76a252f42835.png">

### 实际结果

<img width="694" alt="image" src="https://user-images.githubusercontent.com/11715201/181465696-1783064e-3e47-42f3-abf4-077af247fea9.png">

### 框架版本

react(16.13.1)

### 浏览器版本

Chorme(102.0.5005.115)

### 系统版本

MacOs

**Comment by HQ-Lin** [comment]
0.38 fixed
