### ISSUE TITLE
[Slider] 期望支持 disableRange 禁用某些区间

### ISSUE THREAD

**Issue by agmilli** [Tencent/tdesign-react#1183]
### tdesign-react 版本

"tdesign-react": "0.37.1",

### 重现链接

https://codesandbox.io/s/suspicious-grass-tz9x6l?file=/src/App.js

### 重现步骤

使用Slider组件的时候，需要对带有刻度的进行设置可拖动范围，这时候原本的刻度会跑到盒子外面去

### 期望结果

<img width="1864" alt="_ab2c2d61-e715-4a54-a309-7384b8f9c727" src="https://user-images.githubusercontent.com/23680883/181471056-eee06556-2d5f-4faa-8b99-c8b84ff825df.png">

### 框架版本

React

**Comment by andyjxli** [comment]
@agmilli  你的想法是范围是 0 - 100，但最大能拖拽到 50 是吗？ 目前没有 API 支持的，但可以这样处理的哈。
<img width="620" alt="image" src="https://user-images.githubusercontent.com/19701675/181489633-858d629b-c48a-4cc2-849f-872833f7f77c.png">

**Comment by agmilli** [comment]
好的，谢谢，这样min,max这两参数已经不需要设置了

**Comment by agmilli** [comment]
> @agmilli 你的想法是范围是 0 - 100，但最大能拖拽到 50 是吗？ 目前没有 API 支持的，但可以这样处理的哈。 <img alt="image" width="620" src="https://user-images.githubusercontent.com/19701675/181489633-858d629b-c48a-4cc2-849f-872833f7f77c.png">
好的，谢谢，这样min,max这两参数已经不需要设置了

**Comment by agmilli** [comment]
@安迪杰西里
好的谢谢，不过这样就不需要设置，min和max 了

**Comment by HQ-Lin** [comment]
设置了max 和 min 就意味着用户期望展示 min - max的可拖动区间，组件也不好界定要渲染比 max 大的区间是多少，如果你想展示 0 - 100 但是又要限定只有 0-60可拖动，那其实应该要用 disable 之类的 api 去禁用 60 - 100 的区间不可拖动，我们讨论下看看

**Comment by wanpan11** [comment]
我来跟进🤫🤫

**Comment by wanpan11** [comment]
@HQ-Lin 这个是需要怎么完善呢 有方案吗 😀

**Comment by PBK-B** [comment]
这里好像还暴露出一个刻度值溢出的问题，当 `marks` 参数中有刻度值超过 `max` 参数限定值时，刻度显示将溢出 Slider 组件。

<img width="1485" alt="截屏2022-08-25 10 47 43" src="https://user-images.githubusercontent.com/39079814/186564997-5047b13c-ec52-42c8-bd55-bfca3d03cf33.png">

**Comment by PBK-B** [comment]
> 这里好像还暴露出一个刻度值溢出的问题，当 `marks` 参数中有刻度值超过 `max` 参数限定值时，刻度显示将溢出 Slider 组件。
> 
> <img alt="截屏2022-08-25 10 47 43" width="1485" src="https://user-images.githubusercontent.com/39079814/186564997-5047b13c-ec52-42c8-bd55-bfca3d03cf33.png">

@agmilli @andyjxli @HQ-Lin 我这里尝试重新梳理并理解一下问题：
1. 根据 @agmilli 描述好像就是指进度显示的最大值应该根据 `marks` 中的最大值（or 最小值）显示，但是可拖拽的最大值（or 最小值）是根据 `max` or `min` 值限定。
2. 那么根据上面的规则，就可以实现禁用起始值（or 结束值）至某个值的禁选，如果还需要更加细化的处理中间值的话就可以尝试实现 `disableRange` 参数，控制中间值不可选中。
