### ISSUE TITLE
[Dropdown] 声明了 overlayClassName 属性后，下拉菜单内间距发生变化

### ISSUE THREAD

**Issue by syxysszyw** [Tencent/tdesign-react#1184]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-2jmikx?file=/src/demo.jsx

### 重现步骤
展开下拉菜单即可体验

### 期望结果
下拉菜单（.t-popup__content）内间距保持不变

### 实际结果
下拉菜单（.t-popup__content）内间距发生变化

| Environment | Info |
|---|---|
| 相关版本 | 0.37.1 |
| 框架版本 / 基础库版本 | React(16.14.0) |
| 系统、浏览器 | Chrome(103.0.5060.114（正式版本） (x86_64)) |
| Node版本 |  |

**Comment by CodingOnStar** [comment]
认领

**Comment by HQ-Lin** [comment]
0.38.0 fixed
