### ISSUE TITLE
当Select组件的Option选项值为布尔值时候，选中没有显示对应的文字，并且clearable不生效

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1190]
### tdesign-react 版本

0.37.1

### 重现链接

https://codesandbox.io/s/objective-wave-rk8ptm?file=/src/App.js

### 重现步骤

选择的“正常”Option，Select组件上没有显示“正常”，选择的“取消”Option，Select组件上没有显示“取消”

### 框架版本

react

**Comment by HQ-Lin** [comment]
0.42.0 fixed
