### ISSUE TITLE
[space间距] 水平的分隔符不显示

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1191]
### tdesign-react 版本

0.37.1

### 重现链接

https://ysu6fy--run.stackblitz.io

### 重现步骤

separator={<Divider layout="horizontal"/>}    // 这样写的时候，不显示水平的分隔符

### 期望结果

间距里竖向排列的时候，可以显示水平分隔符

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/react-zlvqmj?file=src%2Fdemo.jsx
你的demo地址打不开，复制这个demo地址给我
<img width="432" alt="image" src="https://user-images.githubusercontent.com/24469546/182057713-b259a718-7dab-4de9-8cd8-9bc26e688f15.png">

纵向分割可以先这么实现下

**Comment by HQ-Lin** [comment]
> ![111](https://user-images.githubusercontent.com/108825798/182076777-7e65518e-e9d7-4c6f-bd5c-d1d46d7cd265.png)
> 
> 如上图，使用了align属性 不显示分隔符
> 
> 因为align不是必传的，所以我不确定算不算bug，不算的话请关闭这个 issues 吧

应该算bug，这边有点奇怪的是 alin-items 属性跟 inline-flex 同时出现的时候导致宽度为0所以没有展示出来分割线，不过这里其实设置align也没什么意义，后面我研究下看看什么原因优化下吧

**Comment by HQ-Lin** [comment]
0.40.5 fixed
