### ISSUE TITLE
[Popup] Popup.children 是一个条件渲染的组件时，行为失效

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1213]
### tdesign-react 版本

^0.38.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-xmjuxk?file=/src/demo.jsx

### 重现步骤

`Popup.children` 是一个条件渲染的组件时，`Popup` 的行为失效。

### 期望结果

能正常展示 `Popup` 组件。

### 实际结果

在项目中，表现为定位失效，`top: 0px; left: 0px`。
在 `CodeSandbox` 中表现为报错。
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/37169906/182569778-1bccc067-ac5c-48dd-9925-b8e1dbb493ca.png">

**Comment by CodingOnStar** [comment]
你这个场景是不是换个写法更好？

**Comment by moecasts** [comment]
> 你这个场景是不是换个写法更好？ `<Popup trigger="hover" showArrow content="这是一个弹出框"> {bool ? <span>Not reach</span> : <Button>Hover me</Button>} </Popup>`

这只是一个简单的例子，实际应用中，不能简单的用三元运算来表达。

**Comment by southorange1228** [comment]
这里popup强依赖ref导致的。
https://github.com/Tencent/tdesign-react/issues/1100

**Comment by HQ-Lin** [comment]
0.40.0 fixed
