### ISSUE TITLE
[dialog] 示例出现拼写错误

### ISSUE THREAD

**Issue by sameenzm** [Tencent/tdesign-react#1214]
### tdesign-react 版本

0.38.0

### 重现链接

https://tdesign.tencent.com/react/components/dialog?tab=demo#%E6%A8%A1%E6%80%81%E4%B8%8E%E9%9D%9E%E6%A8%A1%E6%80%81%E7%B1%BB%E5%AF%B9%E8%AF%9D%E6%A1%86

### 重现步骤

文档中「挂载元素」里的demo拼写有单词拼写错误

### 期望结果

应该是attach ，拼写成了 mattach

### 实际结果

<img width="950" alt="image" src="https://user-images.githubusercontent.com/17029105/182570631-8a785eb5-5f70-40f0-9b70-6379a75ed129.png">

### 框架版本

React(17.0.2)

### 浏览器版本

Chrome(101.0.4951.64)

### 系统版本

MacOS(11.3.1 )

### Node版本

v14.18.2

**Comment by chaishi** [comment]
收到，感谢反馈
