### ISSUE TITLE
[Jumper] 配置提示文本示例效果出不来

### ISSUE THREAD

**Issue by syxysszyw** [Tencent/tdesign-react#1220]
### 重现链接
https://tdesign.woa.com/react/components/jumper

### 重现步骤
<img width="882" alt="image" src="https://user-images.githubusercontent.com/4988284/182604664-5697f8aa-0a5c-47a8-8e8c-aecfb6514f7f.png">

### 期望结果
能看到相关的示例效果

### 实际结果
看不到相关的示例效果

| Environment | Info |
|---|---|
| 相关版本 | 0.38.0 |
| 框架版本 / 基础库版本 | React |
| 系统、浏览器 | MacOS 11.2.1 - Chrome 103.0.5060.114|
| Node版本 |  |

**Comment by southorange1228** [comment]
tips基于原生title属性实现，因此需要一定时间的hover。JS报错问题是没有做兜底

**Comment by syxysszyw** [comment]
get，刚刚简单测算了一下好像差不多1秒才出现第一个 tips， 随后移动鼠标的话 tips 出现就不会有延时了，第一次延时确实比较长...那后续这里有计划优化吗？

**Comment by southorange1228** [comment]
> get，刚刚简单测算了一下好像差不多1秒才出现第一个 tips， 随后移动鼠标的话 tips 出现就不会有延时了，第一次延时确实比较长...那后续这里有计划优化吗？

html标签原生表现是这样的。看下PMC是否考虑使用`Tooltip`实现，我不做修改哈

**Comment by HQ-Lin** [comment]
> get，刚刚简单测算了一下好像差不多1秒才出现第一个 tips， 随后移动鼠标的话 tips 出现就不会有延时了，第一次延时确实比较长...那后续这里有计划优化吗？

这里需要的提示一般比较弱，如果用tooltip会表现的比较强，每次hover都会有气泡出来，考虑到这个组件一般都会出现在用户容易理解的场景里所以用原生的title来实现
