### ISSUE TITLE
[Button] 组件 Block 按钮示例效果有误

### ISSUE THREAD

**Issue by syxysszyw** [Tencent/tdesign-react#1221]
### 重现链接
https://tdesign.woa.com/react/components/button#block-%E6%8C%89%E9%92%AE

### 重现步骤
无

### 期望结果
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/4988284/182606214-65037464-6e28-4bc0-9fe9-d67e2849ee8b.png">

### 实际结果
<img width="923" alt="image" src="https://user-images.githubusercontent.com/4988284/182606241-377ec211-ebe5-4a76-94a8-c66de5d1776c.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.38.0 |
| 框架版本 / 基础库版本 |  React |
| 系统、浏览器 | MacOS 11.2.1 - Chrome 103.0.5060.114 |
| Node版本 |  |

**Comment by southorange1228** [comment]
更新组件示例导致。我来修复下
