### ISSUE TITLE
类型缺失

### ISSUE THREAD

**Issue by cuijinyu** [Tencent/tdesign-react#123]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**
OSX

**Describe the bug**
类型推导提示缺失

![image](https://user-images.githubusercontent.com/22697021/147658816-a5a0041c-4036-40ec-90eb-36724299b651.png)
这个情况存在在多个组件中

**Additional context**

**Comment by HQ-Lin** [comment]
我排查一下

**Comment by carolin913** [comment]
我这里试了两个组件都没问题的，类型约束和提示都有
<img width="666" alt="wecom-temp-0ebdffe8fb6dd021a30c19849e9f9207" src="https://user-images.githubusercontent.com/2638568/147806842-0e3129d7-a966-4162-80d2-7e8953213c44.png">
<img width="999" alt="wecom-temp-a4c415ece29c9f935fdd247e70ee30eb" src="https://user-images.githubusercontent.com/2638568/147806855-c8f8a657-837b-4ec0-b745-32aba45b4a9d.png">
@cuijinyu 麻烦你看下你这边的tsconfig是否正确配置了，还有依赖的tdesign-react版本也麻烦发一下
