### ISSUE TITLE
[Cascader] 添加  excessTagsDisplayType 后，箭头位置错误

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#1238]
### tdesign-react 版本

0.38.0

### 重现步骤
添加 
```js
 tagInputProps={{
    excessTagsDisplayType: 'scroll',
  }}
```
https://codesandbox.io/s/tdesign-react-demo-forked-n3u4ex

**Comment by CodingOnStar** [comment]
这个指的是哪个箭头

**Comment by ontheroad1992** [comment]
> 这个是指哪个箭头

添加前：
<img width="708" alt="image" src="https://user-images.githubusercontent.com/29194619/183240322-ae325fae-a40b-49ba-874f-0de3e05e48eb.png">

添加后：
<img width="701" alt="image" src="https://user-images.githubusercontent.com/29194619/183240304-8763691f-572c-4146-afc5-9010ca231cef.png">

**Comment by CodingOnStar** [comment]
这里的箭头不正好体现了excessTagsDisplayType的动态性吗
