### ISSUE TITLE
Popup动画视觉效果

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#124]
目前看到所有基于popup的弹出窗动画都比较缓慢。给人一种卡顿的感觉，是否考虑优化？

### Tdesign 效果
![Kapture 2021-12-29 at 19 31 35](https://user-images.githubusercontent.com/32590310/147658006-34b04cef-f8bb-48ff-ae43-8e00badca107.gif)

### Antd效果
![QQ20211229-194232-HD](https://user-images.githubusercontent.com/32590310/147658953-eceb7c4c-7e4f-482b-ad5d-bd56fd0d1417.gif)

**Comment by uyarn** [comment]
是需要调整的 视觉正在看问题了。

**Comment by uyarn** [comment]
Tencent/tdesign-common#106 @southorange1228 welcome to discuss
