### ISSUE TITLE
[InputNumber] 受控 `value` 失效

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1240]
### tdesign-react 版本

^0.38.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lc36wy?file=/src/demo.jsx

### 重现步骤

`InputNumber` 组件设置 `value`，且 `onChange` 留空。

### 期望结果

`value` 受控

### 实际结果

`InputNumber` 组件的 `value` 没有受控，去掉 `setState` 之后，仍然会变。

**Comment by HQ-Lin** [comment]
看起来受控效果确实失效了，今天发版本一起处理了

**Comment by HQ-Lin** [comment]
这组件问题有点多，这两天重写下今天估计来不及，周三再发个版本吧
