### ISSUE TITLE
希望Table在树形结构数下有简单的更新数据的方法

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1241]
### 这个功能解决了什么问题

展示树形结构时候，通过刷新后端提供的接口，简单的通过useState更新数据。现在我暂时没有找到，麻烦帮我解决一下，谢谢了。
重现地址：https://codesandbox.io/s/dark-wildflower-bjqml0?file=/src/App.js

### 你建议的方案是什么

AntDesign的Table更新树形结构的数据就很方便，可以看看

**Comment by chaishi** [comment]
当前一行代码就可以更新数据，不知道你说的麻烦是是啥意思？

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/11605702/184151699-d518d62e-7373-44c2-9145-619b2f531ae4.png">

**Comment by chaishi** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/11605702/184151950-225b342b-747d-420d-ae18-46a36c4d4caa.png">

**Comment by nowui** [comment]
谢谢啦
