### ISSUE TITLE
[Switch] 值类型定义

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#1255]
### tdesign-react 版本

0.38.0

### 重现步骤

<img width="725" alt="图片" src="https://user-images.githubusercontent.com/32590310/183591201-ea8e8304-142e-4775-8220-10760a011cff.png">

Switch的值是否有必要做成`string | number | boolean`？

如果考虑value自定义类型  是否通过泛型实现更优雅？大部分业务场景 都只需要一个boolean类型 

如这种代码 很容易就出现TS错误
<img width="1357" alt="图片" src="https://user-images.githubusercontent.com/32590310/183591565-ef42f55c-f10d-44aa-b9d4-51e6093f2406.png">

强制类型对业务成本改造过高

**Comment by chaishi** [comment]
输入框相关组件类型支持范型，已在规划中
