### ISSUE TITLE
[InputNumber]为什么不能直接设置整数呢？

### ISSUE THREAD

**Issue by Allwhispers** [Tencent/tdesign-react#1267]
### 这个功能解决了什么问题

在inputnumber组件时很多场景都是需要直接使用整数的，每次都需要自己format比较麻烦，我建议直接增加设置整数的属性

### 你建议的方案是什么

decimalPlaces为0时直接设置成整数

**Comment by HQ-Lin** [comment]
合理，这周重构了 InputNumber 组件，下版本支持

**Comment by HQ-Lin** [comment]
0.40.0 fixed
