### ISSUE TITLE
[Layout 布局] Header和Footer的height值设置后无效

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1285]
### tdesign-react 版本

0.39.0

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.jsx

### 重现步骤

![222](https://user-images.githubusercontent.com/108825798/184501252-823204da-c936-4316-9b45-2ccbf6bf7d84.png)

### 框架版本

react 17.0.2

### 浏览器版本

chrome

### 系统版本

win7

### 补充说明

https://stackblitz.com/run?file=src%2Fdemo.jsx

https://par2en--run.stackblitz.io/

**Comment by HQ-Lin** [comment]
0.40.0 fixed
