### ISSUE TITLE
table 展开收起功能的回调函数 onExpandChange 希望返回 当前点击的行

### ISSUE THREAD

**Issue by zhb19950914** [Tencent/tdesign-react#1296]
目前返回的是展开收起后所有的行数据
![image](https://user-images.githubusercontent.com/29914762/184638461-151723c0-6bc0-4b36-8db3-199000e913d2.png)

**Comment by chaishi** [comment]
加

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1341

**Comment by HQ-Lin** [comment]
0.40.4 fixed
