### ISSUE TITLE
datePicker显示当前天数标记问题

### ISSUE THREAD

**Issue by zhushibo** [Tencent/tdesign-react#130]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
![image](https://user-images.githubusercontent.com/26269311/147730513-1eb86b5d-42fa-4a42-951e-e42d7609ad5c.png)

**Additional context**
z-index设置问题

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-common/pull/26
fixed.
感谢反馈，周五发版本会一起修复

**Comment by uyarn** [comment]
fixed in 0.22.0
