### ISSUE TITLE
[Divider 分割线] 分割线默认不显示问题

### ISSUE THREAD

**Issue by janily** [Tencent/tdesign-react#1301]
### tdesign-react 版本

必现

### 重现链接

https://codesandbox.io/s/angry-framework-n7nn4d?file=/src/App.js

### 重现步骤

引入分割线组件，不在父级显性设置宽度，组件默认宽度不够，导致水平分割线不显示，还要额外的声明一个宽度才能显示。而垂直方向的分割线是可以显示的，组件表现不统一。

### 期望结果

期望组件本身能够完成闭环，显示分割线，建议在组件本身默认设置一个宽度，并且水平，垂直方向要分别设置。

### 实际结果

不符合期望的显示结果。

### 框架版本

React(0.40.0)

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/blazing-monad-nml0fb?file=/src/App.js:64-106
使用组件库一定要记得引入样式文件，很多css都依赖基础的token做渲染，这里border由于拿不到css token 浏览器不渲染高度了
`import "tdesign-react/es/style/index.css";`

**Comment by janily** [comment]
> https://codesandbox.io/s/blazing-monad-nml0fb?file=/src/App.js:64-106 使用组件库一定要记得引入样式文件，很多css都依赖基础的token做渲染，这里border由于拿不到css token 浏览器不渲染高度了 `import "tdesign-react/es/style/index.css";`

我们现在的场景是在线上只引入了你们这个的 CDN 的样式地址，

`<link rel="stylesheet" href="https://unpkg.com/tdesign-react/dist/tdesign.min.css" />`

这种场景下怎么搞呢，还要单独额外引入下面这个么

`import "tdesign-react/es/style/index.css";`

**Comment by HQ-Lin** [comment]
> > https://codesandbox.io/s/blazing-monad-nml0fb?file=/src/App.js:64-106 使用组件库一定要记得引入样式文件，很多css都依赖基础的token做渲染，这里border由于拿不到css token 浏览器不渲染高度了 `import "tdesign-react/es/style/index.css";`
> 
> 我们现在的场景是在线上只引入了你们这个的 CDN 的样式地址，
> 
> `<link rel="stylesheet" href="https://unpkg.com/tdesign-react/dist/tdesign.min.css" />`
> 
> 这种场景下怎么搞呢，还要单独额外引入下面这个么
> 
> `import "tdesign-react/es/style/index.css";`

使用cdn引入样式也可以啊，保证css加载在前面就行了，参考这个demo
https://codesandbox.io/s/blazing-monad-nml0fb?file=/public/index.html

**Comment by HQ-Lin** [comment]
> > https://codesandbox.io/s/blazing-monad-nml0fb?file=/src/App.js:64-106 使用组件库一定要记得引入样式文件，很多css都依赖基础的token做渲染，这里border由于拿不到css token 浏览器不渲染高度了 `import "tdesign-react/es/style/index.css";`
> 
> 我们现在的场景是在线上只引入了你们这个的 CDN 的样式地址，
> 
> `<link rel="stylesheet" href="https://unpkg.com/tdesign-react/dist/tdesign.min.css" />`
> 
> 这种场景下怎么搞呢，还要单独额外引入下面这个么
> 
> `import "tdesign-react/es/style/index.css";`

unpkg.com 这个是国外的源有可能被墙或者加载较慢，如果还有问题记得先看看network 是否正常加载到样式
