### ISSUE TITLE
[Message] MessagePlugin.error的样式不对

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1308]
### tdesign-react 版本

0.40.1

### 重现链接

https://codesandbox.io/s/dark-wildflower-bjqml0?file=/src/App.js:212-245

### 重现步骤

![image](https://user-images.githubusercontent.com/3635163/184859314-e32e07fe-0ff5-4d71-a4ee-481425287590.png)

**Comment by HQ-Lin** [comment]
0.40.3 fixed
