### ISSUE TITLE
[Dropdown] 未支持 direction 属性设置子级菜单展开方向

### ISSUE THREAD

**Issue by SheenyMeg** [Tencent/tdesign-react#1316]
### tdesign-react 版本

0.38.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-3mrxue?file=/src/demo.jsx

### 重现步骤

设置 direction='left' 属性未生效

### 期望结果

设置 diretion='left' 属性后，二级菜单可向左展开
![image](https://user-images.githubusercontent.com/33172578/185086239-f2314de9-d096-4599-87a4-80e0bcffb800.png)

### 实际结果

![image](https://user-images.githubusercontent.com/33172578/185086794-670bdbc1-968f-49ae-9aa8-81c24a413fd9.png)

### 框架版本

React(16.14.0)

### 浏览器版本

Chorme(104.0.5112.81)

### 系统版本

Window(19042.1706)

### Node版本

Node(14.19.1)

**Comment by duenyang** [comment]
> 

确认，在修复中

**Comment by HQ-Lin** [comment]
0.41.0 fixed
