### ISSUE TITLE
[TextArea] textarea的autosize的minRows在dialog里首次打开不起作用

### ISSUE THREAD

**Issue by tustzdm** [Tencent/tdesign-react#1318]
### tdesign-react 版本

0.40.3

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-bokt0i?file=/src/demo.jsx

### 重现步骤

如codeSandBox

### 框架版本

React

**Comment by HQ-Lin** [comment]
0.40.4 fixed
