### ISSUE TITLE
[Table] empty内容的居中方式，无法适应Table宽度的变化

### ISSUE THREAD

**Issue by tustzdm** [Tencent/tdesign-react#1319]
### tdesign-react 版本

0.40.3

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-894el4?file=/src/demo.jsx

### 重现步骤

见codesandbox

### 期望结果

empty居中

**Comment by chaishi** [comment]
```csss
.t-table__empty {
  Width: auto !important;
}
```

可以这样设置解决问题

**Comment by chaishi** [comment]
其实，不仅仅是 Empty 元素，还有吸顶表头或者表尾，很多其他的元素，都是依赖数据变化更新 DOM。

单纯的外层 div 变化，难以检测。所以会存在部分场景不更新的情况，希望框架哪天能出一个监听 DOM 变化的特性。

为解决实际业务问题，组件会提供 `refreshTable` 实例方法，以便于在特殊场景中，刷新表格

**Comment by chaishi** [comment]
https://codesandbox.io/s/gu-ding-lie-antd-4-22-6-forked-pc5e0z?file=/demo.js

同样示例代码，这是隔壁大哥的效果，没跑起来

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-react/pull/1312

这个 PR 中已新增对外实例方法，`refreshTable`

**Comment by HQ-Lin** [comment]
0.40.4 fixed

**Comment by chaishi** [comment]
https://caniuse.com/?search=MutationObserver

可以使用这个特性监听 DOM，变化，我们修复一下这个问题

**Comment by chaishi** [comment]
修复效果如下方视频所示

https://user-images.githubusercontent.com/11605702/188151256-a016f2c3-051a-4fe9-b53c-0abc90851ce0.mov

**Comment by HQ-Lin** [comment]
0.40.6 fixed
