### ISSUE TITLE
[TextArea] TextArea组件maxlength属性在Safari有Bug

### ISSUE THREAD

**Issue by Charcliu** [Tencent/tdesign-react#1321]
### tdesign-react 版本

0.39.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-oc0c6u?file=/src/demo.jsx

### 测试文本
```
个人可以看到的须知 
事实上是事实上事实上事实上

沙发沙发沙发沙发沙发沙发<a href="https://sbc.sysu.edu.cn/article/600">腾讯电子签协议</a>沙发沙发沙发沙发沙发沙发

沙发沙发沙发沙发沙发沙发
沙发沙发沙发沙发沙发沙发
沙发沙发沙发沙发沙发沙发



沙发沙发沙

沙发沙发沙发沙发沙发沙发
```

maxlength设置为200，复制上面文本继续输入，右下角显示187/200就输入不进去了

### 期望结果

可以正常输入到200字符

### 实际结果

只能输入到187字符

### 框架版本

React 16.10.2

### 浏览器版本

Safari 版本15.4 (17613.1.17.1.13)

### 系统版本

MacOS 12.3.1 (21E258)

### Node版本

v14.17.1

**Comment by carolin913** [comment]
已确认问题，是safari这里的原生maxlength属性对于回车换行统计(长度+2)与chrome不一致，会尽快修复，请关注进展
