### ISSUE TITLE
[Layout 布局] Footer height默认高度才24px，却使用了padding: 24px;不太合适吧

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1323]
### tdesign-react 版本

0.40.3

### 重现步骤

![111](https://user-images.githubusercontent.com/108825798/185384330-d2b5c102-2966-44aa-b411-27e896e57029.png)

![222](https://user-images.githubusercontent.com/108825798/185385839-79a13b94-c8ef-48fa-9a5e-d4f4b1390c62.png)

在设置了Footer 的 height的情况下存在一个问题：height设置一个较大值时没问题（比如64px），但是设置较小值（比如默认的24px）的时候排版是有点错乱的，貌似问题出在padding: 24px;的内边距

**Comment by HQ-Lin** [comment]
> 想了下解决办法： 1.不设置height（那height属性就失去了存在的意义） 2.设置较大height（就没办法做出一个较小的Footer，比如24px高度的Footer） 3.height不用padding，而是用margin
> 
> 不知如何是好....求答案

所有样式你都可以通过style调整的，只是默认情况提供了24px的边距而已，不然就跟普通的div一样了什么样式都没有
