### ISSUE TITLE
[Button] font color same with background color in `ghost` mode

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [Tencent/tdesign-react#1325]
### 重现链接
https://tdesign.tencent.com/react/components/button

### 重现步骤
1. open `ghost` mode.
2. hover button.

### 期望结果
different font color and background color

### 实际结果
![image](https://user-images.githubusercontent.com/54026110/185434966-ee69bb98-ad5b-4f7b-8e4e-9b3a35c74f0c.png)

| Environment | Info |
|---|---|
| 相关版本 | 0.40.3 |
| 框架版本 / 基础库版本 | - |
| 系统、浏览器 | Windows 11 |
| Node版本 | - |

**Comment by uyarn** [comment]
duplicated of https://github.com/Tencent/tdesign-vue/issues/1246

**Comment by HQ-Lin** [comment]
这里其实是 `variant='base'` 没有适配幽灵按钮模式，背景色和边框颜色都需要适配，近期优化一下

**Comment by HQ-Lin** [comment]
0.41.0 fixed
