### ISSUE TITLE
[Textarea] Textarea 组件 emoji length 计算问题

### ISSUE THREAD

**Issue by HelKyle** [Tencent/tdesign-react#1327]
### tdesign-react 版本

0.40.3

### 重现链接

https://tdesign.tencent.com/react/components/textarea#%E9%99%90%E5%88%B6%E6%9C%80%E5%A4%A7%E5%AD%97%E7%AC%A6%E6%95%B0

### 重现步骤

限制最大字符数的 textarea 输入框，输入 👨

### 期望结果

length 计算为 1

### 实际结果

length 为 2

### 补充说明

这里讨论一般开发场景，后端数据库采用四个字节 utf8 编码（utf8mb4）限制字段最大字符长度为 20。

👨 的 utf8 编码后占用四个字节：`0xF0 0x9F 0x91 0xA8`，**数据库是可以存下 20 个 👨 字符的**。而由于 Javascript 字符是 utf-16 编码（`0xD83D 0xDC68`），`length` 属性由于历史原因计算的是 codeunit 的的长度，'👨'.length === 2，**这时候前端仅允许输入 10 个 👨 字符**。

讨论：这里是否需要修改 maxlength 的计算方式，和实际应用场景对齐？

ps: 在 Antd 的 Input/Textarea 组件中，👨 length 为 1。

**Comment by HelKyle** [comment]
如果确认需要支持的话，我可以提 pr 贡献代码

**Comment by HelKyle** [comment]
好奇再补充个问题，`maxcharacter` 是以什么为单位呢？

https://github.com/Tencent/tdesign-common/blob/1f3300700dc2b9266b99f488bdfac7d790d8b90a/js/utils/helper.ts#L109

```ts
for (let i = 0; i < str.length; i++) {
    let currentStringLength = 0;
    if (str.charCodeAt(i) > 127 || str.charCodeAt(i) === 94) {
      currentStringLength = 2;
    } else {
      currentStringLength = 1;
    }
}
```

**Comment by HQ-Lin** [comment]
> 好奇再补充个问题，`maxcharacter` 是以什么为单位呢？
> 
> https://github.com/Tencent/tdesign-common/blob/1f3300700dc2b9266b99f488bdfac7d790d8b90a/js/utils/helper.ts#L109
> 
> ```ts
> for (let i = 0; i < str.length; i++) {
>     let currentStringLength = 0;
>     if (str.charCodeAt(i) > 127 || str.charCodeAt(i) === 94) {
>       currentStringLength = 2;
>     } else {
>       currentStringLength = 1;
>     }
> }
> ```

maxcharacter 是判断中文字符的

**Comment by HQ-Lin** [comment]
> 如果确认需要支持的话，我可以提 pr 贡献代码

欢迎提pr贡献～可以在 common 仓库的公共函数修改，这样其他框架也一起优化了

**Comment by HQ-Lin** [comment]
0.40.4 fixed
