### ISSUE TITLE
[Table] EnhancedTable报Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1330]
### tdesign-react 版本

0.40.3

### 重现链接

https://codesandbox.io/s/objective-wave-rk8ptm?file=/src/App.js:190-203

### 重现步骤

![image](https://user-images.githubusercontent.com/3635163/185583668-abab9ae5-afcf-4283-b446-054eb8523d24.png)

**Comment by HelKyle** [comment]
看起来是因为首次 render 时，treeNodeCol 还没赋值导致的，已提 pr
