### ISSUE TITLE
[Alert 警告] 试了2种写法，onClosed 都没效果

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1333]
### tdesign-react 版本

0.40.3

### 重现步骤

![999](https://user-images.githubusercontent.com/108825798/185666105-757b1d7e-3598-4377-b764-575802da13e4.png)

Alert 警告 的 onClosed 使用了两种写法都没见效

[https://stackblitz.com/run?file=src%2Fdemo.jsx](url)
[https://hqlgts--run.stackblitz.io](url)

**Comment by southorange1228** [comment]
@HQ-Lin 老板确定下是否需要`onClosed`这个API，目前看到`Alert`组件并没有用`CSSTransition`包裹，这个API实际上也没有调用

**Comment by HQ-Lin** [comment]
> @HQ-Lin 老板确定下是否需要`onClosed`这个API，目前看到`Alert`组件并没有用`CSSTransition`包裹，这个API实际上也没有调用

确实是实现的缺陷，需要补上动画以及动画结束的函数

**Comment by HelKyle** [comment]
认领

这里的动画有规范吗？使用 `CSSTransition` 包裹？

**Comment by HQ-Lin** [comment]
> 认领
> 
> 这里的动画有规范吗？使用 `CSSTransition` 包裹？

对的，可以参考 vue 那边的动画

**Comment by HelKyle** [comment]
> 对的，可以参考 vue 那边的动画，有现成的 class 样式

这里有点差异，按文档 onClosed 需要返回 `e: TransitionEvent<HTMLDivElement>` 类型。使用 `CSSTransition` 或者通过手动 addEventListener 的话是没有这个 event 的。 @HQ-Lin 看看

**Comment by HelKyle** [comment]
个人觉得 `onClosed` 事件中的 `event` 是不需要的，建议去掉

```
onClosed?: () => void;
```
