### ISSUE TITLE
[Dialog][Input] Input在Table里面，同时Table在Dialog里面，在Input前面输入值时候光标会跳到结尾，无法完整输入

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1335]
### tdesign-react 版本

0.40.3

### 重现链接

https://codesandbox.io/s/bold-butterfly-6sw22v?file=/src/App.js

### 重现步骤

点击字段名称的input组件，鼠标点击在”123456“的前面任意输入字符，光标会跳转到尾部

**Comment by PBK-B** [comment]
补充描述 Dialog 中 Input 组件输入时光标将移动到尾部

**Comment by PBK-B** [comment]
@nowui 你在浏览器能重现这个问题吗？我这边好像并没有重现这个问题

**Comment by chaishi** [comment]
经过排查，初步判定是 Dialog 组件的问题。有这个组件和没有组件，效果有所不同。我们找人看下

**Comment by chaishi** [comment]
楼主可能需要的是这个功能：https://github.com/Tencent/tdesign-vue-next/issues/1387

**Comment by huoyuhao** [comment]
OK 我今天具体看一下这个bug

**Comment by huoyuhao** [comment]
收到，已经在确认问题原因
