### ISSUE TITLE
[From] 第三方富文本编辑器组件在From组件内不可以敲回车换行，在From组件外就可以

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1340]
### tdesign-react 版本

0.40.3

### 重现链接

https://codesandbox.io/s/cranky-grothendieck-dezn5e?file=/src/App.js

### 重现步骤

![image](https://user-images.githubusercontent.com/3635163/185785827-44261410-f7ab-4904-b3de-e4a32cbbc8a1.png)

**Comment by HQ-Lin** [comment]
<img width="534" alt="image" src="https://user-images.githubusercontent.com/24469546/185825734-8bb1ca78-8335-47cb-b124-4872acae5e0a.png">
https://codesandbox.io/s/modest-benji-is40qn?file=/src/App.js
可以先设置下 `preventSubmitDefault={false}` 处理下，这里为了防止回车导致form提交阻止了冒泡，我再排查下这种情况能不能排除

**Comment by HQ-Lin** [comment]
已经调整为只拦截 input 输入框的回车事件
