### ISSUE TITLE
[Docs] 全局搜索框搜索跳转到空白页面

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [Tencent/tdesign-react#1362]
### tdesign-react 版本

0.40.4

### 重现链接

https://tdesign.tencent.com/react/overview

### 重现步骤

1. 打开重现链接
2. 在顶部搜索框搜索任意组件，如 Table
![image](https://user-images.githubusercontent.com/54026110/186483987-67a5783f-0e68-4c54-bcc1-8075d4b98e6a.png)
3. 选择 **组件概览** 选项
![image](https://user-images.githubusercontent.com/54026110/186484295-41658757-fa6f-435b-b6a5-775645f621e3.png)

### 期望结果

跳转到组件概览页面

### 实际结果

跳转到空白页

### 框架版本

-

### 浏览器版本

-

### 系统版本

-

### Node版本

-

**Comment by Lmmmmmm-bb** [comment]
pr https://github.com/Tencent/tdesign-react/pull/1363

**Comment by HQ-Lin** [comment]
这里根源还是因为搜索的内容没有更新，之前有一次更新过全栈路由规则导致跳转地址有误，我这周处理下
