### ISSUE TITLE
[AnchorItem] href属性如何适配hash路由

### ISSUE THREAD

**Issue by zc422** [Tencent/tdesign-react#1365]
### tdesign-react 版本

0.37.1

### 重现步骤

![image](https://user-images.githubusercontent.com/28388644/186569406-861f5e4c-8bdc-4677-84a9-0b08bc707109.png)

**Comment by HQ-Lin** [comment]
路由跟锚点不是一个概念，路由是用来切换页面内容的，锚点是定位当前页面下的具体某个元素的，硬要关联可以自己写 onClick 跳转路由

**Comment by zc422** [comment]
文档里的hash模式是啥意思呢，不是说的hash路由吗

**Comment by zc422** [comment]
文档里的hash模式是啥意思呢，不是说的hash路由吗

**Comment by zc422** [comment]
> 

文档里的hash模式是指什么呢

**Comment by chaishi** [comment]
文档里的 `hash` 是指 Vue 的，React 不适用，会更新文档
