### ISSUE TITLE
[Loading] iphone 微信/企微 webview 下显示 bug

### ISSUE THREAD

**Issue by mathewzhai** [Tencent/tdesign-react#1366]
### tdesign-react 版本

0.38.0

### 重现链接

官网链接即可复现

### 重现步骤

在苹果手机上用微信/企微浏览器打开 td 官网，点击 loading 加载中 组件，可见 loading 蓝色圆环晃动转圈

**Comment by uyarn** [comment]
fixed 0.40.4
