### ISSUE TITLE
Tooltip 视觉效果

### ISSUE THREAD

**Issue by iseekTo** [Tencent/tdesign-react#137]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Version: _Mac OS Chrome/96.0_

**Describe the bug**
Tooltip 视觉效果，如图，三角icon下出现了一个镂空的边，是设计效果吗，

**Additional context**

Content: 
![image](https://user-images.githubusercontent.com/33739877/147799452-6bd43c77-02ce-46c8-8c6a-224a598b3737.png)

## OTHERS
增加几个labels吧，方便标记与筛选问题

**Comment by chaishi** [comment]
> 增加几个labels吧，方便标记与筛选问题
好的，感谢建议。@yuyang 跟进下吧

**Comment by pattybaby110** [comment]
第一个应该是实现的问题，我们修复一下 😭

**Comment by iseekTo** [comment]
> 第一个应该是实现的问题，我们修复一下 😭

YEP

**Comment by yuyang** [comment]
@chaishi  我觉得您@ 错人了。。。

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-common/pull/106
