### ISSUE TITLE
[TagFilterSearchBox] 带过滤功能的标签下拉搜索框

### ISSUE THREAD

**Issue by HenryLee0** [Tencent/tdesign-react#1370]
### 这个功能解决了什么问题

我希望在项目中对列表数据进行 过滤、对应字段查询、标签搜索... 

### 你建议的方案是什么

![image](https://user-images.githubusercontent.com/93959131/186838360-5ed0ecd4-bf74-4bf7-b364-027c2321c6e7.png)
能把CSIG的这个组件开源么 我也不知道学名叫啥 反正是真的好用👍🏻

**Comment by southorange1228** [comment]
跟PMC讨论过，先由内部实现。后面可能通过物料市场开源

**Comment by chaishi** [comment]
Select 组件支持上面提到的功能，只是下拉框当前会有 checkbox，也会规划不显示 下拉框选项的 checkbox
