### ISSUE TITLE
[Upload] 组件加上files属性就不能调用action属性上传图片了

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#1372]
### tdesign-react 版本

0.40.4

### 重现链接

https://codesandbox.io/s/dark-wildflower-bjqml0?file=/src/App.js

**Comment by chaishi** [comment]
`files` 是受控属性，需要在外部 `onChange` 中进行赋值。辛苦看下官网怎么写的哈

```
<Upload files={fileList} onChange={setFileList} />
```

**Comment by duanbaosheng** [comment]
像@chaishi   说的，file是受控属性，表明需要用户自己去改变它的值。如果给files传了默认值，需要用户在onChange函数中去改变files的值。
如果仅仅是想添加已经上传的默认的文件列表，可以直接将初始值赋值给 defaultFiles 属性。

**Comment by nowui** [comment]
@chaishi @duanbaosheng  我表达的意思是加上files后  不用通过接口来上传文件了，操作过程是：1、点击upload组件；2、选择上传的图片（到这一步就没有响应了，没有办法进行接口上传图片的操作）

**Comment by nowui** [comment]
我不是说要改变fileList的值  这个我能控制的

**Comment by carolin913** [comment]
需要同时定义onChange方法给files赋值，你说的第2步才会有响应

**Comment by nowui** [comment]
@carolin913 "需要同时定义onChange方法给files赋值" 
如果我自定义一个用在组件，里面有upload。该自定义组件用在form表单下，维护自定义组件的props.value好像比较麻烦.
![image](https://user-images.githubusercontent.com/3635163/188875979-31151e9e-61b3-4771-84b1-a597ee772c6e.png)

**Comment by chaishi** [comment]
使用最新版本号 `v0.41.0`，正确的示例代码，
https://codesandbox.io/s/goofy-panka-ykgmlj
