### ISSUE TITLE
[table] 表格筛选 时间面板组件，显示选择时间，切换月份组件报错

### ISSUE THREAD

**Issue by Alex-is-coding** [Tencent/tdesign-react#1375]
### tdesign-react 版本

最新版本可复现

### 重现链接

https://stackblitz.com/edit/react-l3byec-wwnbbl?file=src/demo.jsx

**Comment by chaishi** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/11605702/186901821-681b4bae-b457-4c5b-a679-6d774b614597.png">
