### ISSUE TITLE
[Table] 表头排序按钮位置错误

### ISSUE THREAD

**Issue by mathewzhai** [Tencent/tdesign-react#1398]
### tdesign-react 版本

0.40.4

### 重现步骤

表格表头设置排序可见

### 实际结果

<img width="888" alt="image" src="https://user-images.githubusercontent.com/106570404/187385223-77faff70-6a07-4fd9-95a3-e584b652d6d4.png">

**Comment by chaishi** [comment]
@uyarn 已处理，于 2022-08-29 发布 `v0.45.0`
