### ISSUE TITLE
[Tooltip] 悬浮框宽度计算错误

### ISSUE THREAD

**Issue by lazybonee** [Tencent/tdesign-react#1405]
### tdesign-react 版本

0.40.5

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-ueu24e?file=/src/demo.jsx

### 期望结果

文字不应该超出悬浮框边界

### 实际结果

![Uploading 企业微信截图_1e104539-772a-4a50-8dfe-61dcb25ebbd0.png…]()

### 框架版本

React(17.0.2)

### 浏览器版本

Chorme(102.0.5005.115)

### 系统版本

MacOs

### Node版本

16.5.0

**Comment by HQ-Lin** [comment]
看起来得加上滚动条处理下

**Comment by carolin913** [comment]
<img width="568" alt="企业微信截图_4295d85f-febb-409d-b775-def9a344be8b" src="https://user-images.githubusercontent.com/2638568/187908754-8c8f330e-229e-4ccc-95c7-a0ad2f45bc0a.png">
设置overlayInnerStyle即可
