### ISSUE TITLE
[Popup] hover 到 PopupContent 时，能让 Popup 消失

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1406]
### 这个功能解决了什么问题

连续几个有 `Popup` 的按钮放在一起时，会因为 `PopupContent` 的存在，导致想移到附近 `Button` 有点困难，会被 `PopupContent` 拦截。

### 你建议的方案是什么

增加一个配置项，允许用户自己选择 `hover` 到 `PopupContent` 时，`Popup` 是否消失。

**Comment by HQ-Lin** [comment]
这里大多数需求还是希望能复制里面的元素，所以保留了移入 content 区域还能展示的交互
要实现你的效果可以有两种方式：
一个是控制 visible 自己处理
第二种添加 `overlayStyle={{ pointerEvents: 'none' }}` 阻止 content 元素的所有交互

**Comment by HQ-Lin** [comment]
> > 这里大多数需求还是希望能复制里面的元素，所以保留了移入 content 区域还能展示的交互 要实现你的效果可以有两种方式： 一个是控制 visible 自己处理 第二种添加 `overlayStyle={{ pointerEvents: 'none' }}` 阻止 content 元素的所有交互
> 
> 有些时候就 popup 就放些预览图示意一下的，并不需要有什么交互。 我先自己加上吧，你们再评估下要不要做成开箱即用？

其实就算开放了api设置，内部也是会使用 `pointerEvents: 'none'` 方式禁用content 内容的所有交互，我们再观察下是否有足够多的反馈，目前来看还好，后续比较多反馈的话会考虑加上
