### ISSUE TITLE
时间选择器相关问题

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#141]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**
Chrome 95.0.4638.69

**Describe the bug**
自定义步长时间选择器描述与显示不符。应只显示 **时** 和 **分**。
且 **分** 的步长展示效果不明显。建议改为 5 分钟间隔。
![image](https://user-images.githubusercontent.com/43896664/147813671-13cb0313-51bf-4e6b-b6d1-43ce2cb1279f.png)

**Comment by Tenodec** [comment]
而且还有弹出窗，动画时间我个人感觉太长了。感觉就像卡卡的，我选择日期不需要那个多动效，用户使用起来不就会觉得代码问题，为啥第一时间点了要等半天才能出现

**Comment by uyarn** [comment]
@Tenodec popup动画曲线调整了  之前的透明度变化曲线出现时间确实太长 改成linear了 还在验证中

**Comment by uyarn** [comment]
new site has been published, thanks for @Yilun-Sun =D
