### ISSUE TITLE
[Alert 警告] close 值类型为 string 时 message和close之间没呼吸空间

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1413]
### tdesign-react 版本

0.40.5

### 重现链接

https://stackblitz.com/run?file=src%2Fdemo.jsx

### 重现步骤

![100](https://user-images.githubusercontent.com/108825798/188049357-7587db88-2185-4e03-a2a0-76e8661df424.png)

https://393bu8--run.stackblitz.io

### 期望结果

希望close 值类型为 string 时，message和close之间有空隙，不要连在一起

**Comment by carolin913** [comment]
这个是demo展示问题，这里用了Space包裹需要定一下样式就好了，组件本身没问题
<img width="859" alt="image" src="https://user-images.githubusercontent.com/2638568/188360963-70af502a-18ad-4e0b-b549-4b2665e1b693.png">
