### ISSUE TITLE
[DatePicker] 周选择组件在微信浏览器上的显示问题

### ISSUE THREAD

**Issue by notFoundTheGuy** [Tencent/tdesign-react#1416]
### tdesign 版本

0.40.5

### 重现链接

https://tdesign.woa.com/react/components/date-picker

### 重现步骤

<img width="538" alt="image" src="https://user-images.githubusercontent.com/36075073/187822550-af1f57c4-e899-411b-b71b-06ae98fd3d35.png">

**Comment by HQ-Lin** [comment]
微信浏览器对于 `table-row` 类型的盒子表现有点怪异，子元素上下定位全部失效，宽高也无视 `padding` 计算，有点难搞
