### ISSUE TITLE
[Button 按钮] 按钮为ghost状态时，鼠标hover上去时，无法看清文字

### ISSUE THREAD

**Issue by cw1997** [Tencent/tdesign-react#1429]
### tdesign-react 版本

0.40.5

### 重现步骤

<Button
  block={false}
  ghost
  loading={false}
  shape="rectangle"
  size="medium"
  type="button"
  variant="base"
>
  确定
</Button>

### 期望结果

对于ghost状态的按钮，当鼠标hover上去时，文字显示为白色

### 实际结果

![image](https://user-images.githubusercontent.com/11588555/188282951-91d3b5f7-37b9-4e7b-b1b2-1050c74de81c.png)

**Comment by Lmmmmmm-bb** [comment]
duplicate https://github.com/Tencent/tdesign-vue/issues/1246

**Comment by uyarn** [comment]
待发布
<img width="853" alt="image" src="https://user-images.githubusercontent.com/26377630/188303329-b4a4c0ea-8168-4126-99a0-c6d4662aac7b.png">

**Comment by HQ-Lin** [comment]
0.40.6 fixed

**Comment by cw1997** [comment]
> 0.40.6 fixed

Thank you for your team's work!
