### ISSUE TITLE
[ImageViewer] 刚打开时，预览图片尺寸过大

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1435]
### 这个功能解决了什么问题

小屏情况下，图片预览默认尺寸过大，图片没法展示完整，不利于小屏使用。
https://codesandbox.io/s/flefll?file=/src/demo.jsx&resolutionWidth=320&resolutionHeight=675
<img width="386" alt="image" src="https://user-images.githubusercontent.com/37169906/188372959-00c81ed4-bd19-418f-947f-2ddd19c60f62.png">

### 你建议的方案是什么

打开预览时，将图片的 `max-width` 和 `max-height` 设置为 `100%`，确保刚打开时，能看到整张图片。

**Comment by HQ-Lin** [comment]
这里可以优化一下，适配下屏幕尺寸

**Comment by HQ-Lin** [comment]
0.41.1 fixed
