### ISSUE TITLE
[Table] 筛选filterRow={() => null}无法隐藏过滤行

### ISSUE THREAD

**Issue by yunfeic** [Tencent/tdesign-react#1438]
### tdesign-react 版本

0.40.5

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-ci13tv

### 重现步骤

使用talbe filterRow={() => null}属性来隐藏过滤行时，无法隐藏，仍显示在第一行显示空白过滤结果行

### 期望结果

过滤结果行隐藏

### 实际结果

过滤结果行显示

**Comment by chaishi** [comment]
可以给这一行，加一个 `display: none` 临时解决一下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1566

**Comment by HQ-Lin** [comment]
0.42.2 fixed
