### ISSUE TITLE
进度条相关问题

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#144]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
环形进度条半径计算方法有问题
![image](https://user-images.githubusercontent.com/43896664/147818215-17033360-1581-48fd-bd24-f7c6ac0a08b3.png)

修复后
![image](https://user-images.githubusercontent.com/43896664/147818188-196ca57e-8c99-43c9-a9fe-d10ad90ab947.png)

相关解释：
![image](https://user-images.githubusercontent.com/43896664/147818721-53f1c48e-f8e1-45d0-a1a9-d3f9f232c1b9.png)
svg 中 circle 最后呈现的图形总半径其实是「半径 + strokeWidth / 2」

**Comment by uyarn** [comment]
fixed in 0.22.0, thanks for @Yilun-Sun  =D
