### ISSUE TITLE
[Notification] 组件跟Message的offset的表现不一致，是有意设计成这样么？

### ISSUE THREAD

**Issue by szqyqxgs** [Tencent/tdesign-react#1446]
### tdesign-react 版本

0.40.6

### 重现步骤

![200](https://user-images.githubusercontent.com/108825798/188813226-2a1cd20d-1397-40b4-85f5-8358578c19ee.png)

![100](https://user-images.githubusercontent.com/108825798/188813256-241631e8-23e4-4663-b59e-37633f7fa49a.png)

Message组件多个弹框间自带间距，offset是设置全局距离顶部。感觉这样很合理！

而Notification组件多个弹框间默认没有间距，offset是设置每个弹框间的距离，是有意设计成这样的么？还是说这是个bug？

**Comment by chaishi** [comment]
所有组件的 `offset` 都是相对于 `placement` 位置的偏移

**Comment by HQ-Lin** [comment]
这里应该要保持和message一致的效果 
@kenzyyang 看下

**Comment by HQ-Lin** [comment]
0.42.0 fixed
