### ISSUE TITLE
[Steps] 带图标的步骤条图标样式不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-react#1451]
### tdesign-react 版本

0.40.6

### 期望结果

应该是单独24px大小的图标，不是在圈里修改图标

<img width="790" alt="image" src="https://user-images.githubusercontent.com/89069385/188880108-a84c0ede-4c99-4deb-b9e6-cc3244d42853.png">

### 实际结果

包在了圆圈里面，应该是独立展示的

<img width="615" alt="image" src="https://user-images.githubusercontent.com/89069385/188880505-c3da52e1-b93d-4708-9f7e-fe2eaebce614.png">

### 框架版本

0.40.6

**Comment by AqingCyan** [comment]
这里的意思是 图标应该单独展示，而不是在圆圈里展示？
