### ISSUE TITLE
[Select] 在手机上下拉菜单无法滚动，菜单滚动结束后菜单就收起来了

### ISSUE THREAD

**Issue by huangt2012** [Tencent/tdesign-react#1452]
### tdesign-react 版本

0.40

### 重现链接

 https://tdesign.tencent.com/react/components/select#%E5%88%86%E7%BB%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

Select 组件在手机上无法使用，滚动的时候手指松开下拉菜单就收起来了

### 框架版本

React

**Comment by HQ-Lin** [comment]
0.41.0 fixed
