### ISSUE TITLE
[Cascader] 分割线样式不对，整体padding不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-react#1454]
### tdesign-react 版本

0.40.6

### 期望结果

没有圆角，应该使用的是1px @component-stroke 的分割线

<img width="701" alt="image" src="https://user-images.githubusercontent.com/89069385/188888201-9eac4f91-947f-4ba1-9c0c-bb49231a683d.png">

padding应该是单独6px，而不用一整个再包一层

<img width="815" alt="image" src="https://user-images.githubusercontent.com/89069385/188889368-3a99c85d-48ed-42f5-91d6-4b680e0c132a.png">

### 实际结果

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/89069385/188887820-46b735e1-f580-4b06-ac63-12445496e15e.png">

padding要取消
<img width="941" alt="image" src="https://user-images.githubusercontent.com/89069385/188889578-97496e50-0978-4180-8c5c-39e3870f91f7.png">

### 框架版本

0.40.6

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-common/pull/811

**Comment by pengYYYYY** [comment]
已修复

**Comment by HQ-Lin** [comment]
0.42.0 fixed
