### ISSUE TITLE
[Dropdown] hideAfterItemClick 配置在移动端下失效

### ISSUE THREAD

**Issue by mathewzhai** [Tencent/tdesign-react#1459]
### tdesign-react 版本

0.40.6

### 重现步骤

Dropdown  配置 hideAfterItemClick={false}，用移动端（真机或者chrome模拟）打开页面

### 期望结果

点击选项后不要隐藏弹窗

### 实际结果

hideAfterItemClick 在移动端下配置无效，点击选项后始终会关闭弹窗

**Comment by HQ-Lin** [comment]
移动端点击后关闭是popup的问题，我这个 pr 一起修复了
https://github.com/Tencent/tdesign-react/pull/1444

**Comment by HQ-Lin** [comment]
0.41.0 fixed
