### ISSUE TITLE
[Select可过滤的选择器] 展开后失去焦点选中不是我预期的选项

### ISSUE THREAD

**Issue by mbb88868** [Tencent/tdesign-react#1462]
### tdesign-react 版本

0.40.6

### 重现链接

https://tdesign.tencent.com/react/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

1 首选选中的是选项一
![image](https://user-images.githubusercontent.com/78438100/189266481-2447db83-a5ec-4a9f-8756-b2e9bd2c9b1a.png)
2 然后滚动滚动条失去焦点选择一个
![image](https://user-images.githubusercontent.com/78438100/189266739-6eadb405-8521-4662-979a-5b1a6af9afe1.png)
3会跳到之前的选项一
![image](https://user-images.githubusercontent.com/78438100/189266887-06f5700d-efdc-4dbb-9206-495ea276317e.png)

### 期望结果
我期望选中我所选中的
_No response_

### 实际结果
只有失去焦点的时会出现,跑到之前已选择的选项中去了
_No response_

**Comment by HQ-Lin** [comment]
提供一下codesanbox 链接吧，官网案例是正常的

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/react-mbnodx?file=src%2Fdemo.jsx
