### ISSUE TITLE
[Image] ImageViewer使用时，弹窗会跳过handleToggleOverlay，使得overlayContent展示错误

### ISSUE THREAD

**Issue by Ylushen** [Tencent/tdesign-react#1470]
### tdesign-react 版本

0.40.6

### 重现步骤

![image](https://user-images.githubusercontent.com/44960823/189602897-746d9208-2772-447d-8260-174f21850b23.png)

### 期望结果

正确展示内容

### 补充说明

<img width="546" alt="image" src="https://user-images.githubusercontent.com/44960823/189603020-bf64358e-2833-464f-8d09-250b954ebd95.png">
建议在这里，添加固定参数，onMouseLeave重置为false, onMouseEnter重置为true

**Comment by HQ-Lin** [comment]
0.41.1 fixed
