### ISSUE TITLE
[Tree] DataOption节点disabled后，展示收起icon点击无效

### ISSUE THREAD

**Issue by yunfeic** [Tencent/tdesign-react#1473]
### tdesign-react 版本

0.40.6

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-hbtv7t?file=/src/demo.jsx

### 重现步骤

见https://codesandbox.io/s/tdesign-react-demo-forked-hbtv7t?file=/src/demo.jsx

### 期望结果

节点disabled后，仍能展开收起

### 实际结果

节点disabled后，不能展开收起

**Comment by HQ-Lin** [comment]
0.41.0 fixed
