### ISSUE TITLE
[TagInput] 输入空格时，文本位置有问题

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1494]
### tdesign-react 版本

0.41.1

### 重现链接

[Code Sandbox](https://codesandbox.io/s/xseein?file=/src/demo.jsx)

### 重现步骤

输入文本后再输入空格，字符部分被挤出
![QQ20220919-102722-HD](https://user-images.githubusercontent.com/37169906/190940825-ddc8997e-f20f-48e2-a3a9-06a7f59b1de3.gif)

### 期望结果

字符位置能保持正常

### 实际结果

字符部分被挤出

**Comment by HQ-Lin** [comment]
0.42.0 fixed
