### ISSUE TITLE
[Dropdown] 未采用通用阴影

### ISSUE THREAD

**Issue by mathewzhai** [Tencent/tdesign-react#1499]
### tdesign-react 版本

0.41.1

### 重现步骤

Dropdown 的阴影应该和 select popup tooltip 的阴影保持一致？

Dropdown 阴影 
<img width="134" alt="image" src="https://user-images.githubusercontent.com/106570404/190973824-81c79f06-aed4-44e2-9fba-9a8959a1d409.png">

Select 阴影
<img width="244" alt="image" src="https://user-images.githubusercontent.com/106570404/190974020-3f55304f-e35f-40ff-9b9e-6662fcf943e6.png">

Popup 阴影
<img width="251" alt="image" src="https://user-images.githubusercontent.com/106570404/190974125-45a0e413-5f15-42c9-8f40-da8511d53eb3.png">

Tooltip 阴影
<img width="149" alt="image" src="https://user-images.githubusercontent.com/106570404/190974504-e53b2244-c010-4841-beab-9343b7e7205d.png">

**Comment by uyarn** [comment]
cc @wen1kang

**Comment by Wen1kang** [comment]
我的锅，应该是shadow2

**Comment by HQ-Lin** [comment]
0.42.3 fixed
