### ISSUE TITLE
[Table] 单元格中编辑校验数据异常（可编辑行数据校验）

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1514]
### tdesign-react 版本

0.42.0

### 重现链接

https://stackblitz.com/edit/react-bbqyd1?file=src%2Fdemo.jsx,package.json,src%2Findex.js

### 重现步骤

1. 将组件数据清空
2. 点击保存
3. 出现一次错误信息后，继续点保存，空数据也能保存成功

https://user-images.githubusercontent.com/37169906/191685507-3032037f-a91d-415e-be65-624c2281a56f.mp4

https://user-images.githubusercontent.com/37169906/191428660-56609c41-1a24-4259-a0cb-f83766ae1de6.mp4

### 期望结果

再次点击保存时，依旧有校验失败信息

### 实际结果

第二次保存成功了

### 框架版本

React 16.13.1

### 补充说明

第二次点击保存时貌似读取了 row 的原始数据，导致可以通过校验

**Comment by chaishi** [comment]
经过测试，React 确实存在校验问题（Vue2 和 Vue3 没有问题）

我来处理一下
