### ISSUE TITLE
[Collapse]某些场景无法收起

### ISSUE THREAD

**Issue by extimo** [Tencent/tdesign-react#1517]
https://stackblitz.com/edit/react-mejowu?file=src%2Fdemo.jsx

**Comment by AqingCyan** [comment]
似乎是Form组件造成的

**Comment by duanbaosheng** [comment]
这里原因是form中的一个css 浮动属性，影响了collapse组件的样式。我来改一下

**Comment by HQ-Lin** [comment]
0.42.3 fixed
