### ISSUE TITLE
[Select] 新创建的条目与已有项重复时，重复显示

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1519]
### tdesign-react 版本

0.42.0

### 重现步骤

1. Select组件，打开filterable与creatable
2. 设置若干option，保持label与value一致（确保不是value不一致的逻辑正确但显示不合理情况）
3. 输入与已有options重复的项

### 期望结果

新创建的条目与已有项重复时，应只显示一个

### 实际结果

出现两个重复项
![企业微信截图_5bb3aa03-5dfd-410a-9597-65e3ccf0701e](https://user-images.githubusercontent.com/34512403/191520973-00c8bab6-8e99-434b-99b2-c6b326b3fb10.png)

### 框架版本

tdesign-react 0.42.0

**Comment by HQ-Lin** [comment]
0.42.3 fixed
