### ISSUE TITLE
[Select] filterable输入值时下拉框没有自动弹出

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1523]
### tdesign-react 版本

0.42.0

### 重现步骤

1、配置支持搜索的Select，以官网demo的【多选选择器】为例
2、点击空白处两次，使组件input部分处于focus状态，下拉框处于收起状态
<img width="847" alt="image" src="https://user-images.githubusercontent.com/34512403/191674578-e35d036f-b2c6-47d0-8bc7-bf3ed0b787d3.png">

3、搜索合法的筛选项，此时没有匹配的项展示。若重新展开下拉框，则输入的搜索项会被清空，需要重新输入
<img width="856" alt="image" src="https://user-images.githubusercontent.com/34512403/191674623-16db056b-aa5f-438b-b63a-ac19a0c7aa0b.png">

### 期望结果

<img width="858" alt="image" src="https://user-images.githubusercontent.com/34512403/191674519-3e1e9a9c-aa50-4fb7-834a-5e1d423f6c6c.png">

**Comment by uyarn** [comment]
这个交互在处理了 下个版本会改正。

**Comment by HQ-Lin** [comment]
0.42.2 fixed
