### ISSUE TITLE
[select] when multiple is true, values can still be deleted although its disable

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#1525]
### tdesign-react 版本

new 0.42.0

### 重现链接

https://tdesign.tencent.com/react/components/select

### 期望结果

the value should not be deleted

**Comment by fangxiezhen** [comment]
the option text need to be disabled too

**Comment by AqingCyan** [comment]
soga

**Comment by AqingCyan** [comment]
> soga

我来尝试fix

**Comment by HQ-Lin** [comment]
0.42.1 fixed
