### ISSUE TITLE
[SelectInput] react 低版本下 BreakSpace 删除失效

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1527]
### tdesign-react 版本

0.42.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-8dj9v3?file=/src/demo.jsx

### 重现步骤

在有 tag 的情况下按退格键 (breakspace) 

### 期望结果

会触发删除标签操作

### 实际结果

不会触发删除操作

### 框架版本

React 16.13.1

### 补充说明

TagInput 组件也有这个问题

**Comment by HQ-Lin** [comment]
0.42.1 fixed
