### ISSUE TITLE
使用autosize={{ minRows: 1, maxRows: 2 }}时，刷新页面文本域高度抖动，且文本域宽度固定时，字符限制挡住文本域文案

### ISSUE THREAD

**Issue by CuzyouZQL** [Tencent/tdesign-react#1528]
### tdesign-react 版本

0.39.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-blozft?file=/src/demo.jsx:350-387

### 重现步骤

1.刷新页面，文本域高度抖动
2.输入文本域文案，字符限制挡住文本域文案

### 框架版本

react16.12.0

### 浏览器版本

Chrome(104.0.5112.79)

### 系统版本

MaxOs(10.15.7 )

### Node版本

14.19.1

**Comment by duanbaosheng** [comment]
对于这两个问题：
1. 确实存在高度抖动的问题，
2. 字符限制文案阻挡文本的情况存在
我来解决一下这两个问题
