### ISSUE TITLE
[TagInput] placeholder 宽度异常

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1530]
### tdesign-react 版本

0.42.0

### 重现链接

https://tdesign.tencent.com/react/components/tag-input

### 重现步骤

`hover` 到 `TagInput` 上, `placeholder` 展示不全。
<img width="902" alt="image" src="https://user-images.githubusercontent.com/37169906/191930747-be07c2e3-51f0-45c9-b227-1893e1940433.png">

### 期望结果

`placeholder` 能展示全

### 实际结果

`placeholder` 展示不全

### 补充说明

高阶组件 `SelectInput` 也有这个问题

**Comment by AqingCyan** [comment]
我来尝试fix一下这个问题🤏

**Comment by moecasts** [comment]
> 我来尝试fix一下这个问题🤏
好像是因为给了个 width，导致了这个错误
![image](https://user-images.githubusercontent.com/37169906/192096440-42903b80-8975-4ec0-b26a-3b4a3b722792.png)

**Comment by HQ-Lin** [comment]
0.42.1 fixed
