### ISSUE TITLE
[文档过时] Layout 布局： Aside组件似乎已更名为Sider

### ISSUE THREAD

**Issue by sheason2019** [Tencent/tdesign-react#154]
文档内容：

![layout1](https://user-images.githubusercontent.com/73812146/148003171-f9450cf4-ca39-448c-9c48-a981dbb91151.png)

代码内容：

![layout2](https://user-images.githubusercontent.com/73812146/148003207-6e9a1311-de2b-4c80-a43b-d0428100be34.png)

**Comment by chaishi** [comment]
这… 两者没有关系 @HQ-Lin 看看是不是导出出错了

**Comment by HQ-Lin** [comment]
> 这… 两者没有关系 @HQ-Lin 看看是不是导出出错了

早期应该是叫 `Sider` 吧代码一直没变过...  我处理下
