### ISSUE TITLE
[Select] 浮层宽度不稳定

### ISSUE THREAD

**Issue by blanky01** [Tencent/tdesign-react#1540]
### tdesign-react 版本

0.42.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-rr6ove?file=/src/demo.jsx

### 重现步骤

1.初始加载点开浮层，这时浮层宽度是按内容自适应的。
2.关闭浮层再次打开，这时浮层宽度变成和trigger一样的宽度了，并且当浮层内的文本被截断时没有完整内容的hover tips。

### 期望结果

1.在没有限定浮层宽度时，浮层按照内容自适应。或者开放配置可以配置浮层宽度模式。
2.内容被截断时有完整内容的hover tips

### 框架版本

react

### 浏览器版本

Chrome（ 103.0.5060.114）

**Comment by carolin913** [comment]
style是设置input框宽度的，autowidth的含义是这个输入框的宽度要随着选中项的宽度变化而变化，随意如果设置了style那autowidth没法生效的

这里的用法建议改成以下方式，下拉浮层只要不是内容特别特别长，宽度随下拉选项内容才是最合理的交互
https://codesandbox.io/s/tdesign-react-demo-forked-mn73d3?file=/src/demo.jsx

**Comment by blanky01** [comment]
> style是设置input框宽度的，autowidth的含义是这个输入框的宽度要随着选中项的宽度变化而变化，随意如果设置了style那autowidth没法生效的
> 
> 这里的用法建议改成以下方式，下拉浮层只要不是内容特别特别长，宽度随下拉选项内容才是最合理的交互 https://codesandbox.io/s/tdesign-react-demo-forked-mn73d3?file=/src/demo.jsx

**Comment by blanky01** [comment]
> style是设置input框宽度的，autowidth的含义是这个输入框的宽度要随着选中项的宽度变化而变化，随意如果设置了style那autowidth没法生效的
> 
> 这里的用法建议改成以下方式，下拉浮层只要不是内容特别特别长，宽度随下拉选项内容才是最合理的交互 https://codesandbox.io/s/tdesign-react-demo-forked-mn73d3?file=/src/demo.jsx

问题解决了，多谢
