### ISSUE TITLE
[ImageViewer] 样式问题

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign-react#1542]
### tdesign-react 版本

React 0.42.0

### 1.悬浮态下，icon的大小不对
·应为16×16
<img width="192" alt="截屏2022-09-26 13 55 09" src="https://user-images.githubusercontent.com/103838357/192203335-79306c40-1678-438f-b21e-7850bcccb8ca.png">
### 2.小窗缺少阴影
·阴影为--td-shadow-3
<img width="1042" alt="截屏2022-09-26 13 56 03" src="https://user-images.githubusercontent.com/103838357/192203402-6593dc3e-673d-491d-bfd5-1186e7280695.png">
### 3.文字提示无白色描边
·应去掉描边
<img width="354" alt="截屏2022-09-26 13 56 55" src="https://user-images.githubusercontent.com/103838357/192203611-94745c8a-3d2d-42d3-8bfd-e56bba2fea38.png">
### 4.文字提示与操作区的间距不对
·应为8
<img width="368" alt="截屏2022-09-26 13 58 48" src="https://user-images.githubusercontent.com/103838357/192203891-bf01deb3-bf1c-4bed-afd3-875744b9766b.png">
### 5.缩略图尺寸不对
·应为52*32
<img width="523" alt="截屏2022-09-26 14 01 14" src="https://user-images.githubusercontent.com/103838357/192204096-c7bf6a35-c7e3-40b8-93bd-3eaa32beefe0.png">
### 6.缩略图的间距不对
·应为8
<img width="171" alt="截屏2022-09-26 14 02 10" src="https://user-images.githubusercontent.com/103838357/192204250-a3b7fbfa-662b-4f16-9e6c-f71a3f4d9fd8.png">
### 7.提示的高度位置不对
·应与页面顶部保持92的距离。
<img width="1233" alt="截屏2022-09-27 16 50 57" src="https://user-images.githubusercontent.com/103838357/192480243-f8bf084b-fabb-468a-9b15-2781c34e9550.png">
### 8.提示的文案不对
·应为“相册封面标题1/5”
<img width="1036" alt="截屏2022-09-26 14 04 51" src="https://user-images.githubusercontent.com/103838357/192204571-e50b188a-7972-4855-bab7-8d803f234b71.png">
### 9.收起箭头和缩略图间距不对
·应为8
<img width="423" alt="截屏2022-09-26 14 05 56" src="https://user-images.githubusercontent.com/103838357/192204739-84ca1d9a-cb93-455f-bc71-23e58aaae2d3.png">
### 10.封面操作按钮间距不对
·应为16
<img width="282" alt="截屏2022-09-26 14 07 44" src="https://user-images.githubusercontent.com/103838357/192204888-a50208fd-c5a8-4838-b1af-c832fea80ded.png">
### 11.渐进加载样式未显示
·应增加“加载样式”时长
<img width="329" alt="截屏2022-09-26 14 09 33" src="https://user-images.githubusercontent.com/103838357/192205196-10d1d99a-6a6b-4dd8-880b-acd278436884.png">

**Comment by Ylushen** [comment]
第4点 为组件TooltipLite自带属性
第11点 图片有优先使用预加载图片，网速过快效果不明显。
