### ISSUE TITLE
使用autosize时，刷新页面textarea高度抖动，字符限制数挡住textarea文案

### ISSUE THREAD

**Issue by CuzyouZQL** [Tencent/tdesign-react#1544]
### tdesign-react 版本

0.39.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-sd0iv9?file=/src/demo.jsx

### 重现步骤

刷新页面时高度先渲染最小行数高度后变成最大行数高度，设置固定宽度时，文本文案输入满输入框时，限制字符数遮挡文本文案

### 框架版本

react16.12.0

### 浏览器版本

Chrome(104.0.5112.79)

### 系统版本

MaxOs(10.15.7 )

### Node版本

14.19.1

**Comment by HQ-Lin** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/24469546/192222559-7066a28a-1c3e-4c6b-b35a-e9d72f828590.png">
限制文案遮挡输入的文字问题我让设计师一起看看
高度抖动问题我处理下

**Comment by GuangMingZ** [comment]
同样遇到该问题，textarea这里的处理确实可以优化下
