### ISSUE TITLE
希望Layout中的Sider增加对styled-components的支持

### ISSUE THREAD

**Issue by sheason2019** [Tencent/tdesign-react#155]
# 文档描述

> 当子元素中包含 `<Aside>` 时，全部子元素会水平排列，否则会垂直排列。

# 现状

我使用`styled-components`包裹了一下`Sider`组件，希望能在保持横向flex的同时自定义侧边栏的样式。

```javascript
import React from 'react';
import { Layout } from 'tdesign-react';
import styled from 'styled-components';

const { Header, Content, Sider } = Layout;

const StyledHeader = styled(Header)`
  background: white;
  font-size: 1.5rem;
  box-shadow: 2px 1px 2px 0 gray;
  position: sticky;
  z-index: 200;
`;
const StyledSider = styled(Sider)`
  border-radius: 0.5rem;
`;
const IconContainer = styled.div`
  width: 14.5rem;
  display: flex;
  justify-content: center;
  align-items: center;
`;
const Root = styled(Layout)`
  min-height: 100vh;
`;
console.log(<StyledSider />);
console.log(<Sider />);

const LayoutContainer: React.FC = () => {
  return (
    <Root>
      <StyledHeader>
        <IconContainer>View Mock</IconContainer>
      </StyledHeader>
        <Layout>
          <StyledSider>
            1
          </StyledSider>
          <Content>
            123
          </Content>
        </Layout>  
    </Root >
  )
};

export default LayoutContainer;

```

表现：

![layout3](https://user-images.githubusercontent.com/73812146/148004432-f84a0bc1-f146-4997-8c33-81fe6d02d42a.png)

实际渲染出来的direction是纵向的。

个人分析：

Layout的Class挂载逻辑可能不支持styled-components，在这个情况下的Layout class如下图所示：

![layout4](https://user-images.githubusercontent.com/73812146/148004610-0921052d-babc-47d1-ab7f-aa851c3b22ba.png)

是`t-layout`，而观察源码：

![layout5](https://user-images.githubusercontent.com/73812146/148004678-25aadd7f-12a1-487c-b2d3-d65e4910f082.png)

发现横向时的代码应该是`t-layout--with-sider`，因为useEffect中判断有无`Sider`组件的逻辑是根据`child.type`判断的，而Styled-components会把组件封装一次，将原组件的类型保存到`target`属性中，导致Layout的方向失效。

![layout6](https://user-images.githubusercontent.com/73812146/148004973-273df575-056a-4eb3-8de1-04d8602c7c2d.png)

如图：上面是`Styled-components`组件，下面是t-design的`Sider`组件，可以看到Sider组件类型被封装到了`type.target`属性里，导致Layout没有在逻辑中找到children中的Sider组件。

**Comment by HQ-Lin** [comment]
很详细的 issue ，之前没考虑到会有这类情况，这两天处理下

**Comment by HQ-Lin** [comment]
尝试改造了一下，感觉不太通用，style-components 将 type 改动的有点多后续还需要跟踪他们版本的字段变化，还是开放 direction api 给到用户自由选择吧。
如果理想状态下嵌套 Aside 组件我还是会自动判断方向，优先级最高的还是用户指定的 direction。
详见以下 commit：
https://github.com/Tencent/tdesign-react/pull/157/commits/84485811f5f7f99188fe8c9661a74570004c7571

**Comment by sheason2019** [comment]
👍🏻，那这个issue我先关掉了？

**Comment by HQ-Lin** [comment]
> 👍🏻，那这个issue我先关掉了？

这两天发版本我会清理一波 issue，我来关吧

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-react/releases/tag/0.22.0 fixed
