### ISSUE TITLE
[TreeSelect] 启用filterable时会闪一下

### ISSUE THREAD

**Issue by Thinker-Mars** [Tencent/tdesign-react#1565]
### tdesign-react 版本

0.42.1

### 重现步骤

		<TreeSelect
			filterable
			data={TodoTree}
			value={value}		
		/>

### 期望结果

点击TreeSelect时不闪

### 框架版本

17.x

### 系统版本

Win10 21H2

### Node版本

16.14.0

**Comment by HQ-Lin** [comment]
0.42.2 fixed
