### ISSUE TITLE
[upload] 编译后的esm upload.d.ts 引入interface不存在

### ISSUE THREAD

**Issue by genyuMPj** [Tencent/tdesign-react#1586]
### tdesign-react 版本

0.42.2

### 重现链接

https://github.com/Tencent/tdesign-react/blob/0.42.2/src/upload/interface.d.ts

### 重现步骤

<img width="600" alt="image" src="https://user-images.githubusercontent.com/50562327/195086456-aa73d7d7-f5f8-4466-a440-70326a87751c.png">
****
npm 包中，tdesign-react/esm/upload/upload.d.ts中，
import { UploadProps, UploadRef } from './interface'; 如图，interface 文件不存在。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1616
