### ISSUE TITLE
Popup 组件的内容（children）不支持自定义组件

### ISSUE THREAD

**Issue by LisaIsCoding** [Tencent/tdesign-react#1588]
### tdesign-react 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-45cbq6?file=/src/demo.jsx

### 重现步骤
见视频
[tdesign-react-demo (forked) - CodeSandbox.webm](https://user-images.githubusercontent.com/101237384/195289280-68c27630-7198-42e3-a057-7373466ffd56.webm)

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-66s1rl
先透传一下props，下版本兼容下报错，但是这种不透传props的自定义组件本身就没办法做popup定位计算

**Comment by LisaIsCoding** [comment]
了解，能否把 `Anchor` 或 `popupState` 暴露出来呢，pop 自定义组件还是很常用的。我理解你这里透传下去的 props，其实只是需要用里边的一两个属性而已，只是 `<Button {...props}>` 这样写是解决当前这个问题的最快速简单的回复，对吗？

---
https://mui.com/material-ui/react-popover/

**Comment by LisaIsCoding** [comment]
> https://codesandbox.io/s/tdesign-react-demo-forked-66s1rl 先透传一下props，下版本兼容下报错，但是这种不透传props的自定义组件本身就没办法做popup定位计算

这个方法在 0.35.1 行不通，想问一下修复这个问题的版本是多少呢
https://codesandbox.io/s/tdesign-react-demo-forked-7y02e6?file=/src/demo.jsx
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/101237384/195490198-3caa3f43-5aaa-453f-a044-abe5e9555a2a.png">

**Comment by HQ-Lin** [comment]
> 了解，能否把 `Anchor` 或 `popupState` 暴露出来呢，pop 自定义组件还是很常用的。我理解你这里透传下去的 props，其实只是需要用里边的一两个属性而已，只是 `<Button {...props}>` 这样写是解决当前这个问题的最快速简单的回复，对吗？
> 
> https://mui.com/material-ui/react-popover/

因为popup需要代理trigger 元素的 mouseEnter click 等交互事件来实现不同的触发效果，所以需要trigger元素支持属性透传，不是很理解你说的 anchor、popupState 指的是什么。
placement应该就是你说的 anchor？
这个组件是基于popperjs给的定位计算能力，组件也有暴露 getPopper 方法，可以通过ref 获取，应该就是你说的 popupState？

**Comment by HQ-Lin** [comment]
> > https://codesandbox.io/s/tdesign-react-demo-forked-66s1rl 先透传一下props，下版本兼容下报错，但是这种不透传props的自定义组件本身就没办法做popup定位计算
> 
> 这个方法在 0.35.1 行不通，想问一下修复这个问题的版本是多少呢 https://codesandbox.io/s/tdesign-react-demo-forked-7y02e6?file=/src/demo.jsx <img alt="image" width="1449" src="https://user-images.githubusercontent.com/101237384/195490198-3caa3f43-5aaa-453f-a044-abe5e9555a2a.png">

popup在 0.40.0 重构了一版本，处理了比较多的问题，建议升级一下新版本
