### ISSUE TITLE
upload组件不能上传gif图片

### ISSUE THREAD

**Issue by CuzyouZQL** [Tencent/tdesign-react#1592]
### tdesign-react 版本

0.39.0

### 重现链接

https://codesandbox.io/s/fxg3t3?file=/src/demo.jsx

### 框架版本

react16.12.0

### 浏览器版本

Chrome(104.0.5112.79)

### 系统版本

MaxOs(10.15.7 )

### Node版本

14.19.1

**Comment by chaishi** [comment]
可以先尝试使用自定义上传方法 `requestMethod`
