### ISSUE TITLE
[Select] onCreate与multiple不兼容

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1593]
### tdesign-react 版本

0.42.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-yi8uno?file=/src/demo.jsx

### 重现步骤

官网创建新条目demo，增加multiple={true}，onCreate不可用（value变成了数组）

### 期望结果

添加的项与实际的项一致

**Comment by uyarn** [comment]
你需要同时把value改成数组 multiple的格式下就是数组value 我们再补充个新的示例
