### ISSUE TITLE
站点无法访问

### ISSUE THREAD

**Issue by snakeUni** [Tencent/tdesign-react#16]

**Comment by chaishi** [comment]
收到，我们尽快处理

**Comment by HQ-Lin** [comment]
目前外网域名还未做公网解析，待正式开源后会访问正常，先使用内网域名访问

**Comment by notFoundTheGuy** [comment]
![image](https://user-images.githubusercontent.com/36075073/146722304-cfc9171f-4c21-4e69-986f-670222eeabae.png)
Message类方法，文档中duration是可选的，默认3000，但是生成的TS声明为必填
