### ISSUE TITLE
[穿梭框] 文字过多的情况下checkbox变形

### ISSUE THREAD

**Issue by dufemeng** [Tencent/tdesign-react#1605]
### tdesign-react 版本

最新版本

### 重现链接

https://tdesign.tencent.com/react/components/transfer

### 重现步骤

<img width="814" alt="截屏2022-10-18 15 05 47" src="https://user-images.githubusercontent.com/10006784/196360193-8f4e67b8-9257-4d37-87a3-6741b5b9b04f.png">

### 期望结果

不要变形

### 实际结果

变形了

**Comment by uyarn** [comment]
fixed 0.42.6
