### ISSUE TITLE
[Menu] 双层导航 菜单切换后子菜单 bar 位置不对

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#161]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
官网示例 -> 双层导航 -> 选择「菜单3」 -> 选择「二级菜单-2」-> 选择「菜单2」
效果：原「二级菜单-2」下的蓝条并未消失
![image](https://user-images.githubusercontent.com/43896664/148041678-5b462c3a-0fcb-4aed-b32f-741a77d22363.png)

**Additional context**

**Comment by HQ-Lin** [comment]
@andyjxli 帮忙看下

**Comment by andyjxli** [comment]
tab's value  can't  be controled
