### ISSUE TITLE
[ImageViewer] 无法指定挂载的dom节点

### ISSUE THREAD

**Issue by lgybetter** [Tencent/tdesign-react#1610]
### 这个功能解决了什么问题

React 版本 ImageViewer 图片预览组件目前没有有 api 可以指定 dom 挂载渲染的节点，在微前端框架中使用，需要能够指定全局弹窗类的 dom 节点，防止样式在沙箱模式中丢失。

### 你建议的方案是什么

希望能够提供跟 Dialog 组件一样的api: attach，用于指定 ImageViewer 图片预览挂载渲染的节点，
![image](https://user-images.githubusercontent.com/18067476/196882593-e85816b1-5cdc-4ff6-a07e-1aaceeb03819.png)

**Comment by HQ-Lin** [comment]
合理，这周补充一下
