### ISSUE TITLE
关于无障碍化的支持，请问是否有相关的计划？

### ISSUE THREAD

**Issue by jiangyijie27** [Tencent/tdesign-react#1625]
### 这个功能解决了什么问题

用 Chrome Screen Reader 体验了一下 Tabs / Dropdown 等组件，对于无障碍化（accessibility) 的支持比较有限。

请问有没有关于支持无障碍化的 roadmap？

### 你建议的方案是什么

无

**Comment by xiaosansiji** [comment]
组件库的无障碍改造刚刚启动，现在是在移动端（小程序）技术栈上在做，桌面端预计要等小程序改造差不多后才会启动，大概在年底或23年初
