### ISSUE TITLE
[Cascader] 当节点为非叶子节点时，无法被搜索到

### ISSUE THREAD

**Issue by GuangMingZ** [Tencent/tdesign-react#1629]
### tdesign-react 版本

0.40.6

### 重现链接

https://stackblitz.com/edit/react-ts-jwzxds?file=App.tsx,index.tsx,index.html

### 重现步骤

1. 输入1搜索节点
2. 搜索结果为“暂时数据”

### 期望结果

搜索出label为1的节点

### 实际结果

搜索结果为空（暂无数据）

### 框架版本

React18

### 浏览器版本

Chrome 106.0.5249.119

### 系统版本

MacOS Monterey 12.5.1

### Node版本

v16.8.0

**Comment by HelKyle** [comment]
原因是，你的 options 写的有问题，`children: true` 会被树组件认为是非叶子节点 [代码](https://github.com/Tencent/tdesign-react/blob/4933c0222ad7a44b9e73eb8a125308d17e1f5189/src/cascader/core/effect.ts#L178)，在过滤的时候不生效。把它去掉就可以了。

```js
const options = [
  { value: 1, label: '1' },
  { value: 2, label: '2' },
  { value: 3, label: '3' },
];
```
