### ISSUE TITLE
[Table] 基础示例 Pagination 不正常工作

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#163]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
基础示例 Pagination 不正常工作
点击无反应
![image](https://user-images.githubusercontent.com/43896664/148050814-cd8a14c8-ff23-4995-8ffe-4df100105cee.png)

**Additional context**

**Comment by yunfeic** [comment]
【原因】该demo分页提供的是受控用法，demo中受控逻辑暂未补全。后面会优化调整下
【建议】table分页完整用法，建议看下“可分页的表格”demo

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-react/pull/164 fixed
