### ISSUE TITLE
[Table] 合并cell很难，rowspanAndColspan函数并不好用，甚至用不明白。

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign-react#1632]
### 这个功能解决了什么问题

可以通过data，自动检测需要合并的cell，而不是通过再写rowspanAndColspan进行合并，表头也是一样的，如果一样的希望可以自动合并。

### 你建议的方案是什么

可以通过data，自动检测需要合并的cell，而不是通过再写rowspanAndColspan进行合并，表头也是一样的，如果一样的希望可以自动合并。

**Comment by chaishi** [comment]
辛苦提供一下自动合并的算法，入参和出参分别是什么。满足什么条件，进行什么操作，得出什么结果。

是否所有业务都可用

**Comment by 2513483494** [comment]
比如table增加一个字段，mergeCell，开启合并模式后，data：[{name:'a',type:'a1'},{name:'a',type:'a2'}],那么name相同，这两个地方就进行合并，就是这个意思。

**Comment by chaishi** [comment]
`rowspanAndColspan` 函数不好用，也用不明白，说明这个函数在某些场景下存在 BUG，

提供示例代码 以及 期望实现的效果，然后针对明确的问题或需求，我们便可以解决问题

**Comment by chaishi** [comment]
> 比如table增加一个字段，mergeCell，开启合并模式后，data：[{name:'a',type:'a1'},{name:'a',type:'a2'}],那么name相同，这两个地方就进行合并，就是这个意思。

也可以描述的还不够清晰，纵向相同合并，还是横向相同合并，还是都合并。还是特殊场景下某个单元格也要合并，或者跨行合并

**Comment by 2513483494** [comment]
目前就是有这个想法，感觉会极大增加这个合并单元格的易用性，提一个意见。
目前我在写合并单元格时，这样写的
<img width="804" alt="截屏2022-10-28 11 19 36" src="https://user-images.githubusercontent.com/48058550/198494586-1f198f0b-36d0-4e4b-922f-da259528b196.png">
我认为就是第一列全都占三行，但是表现确实这样的
<img width="1348" alt="截屏2022-10-28 11 20 07" src="https://user-images.githubusercontent.com/48058550/198494659-cf7f5e13-9b20-41c2-94f0-a9f72adb65df.png">
所以用起来就很疑惑
data是这样的
<img width="377" alt="截屏2022-10-28 11 20 40" src="https://user-images.githubusercontent.com/48058550/198494717-f8409b9c-026e-42be-95d2-d20703374438.png">

**Comment by 2513483494** [comment]
合并策略我觉得可以选择，比如横向合并、纵向合并、混合合并、横的字段可以自行设置或者默认全部字段都合并，相同的就合并等等，这样直接写data就可以合并了，目前通过异步获取data，再写rowspanAndColspan，我还没有很好的实现合并单元格，文档也没有很清晰，不确定怎么写rowspanAndColspan这个函数。

**Comment by 2513483494** [comment]
企微jiqixing，有可能的话，企微联系呢，想了解一下rowspanAndColspan，应该怎么写，比如异步获取到了data，我怎么写rowspanAndColspan函数才能正确合并单元格，实在疑惑。

**Comment by chaishi** [comment]
后面时间充足一些的时候，会逐步实现相同内容单元格合并。
当前，我们先一起解决 `rowspanAndColspan` 的问题，想来应该是有些 BUG

**Comment by chaishi** [comment]
以后可以点击这里，发布完整的，可运行的示例代码。（不要复制代码，更不要截图，大家的时间有限，这次我先试着一个字母一个字母敲）

<img width="336" alt="image" src="https://user-images.githubusercontent.com/11605702/198870265-3659e111-f4f7-47b2-93c7-e870d2904cbe.png">

**Comment by chaishi** [comment]
合并相同行数据，示例代码。需准确计算哪一个行需要 rowspan: 3，也再仔细理解下 `rowspan` 的含义，`rowspan > 1` 除了自己还会隐藏后面的 `rowspan - 1` 行

```
function rowspanAndColspan({ col, rowIndex, colIndex }) {
    // 如果当前行和下一行的数据不相同，则开始合并相同数据
    if (colIndex === 0) {
      const mergeName = data[rowIndex].queueName;
      let sameLine = 0;
      for (let i = rowIndex; i < data.length; i++) {
        if (mergeName === data[i].queueName) {
          sameLine += 1;
        } else {
          break;
        }
      }
      return {
        rowspan: sameLine,
        colspan: 1,
      }
    }
  }
```

**Comment by 2513483494** [comment]
> 

发现更新了版本后，这个合并的方式大多数情况下不生效了。
也就是刷新页面100次大概生效30次的样子。

**Comment by heeween** [comment]
只有在一修改的那瞬间可以看到合并单元格是生效的，但是网络请求回来就不生效了。Ai最后帮我解决了这个问题，添加了:key 绑定。这样会使得rowspanAndColspan重新计算。:key="followTableStore.tableData.length"
