### ISSUE TITLE
[popup] 设置了 offset 后，hover 触发方式下，content 会闪烁

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#1639]
### tdesign-react 版本

0.42.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lrmslc?file=/src/demo.jsx

### 补充说明

https://user-images.githubusercontent.com/29194619/198923101-f88c31f8-7d6f-4fbb-93d0-6196c32f2135.mov

**Comment by HQ-Lin** [comment]
emm 因为移出trigger 元素原本是要隐藏浮层的，但是又出发了浮层的hover显示了

**Comment by honkinglin** [comment]
可以使用 delay api 延迟关闭 popup
