### ISSUE TITLE
[Message] 组件的函数调用方式，在组件加载完成后未执行

### ISSUE THREAD

**Issue by my3188** [Tencent/tdesign-react#1640]
### tdesign-react 版本

0.42.4

### 重现链接

https://stackblitz.com/edit/react-q1wcdi?file=src%2Fdemo.jsx

### 重现步骤

等待页面加载完成

### 期望结果

弹窗message提示

### 实际结果

没有弹出

**Comment by kenzyyang** [comment]
https://github.com/Tencent/tdesign-react/pull/1641
