### ISSUE TITLE
[Select] Select内容宽度与触发元素宽度不一致

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1643]
### tdesign-react 版本

0.42.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-weec49?file=/src/demo.jsx

### 重现步骤

dropdown宽度大于触发器的宽度时，dropdown内容不能完整显示。
![image](https://user-images.githubusercontent.com/34512403/199020735-f391e7aa-425a-495b-863a-57844c972f3e.png)

**Comment by uyarn** [comment]
fixed 0.42.6
