### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by cq0702** [Tencent/tdesign-react#1647]
### tdesign-react 版本

是

### 重现步骤

自定义一个父类组件，有点击事件，在父类组件下添加子类图片组件，点击图片，预览，仿造官方预览demo，在点击预览的同时增加阻止事件冒泡代码
const trigger = ({open}) => {
                        console.log('--trigger-open--',open)
                        const mask = (
                            <div>
                                <div
                                    style={{
                                        background: 'rgba(0,0,0,.6)',
                                        color: '#fff',
                                        height: '100%',
                                        display: 'flex',
                                        alignItems: 'center',
                                        justifyContent: 'center'
                                    }}
                                    onClick={(e)=>{
                                        e.stopPropagation();
                                        e.nativeEvent.stopPropagation();
                                        e.nativeEvent.stopImmediatePropagation();
                                        console.log('--trigger-e--',e)
                                        open();
                                    }}
                                >

### 期望结果

执行open预览代码，图片预览，并且父类onclick事件不执行

### 实际结果

执行open预览代码，图片预览，父类onclick事件不执行，然后点击关闭预览，发现父类onclick事件执行了

### 框架版本

0.42.1

### 浏览器版本

 chrome(106.0.5249.119)

### 系统版本

MacOS(12.5.1 (21G83))

### Node版本

v16.17.0

**Comment by HQ-Lin** [comment]
都写了这么多文字了，要不给个可以复现的 demo 链接吧哥
<img width="441" alt="image" src="https://user-images.githubusercontent.com/24469546/199430154-1f24ca4a-2bf6-4671-b23f-1736b8421d65.png">
