### ISSUE TITLE
[input-number] theme 设置为 column 并启用 autoWidth 时，按钮位置错误

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-react#1652]
### tdesign-react 版本

tdesign-react 0.42.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-7ufimt?file=/src/demo.jsx

### 重现步骤

使用 `InputNumber` 组件，将 `theme` 属性的值设为 `"column"` ，即增减按钮出现在输入框右侧。

同时设置 `autoWidth` 属性为 `true` ，即输入时自动调整组件宽度。

### 期望结果

进行输入时，组件自动调整宽度，组件右侧的增减按钮也应当自动调整位置，保证出现在输入框右侧。

### 实际结果

组件自动调整宽度时，增减按钮的位置不会自动调整，固定在起始位置上，即有时会出现在输入框中间。

### 框架版本

React(17.0.2)

### 浏览器版本

Chrome(104.0.5112.102)

### 系统版本

Windows 10

### Node版本

14.15.1

**Comment by chaishi** [comment]
效果确实丑
<img width="793" alt="image" src="https://user-images.githubusercontent.com/11605702/200157224-b1fb5ffb-0797-4203-be21-75deb82b83bb.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/969/files

https://user-images.githubusercontent.com/11605702/200157271-58c0f4d5-4796-42a9-b9c3-044f95916a59.mov

**Comment by uyarn** [comment]
fixed 0.42.6
