### ISSUE TITLE
[Select] multiple属性与inputProps的autofocus冲突

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1654]
### tdesign-react 版本

0.42.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-myz7xy?file=/src/demo.jsx

### 重现步骤

期望当指定inputProps的autofocus时，能实现Select组件中Input部分的自动聚焦功能。实际上在multiple时，该属性不生效

**Comment by uyarn** [comment]
看起来是可以聚焦的 是需要聚焦到哪？
![image](https://user-images.githubusercontent.com/26377630/200239513-a7bf0287-d0ac-46e2-a548-28040fff3cc4.png)
