### ISSUE TITLE
tdesign-site-components td-doc-header 组件问题

### ISSUE THREAD

**Issue by EastblueOkay** [Tencent/tdesign-react#166]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Chrome 96.0.4664.110 arm64

**Describe the bug**
When using the `document.documentElement.setAttribute` method to switch from dark mode back to light mode, the src of the iframe in `<td-doc-header>` does not change. (Under a specific page: https://tdesign.tencent.com/react/components/dark-mode)

使用`document.documentElement.setAttribute`方法在特定页面将主题从暗黑切换回明亮模式后，`<td-doc-header>` 组件中 ifrrame 的 src 没有正确切换回来。页面地址：https://tdesign.tencent.com/react/components/dark-mode。

**Steps to reproduce**
1. visit https://tdesign.tencent.com/react/components/dark-mode
2. document.documentElement.setAttribute('theme-mode', 'dark')
3. document.documentElement.removeAttribute('theme-mode')

**Comment by HQ-Lin** [comment]
感谢反馈，现网已修复
