### ISSUE TITLE
select组件使用select.option的时候无法使用filterable

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#1663]
### tdesign-react 版本

0.42.5-alpha.3

### 重现链接

https://stackblitz.com/edit/react-xnejy5?file=src%2Fdemo.jsx

### 重现步骤

直接运行demo就可以看到了

### 期望结果

和在select组件中使用options的api效果一样就行

### 框架版本

    "react": "^18.2.0",

**Comment by HQ-Lin** [comment]
0.43.0 fixed
