### ISSUE TITLE
[select] 当滚动到下方的时候，选择顶端的数据选项，选项会跳转

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#1666]
### tdesign-react 版本

0.42.5-alpha.3

### 重现步骤

<img width="429" alt="image" src="https://user-images.githubusercontent.com/52768985/199879418-387d4612-a873-49da-8eae-98bf3e43ae61.png">
滚动条滚动一下

<img width="457" alt="image" src="https://user-images.githubusercontent.com/52768985/199879581-65ac43b7-1102-4f1d-b989-77927b5b0aed.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/52768985/199879619-5d60b89f-e1ef-459e-ac5a-cc211237c323.png">

### 期望结果

不论怎么点击，都不会选项条都不会跳，貌似是加了filterable字段的原因，可以排查一下。。。

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-react/issues/1462

**Comment by HQ-Lin** [comment]
0.42.6 fixed
