### ISSUE TITLE
[select] minCollapsedNum可配置响应式折叠，当宽度不够时才折叠

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-react#1684]
### 这个功能解决了什么问题

多选下通过响应式布局让选项自动收缩，让选择框更灵活的显示多个tag

### 你建议的方案是什么

实现antd效果：
https://ant.design/components/select-cn/#components-select-demo-responsive

**Comment by uyarn** [comment]
这个功能一直有的https://tdesign.tencent.com/react/components/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%98%E5%8F%A0%E9%80%89%E4%B8%AD%E9%A1%B9%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by chaishi** [comment]
这位同学的意思，应该是指固定宽度的场景下，标签超出后自动计算折叠的标签数量，而非父组件指定折叠数量。

见过一些实现这个功能的组件库，总能发现一些奇奇怪怪的 BUG，比如默认位置不正常啊，一次选择过多啊。
