### ISSUE TITLE
[upload] 上传文件之后日期不能回显

### ISSUE THREAD

**Issue by tengcaifeng** [Tencent/tdesign-react#1687]
### tdesign-react 版本

0.42.6

### 期望结果

能正常显示上传日期

### 实际结果

上传日期显示为空

### 框架版本

react17.x

### 补充说明

将版本回滚至0.40.5都能正常显示上传日期，应该是新版本引入的bug

**Comment by chaishi** [comment]
如何复现这个问题，代码是怎么写的，单文件上传，还是多文件上传，还是单图片，还是多图片，是否可拖拽

**Comment by chaishi** [comment]
点击下面的图标，进去复现你提到的问题，保存，在 issue 里面粘贴新生成的链接

<img width="916" alt="image" src="https://user-images.githubusercontent.com/11605702/200724826-750fbae0-e059-4ec2-8eeb-3da8c2c87fd5.png">
