### ISSUE TITLE
[Table] 减少不必要的rerender

### ISSUE THREAD

**Issue by jsonz1993** [Tencent/tdesign-react#1688]
### tdesign-react 版本

0.42.6

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-58116l

### 重现步骤

左右滑动表格，即使在中间的区域，也会一直触发rerender

### 期望结果

减少不必要的rerender，表格页面复杂会有性能问题，我理解应该是表格在中间滚动的时候，没有触发左右冻结列的变化，应该不需要rerender。

**Comment by chaishi** [comment]
可以尝试提个 PR
