### ISSUE TITLE
[Dialog] footer props 中使用 button 时，button loading 样式有问题

### ISSUE THREAD

**Issue by bemzhao** [Tencent/tdesign-react#1692]
### tdesign-react 版本

0.42.5

### 重现链接

https://jn1h7i.csb.app/

### 重现步骤

<img width="928" alt="image" src="https://user-images.githubusercontent.com/27409590/200816214-dd8db3e4-f177-49ac-956a-cfeaee4b4668.png">

### 实际结果

<img width="637" alt="image" src="https://user-images.githubusercontent.com/27409590/200816593-c805c04b-b27f-4bc0-8930-5f8fb2438ab3.png">

**Comment by chaishi** [comment]
从示例代码来看，确实有点问题

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/11605702/200816710-bc3c413a-3234-4d6c-adff-ee2b36cee2f7.png">

**Comment by chaishi** [comment]
https://tdesign.tencent.com/react/components/dialog
官网可直接复现
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/11605702/200817073-4a0ad5b6-0815-45e2-952a-75845733ce3f.png">

**Comment by uyarn** [comment]
已修复待发布
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/26377630/200820929-a0255d89-e9aa-48e1-a85d-6c90c877863b.png">

**Comment by uyarn** [comment]
0.43.0已修复
