### ISSUE TITLE
[Tree] 有重复节点时，表现异常

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1695]
### tdesign-react 版本

0.42.6

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-vlnufb?file=/src/demo.jsx

### 重现步骤

当 tree 中有重复的节点时，表现奇怪。
eg:
- 重复的节点没有展示完全，如上面的例子，duplicate 下的节点没了
- 当 1.1, 1.2 都选中时，无法反选 1.1 (其他重复的节点也是如此)

### 期望结果

重复的节点也能显示，且切换选中状态正常。

### 补充说明

业务场景：
人员选择器，一个人可以属于不同的组。

解决思路：
以 path 作为节点的 key，而不是 value。

**Comment by HQ-Lin** [comment]
目前tree内部维护唯一不同的key用的也是value字段，与外部业务理解的value不一样，需要通过keys 更改为别的字段并且提供一个不重复的key给到tree
可以暴露 treeRef 给到外部方便调用 tree 的能力
