### ISSUE TITLE
[Select] 单选模式开启clearable选中一个选项后无法清除掉选项

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign-react#1719]
### tdesign-react 版本

"tdesign-react": "0.42.3",

### 重现步骤

单选模式开启clearable选中一个选项后无法清除掉选项

### 期望结果

单选模式选中选项也可以清除掉

**Comment by 2513483494** [comment]
<img width="321" alt="截屏2022-11-18 16 46 38" src="https://user-images.githubusercontent.com/48058550/202659939-4c4210ad-a5a5-428d-8577-6a7d4deb9bdc.png">
选中一个选项后就不能清空选项了。。。

**Comment by uyarn** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-chek7h?file=/src/demo.jsx 没复现这个问题  麻烦在这复现一下

**Comment by uyarn** [comment]
label只支持string类型喔 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/26377630/202667340-e377c636-c5fb-4493-86a7-8060802f339a.png">
你是需要什么效果 可以描述一下 也许有其他方式实现

**Comment by 2513483494** [comment]
> label只支持string类型喔 <img alt="image" width="497" src="https://user-images.githubusercontent.com/26377630/202667340-e377c636-c5fb-4493-86a7-8060802f339a.png"> 你是需要什么效果 可以描述一下 也许有其他方式实现

可以企微交流么。。。我们的业务需求有点奇怪

**Comment by 2513483494** [comment]
> > label只支持string类型喔 <img alt="image" width="497" src="https://user-images.githubusercontent.com/26377630/202667340-e377c636-c5fb-4493-86a7-8060802f339a.png"> 你是需要什么效果 可以描述一下 也许有其他方式实现
> 
> 可以企微交流么。。。我们的业务需求有点奇怪

jiqixing  企微

**Comment by 2513483494** [comment]
https://semi.design/zh-CN/input/select
交互上可以参考着抖音的ui库，确实交互体验和开发体验要好很多
