### ISSUE TITLE
【datepicker】选择时间后，通过value来控制时间，日期active不正确

### ISSUE THREAD

**Issue by zhushibo** [Tencent/tdesign-react#172]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
value写今天，切换其它时间后(1月7号)，再次点开日期，active日期为上次点击日期（1月7号）
**Additional context**
![image](https://user-images.githubusercontent.com/26269311/148183630-135ae5e6-38de-4b2a-a6b0-646f95fccb15.png)

https://codesandbox.io/s/tdesign-react-demo-forked-cqk76

**Comment by uyarn** [comment]
fixed in 0.22.0
