### ISSUE TITLE
[Swiper] 导航器类型点状(dots)、点条状(dots-bar)参数无效

### ISSUE THREAD

**Issue by SheenyMeg** [Tencent/tdesign-react#1720]
### tdesign-react 版本

0.43.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-jqsu2x?file=/src/demo.jsx:228-238

### 实际结果

![企业微信截图_16687564724150](https://user-images.githubusercontent.com/33172578/202709686-fe9b4689-6248-40f6-a685-d0b592e41720.png)
设置导航器类型为点状(dots)未显示

**Comment by carolin913** [comment]
type目前暂时只支持bars和fraction，api里提到的另外两种模式等确定设计这边ready之后我们会尽快补充上，api这里我们会做下补充说明
