### ISSUE TITLE
[Table] 滚动和分页同时开启时，样式错误

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1726]
### tdesign-react 版本

0.43.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-ztslod

### 重现步骤

<img width="768" alt="image" src="https://user-images.githubusercontent.com/37169906/203006465-f77ee9dd-3467-439a-8b7c-83283b894f7e.png">

用的 `bottom` 来定位，导致错误。

<img width="301" alt="image" src="https://user-images.githubusercontent.com/37169906/203006488-3b3d8899-7820-40b7-b796-66c9538e8704.png">

### 期望结果

样式正常

**Comment by chaishi** [comment]
可以先写个线条的高度 CSS !important 临时解决问题，

我周末处理下

**Comment by chaishi** [comment]
> https://codesandbox.io/s/tdesign-react-demo-forked-ztslod

这个链接打开，看不到分页，辛苦先保存一下代码，再贴链接

**Comment by moecasts** [comment]
> > https://codesandbox.io/s/tdesign-react-demo-forked-ztslod
> 
> 这个链接打开，看不到分页，辛苦先保存一下代码，再贴链接

@chaishi 保存了，随便弄个 pagination 和 scrollbar 共存的情况就可以复现了

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1755
