### ISSUE TITLE
[Select] valueDisplay参数为函数时直接报错

### ISSUE THREAD

**Issue by zhaosqgit** [Tencent/tdesign-react#1728]
### tdesign-react 版本

0.42.6

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-yyeypc?file=/src/demo.jsx

### 重现步骤

直接设置valueDisplay参数为函数

### 期望结果

不报错，且正常按valueDisplay展示，无值时展示placeholder

### 实际结果

TypeError
Cannot read properties of undefined (reading 'length')

### 框架版本

react

### 浏览器版本

107

### 系统版本

macos 12.6

**Comment by uyarn** [comment]
valueDisplay当前版本只支持多选 可以优化下支持下单选的使用~

**Comment by zhaosqgit** [comment]
同一个组件，可以设置多选和单选，这样一来，valueDisplay就报错了

**Comment by uyarn** [comment]
fixed 0.43.1
