### ISSUE TITLE
[PrimaryTable] PrimaryTable的columns属性若用cell函数，会造成严重多次渲染（最新版本已减少一半）

### ISSUE THREAD

**Issue by sin911** [Tencent/tdesign-react#1731]
### tdesign-react 版本

0.43

### 重现链接

https://yuc3h6.csb.app/

### 重现步骤

在Table组件中，如果Table组件中的columns采用cell函数渲染，会造成多次渲染，这是为什么呢？
以下代码非常纯净，是从TDesign复制来的，为了说明问题，我把数据量只保留了1条，所以理论上cell应该只执行了一次，但实际在console中发现，执行了10次！
如果数据量多的话，执行次数会更多，令人困惑。
在线代码预览：
https://codesandbox.io/embed/lucid-gianmarco-yuc3h6?fontsize=14&hidenavigation=1&theme=dark
`import { useRef } from 'react';
import { PrimaryTable } from 'tdesign-react';
import 'tdesign-react/es/style/index.css';
function App() {
  return (
    <div>
      <PrimaryTable
        columnControllerVisible={undefined}
        columns={[
          {
            colKey: 'index',
            title: 'index',
          },
          {
            colKey: 'platform',
            title: '平台',
          },
          {
            colKey: 'description',
            title: '说明',
            cell: () => {
              console.log('======渲染');//这个地方应该只执行一次，但实际执行了10次！太吓人了！
              return 111;
            },
          },
        ]}
        data={[
          {
            description: '数据源',
            id: 0,
            index: 0,
            platform: '公有',
          },
        ]}
        defaultExpandedRowKeys={[]}
        defaultSelectedRowKeys={[]}
        expandIcon
        maxHeight={140}
        multipleSort={false}
        showSortColumnBgColor={false}
        size="medium"
        sortOnRowDraggable={false}
        tableLayout="fixed"
        verticalAlign="middle"
      />
    </div>
  );
}

export default App;
`

### 期望结果

根据我所给的例子，cell函数应该只执行一次

### 实际结果

实际却执行了10次！我感到很困惑

### 框架版本

react18

### 浏览器版本

Chrome105

### 系统版本

win10

**Comment by chaishi** [comment]
经实际验证，从单条数据单个单元格来看，

AntDesign https://ant.design/components/table-cn，初次渲染 3 次。
ArcoDesign https://arco.design/vue/component/table#API ，初次渲染 5 次。
TDesign，初次渲染 6 次，当进行优化。


问题已查到，TBody 组件依赖重复渲染，通过添加 useMemo 可从 6 次降低到 3 次。

从 3 次到 1 次，需找到不依赖 `tableElm` 和 `tableWidth` 之法，这个处理会比较细节，容易引起固定列、列宽拖拽等问题（这些特性都依赖表格的第一次渲染）

**Comment by sin911** [comment]
期待优化
