### ISSUE TITLE
[Menu] 菜单名称超过5个字，HeadMenu模式下一级菜单拥挤，样式丑陋

### ISSUE THREAD

**Issue by my3188** [Tencent/tdesign-react#1747]
### tdesign-react 版本

0.42.6

### 重现链接

https://stackblitz.com/edit/react-nkma99?file=src%2Fdemo.jsx

### 重现步骤

打开重新链接即可看到

### 期望结果

查看超过5个字的菜单样式，期望菜单不拥挤  样式好看

### 实际结果

菜单拥挤，样式丑陋

### 补充说明

ant的横向菜单  一级采用tab风格，不管菜单名字多长都不会有这样的问题

**Comment by honkinglin** [comment]
0.45.0 已优化调整展示区域的大小

**Comment by honkinglin** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/24469546/209913926-4874c83e-d9f3-4aff-b114-7276c2fc925b.png">
