### ISSUE TITLE
[Message] 函数式调用时MessageOptions中style参数失效

### ISSUE THREAD

**Issue by ColoeusEdward** [Tencent/tdesign-react#1759]
### tdesign-react 版本

0.43.1

### 重现链接

https://stackblitz.com/edit/react-stgvib-z3mwu1?file=src/demo.jsx

### 期望结果

style参数能正常生效

### 实际结果

只有带上offset参数时, style才生效

### 框架版本

React(18.2.0)

### 浏览器版本

Chrome(107.0.5304.122)

**Comment by kenzyyang** [comment]
https://github.com/Tencent/tdesign-react/pull/1762
