### ISSUE TITLE
[Dialog] 实例里的方法都是存在的，为什么定义成可选的类型？

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1782]
### tdesign-react 版本

0.44.0

### 重现步骤

定义成可选的话，老代码都要改成 `dialog.hide?.()`，对于已经大量使用 `dialog` 组件的项目极不友好。

### 期望结果

https://github.com/Tencent/tdesign-react/blob/8b097611c10e7180e03e36bb7586067b1c1054ab/src/dialog/type.ts#L167-L184

### 实际结果

可以将类型定义成必选的。

**Comment by chaishi** [comment]
改
