### ISSUE TITLE
【Dropdown】出现滚动条时多层子项鼠标不能选中

### ISSUE THREAD

**Issue by FE-Acmen** [Tencent/tdesign-react#1785]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-tyutmg?file=/src/main.jsx

### 重现步骤
层级关系的操作下拉菜单，出现滚动条时不能选中子项

### 期望结果
层级关系的操作下拉菜单，出现滚动条时也能选中子项

### 实际结果
![20221207-163829](https://user-images.githubusercontent.com/44191856/206129613-30879a43-bc90-49ca-ae65-52b3bff8d2c9.gif)

| Environment | Info |
|---|---|
| 相关版本 | 0.44.0 |
| 框架版本 / 基础库版本 | React@18.2.0 |
| 系统、浏览器 | MacOS(12.4) |
| Node版本 | v14.18.0 |

**Comment by uyarn** [comment]
fixed 0.45.0
