### ISSUE TITLE
[按钮] 和tailwindcss混用会导致按钮样式异常

### ISSUE THREAD

**Issue by duxphp** [Tencent/tdesign-react#1796]
### tdesign-react 版本

0.44.1

### 重现步骤

和tailwindcss混用会导致按钮样式异常，按下状态会有黑色的边框

**Comment by chaishi** [comment]
这个问题，可能神仙也答不上来，背景方便描述么，不然我心里会有十万个为什么

tailwindcss 具体用了哪些样式，样式冲突，为何不是 tailwindcss 改，而是 TD 改。

为了不是业务里面改（一个业务），而是组件库改（上千个业务）

**Comment by duxphp** [comment]
> 

因为这个问题是样式没有定义到具体的元素引起的，其他UI框架也有同样的问题，给他们反馈过基本都处理了

**Comment by AqingCyan** [comment]
> > 
> 
> 因为这个问题是样式没有定义到具体的元素引起的，其他UI框架也有同样的问题，给他们反馈过基本都处理了

可能需要你提供一下复现的仓库 bro 🕵🏻
