### ISSUE TITLE
React 版本 TreeSelect 组件选项过多时会全部显示，不会出现滚动条，与 Vue 对应组件表现形式不一致

### ISSUE THREAD

**Issue by Monetchang** [Tencent/tdesign-react#1804]
### tdesign-react 版本

tdesign-react@0.44.1

### 重现步骤

React TreeSelect 组件
![image](https://user-images.githubusercontent.com/18139783/207533048-7a545d2d-fd7b-4b86-86b5-c49f26ccb090.png)
<img width="830" alt="企业微信截图_6677fca3-507b-423f-9a7f-901e8a4c55ea" src="https://user-images.githubusercontent.com/18139783/207533074-b2a7aef4-9e03-40d4-9470-469da9647c03.png">

Vue TreeSelect 组件
<img width="465" alt="企业微信截图_bbcf9bae-9406-44cf-bcb6-aa9007691430" src="https://user-images.githubusercontent.com/18139783/207533143-d1be8aa2-a7f2-4213-ac2f-3129e37abefc.png">
<img width="431" alt="企业微信截图_6216f342-36ac-4648-9b30-6c3d128dbcee" src="https://user-images.githubusercontent.com/18139783/207533176-5cb6bf8b-d661-4e2c-8c6a-7ff108101b15.png">

### 期望结果

希望 React 版本 TreeSelect 也像 Vue 版本一样，过多选项时出现滚动条。

### 实际结果

相同的配置和数据，但 React 版本选项会将整个容器撑开

### 框架版本

react@18.2.0

### 浏览器版本

Chrome(108.0.5359.94)

### Node版本

v16.17.0

**Comment by honkinglin** [comment]
0.44.2 fixed
