### ISSUE TITLE
[React] Tree Select 异步加载数据的时候，无法滚动查看下面的节点，必须失焦重新render才可以

### ISSUE THREAD

**Issue by chenxihub** [Tencent/tdesign-react#181]
**Describe Framework**

- [x] tdesign-react
![image](https://user-images.githubusercontent.com/34295619/148323620-ec1d9f47-571b-45b4-ae8f-bb12234aa989.png)

**Describe Environment**

Add browser version here

**Describe the bug**

**Additional context**

**Comment by uyarn** [comment]
0.21新增popup的动画引起的问题 这周的版本会修复。

**Comment by uyarn** [comment]
fixed in 0.22.0
