### ISSUE TITLE
[Table] Table 的 onScroll 方法中获取 scroll 垂直偏移量

### ISSUE THREAD

**Issue by Monetchang** [Tencent/tdesign-react#1811]
### tdesign-react 版本

"tdesign-react": "^0.44.2"

### 重现步骤

我的场景是通过 Table 组件开发一个无限列表。
我已经设置了 Table 的 maxHeight，期望内容超过 maxHeight 时会出现滚动条，当用户滚动到表格底部是自动发起请求数据加载。但现在在 onScroll 方法中获取不到 scroll 的偏移量，无法判断用户是否滑动到了底部。
![image](https://user-images.githubusercontent.com/18139783/207805620-91374637-1748-4528-aeea-28826fa51494.png)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/18139783/207805791-520c7813-b9f4-439d-8eeb-29d6a0f1c508.png">

### 期望结果

获取到 scroll 的偏移量，判断用户滑动到 Table 底部并自动进行下一步操作

### 实际结果

无法获取 scroll 偏移量

### 框架版本

react@18.2.0

### 浏览器版本

Chrome(108.0.5359.94)

### Node版本

v16.17.0

**Comment by chaishi** [comment]
如果完全自己做无限滚动，还需要使用 `scroll={ type: ‘virtual' }` 吗

**Comment by Monetchang** [comment]
其实可以不需要使用虚拟列表，但这个设置应该不影响获取 scroll 垂直偏移量。并且即使我删除这个配置，还是无法获取到 scroll 垂直偏移量。

**Comment by chaishi** [comment]
简单试了下，可以判断是否到底部

示例代码链接：https://stackblitz.com/edit/react-c7cbzs?file=src%2Fdemo.jsx

<img width="1316" alt="image" src="https://user-images.githubusercontent.com/11605702/207808367-a0f796f1-23e8-47d1-8d76-025efdebdddb.png">

**Comment by Monetchang** [comment]
确实可以，非常感谢🌹。
但我有个疑问，在控制台打印出来的 e.target 中并没有 scrollTop 这个属性，这个是为什么呢？

**Comment by chaishi** [comment]
肯定有，注意 onScroll 的参数是一个大对象。`(context: { e }) => void`，而非 `(e) => void`

**Comment by chaishi** [comment]
对于数据加载来说，无限滚动，也属于一个常见需求，后面我们加一下这个特性

不需要每个业务都自己搞一遍

**Comment by Monetchang** [comment]
刚刚我仔细找了，确实存在 scrollTop，应该是因为属性过多自动折叠了，我的问题
<img width="883" alt="image" src="https://user-images.githubusercontent.com/18139783/207810959-27867319-7468-4a42-b25f-a70ca5a29951.png">
期待这个特性上线
