### ISSUE TITLE
[TreeSelect] 多选状态下，点击叶子结点 label 文本无法选中

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1815]
### tdesign-react 版本

0.44.2

### 重现链接

https://stackblitz.com/edit/react-g2tcxr

### 重现步骤

点击叶子结点文本
![image](https://user-images.githubusercontent.com/37169906/207852059-6f1bd066-f713-45c1-b8e3-2dc7a3feca85.png)

### 期望结果

能选中叶子结点

### 实际结果

无法选中

### 补充说明

vue 的可以，希望能和 vue 保持同步。
https://tdesign.tencent.com/vue/components/tree-select#%E5%B8%A6%E5%A4%9A%E9%80%89%E7%9A%84%E6%A0%91%E9%80%89%E6%8B%A9

**Comment by chaishi** [comment]
第一个问题：不存在 `setMulValue` 方法，所以报错

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/11605702/208009272-b33a4d8c-3772-4545-ad74-21cb0ef4f64e.png">

**Comment by honkinglin** [comment]
之前还有人反馈不希望点击 label 就选中所以调整了一下。

**Comment by chaishi** [comment]
点击有子节点的节点，展开不选中
点击叶子结点，选中

**Comment by moecasts** [comment]
> 第一个问题：不存在 `setMulValue` 方法，所以报错

抱歉，可以忽略这个报错，重点不在这。label 选中行为的问题，官网的示例就能复现。

**Comment by moecasts** [comment]
> 之前还有人反馈不希望点击 label 就选中所以调整了一下。

@honkinglin 如果两个都有需求的话是不是开个 api 来让用户自己选更好？

**Comment by honkinglin** [comment]
0.45.0 fixed
