### ISSUE TITLE
[提议] 提升代码质量和专业性 

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-react#182]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here

**Describe the bug**
人人都应该安装的 VSCODE 插件：
[code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) 它不香吗
作为一个开源 repo，要尽量避免出现低级的 typo 哇。

**Additional context**
[在 tdesign-common 中的原 issue](https://github.com/Tencent/tdesign-common/issues/104#issue-1094936070)

**Comment by southorange1228** [comment]
可以考虑`.vscode`新增`extensions.json`配置文件
