### ISSUE TITLE
[Tag] 组件内部图标和文本没有默认居中对齐，原因：DOM 结构和 Vue 不同，导致两边视觉效果有差异

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#1823]
### tdesign-react 版本

0.44.2

### 重现链接

https://tdesign.tencent.com/react/demos/table/virtual-scroll

### 重现步骤

组件内部图标和文本没有默认居中对齐，Vue 的表现是居中对齐的。原因是 React 多了一层 DOM

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/11605702/208411596-6cb5cc5f-7eb7-47c2-95f6-29a9b4c925b3.png">

### 期望结果

期望每个框架的 DOM 结构保持一致，方便 复用 CSS 达到一样的效果

**Comment by yaogengzhu** [comment]
这看起来像是一个Tag组件 错误用法导致的
