### ISSUE TITLE
[Dialog] header 结构变化

### ISSUE THREAD

**Issue by bemzhao** [Tencent/tdesign-react#1828]
### tdesign-react 版本

0.44.2

### 重现步骤

header={false} 时关闭按钮在左边是符合预期的吗

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/27409590/208568646-661c6023-9d8d-4d13-83d4-d742b1f1e26b.png">

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/27409590/208568691-f05cc130-2b83-4970-92b5-2435fea29c4c.png">

### 期望结果

0.41.1 下是在关闭按钮是在右边的

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/27409590/208568814-d5d86736-162f-4e48-91e6-5ff39c961343.png">

看起来新版本里有对 header 结构做过更改

因为业务中有对 dialog 做样式上的调整，如果 dialog 组件结构的再次更改是有必要的，请在 change log 标明

**Comment by honkinglin** [comment]
这里关闭按钮往左侧移动是不对的，0.45.0 新版本已经处理
