### ISSUE TITLE
DateRangePicker 与 Radio.Group 组合使用，数据更新后，Radio.Group 会失去焦点

### ISSUE THREAD

**Issue by Monetchang** [Tencent/tdesign-react#1852]
### tdesign-react 版本

0.45.1

### 重现链接

https://easy-events.testsite.woa.com/#/list/select

### 重现步骤

代码：
<img width="739" alt="image" src="https://user-images.githubusercontent.com/18139783/210294287-6a4acc37-bba3-4989-bffb-699ae11a739e.png">
<img width="796" alt="image" src="https://user-images.githubusercontent.com/18139783/210294294-489ac61e-bb3b-4302-8915-b61d52b8de97.png">
界面：
![image](https://user-images.githubusercontent.com/18139783/210294493-99b596ad-25c6-467f-baad-24d25c0dcc9b.png)

操作：
1. 点击【近十分钟】【近半小时】【近两小时】快捷选择按钮，焦点会出现
2. 点击【查询】，数据更新，按钮焦点消失

### 期望结果

点击【查询】，数据更新，焦点不消失

### 实际结果

点击【查询】，数据更新，焦点消失

### 框架版本

react@18.2.0

### 浏览器版本

Chrome(108.0.5359.94)

### Node版本

v16.17.0

**Comment by yaogengzhu** [comment]
这个要是有一个代码demo就更好了， 如： https://codesandbox.io/s/q0ettr?file=/src/demo.jsx

**Comment by honkinglin** [comment]
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/24469546/211479995-aa6310db-22d7-40d9-9250-ebcd8b3b0f65.png">
第一次见到有人给radio的value赋值了对象，目前radio 的value 仅支持简单数据结构，所以比对的时候用的是全等，重新渲染时候引用地址变了导致全等失效checked 失效了
