### ISSUE TITLE
[TooltipLite] disabled button 触发的提示无法正常消失

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1853]
### tdesign-react 版本

0.45.1

### 重现链接

https://stackblitz.com/edit/react-tcwz63?file=src%2Fdemo.jsx

### 重现步骤

TooltipLite 包括 button[disabled] 元素

### 期望结果

失焦时弹窗正常消失

### 实际结果

失焦时弹窗不消失

**Comment by chaishi** [comment]
按理说 `button[disabled]` 会禁用掉所有的 hover 行为，如此便不会有任何 hover 效果

使用 `<Button tag=‘div’ disabled>` 试试

**Comment by moecasts** [comment]
> 使用 `<Button tag=‘div’ disabled>` 试试

@chaishi  `Switch` 之类的组件用的也是 `button[disabled]`，`tag=div` 就不适用了。

**Comment by yaogengzhu** [comment]
看demo 是原生的button ，所以有这个问题。

**Comment by moecasts** [comment]
> 看demo 是原生的button , 内置Button做了相应的处理了，所以有这个问题。 @moecasts 看你要不要用组件的Button 尝试下

@yaogengzhu `button` 只是举个例子，正如上面说的 `switch` 之类的组件就不行了

**Comment by yaogengzhu** [comment]
Switch 没做相应的实现，所以也不行
