### ISSUE TITLE
[DatePicker] 增加额外的按钮，增加可操作性

### ISSUE THREAD

**Issue by xianmua** [Tencent/tdesign-react#1867]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/40600497/211152534-e8761d93-508b-4807-9add-fa91220af1c0.png)
我希望在打开日期选择框的时候，增加一个按钮让用户选是否需要时间选择部分。

### 你建议的方案是什么

增加一个额外操作，或者组件本身增加这个功能

**Comment by xiaosansiji** [comment]
可以自己用 Switch 和 Datepicker 组件组合一下，Switch 改变时同步修改下 Datepicker.enableTimePicker 和 Datepicker.format。

Datepicker 组件本身的功能范围限定在日期输入框和日期选择的下拉框内
