### ISSUE TITLE
水印防删除不起作用

### ISSUE THREAD

**Issue by li-jia-nan** [Tencent/tdesign-react#1872]
### tdesign-react 版本

0.45.2

### 重现链接

https://tdesign.tencent.com/react/components/watermark

**Comment by carolin913** [comment]
这里需要把removable设置为false就可以实现防删除了，api这里的描述不太对，我们会尽快优化下这里

**Comment by li-jia-nan** [comment]
我试了一下也不行，看了一下源码，useMutationObserver 的回调是触发了，但是 appendChild 那一块逻辑应该有点问题，我的理解是在回调中应该重新生成一遍 canvas，然后再添加元素，而不是简单的执行 appendChild

**Comment by li-jia-nan** [comment]
或者请问可以在官网的文档中添加一个防删除的 demo 吗？

**Comment by carolin913** [comment]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/2638568/211757689-dfe9153c-e81b-442c-ad0f-77d615a452b8.png">
防删的是水印节点哦，更上一级包裹水印的节点删了是没法感知的
https://codesandbox.io/s/tdesign-react-demo-forked-t6d7fp?file=/src/demo.jsx:145-154

**Comment by li-jia-nan** [comment]
https://user-images.githubusercontent.com/49217418/211762956-601a4886-8113-4f54-b3a6-d50c927c9f08.mp4

你这个 codesandbox 的 Demo 好像也是可以复现的，麻烦看一下～

**Comment by carolin913** [comment]
哦你这个是改变样式是吧，目前只监听了删除节点，并未对样式的变化做监听，这里应该还需要细致化的判断下mutation.type，我再修复完善下这里吧

**Comment by li-jia-nan** [comment]
> 哦你这个是改变样式是吧，目前只监听了删除节点，并未对样式的变化做监听，这里应该还需要细致化的判断下mutation.type，我再修复完善下这里吧

好的，辛苦～

**Comment by li-jia-nan** [comment]
那我先close了
