### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by coffeew** [Tencent/tdesign-react#1880]
### tdesign-react 版本

是

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-hksy7j?file=/src/demo.jsx

### 重现步骤

 级联选择组件， value为 number类型切为0 的时候， 节点选中不了

### 期望结果

节点value值为0是 也应该能被选中

### 实际结果

 级联选择组件， value为 number类型切为0 的时候， 节点选中不了

### 框架版本

"react": "^18.2.0",

### Node版本

v16.15.1

**Comment by honkinglin** [comment]
duplicate #1881
