### ISSUE TITLE
[Table] 使用官方的虚拟滚动案例，会在滚动过程中出现多余的异常表头

### ISSUE THREAD

**Issue by hard-man** [Tencent/tdesign-react#1882]
### tdesign-react 版本

0.45.2出现该问题

### 重现步骤

直接复制官方的虚拟滚动案例代码，将其放置在一个Modal弹窗中展示

### 期望结果

表头吸顶，正常滚动不会出现异常

### 实际结果

滚动过程中出现多余的异常表头

### 框架版本

React(16.8.6)

### 浏览器版本

Chrome(107.0.5304.10)

### 系统版本

Windows10(21H1)-操作系统内部版本 19043.2364

### Node版本

8.14.0

### 补充说明

需要使用Table来实现表头吸顶的虚拟滚动，同时包含可伸缩列的功能，滚动条上下滚动时仍能看到表头

**Comment by hard-man** [comment]
[https://www.helloimg.com/images/2023/01/12/oGWjvS.png](url)

**Comment by hard-man** [comment]
上面的链接是bug截图，请跳转查看

**Comment by hard-man** [comment]
https://www.helloimg.com/images/2023/01/12/oGWufC.png

**Comment by hard-man** [comment]
上面的链接是滚动过程中表头吸顶也会消失

**Comment by chaishi** [comment]
凡事吸顶功能有关的功能，都需要明确希望一个元素在哪个容器里面滚动。

如果 Table 独立存在于页面，滚动容器为 document 或 document.body。

如果 Table 存在于 Dialog，滚动容器则需要变动 Dialog，请问是否有设置 `attach`。（很早之前 Vue 的用户已经提过类似问题，设置滚动容器后表现正常，而 React 的代码逻辑和 Vue 几乎一致，应该是没有问题的）。

<img width="914" alt="image" src="https://user-images.githubusercontent.com/11605702/219878679-30f6d27f-aa1b-4d33-a684-78823a3ff9b9.png">


由于没有正确使用组件，且没有提供可复现问题的链接，issue 暂时关闭。后续提供后，可以 reopen。
