### ISSUE TITLE
[Dialog] dialog 自定义 footer 时，引入了 break change？

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1901]
### tdesign-react 版本

0.45.3

### 重现步骤

dialog 这个自定义 footer 时，footer 的 className 没有了的 break change 是设计如此还是 bug 呀？changelog 里面没有写喔。

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/37169906/212841617-90583450-c37c-4b04-9f27-e72bf202c6ed.png">

<img width="791" alt="企业微信截图_271001c9-2692-4988-9cb0-35aaf4bbb1c3" src="https://user-images.githubusercontent.com/37169906/212841164-de877844-0389-46bc-a4a3-880f89cbf597.png">

<img width="516" alt="企业微信截图_31ff9f6d-7d18-4ac0-8db1-c1112b309e0f" src="https://user-images.githubusercontent.com/37169906/212841184-31bcbfde-2a74-42bc-b7d6-a9f1f5021f11.png">

### 期望结果

保留 footer 的类名。

**Comment by chaishi** [comment]
设计如此，应该是为了和 Vue 保持统一
