### ISSUE TITLE
[ColorPicker] 首次加载时，颜色值、透明度 slider 的 thumb 未位于正确位置

### ISSUE THREAD

**Issue by MrWeilian** [Tencent/tdesign-react#1906]
### tdesign-react 版本

0.45.4

### 重现链接

https://codesandbox.io/s/8vutmo?file=/src/demo.jsx

### 重现步骤

一、CodeSandbox
1. 首次加载，透明度 slider 未正确处于 100% 位置，拖动后 `透明度slider` 可正确到达 `100%` 处；且**首次**拖动 `透明度thumb` 时 `颜色slider` 的 `thumb` 稍微抖动。

二、官方文档——ColorPicker颜色选择器
1. 直接打开 [文档 #允许调整透明度的颜色选择器](https://tdesign.tencent.com/react/components/color-picker#%E5%85%81%E8%AE%B8%E8%B0%83%E6%95%B4%E9%80%8F%E6%98%8E%E5%BA%A6%E7%9A%84%E9%A2%9C%E8%89%B2%E9%80%89%E6%8B%A9%E5%99%A8)
![image](https://user-images.githubusercontent.com/30046649/213068885-b618972a-75ac-4154-ba30-f2d6b9a3b07c.png)

### 期望结果

首次加载时，`slider` 组件的 `thumb` 位置正确。

### 实际结果

首次加载时，`slider` 组件的 `thumb` 位置有误。

### 补充说明

当前问题应该是用了这个默认值 `168` 导致的，原因如下描述。
![image](https://user-images.githubusercontent.com/30046649/213070034-58582798-02da-4eb8-95b7-a39ed462e04a.png)

这里的位置计算应该在组件 `mounted` 后执行，目前是直接计算了（最后一张图）。
![image](https://user-images.githubusercontent.com/30046649/213069747-0fb927de-4a50-4451-bf61-bfdd62b62350.png)

![image](https://user-images.githubusercontent.com/30046649/213069828-0a87ac27-dc26-40ea-9421-95812b260e8a.png)

**Comment by honkinglin** [comment]
1.0.1 fixed
