### ISSUE TITLE
[Dialog] server error in nextjs

### ISSUE THREAD

**Issue by xinchaobeta** [Tencent/tdesign-react#1924]
### tdesign-react 版本

0.45.4

### 重现链接

https://stackblitz.com/edit/nextjs-xkeyja?file=pages%2Findex.js

### 重现步骤

![image](https://user-images.githubusercontent.com/2239514/215315798-0a60ce14-981f-4361-88eb-b05d2aa24b0d.png)

### 期望结果

正常运行

### 实际结果

Server Error
ReferenceError: document is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
document
node_modules/tdesign-react/lib/dialog/hooks/useLockStyle.js (31:28)
eval
node_modules/tdesign-react/lib/dialog/Dialog.js (124:21)
renderWithHooks
file:///home/projects/nextjs-xkeyja/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderForwardRef
file:///home/projects/nextjs-xkeyja/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5842:18)
renderElement
file:///home/projects/nextjs-xkeyja/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6005:11)
renderNodeDestructiveImpl
file:///home/projects/nextjs-xkeyja/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)

### 框架版本

nextjs(13.0.6)

### Node版本

16.14.2

**Comment by honkinglin** [comment]
我兼容下

**Comment by uyarn** [comment]
fixed 0.45.5
