### ISSUE TITLE
API文档优化

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#193]
## 1. 目前API的复杂类型都是通过跳转的方案展示的，在实际使用中有所不便。是否考虑当前页展示
![image](https://user-images.githubusercontent.com/32590310/148374541-90a2e3bc-bceb-4aa1-b2d0-b1f949031bab.png)

目前看到比较好的两种方案是：
1. 当前页紧随其后展示复杂类型
2. 当前复杂类型点击弹窗展示

## 2. API类型取值定义不够清晰明了。
例如： `dialog`组件的API 
![image](https://user-images.githubusercontent.com/32590310/148375016-4bac50c6-7640-4cd5-b04e-cec2c2140f32.png)

最好是类型一栏有强提醒 & 更加详细的类型。而不是TS的基本类型

**Comment by chaishi** [comment]
看上去 1 和 2 是一个问题，都是希望直接显示 TS 详细类型，我们整体输出一下。

当初觉得类型太多，特地隐藏了，现在放开一下吧

**Comment by southorange1228** [comment]
> 看上去 1 和 2 是一个问题，都是希望直接显示 TS 详细类型，我们整体输出一下。
> 
> 当初觉得类型太多，特地隐藏了，现在放开一下吧

是的，整体来说就是API的类型定义要对开发者更加友好。

**Comment by chaishi** [comment]
Vue PR：https://github.com/Tencent/tdesign-vue/pull/219

**Comment by chaishi** [comment]
React PR：https://github.com/Tencent/tdesign-react/pull/218

**Comment by southorange1228** [comment]
![image](https://user-images.githubusercontent.com/32590310/149057694-bcf3937f-9129-44e4-a4f8-dea74bf5eb93.png)

这个是没有改全吗？还是预览产物有问题？看起来好像没有什么区别 @chaishi

**Comment by southorange1228** [comment]
另外这里有个开发问题。组件对应的`md`文件内容是通过脚本生成的么？还是手动维护的

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/150738305-36f036e7-61a2-448f-a8bd-b1b75aff0ea6.png)

看代码变更，补了一对的 TS 类型。@southorange1228

应该是漏了类似 RadioValue/SelectValue/CheckboxValue 这种 xxxValue 的 TS 类型，我们再补一下

**Comment by southorange1228** [comment]
确实看commit是增加了很多类型。但是好像更为复杂的类型没有说明。比如`Table`中的`RowEventContext`这种类似的
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/32590310/153786774-525ba5f8-14a0-4738-8578-c053a2460d73.png">

这也是我之前提到的问题。就是说，更复杂的类型我不知道里面到底有什么属性。是做什么的

**Comment by 94dreamer** [comment]
@chaishi
