### ISSUE TITLE
select组件下拉内容被截断

### ISSUE THREAD

**Issue by partical** [Tencent/tdesign-react#195]
**Describe Framework**

 tdesign-react

**Describe Environment**

windows 系统（mac未复现）

**Describe the bug**
select组件下拉内容高度不正确。其中max-height属性比设置的height小，导致被截断。
![企业微信截图_16415225163875](https://user-images.githubusercontent.com/9391316/148482529-d7dd35c2-e467-4598-8c73-de2e7c216ab8.png)
![企业微信截图_16415225471530](https://user-images.githubusercontent.com/9391316/148482540-62c60488-1336-49f1-9116-cfaf2be32220.png)

**Additional context**
复现步骤：
select 组件设置远程搜索，搜索结果未返回时输入新的内容进行搜索。

组件使用如下：
`
 <Select
          filterable
          value={uin}
          onChange={onChange}
          loading={loading}
          onSearch={onSearch}
          placeholder=""
          popupProps={{ placement: 'bottom-left', overlayStyle: { width: 300, height: 280 } }}
        >
`

**Comment by uyarn** [comment]
0.22.0 已经修复了 更新一下。
