### ISSUE TITLE
[Select组件] onchange、oninputchange

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#1959]
### tdesign-react 版本

0.45.5

### 重现链接

https://stackblitz.com/edit/react-hgtdjj?file=src%2Fdemo.jsx

### 重现步骤

https://stackblitz.com/edit/react-hgtdjj?file=src%2Fdemo.jsx，select的onchange和oninputchange在点击清空或者下拉选择的时候会同时触发，这个不太合理

1、清除的时候有onclear

2、下拉选择项的时候，oninputchange也会触发，这个我就没办法做控制用户输入类型和选择类型了，全都混在一起

**Comment by chaishi** [comment]
onInputChange 有个参数 `trigger`，说明了触发的来源，你试试看不同的来源进行不同的操作

**Comment by honkinglin** [comment]
1.0.1 fixed
