### ISSUE TITLE
[button] 按钮样式问题

### ISSUE THREAD

**Issue by 121595113** [Tencent/tdesign-react#1965]
### tdesign-react 版本

0.45.6

### 重现链接

https://tdesign.tencent.com/react/components/button

### 重现步骤

<img width="648" alt="image" src="https://user-images.githubusercontent.com/9419773/218140352-9826f6c6-c17b-4593-b463-9e53dc9d8b7f.png">

### 期望结果

应该是个圆

### 实际结果

长方体

**Comment by honkinglin** [comment]
你的疑问是？
shape 和圆角有关，size 和 padding 以及宽高有关，当 button 是 block 状态时这个效果是符合预期的

**Comment by 121595113** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/9419773/218493673-96da2ede-4e42-4545-96a3-2bbc35dbfbc4.png">
<img width="900" alt="image" src="https://user-images.githubusercontent.com/9419773/218493820-5dde3fdd-decc-48d5-bf0a-38b01e2c5147.png">
@honkinglin 结合这两张图或许能知道问题出在哪里，总有一种不符合预期的
问题应该出在下面截图这里
<img width="903" alt="image" src="https://user-images.githubusercontent.com/9419773/218494452-d9ebb797-3e0e-4e51-bd1d-9743f696280c.png">
