### ISSUE TITLE
[Table] 文档范例不可用

### ISSUE THREAD

**Issue by aaronangxz** [Tencent/tdesign-react#1966]
### tdesign-react 版本

0.45.6

### 重现链接

https://tdesign.tencent.com/react/components/table#%E6%9C%AC%E5%9C%B0%E6%95%B0%E6%8D%AE%E6%8E%92%E5%BA%8F

### 重现步骤

勾选`是否允许多字段排序`后结果不符合预期
![image](https://user-images.githubusercontent.com/66870149/218248051-ef9ad0d1-f483-4d9c-8748-61190c1efe14.png)

### 期望结果

实现多字段排序

### 实际结果

排序失败

**Comment by chaishi** [comment]
待确认
