### ISSUE TITLE
[Message] 希望鼠标悬停时不自动关闭

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#1972]
### 这个功能解决了什么问题

message组件可能用于请求报错的提示。用户可能需要复制这些提示，用于后续操作

### 你建议的方案是什么

onmouseenter时暂停duration参数的计时器，onmouseleave时恢复

**Comment by chaishi** [comment]
我以为这个特性很早支持了

**Comment by textGuan** [comment]
> 我以为这个特性很早支持了
> 
> Vue 应该已经是这样的效果了，React 可能需要再确认下

是的，react目前来看还没支持。感谢
