### ISSUE TITLE
[Table] 在 react 低版本中，单元格编辑状态错误失焦

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1974]
### tdesign-react 版本

0.45.5

### 重现链接

https://stackblitz.com/edit/react-hadz5z?file=src%2Fdemo.jsx

### 重现步骤

在 react 16.13.1 的时候，表格编辑状态异常失焦。

https://user-images.githubusercontent.com/37169906/218413093-09516f9f-b3a0-4e67-8b15-082dd4bfb732.mp4

### 期望结果

处于编辑状态时，点击输入框不会失焦

### 实际结果

处于编辑状态时，点击输入框失焦了

### 框架版本

react 16.13.1

**Comment by chaishi** [comment]
下次，尽量把代码集中到一个文件里面

**Comment by honkinglin** [comment]
调整一下取消冒泡的机制就好了
16 的 react 是事件托管到 document 节点，17 改到了 root 节点了，所以在 16版本中的事件跟 document 的事件是平级的，多加一行这个兼容下 `e.nativeEvent.stopImmediatePropagation();`
