### ISSUE TITLE
请问有umd的地址吗，有的话怎么引用

### ISSUE THREAD

**Issue by wen-haoming** [Tencent/tdesign-react#1976]
### 重现链接
https://tdesign.tencent.com/starter/

### 重现步骤
无

### 期望结果
通过umd的形式 全局引入

### 实际结果
不知道有没有

| Environment | Info |
|---|---|
| 相关版本 | 1.0.0 |
| 框架版本 / 基础库版本 | react |
| 系统、浏览器 | chrome |
| Node版本 |  |

**Comment by honkinglin** [comment]
有的，jsdelivr 和 unpkg 都可以直接引入组件代码
https://www.jsdelivr.com/package/npm/tdesign-react
https://unpkg.com/browse/tdesign-react/
