### ISSUE TITLE
[DatePicker] 希望日期格式化中增加 Unix 时间戳

### ISSUE THREAD

**Issue by nikbobo** [Tencent/tdesign-react#1986]
### 这个功能解决了什么问题

目前的 Timestamp 返回的是毫秒级时间戳，希望增加秒级时间戳。
`valueType` = `'time-stamp'` 这里。
day.js 是支持秒级时间戳的，使用的转换方法不同，请看 [解析 | Day.js中文网](https://dayjs.fenxianglu.cn/category/parse.html#unix-%E6%97%B6%E9%97%B4%E6%88%B3-%E6%AF%AB%E7%A7%92)。

> Unix 时间戳 (毫秒)
> `dayjs(1318781876406)`
> Unix 时间戳 (秒)
> `dayjs.unix(1318781876)`
> `dayjs.unix(1318781876.721)`

### 你建议的方案是什么

目前的 Timestamp 返回的是毫秒级时间戳，希望增加秒级时间戳。
`valueType` = `'time-stamp'` 这里。
day.js 是支持秒级时间戳的，使用的转换方法不同，请看 [解析 | Day.js中文网](https://dayjs.fenxianglu.cn/category/parse.html#unix-%E6%97%B6%E9%97%B4%E6%88%B3-%E6%AF%AB%E7%A7%92)。

> Unix 时间戳 (毫秒)
> `dayjs(1318781876406)`
> Unix 时间戳 (秒)
> `dayjs.unix(1318781876)`
> `dayjs.unix(1318781876.721)`

**Comment by honkinglin** [comment]
返回值当中包含了日期对应的 dayjs 对象可以自行转化，也可以通过第三方日期库对毫秒级时间戳自定义转化，组件 API 无法涵盖所有应用场景，暂时不考虑提供非通用场景
