### ISSUE TITLE
[Select组件] multiple且filterable时，点击列表选项无法选中

### ISSUE THREAD

**Issue by HandsomeOne** [Tencent/tdesign-react#1987]
### tdesign-react 版本

1.0.0

### 重现链接

https://tdesign.tencent.com/react/components/select

### 重现步骤

官网文档即可复现。
<img width="1167" alt="图片" src="https://user-images.githubusercontent.com/8336227/219262013-fbe5c164-5fa1-4aeb-9579-7f6862707a97.png">
第一个示例开启multiple和filterable，然后输入“b”，无法选中“Banana"。

### 期望结果

筛选后的结果能正常选中。

### 实际结果

无法选中“Banana"。

### 框架版本

React

**Comment by uyarn** [comment]
0.45.4版本后引入的Bug

**Comment by honkinglin** [comment]
1.0.1 fixed
