### ISSUE TITLE
[Dialog] DialogPlugin 插件形式增加 defaultVisible 参数

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#1997]
### 这个功能解决了什么问题

有时候要示例化一个弹窗不一定要立即显示，希望可以让用户自己控制。

### 你建议的方案是什么

增加 `defaultVisible` 属性或者允许用户自定义 `visible`。

**Comment by chaishi** [comment]
如果是不一定立即显示，可以先添加参数，设置 `visible: false`

**Comment by moecasts** [comment]
> 如果是不一定立即显示，可以先添加参数，设置 `visible: false`

@chaishi  插件形式的不行，被写死了。
https://github.com/Tencent/tdesign-react/blob/develop/src/dialog/plugin.tsx#L19
<img width="921" alt="image" src="https://user-images.githubusercontent.com/37169906/219594471-0a25e8f9-741f-4ca0-b0cd-29a195b830ba.png">

**Comment by honkinglin** [comment]
1.0.1 fixed
