### ISSUE TITLE
[Space] 在360极速浏览器上不会显示间距

### ISSUE THREAD

**Issue by nowui** [Tencent/tdesign-react#2016]
### tdesign-react 版本

1.01

### 重现链接

https://tdesign.tencent.com/react/components/space

### 重现步骤

在360极速浏览器上打开，就可以看到示例的按钮会紧挨在一起。

![tdesign tencent com_react_components_space](https://user-images.githubusercontent.com/3635163/220961823-cf530d61-f133-4885-bebe-3e16f6fe24ab.png)

**Comment by honkinglin** [comment]
可以提供下浏览器内核版本吗? 确认下这个 `navigator.userAgent`
间距使用的是 row-gap 需要chrome 内核84版本以上才支持
https://caniuse.com/mdn-css_properties_row-gap_flex_context

**Comment by nowui** [comment]
360极速浏览器应该是78

![image](https://user-images.githubusercontent.com/3635163/221202565-4ef15937-370b-4a9a-8c39-f9454afabe42.png)

**Comment by honkinglin** [comment]
> 360极速浏览器应该是78
> 
> ![image](https://user-images.githubusercontent.com/3635163/221202565-4ef15937-370b-4a9a-8c39-f9454afabe42.png)

你这版权都还停留在2019年，最新版本的内核已经用上了 Chromium 95 了，升级下吧

**Comment by nowui** [comment]
![image](https://user-images.githubusercontent.com/3635163/221587308-f8c772ee-6764-4aa4-b22f-2a88b13f6ef0.png)

我这个是mac版本浏览器  已经是最新版了
