### ISSUE TITLE
颜色选择器react版本输入框不能输入

### ISSUE THREAD

**Issue by mysllove** [Tencent/tdesign-react#2020]
### tdesign-react 版本

最新版出现

### 重现链接

https://tdesign.tencent.com/react/components/color-picker

**Comment by honkinglin** [comment]
并没有发现问题，录个视频看看？

**Comment by mysllove** [comment]
> 并没有发现问题，录个视频看？

![29302C08-CE11-4C20-8966-9F483C12EE34_1_102_o](https://user-images.githubusercontent.com/27664778/221490179-a24be40a-a531-416e-ab2d-ac8d3e2e585d.jpeg)
@洪金林

**Comment by mysllove** [comment]
> 并没有发现问题，录个视频看？
react版本
