### ISSUE TITLE
[Select] onEnter不触发

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign-react#2039]
### tdesign 版本

0.42.3

### 重现步骤

<Select
              style={{ minWidth: 200 }}
              value={value}
              onChange={onChange}
              filterable
              onEnter={() => console.log('select')}
              clearable
              multiple
              options={roleOptions}
              popupProps={{ attach: '#userAttach' }}
            />
就这么写选了选项按enter不触发

### 期望结果

能正常触发onEnter

**Comment by HaixingOoO** [comment]
@2513483494 您好，无法复现你提出的问题，建议提供详细信息和CodeSandBox在线demo，当前issue关闭了，谢谢！！！
