### ISSUE TITLE
是不是不支持 Next.js 13 啊？

### ISSUE THREAD

**Issue by dogeow** [Tencent/tdesign-react#2050]
### tdesign-react 版本

1.0.3

### 重现步骤

yarn create next-app

然后按照你们的指南使用 Button。

### 期望结果

没报错

### 实际结果

error - ./node_modules/tdesign-react/es/button/style/index.css
Global CSS cannot be imported from within node_modules.

### 框架版本

Next.jd 13

**Comment by honkinglin** [comment]
支持的，可以参考下这个案例，稍后完善下文档说明
https://stackblitz.com/edit/nextjs-jimgwx?file=package.json,pages%2Findex.js,next.config.js
