### ISSUE TITLE
[Input]带长度限制的输入框的是否可以支持限制最小多少字数

### ISSUE THREAD

**Issue by sameenzm** [Tencent/tdesign-react#2051]
## 你建议的方案是什么
带长度限制的输入框的是否可以支持限制最小多少字数，比如字数不少于2个字。看现在已有最大的限制字数maxlength和maxcharacter。是否可支持minxxxx

<img width="663" alt="image" src="https://user-images.githubusercontent.com/17029105/224710260-9d7a4f9e-d0f2-49aa-a275-0b31cc811288.png">

**Comment by honkinglin** [comment]
这个需求看起来更像是校验相关的，限制最少多少字数那如果还未填写应该如何展示，或者填写字数不够的话应该展示什么
