### ISSUE TITLE
[ColorPicker] react版本输入框不能输入,vue版本是正常的

### ISSUE THREAD

**Issue by mysllove** [Tencent/tdesign-react#2059]
### tdesign-react 版本

1.0.3

### 重现链接

https://tdesign.tencent.com/react/components/color-picker

**Comment by mysllove** [comment]
正在用这个功能，还请尽快修复

**Comment by honkinglin** [comment]
能否再具体一点，什么条件下不能输入？
官网的案例没有这个问题，给个在线 demo 复现下你说的场景才能帮你定位到问题
https://stackblitz.com/edit/react-wdpgcg?file=src%2Fdemo.jsx

**Comment by mysllove** [comment]
> 能不能再具体一点，什么条件下不能输入？ 官网的案例没有这个问题，给个在线演示 复现下你说的场景才能帮你确定位置问题 [https ://stackblitzg-file? =src%2Fdemo.jsx](https://stackblitz.com/edit/react-wdpgcg?file=src%2Fdemo.jsx)

<img width="318" alt="image" src="https://user-images.githubusercontent.com/27664778/225232801-71d45193-9b4e-4a6d-b8d2-ff5c75bbfc8e.png">

**Comment by mysllove** [comment]
面板里面的输入框啊
