### ISSUE TITLE
TreeSelect组件，当multiple和filterable同时开启时，希望已选择项可以通过键盘删除键删除

### ISSUE THREAD

**Issue by superSnowPear** [Tencent/tdesign-react#206]
<img width="754" alt="企业微信截图_50efe5dd-72b8-4cfe-a305-446002998a71" src="https://user-images.githubusercontent.com/95472279/148729898-ce1e23e8-f451-4d13-87d2-46842499081f.png">

**Comment by HQ-Lin** [comment]
挺好的建议，后续会支持一下

**Comment by HQ-Lin** [comment]
这个能力在之后的 `input-select` 组件会一起支持了，目前 treeSelect 、select 、cascader 一些交互表现还是有点差异
