### ISSUE TITLE
[ColorPicker] react版本颜色面板输入框不能输入的问题还是没解决啊，项目都不测试的吗

### ISSUE THREAD

**Issue by mysllove** [Tencent/tdesign-react#2070]
### tdesign-react 版本

https://tdesign.tencent.com/react/components/color-picker

### 重现步骤

<img width="365" alt="image" src="https://user-images.githubusercontent.com/27664778/226153765-bb9881fa-9703-4699-a569-b498a76ed0c2.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/27664778/226153794-14cbd8b4-574c-42e6-83a8-6b19d794f8d3.png">

**Comment by carolin913** [comment]
你好之前反馈的几个地方的输入问题，已经在上个版本1.0.4中解决了，但是这次的问题用到的内部控件不一样，需要分别处理下，我们会尽快修复，感谢反馈
