### ISSUE TITLE
[Tree] 传入filter时异步加载数据展开后无法收起

### ISSUE THREAD

**Issue by ArthurYung** [Tencent/tdesign-react#2072]
### tdesign-react 版本

1.0.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-p7uek7

### 重现步骤

如上述demo必现：
https://codesandbox.io/s/tdesign-react-demo-forked-p7uek7

### 期望结果

展开后节点后可以收起

### 实际结果

展开后节点后无法收起

### 框架版本

React 16

**Comment by honkinglin** [comment]
1.1.1 fixed
