### ISSUE TITLE
[DialogPlugin] onCloseBtnClick参数无效

### ISSUE THREAD

**Issue by ArthurYung** [Tencent/tdesign-react#2075]
### tdesign-react 版本

1.0.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-e0tc7p?file=/src/demo.jsx

### 重现步骤

- DiloagPlugin打开弹窗
- 点击右上角关闭按钮

### 期望结果

调用`onCloseBtnClick`回调

### 实际结果

无响应

**Comment by uyarn** [comment]
fixed in 1.1.0
