### ISSUE TITLE
[Tree] 受控状态下checked状态渲染异常

### ISSUE THREAD

**Issue by textGuan** [Tencent/tdesign-react#2077]
### tdesign-react 版本

1.0.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lfs6vy?file=/src/demo.jsx

### 重现步骤

输入框输入任意值筛选，使得传入tree的数据发生变化，再删除输入框的值，使传入tree的值恢复，可以观察到在没有修改value的前提下，checked的渲染发生了变化

### 期望结果

受控状态下checked的渲染状态与传入的value保持一致

### 实际结果

不一致

### 框架版本

react 18.2.0

**Comment by honkinglin** [comment]
1.1.1 fixed
