### ISSUE TITLE
[table] _官网 Demo 点击筛选按钮  Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#2086]
### tdesign-react 版本

react

### 重现链接

https://stackblitz.com/run?file=src%2Findex.js

### 重现步骤

点击筛选按钮就报错https://stackblitz.com/run?file=src%2Findex.js

### 期望结果
不报错，能正常试用demo

_No response_

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/2089
