### ISSUE TITLE
[table] filterRow={() => null} 描述有误，应为 filterRow={null}

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#2087]
### tdesign-react 版本

react

### 重现步骤

<img width="957" alt="image" src="https://user-images.githubusercontent.com/52768985/227511836-b00bd7b3-d89d-46e1-8f80-e8187893d77e.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/52768985/227511898-ed1d464d-90e8-4cc9-aa32-f16291afe926.png">
<img width="1163" alt="企业微信截图_df75229b-2ddf-45f7-94e6-b99b2b18f16e" src="https://user-images.githubusercontent.com/52768985/227511914-683beabf-6797-4582-b873-2d5fdbbe8073.png">

**Comment by chaishi** [comment]
这个属于文档问题，文档是 Vue2/Vue3/React 复用的，Vue 里面是这么写，React 不是，我来更新下描述

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1219
