### ISSUE TITLE
layout组件出现闪烁问题

### ISSUE THREAD

**Issue by SKcong** [Tencent/tdesign-react#2088]
### 这个功能解决了什么问题

<img width="650" alt="image" src="https://user-images.githubusercontent.com/64339958/227692485-1331faf0-6d2a-41b7-98a5-3935747454f8.png">
useEffect是在组件render后才执行的，Layout组件在useEffect中去修改样式，会导致闪一下的问题

### 你建议的方案是什么

建议修改为useLayoutEffect

**Comment by Zzongke** [comment]
@SKcong 您好，能否提供個復現的demo，我好排查！
