### ISSUE TITLE
[Select] 输入文字删除tag bug

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign-react#2112]
### tdesign-react 版本

1.0.5

### 重现链接

https://codesandbox.io/s/w688e6?file=/src/demo.jsx

### 重现步骤

输入一个字符，按退格会删除最后一个tag
输入多个字符，字符全部删除后按两次退格才会删除tag

### 期望结果

输入一个字符，按退格不会删除最后一个tag
输入多个字符，字符全部删除后按一次退格才会删除tag

需要符合预期

**Comment by uyarn** [comment]
fixed in 1.1.1
