### ISSUE TITLE
[table] 固定头+固定列+虚拟滚动，固定列表头宽度未对齐

### ISSUE THREAD

**Issue by fanioc** [Tencent/tdesign-react#2126]
### 重现链接
https://stackblitz.com/edit/react-62kcbj?file=src%2Fdemo.jsx

### 重现步骤
同时开启，固定头 固定列 虚拟滚动，操作列表头宽度未对齐

![image](https://user-images.githubusercontent.com/33722465/229748778-a8f0e215-b84f-4410-acdd-c8b6acc59f11.png)

不清楚是不是需要额外配置宽度，还是组件行为上的问题

### 期望结果
表头宽度对齐

### 实际结果
表头宽度未对齐

| Environment | Info |
|---|---|
| 相关版本 | 1.1.0 |
| 框架版本 / 基础库版本 | React 18.2.0 |
| 系统、浏览器 | MacOS 12.6, Chrome 111.0.5563.146 |
| Node版本 |  |

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/2297
