### ISSUE TITLE
[ColorPicker] 如果defaultRecentColors中有渐变色，打开ColorPicker并且删掉这个颜色之后，切换回单色选择时会出错

### ISSUE THREAD

**Issue by renzhiVivio** [Tencent/tdesign-react#2141]
### tdesign-react 版本

1.1.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-pwm30y?file=/src/demo.jsx

### 重现步骤

1. 打开ColorPicker
2. 选择最近颜色中的渐变色
3. 点击删除
4. 切换到单色
5. 在大调色板中选择颜色，就会看到error

### 期望结果

打开ColorPicker是的渐变色可以正常删除

### 框架版本

React

**Comment by renzhiVivio** [comment]
♥️ 有劳 @gedy  @yunfeic @honkinglin  尽快确认问题。
确认有效后将下一步计划和可能需要的时间回复给 @renzhiVivio 。

**Comment by carolin913** [comment]
麻烦更新1.1.8版本，未复现问题
