### ISSUE TITLE
[select] 多选size属性未生效

### ISSUE THREAD

**Issue by wfq1095745112** [Tencent/tdesign-react#2149]
### tdesign-react 版本

1.1.2

### 重现步骤

Select: 修复多选分组展示样式异常的问题 @uyarn ([#2138](https://github.com/Tencent/tdesign-react/pull/2138))

### 期望结果

Select size="large" clearable multiple >

### 实际结果

Select clearable multiple >

### 补充说明

Select size="large" clearable multiple >
尺寸还是没有变化

**Comment by uyarn** [comment]
fixed in 1.1.3
