### ISSUE TITLE
[Table] edit数据类型定义错误

### ISSUE THREAD

**Issue by jacksonjin** [Tencent/tdesign-react#2151]
### tdesign-react 版本

1.1.1

### 重现步骤

图一：![image](https://user-images.githubusercontent.com/71485170/232448049-5f30db0d-f1a6-4012-81d2-69b98afac26d.png)
图二：![image](https://user-images.githubusercontent.com/71485170/232448837-114a63c5-6196-4171-9e5a-b6bc96b1010c.png)
图三：![image](https://user-images.githubusercontent.com/71485170/232449196-f02d2268-caf7-44c1-a4cf-69b6fc5908d8.png)
图一是项目中定义类型之后提示的错误
图二是在项目中触发onEdited方法打印的context的值
图三是tdesign中对用的onEdited类型的定义

### 框架版本

React(18.2.0)

**Comment by chaishi** [comment]
截图信息不完整，看不明白问题，辛苦提供一个示例代码。
