### ISSUE TITLE
[Input] tips 不占用实际高度，过长换行时会被遮挡

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#2166]
### tdesign-react 版本

1.1.2

### 重现链接

https://stackblitz.com/edit/react-5ak4ss?file=src%2Fdemo.jsx

### 重现步骤

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/37169906/232954596-088c5469-b0ad-4e7f-958d-9bbf1d0343a4.png">

### 期望结果

让 tips 内容也占用高度

**Comment by honkinglin** [comment]
占据高度也会有破坏产品体验的问题，例如在有些对齐的场景因为有了高度所以出现错乱，这块加个省略号然后气泡处理吧

**Comment by moecasts** [comment]
能不能加个属性，让用户自己来控制出不出现高度？省略号加 tooltip 的方法好像不太好。。。

**Comment by HaixingOoO** [comment]
@uyarn @NWYLZW 这个我提几个建议：
- 1、`tip`不用`absolute`来定位了，然后里面有多少值就填充下去显示多少高度；
- 2、然后添加个api来实现用户需要超出一行时出现省略号，然后加`tooltip`(不一定要组件，就默认的css来显示，用户需要的话自己使用Tooltip)来显示；

你们觉得呢？
