### ISSUE TITLE
[Upload] 上传图片时不能自定义文件列表内容，也就是theme选择image时fileListDisplay无效

### ISSUE THREAD

**Issue by Alicecsl** [Tencent/tdesign-react#2173]
### tdesign-react 版本

1.1.1

### 重现链接

https://stackblitz.com/edit/react-mgcbk6?file=src%2Fdemo.jsx

### 重现步骤

<img width="720" alt="image" src="https://user-images.githubusercontent.com/38271506/233816336-2fbdb2e1-14af-4f24-9c43-42dcd93303e3.png">

**Comment by chaishi** [comment]
当前特性，已于 2023-07-12 `v1.1.14` 中支持，issue close

自定义示例代码：https://stackblitz.com/edit/react-ml7zv3?file=src%2Fdemo.jsx

更新日志：https://tdesign.tencent.com/react/changelog
<img width="758" alt="image" src="https://github.com/Tencent/tdesign-react/assets/11605702/95845c2b-0d1c-4d94-9dde-8c5a600994c3">
