### ISSUE TITLE
[table] 表头筛选，设置false为value筛选状态失效

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#2179]
### tdesign-react 版本

1.1.3

### 重现链接

https://stackblitz.com/edit/react-arcxcf?file=src%2Fdemo.jsx

### 重现步骤

<img width="1223" alt="企业微信截图_958973f6-477e-4e50-99ec-00f0e9820238" src="https://user-images.githubusercontent.com/52768985/234517298-e38cfb1a-61d8-4ab3-b29d-dbc06a9b5265.png">

**Comment by chaishi** [comment]
我这边根据提供的代码，稍微改造了一下，可以实现，示例代码见：
https://stackblitz.com/edit/react-62kcbj-8wj4ed?file=src%2Fdemo.jsx

<img width="871" alt="image" src="https://github.com/Tencent/tdesign-react/assets/11605702/a694c726-952b-426e-b5d4-6b011d20af3f">

由于当前 issue 属于使用不当，组件本身无需进行问题修复，issue close。
