### ISSUE TITLE
tree组件改变数据源时整个组件刷新

### ISSUE THREAD

**Issue by CuzyouZQL** [Tencent/tdesign-react#2180]
### tdesign-react 版本

1.0.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-i76j0m?file=/src/demo.jsx

### 重现步骤

点击按钮给树添加一个节点时，整个组件会重新刷新，业务中希望能通过局部刷新的方式来更新treeData，目前貌似未能找到现成api实现

### 期望结果

部分数据源改变时，局部更新，而不是全局更新

### 实际结果

部分数据源改变时，整个组件刷新了一次

### 框架版本

react16.14.0

### 浏览器版本

版本 108.0.5359.98（正式版本） (x86_64)

### 系统版本

MacOs12.6.2

### Node版本

v16.18.1

### 补充说明

业务中需要给ckeditor5富文本添加一个目录大纲，实现过程中时通过监听编辑区域变化，获取标题且构建成treeData，在将treeData通过tree组件展示为目录大纲；在编辑器中输入标题之后，左侧对应展示目录大纲，但是输入过程中，左侧都会刷新一遍

**Comment by honkinglin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-jhpop5?file=/src/demo.jsx
