### ISSUE TITLE
[TreeSelect] label 为 ReactNode 时，输入框的值和 title 都变成了 [object Object]

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#2181]
### tdesign-react 版本

1.0.1

### 重现链接

https://stackblitz.com/edit/react-wbn734?file=src%2Fdemo.jsx

### 重现步骤

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/37169906/234788437-69e30325-0896-4010-8b59-c09911a61e49.png">

### 期望结果

输入框能正常渲染，title 能渲染成文字则渲染，不行就去掉？

**Comment by honkinglin** [comment]
如果是多层dom结构，似乎没有办法从 ReactNode 节点上直接获取到文本信息

**Comment by moecasts** [comment]
> 如果是多层dom结构，似乎没有办法从 ReactNode 节点上直接获取到文本信息
用 `innerText` 去拿？

**Comment by Ali-ovo** [comment]
> 如果是多层dom结构，似乎没有办法从 ReactNode 节点上直接获取到文本信息

看了一下源码 如果要满足 label 可以传入 ReactNode 的格式的话， 貌似需要自己写一个假的 input 框， 这样里面就可以渲染 ReactNode了

**Comment by moecasts** [comment]
> 看了一下源码 如果要满足 label 可以传入 ReactNode 的格式的话， 貌似需要自己写一个假的 input 框， 这样里面就可以渲染 ReactNode了

emm，这个 input 框又没啥关系，是 `title` 的问题。
<img width="755" alt="image" src="https://github.com/Tencent/tdesign-react/assets/37169906/71ab7fe8-3802-4bbb-aa71-1f9be63a5503">

**Comment by Ali-ovo** [comment]
> 

我指的是你的bug中 input框里面是 [object object] 的情况

**Comment by moecasts** [comment]
> 我指的是你的bug中 input框里面是 [object object] 的情况

现在本来就是自定义的，valueDisplay 就可以改。

**Comment by Ali-ovo** [comment]
> 如果是多层dom结构，似乎没有办法从 ReactNode 节点上直接获取到文本信息

提了一个pr，目前是直接隐藏掉了， 如有更好的方案可以后续再优化更新
