### ISSUE TITLE
[Skeleton] 默认主题text携带了默认样式进来

### ISSUE THREAD

**Issue by pnuocao** [Tencent/tdesign-react#2185]
### tdesign-react 版本

1.1.3

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-ds4nng

### 重现步骤

点击链接即可

### 期望结果

渲染两个指定宽高的骨架图

### 实际结果

渲染两个指定宽高的骨架图，但是多了一个因为theme字段的defalutValue带来的骨架

### 框架版本

react1.1.3

### Node版本

16

**Comment by uyarn** [comment]
fixed in 1.1.6
