### ISSUE TITLE
[Upload] Upload 怎么回显？

### ISSUE THREAD

**Issue by NiLinli** [Tencent/tdesign-react#2187]
### 这个功能解决了什么问题
1. 新增时候上传图片
2. 编辑时候获取 url  回显示图片

### 你建议的方案是什么？
文档没有告知回显方法，尝试通过 url 构造 fake UploadFile 值，然后 form.setFieldsValue ，也没有效果

**Comment by chaishi** [comment]
### 传入 `files` 属性可以自动回显
<img width="884" alt="image" src="https://github.com/Tencent/tdesign-react/assets/11605702/5beff8db-cb7a-45ca-89c9-058e227561f3">

<img width="986" alt="image" src="https://github.com/Tencent/tdesign-react/assets/11605702/286f98d1-d31f-4b50-9384-be315c6511b5">


```
const [files2, setFiles2] = useState([
  {
    url: 'https://tdesign.gtimg.com/demo/demo-image-1.png',
    name: 'default.jpeg',
    status: 'success',
  },
]);

<Upload files={files} />
```
