### ISSUE TITLE
[formitem] 请问一下用这个正则匹配规则做校验，当数据量大的时候会导致页面卡死

### ISSUE THREAD

**Issue by CassenChan** [Tencent/tdesign-react#2195]
### tdesign-react 版本

1.1.4

### 重现链接

https://stackblitz.com/edit/react-tgrywh?file=src%2Fdemo.jsx，

### 重现步骤

输入700000611006,700000611005,700000611004,700000611003,700000610995,700000610994,700000610993,700000610992,700000610991,700000610989,700000610988,700000610987,700000610986,700000610985,700000610984,700000610983,700000610982,700000608277,700000608276,700000608273,700000608267,700000608266,700000608265,700000608264,700000608263,700000608262,700000608261,700000608259,700000608258,700000608257,700000608256,700000608255,700000608254,700000608253,700000608252,700000608251,700000608249,700000608248,700000608247,700000608242,700000608238,700000608237,700000608236,700000608235,700000608234,700000608233,700000608232,700000600789,700000600788,700000600787,700000600786,700000600785,700000600784,700000600783,700000600782,700000600781,700000600779,700000600777,700000588921,700000587555,700000612431,700000612429,700000612428,700000612427,700000612426,700000612425,700000612424,700000612423,700000612422,700000612421,700000612419,700000612418,700000612417,700000612416,700000612415,700000612414,700000612413,700000612409,700000612408,700000612406,700000612405,700000612403,700000612401,700000612398,700000612397,700000612396,700000612395,700000612394,700000612393,700000612392,700000612391,700000612389,700000612388,700000612387,700000612386,700000612385,700000612384,700000612383,700000612382,700000612381,700000612379,700000612378,700000612377,700000612376,700000612375,700000612374,700000612373,700000612372,700000612371,700000612369,700000612368,700000612367,700000612366,700000612365,700000612364,700000612363,700000612362,700000612346,700000611242,700000587601,700000619515,3211064422

之后 敲一个空额空格

**Comment by honkinglin** [comment]
```javascript
/^(([a-zA-Z0-9]){6,},?)+$/.test(`700000611006,700000611005,700000611004,700000611003,700000610995,700000610994,700000610993,700000610992,700000610991,700000610989,700000610988,700000610987,700000610986,700000610985,700000610984,700000610983,700000610982,700000608277,700000608276,700000608273,700000608267,700000608266,700000608265,700000608264,700000608263,700000608262,700000608261,700000608259,700000608258,700000608257,700000608256,700000608255,700000608254,700000608253,700000608252,700000608251,700000608249,700000608248,700000608247,700000608242,700000608238,700000608237,700000608236,700000608235,700000608234,700000608233,700000608232,700000600789,700000600788,700000600787,700000600786,700000600785,700000600784,700000600783,700000600782,700000600781,700000600779,700000600777,700000588921,700000587555,700000612431,700000612429,700000612428,700000612427,700000612426,700000612425,700000612424,700000612423,700000612422,700000612421,700000612419,700000612418,700000612417,700000612416,700000612415,700000612414,700000612413,700000612409,700000612408,700000612406,700000612405,700000612403,700000612401,700000612398,700000612397,700000612396,700000612395,700000612394,700000612393,700000612392,700000612391,700000612389,700000612388,700000612387,700000612386,700000612385,700000612384,700000612383,700000612382,700000612381,700000612379,700000612378,700000612377,700000612376,700000612375,700000612374,700000612373,700000612372,700000612371,700000612369,700000612368,700000612367,700000612366,700000612365,700000612364,700000612363,700000612362,700000612346,700000611242,700000587601,700000619515,3211064422 `)
```
<img width="779" alt="image" src="https://user-images.githubusercontent.com/24469546/236416990-d175b4a1-9ed8-4a4c-a010-88914bbf776d.png">

只匹配一次也会导致崩溃，看着像正则的bug，无能为力

**Comment by HelKyle** [comment]
@CassenChan 你的正则写的有问题，`{6,},?)+` 这部分会产生非常多的排列组合（因为`,` 可选，正则会将每个数字拆成 6 + 6 回溯很多次）。

改造成下面这样应该就可以了：
```js
^(([a-zA-Z0-9]){6,})(,([a-zA-Z0-9]){6,})*$
```
