### ISSUE TITLE
[Table] validateTrigger: 'change' 校验不正确

### ISSUE THREAD

**Issue by NiLinli** [Tencent/tdesign-react#2219]
### tdesign-react 版本

1.1.4

### 重现链接

https://stackblitz.com/edit/react-inliuo?file=src%2Fdemo.jsx

### 重现步骤

官网demo
1. 申请人 col 添加    validateTrigger: 'change',
2. 在对应的 input 输入任意一个字 

### 期望结果

没有任何提示

### 实际结果

会提示 不能为空

bug原因分析：
输入 ‘你' 校验的是 ''
输入 '你好' 校验的是 '你'
bug 在于校验的是 prevValue

### 框架版本

React

**Comment by chaishi** [comment]
`validateTrigger: 'change'` 原计划是应用在 可编辑单元格场景，对于 可以编辑行 场景，没有特地支持和校验。

需要针对 可以编辑行 场景进行开发验证

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/2297
