### ISSUE TITLE
table组件设置expandOnRowClick为true时，点击整行报错

### ISSUE THREAD

**Issue by songdongdong123** [Tencent/tdesign-react#2238]
### tdesign-react 版本

1.1.7

### 重现链接

https://stackblitz.com/edit/react-jvtfam?file=src%2Fdemo.jsx

### 重现步骤

点击行，展开时报错

### 期望结果

修复该报错

### 框架版本

react 18.2.0

### 浏览器版本

Chrome(113.0.5672.126)

### 系统版本

MacOs(13.3.1 (a))

### Node版本

v14.21.2

### 补充说明

官网demo就存在报错问题

**Comment by songdongdong123** [comment]
<img width="1373" alt="image" src="https://github.com/Tencent/tdesign-react/assets/20263883/44ace210-beaf-444d-8afa-591ad9b7a346">

**Comment by chaishi** [comment]
fixed in `v1.1.10`,  2023-06-13
