### ISSUE TITLE
[Select] select组件添加popupProps属性之后，panelTopContent下面的input输入的时候会失去焦点。

### ISSUE THREAD

**Issue by yangdong6** [Tencent/tdesign-react#2245]
### tdesign-react 版本

1.1.8

### 重现链接

https://stackblitz.com/edit/react-zkakbq?file=src%2Fdemo.jsx

### 重现步骤

1、给select组件添加popupProps属性
2、panelTopContent下面的input输入
3、input自动失去焦点

### 期望结果

input可以正常使用

### 框架版本

react（18）

**Comment by carolin913** [comment]
<img width="441" alt="企业微信截图_4ad133da-95aa-4d2e-a777-338fa89ea701" src="https://github.com/Tencent/tdesign-react/assets/2638568/7c3bc982-6551-410e-b31a-af57d1f5df7e">
可以先用string来解决下，具体function传入attach会导致的问题还在排查中

**Comment by honkinglin** [comment]
这个不应该算bug，使用箭头函数作为props传入组件，每次render时期都会重新生成新的箭头函数，站在组件的角度上props变更了就是应该重新渲染，所以panel整个重新渲染后就失去焦点了，正确的写法应该是用useCallback包裹函数后作为参数传入
参考这个：
https://stackblitz.com/edit/react-zrnqmz-cjnusa?file=src%2Fdemo.jsx

**Comment by honkinglin** [comment]
<img width="566" alt="image" src="https://github.com/Tencent/tdesign-react/assets/24469546/8b0564fe-3417-49b8-91e3-cd211a6e6184">
