### ISSUE TITLE
[Table] 是否可以支持监听列宽resize事件

### ISSUE THREAD

**Issue by night-c** [Tencent/tdesign-react#2247]
### 这个功能解决了什么问题

可以在本地或服务端保存用户调整后的列宽

### 你建议的方案是什么

增加列resize事件
onColumnResize(colKey: string, width: number): void

**Comment by chaishi** [comment]
后续支持

**Comment by chaishi** [comment]
supported in `v1.1.9` by @honkinglin, 2023-06-06
