### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by brandonwei** [Tencent/tdesign-react#2276]
### tdesign 版本

1.1.8

### 重现步骤

npx create-react-app my-app
npm install tdesign-react
修改./src/App.js，引入layout，如下图
![image](https://github.com/Tencent/tdesign/assets/13963840/1a7cf3fb-27df-4459-b445-738097916d98)

npm run test
![image](https://github.com/Tencent/tdesign/assets/13963840/4a645f29-ded6-45c2-8038-5b01e61e8b27)

**Comment by HaixingOoO** [comment]
> It seems that it won't happen again now. If it happens again, please reopen the issue. @uyarn

ok
