### ISSUE TITLE
[Swiper] 在第一个 item 继续向前时，动画会跨过其他的 item

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#2278]
### tdesign-react 版本

1.1.9

### 重现链接

https://tdesign.tencent.com/react/components/swiper#%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8

### 重现步骤

vue-next 那边是正常的

### 期望结果

和 vue 保持一致。

**Comment by Ali-ovo** [comment]
好像在vue那边也是同样的效果
你的这个问题是说： 
假如我现在有 1，2，3，4， 这四个图片
当我在 `1 点击上一个`的时候，动画会显示 `1 -> 2 -> 3 -> 4`这样的效果，而不是直接 `1 -> 4` 这样的效果对吗

**Comment by moecasts** [comment]
> 好像在vue那边也是同样的效果 你的这个问题是说： 假如我现在有 1，2，3，4， 这四个图片 当我在 `1 点击上一个`的时候，动画会显示 `1 -> 2 -> 3 -> 4`这样的效果，而不是直接 `1 -> 4` 这样的效果对吗

确实，只有 `vue-next` 的正常

**Comment by uyarn** [comment]
fixed 1.5.1
