### ISSUE TITLE
[Popup] hideEmptyPopup 无效果

### ISSUE THREAD

**Issue by rizhaoyuanshan** [Tencent/tdesign-react#2283]
### tdesign-react 版本

1.1.9

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-wl2z83?file=/src/demo.jsx

### 重现步骤

如果是content传入一个空组件，hideEmptyPopup没有效果

### 框架版本

react18

**Comment by Ali-ovo** [comment]
应该是可以加一个 `content={() => null}` 这个的判断， 
你这个示例中 `content={<Comp/>}`其实已经是一个组件了，所以不太好判断渲染的节点到底是不是有效的

**Comment by uyarn** [comment]
是的 这里因为传了content 这个API只是确保content为空时不会渲染
