### ISSUE TITLE
[Switch] customValue该怎么写才不报错?

### ISSUE THREAD

**Issue by sin911** [Tencent/tdesign-react#2285]
### tdesign-react 版本

"tdesign-react": "^1.0.1"

### 重现链接

https://codesandbox.io/embed/pedantic-poitras-252lyy?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤

<Switch size='large' customValue={['1', '0']} />
会报错:TDesign Switch Error: value is not in customValue: ["1","0"]
如果换如下写法,也报一样的错误
<Switch size='large' customValue={['1', '0']} defaultValue={'1'} />
或 <Switch size='large' customValue={['1', '0']} value={'1'} />
所以customValue该怎么写呢?

### 期望结果

customValue该怎么写呢?

### 框架版本

react18

### 浏览器版本

chrome113

### 系统版本

Macos

**Comment by huangyulie** [comment]
@sin911 康康这个，他这个组件用customValue的时候，得有一个value指作为最初的值，加上就不会出错了，源码在这里进行判断
<img width="665" alt="image" src="https://github.com/Tencent/tdesign-react/assets/73587626/92027ace-ede3-4e53-87bd-a268684ad33e">
下面是我写的例子，随便写的，可以参考🤗
<img width="645" alt="image" src="https://github.com/Tencent/tdesign-react/assets/73587626/95942805-52e7-47a4-a42f-255dad8934be">
<img width="700" alt="image" src="https://github.com/Tencent/tdesign-react/assets/73587626/7cbdf8af-4bef-4347-a98b-82861c86046d">

**Comment by sin911** [comment]
@huangyulie 多谢,问题解决了
