### ISSUE TITLE
[ImageViewer] 文档站上面的主题选择器遮挡了图片预览的toolbar

### ISSUE THREAD

**Issue by cw1997** [Tencent/tdesign-react#2287]
### tdesign-react 版本

1.1.9

### 重现链接

https://tdesign.tencent.com/react/components/image-viewer 

### 重现步骤

如图所示

![image](https://github.com/Tencent/tdesign-react/assets/11588555/aa06d56e-6106-4e01-b3f0-1087923f9fb9)

**Comment by Ali-ovo** [comment]
感觉需要这个需要重新设计一下位置，日常开发使用的话肯定不会有这个情况。只是官网示例会有这个问题

**Comment by uyarn** [comment]
挺尴尬的 这个imageviewer的层级有点低 之前测试是发现在table等组件里会被固定列等场景遮盖所以把dock的层级往上提了
