### ISSUE TITLE
[Message] 希望跟 MessagePlugin 一样，能够支持 placement 、 attach 和 offset 的配置

### ISSUE THREAD

**Issue by zww-v5** [Tencent/tdesign-react#2291]
### 这个功能解决了什么问题

Message 在使用时由于无法配置以上的内容，导致无法调整位置。而这两个属性又是非常常用的功能。这就导致基本上只能使用 MessagePlugin ，但有些场景下 Message 的使用会更为直观。
比如以下的场景，要把 Alert 调整为 Message 时，用 Message 更为对应，但改为 MessagePlugin 就得调整整个写法。
<img width="939" alt="image" src="https://github.com/Tencent/tdesign-react/assets/9295948/1f29f2b7-4f8f-4c10-8276-456482a515ca">

### 你建议的方案是什么

Message 同样支持这几类属性的配置，而不是只能使用 MessagePlugin。

**Comment by chaishi** [comment]
文字描述是 Message
但是截图是 Alert

**Comment by chaishi** [comment]
> 比如以下的场景，要把 Alert 调整为 Message 时，用 Message 更为对应

这里的 “以下场景”，是指什么场景，为什么要把 Alert 调整为 Message。

Alert 应用场景，固定在某一个地方，一般为顶部，除非用户操作，否则永远不消失。
Message 消息纯组件，用于业务自行封装更多功能。
MessagePlugin 消息组件插件，显示几秒钟之后自动消失。

你要的是什么场景，Message 的组件的样式，还是自动消失的功能？

**Comment by chaishi** [comment]
看到一个 onDismiss，Alert 组件好像没有这个 API
