### ISSUE TITLE
[AutoComplete] 未完全匹配时，框内按回车键，弹框未收起，且控制台报错

### ISSUE THREAD

**Issue by ghostpanda** [Tencent/tdesign-react#2298]
### tdesign-react 版本

1.1.10

### 重现步骤

未完全匹配框内按回车键，弹框未收起，后台报错  
<img width="903" alt="image" src="https://github.com/Tencent/tdesign-react/assets/8744841/213ba849-13fa-497f-99bb-47aeb8e1d915">  

<img width="594" alt="image" src="https://github.com/Tencent/tdesign-react/assets/8744841/0f3b6765-6874-4a31-8c9a-824991db6f06">

### 期望结果

弹框收起，控制台无报错

### 框架版本

React(18.2.0)

**Comment by chaishi** [comment]
信息已收到，抽空处理

**Comment by Ali-ovo** [comment]
> 未完全匹配框内按回车键，弹框未收起，后台报错

我感觉这个交互可以改成 
当没有匹配的时候 `按回车 会自动填入第一项`会不会交互更友好一点

如果这个交互可以的话，我可以来帮忙修复这个 issues

**Comment by ghostpanda** [comment]
> > 未完全匹配框内按回车键，弹框未收起，后台报错
> 
> 我感觉这个交互可以改成 当没有匹配的时候 `按回车 会自动填入第一项`会不会交互更友好一点
> 
> 如果这个交互可以的话，我可以来帮忙修复这个 issues

AutoComplete本质上是Input的一个扩展，毕竟不是Select，从这个角度看，应该不需要默认选中第一项😀

**Comment by Ali-ovo** [comment]
> > > 未完全匹配框内按回车键，弹框未收起，后台报错
> > 
> > 
> > 我感觉这个交互可以改成 当没有匹配的时候 `按回车 会自动填入第一项`会不会交互更友好一点
> > 如果这个交互可以的话，我可以来帮忙修复这个 issues
> 
> AutoComplete本质上是Input的一个扩展，毕竟不是Select，从这个角度看，应该不需要默认选中第一项😀

但是单单回车关闭下拉框的交互也是有点过于生硬
