### ISSUE TITLE
[Statistic/数值显示] 功能需求，希望增加这个组件！ 

### ISSUE THREAD

**Issue by kwooshung** [Tencent/tdesign-react#2309]
### 先说下背景
先后用过 Ant Design，Arco Design等众多UI，感觉不是缺少这个就是缺少那个。前几天我在想，蚂蚁、头条都有自己的前端框架，我觉得作为特别重视用户体验的腾讯，应该也得有，一搜还真有，发现想要的功能都有，连颜色选择器都有，感觉特别对胃口！

10天后新项目就要启动了，也在打量到底使用谁更好，目前感觉腾讯做的最完善，各种平台都兼容，所以打算使用TDesign！

### 解决了什么问题
> 突出展示某个或某组数字，如显示数值，如金额，排名、带描述的统计类数据。

### 你建议的方案是什么

我认为不必细说，看看同类产品的 **数值显示** 组件，我相信腾讯能做的更好，甚至这个组件可能会有同类产品没有的功能。

- Ant Design：https://ant.design/components/statistic-cn
- Arco Design：https://arco.design/react/components/statistic
- ELEMENT UI：https://element.eleme.cn/#/zh-CN/component/statistic
```[tasklist]
### Tasks
- [ ] https://github.com/Tencent/tdesign-react/issues/2310
- [ ] https://github.com/Tencent/tdesign-react/issues/2311
- [ ] https://github.com/Tencent/tdesign-react/issues/2312
- [ ] https://github.com/Tencent/tdesign-react/issues/2313
- [ ] https://github.com/Tencent/tdesign-react/issues/2314
- [ ] https://github.com/Tencent/tdesign-react/issues/2315
```

**Comment by uyarn** [comment]
这个组件已经在开发中 可以参考这个的进度 这个issue先关闭了https://github.com/orgs/Tencent/projects/1/views/31?pane=issue&itemId=13678494
