### ISSUE TITLE
popup提示隐藏时遮挡了其他组件，导致其他组件无法响应事件

### ISSUE THREAD

**Issue by partical** [Tencent/tdesign-react#231]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

版本：0.22.1

**Describe the bug**
popup提示隐藏时，dom元素还存在，且z-index比较高，遮挡了底下的组件，导致组件无法响应事件
![image](https://user-images.githubusercontent.com/9391316/149282506-0220acec-8215-4a55-8a3f-b0397d3f7e3b.png)

**Additional context**

**Comment by chaishi** [comment]
是一个问题

**Comment by uyarn** [comment]
可以先加个`destroyOnClose`处理一下

**Comment by HQ-Lin** [comment]
> 可以先加个`destroyOnClose`处理一下

还是得处理一下默认情况 `display: none`

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-react/releases/tag/0.23.1 fixed
