### ISSUE TITLE
[Result/结果] 功能需求，希望增加这个组件！

### ISSUE THREAD

**Issue by kwooshung** [Tencent/tdesign-react#2312]
### 这个功能解决了什么问题

用于反馈一系列操作任务的处理结果，当有重要操作需告知用户处理结果，且反馈内容较为复杂时使用。

因为有的时候，总是使用弹窗之类的告知用户结果，也不是一种好的设计。

### 你建议的方案是什么

参考同类产品：

- Ant Design：https://ant.design/components/result-cn
- Arco Design：https://arco.design/react/components/result
- ELEMENT UI：https://element.eleme.cn/#/zh-CN/component/result
- UDC Desing：https://findesign.jd.com/#/components/result

```[tasklist]
### Tasks
- [ ] https://github.com/Tencent/tdesign-react/issues/2309
- [ ] https://github.com/Tencent/tdesign-react/issues/2310
- [ ] https://github.com/Tencent/tdesign-react/issues/2311
- [ ] https://github.com/Tencent/tdesign-react/issues/2313
- [ ] https://github.com/Tencent/tdesign-react/issues/2314
- [ ] https://github.com/Tencent/tdesign-react/issues/2315
```

**Comment by uyarn** [comment]
在计划内 可以参考这个的进度 这个issue先关闭了https://github.com/orgs/Tencent/projects/1/views/31?pane=issue&itemId=13678494
