### ISSUE TITLE
select组件下拉面板跳动

### ISSUE THREAD

**Issue by partical** [Tencent/tdesign-react#232]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

版本：0.22.1

**Describe the bug**
点击选择时，第一次点击展示在下面，再点一次跳到上面去了。
![Kapture 2022-01-13 at 15 19 27](https://user-images.githubusercontent.com/9391316/149283831-83dc7176-2593-471e-a216-f710c3683af4.gif)

**Additional context**
popupProps 设置为popupProps={{ placement: 'bottom-left', overlayStyle: { width: 300, height: 280 } }}

**Comment by uyarn** [comment]
Duplicate of  #93
