### ISSUE TITLE
[DatePicker/日期选择器] 清空内容，弹窗会闪烁一下。

### ISSUE THREAD

**Issue by kwooshung** [Tencent/tdesign-react#2320]
### tdesign-react 版本

1.4.4

### 重现链接

https://tdesign.tencent.com/react/components/date-picker

### 重现步骤

就第一个示例，把配置中的clearable打开。

随便选择一个日期，然后点击右侧的×清空，弹窗会闪一下。

### 期望结果

两个方案：
1、点击x，弹窗根本不会显示。
2、点击x，弹窗自动弹出。

这两个方案甚至可以给个api，设置不同的处理效果。

### 框架版本

React18

### 浏览器版本

Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51

### 系统版本

Windows11

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/f7c11701-3aea-4736-b0eb-5cb2fb0575f8)

我看了一下，發現是date-picker的觸發事件有個是mousedown傳到popup組件，導致點擊清除時先觸發mousedown，然後才觸發clear按鈕的click事件，所有我現在有兩種解決辦法；
1.設置傳入的popup的trigger=“click”；
![image](https://github.com/Tencent/tdesign-react/assets/65376724/d15947e9-c949-4647-aeb0-4442b72086f4)
2.設置clear的清除按鈕點擊事件click為mousedown；
![image](https://github.com/Tencent/tdesign-react/assets/65376724/0f0dd7cb-d572-46ab-bc98-1a0af6c20f81)

**Comment by uyarn** [comment]
fixed 1.4.1

**Comment by huangchen1031** [comment]
这个修改导致了另一个问题，我在Popup里放了一个clearable的Input时，点击清空会导致Popup意外关闭。。。
因为阻止了冒泡，Popup上这个hasPopupMouseDown无法被标记，
![image](https://github.com/Tencent/tdesign-react/assets/16714412/b6c43474-4593-40e8-88df-eabb7e27da4b)
在处理click事件的时候被当做了overlay意外的元素被关闭。。。
![image](https://github.com/Tencent/tdesign-react/assets/16714412/50ed57da-3386-4a2f-94c2-8aee98cddf15)

**Comment by HaixingOoO** [comment]
您好，可以给个在线demo看看吗？[在线stackblitz](https://stackblitz.com/edit/react-qhfyzy?file=src%2Fdemo.jsx)
我这里测试好像没问题啊，是我哪里和你的不同嘛？

**Comment by huangchen1031** [comment]
> 您好，可以给个在线demo看看吗？[在线stackblitz](https://stackblitz.com/edit/react-qhfyzy?file=src%2Fdemo.jsx) 我这里测试好像没问题啊，是我哪里和你的不同嘛？

这个demo把react和react-dom版本下降到16.14.0可以复现。这是个react16事件系统的问题，`stopPropagation`没能阻止document对事件的监听，导致没有触发`PopupProps`中的`onMouseDown`事件，却触发了`document`上监听的`mousedown`事件。

**Comment by HaixingOoO** [comment]
> > 您好，可以给个在线demo看看吗？[在线stackblitz](https://stackblitz.com/edit/react-qhfyzy?file=src%2Fdemo.jsx) 我这里测试好像没问题啊，是我哪里和你的不同嘛？
> 
> 这个demo把react和react-dom版本下降到16.14.0可以复现。这是个react16事件系统的问题，`stopPropagation`没能阻止document对事件的监听，导致没有触发`PopupProps`中的`onMouseDown`事件，却触发了`document`上监听的`mousedown`事件。

在下一个版本修复😃
