### ISSUE TITLE
[Upload] 多选上传文件后，展示的文件列表有概率翻倍

### ISSUE THREAD

**Issue by fakeou** [Tencent/tdesign-react#2331]
### tdesign-react 版本

1.1.5

### 重现链接

https://codesandbox.io/s/nkyx2d?file=/src/demo.jsx

### 重现步骤

在官方的多选上传示例中，如果选中多个文件上传，其中包含未成功上传的文件，有概率使得displayFile与files不同步，如图，一般较大的exe或者dmg文件上传时会报错（files中的文件列表是正确的，而displayFiles列表除了失败的文件都重复了）

![image](https://github.com/Tencent/tdesign-react/assets/7885490/7466f568-ce38-4abc-8a3b-aa8f4d838e4f)

![image](https://github.com/Tencent/tdesign-react/assets/7885490/be97d3b4-a9e1-4334-8b7d-122f88b9ae35)

这是工作时截取的组件数据
![image](https://github.com/Tencent/tdesign-react/assets/7885490/c843f9dd-753e-4b2a-beca-1331c1bb408b)

### 期望结果
展示的文件数量与files一致
_No response_

### 实际结果
展示的文件数量不正确
_No response_

**Comment by chaishi** [comment]
对于概率事件的问题，我这边尝试了很多次，暂时没有复现，
辛苦提供一下明确可复现问题的操作路径，以便我们解决问题。

当前问题描述，暂时无法解决
