### ISSUE TITLE
[BreadCrumb] 类型未完全抛出

### ISSUE THREAD

**Issue by fatWill** [Tencent/tdesign-react#2340]
### tdesign-react 版本

1.1.12

### 重现步骤

![image](https://github.com/Tencent/tdesign-react/assets/20520334/3460ef0d-8218-4306-a068-72e8e1072f02)

在 BreadCrumbItem 中，这里是将所有传递的 props 全部 reset 进去了。

但是在某次更新却把这个类型去抹掉了。

![image](https://github.com/Tencent/tdesign-react/assets/20520334/47c2facb-01aa-4443-8c57-0e0dc1a5941f)

而我们的版本使用是有在 BreadCrumbItem 中使用 onclick 事件，结果却报 ts 类型错误。

**Comment by HaixingOoO** [comment]
fixed 1.5.3!
