### ISSUE TITLE
[popupconfirm] 建议添加鼠标hover的时候就展示出来的能力

### ISSUE THREAD

**Issue by 2513483494** [Tencent/tdesign-react#2351]
### 这个功能解决了什么问题

建议添加鼠标hover的时候就展示出来的能力，目前的话似乎只能通过点击的方式触发，但是如果有场景需要hover的时候触发就不行了。

### 你建议的方案是什么

建议添加鼠标hover的时候就展示出来的能力

**Comment by chaishi** [comment]
```
<Popconfirm trigger="hover" content={'确认删除订单吗'} cancelBtn={null}>
        <Button theme="primary">删除订单</Button>
      </Popconfirm>
```
试了下，确实无效

**Comment by 2513483494** [comment]
> ```
> <Popconfirm trigger="hover" content={'确认删除订单吗'} cancelBtn={null}>
>         <Button theme="primary">删除订单</Button>
>       </Popconfirm>
> ```
> 
> 试了下，确实无效

是的，感觉这个功能挺实用的，如果可以的话，希望可以添加这个能力

**Comment by chaishi** [comment]
Popup 支持 hover，是否有兴趣尝试一下 提一个 PR 支持这个特性

**Comment by Ali-ovo** [comment]
我来吧

**Comment by Zzongke** [comment]
@2513483494 解决方案：https://github.com/Tencent/tdesign-react/pull/2366#issuecomment-1690908083
