### ISSUE TITLE
[Popconfirm] confirmBtn 的属性设置为对象不生效

### ISSUE THREAD

**Issue by jacksonjin** [Tencent/tdesign-react#2360]
### tdesign-react 版本

1.1.13

### 重现步骤

https://codesandbox.io/s/5lq5c4?file=/src/demo.jsx
![image](https://github.com/Tencent/tdesign-react/assets/71485170/8dca3540-2227-4924-ace0-1ca184e7a4af)

**Comment by imp2002** [comment]
verified, I'm try to resolve.
