### ISSUE TITLE
dialog 的 theme='danger' 无效

### ISSUE THREAD

**Issue by zww-v5** [Tencent/tdesign-react#2364]
### tdesign-react 版本

tdesign-react@1.1.8

### 重现步骤

在 Dialog 组件中配置 theme='danger' 时，最终弹出的窗口没有出错的图标。
<img width="308" alt="image" src="https://github.com/Tencent/tdesign-react/assets/9295948/b3e162b3-af60-43eb-b53c-88e00fd40834">
<img width="507" alt="image" src="https://github.com/Tencent/tdesign-react/assets/9295948/d0bd9518-8d7c-4a23-8e65-22c00215ac73">

查看了下源码，写的是 error，而非 danger，但 ts 定义则是 danger，虽然用 theme='error' 可以显示错误类型的弹窗，但会报 ts 错误。
<img width="609" alt="image" src="https://github.com/Tencent/tdesign-react/assets/9295948/5d8e3f45-f994-4dec-a4bc-8e7a5a79d669">
<img width="1160" alt="image" src="https://github.com/Tencent/tdesign-react/assets/9295948/879d335d-b0e0-40a0-b4b4-15b9a3399794">

### 期望结果

希望支持 theme='danger' 的配置

**Comment by chaishi** [comment]
Vue 是 danger
React 需要改下代码

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-react/pull/2365
