### ISSUE TITLE
[list] ListItemMeta 组件的 description  自定义能不能优化一下？

### ISSUE THREAD

**Issue by anming-john** [Tencent/tdesign-react#2394]
### tdesign-react 版本

1.1.8

### 重现步骤

![企业微信截图_8b0c2f04-b044-45e7-bb20-cd8eab1bf0c1](https://github.com/Tencent/tdesign-react/assets/15686326/54a38bd1-4daa-4e32-802a-50798aab08ae)

类型参数支持  传入 TNODE， 但是你默认一个P 就会导致自定义的内容报warining
![企业微信截图_1b043699-2a7e-4f68-b743-d0c2ff31665b](https://github.com/Tencent/tdesign-react/assets/15686326/57d57ddd-c343-4b00-841f-893edf7822a3)

请优化下， 可以做下判断， 如果  description 是TNODE 可以直接写入， 如果是  string ， 可以带上一个 P

### 期望结果

如上描述

### 实际结果

如上描述

### 框架版本

react

**Comment by anming-john** [comment]
比如你在   description 传入 
（
<div className="my-styles"> <otherComponent /></div>
）
直接warining

**Comment by uyarn** [comment]
fixed in 1.1.17
