### ISSUE TITLE
[Table] EnhancedTable组件中，使用tree结构，data属性的某一项数据无rowKey（undefined） 就报错白屏，未做空判断

### ISSUE THREAD

**Issue by jiangxin829** [Tencent/tdesign-react#2395]
### tdesign-react 版本

1.1.16

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-28ggps?file=/src/demo.jsx:1001-1163

### 重现步骤

demo中第26行rowKey不传时（为undefined）即可复现

### 期望结果

兼容rowKey为undefined的场景不报错，数据来源经常是api，数据不可控，前端不应该做这个兼容，UI库做才合理

### 实际结果

<img width="1482" alt="image" src="https://github.com/Tencent/tdesign-react/assets/52950345/ea287da1-6d39-47fa-82f6-dbb5ed58c6da">

**Comment by chaishi** [comment]
> 前端不应该做这个兼容，UI库做才合理

十分抱歉，不太认同这样的结论。

如果只有 UI 库做这样的兼容，不抛出错误，那么就会认为不存在行唯一标识也是合理的。
但是其实，缺少行唯一标识是非常不合理的数据，比如：在行展开功能、行选中功能、树形节点展开功能中，都会因为缺少行唯一标识导致组件无法识别 应该展开哪一个行，展开哪一个节点，又选中哪一个节点，如此，便是一乱到底了。而此时，如果控制台没有抛出明确地错误提醒，则会非常难以排查问题所在。到时候就会出现另一个 issue “EnhanceTable 无法正常选中节点，无法正常展开节点...” 等等

综上，个人认为，这类缺少重要信息的数据，应当在组件外层处理，而非 UI 组件内部。故而 issue close

**Comment by jiangxin829** [comment]
@chaishi 
可能理解有差异，我也认同缺少rowKey等重要信息的数据在外层处理，而且UI库也不应该忽略错误，控制台提示error很ok。但是这里看起来是UI组件内部没有处理错误，导致浏览器页面白屏。
