### ISSUE TITLE
Message组件声明问题

### ISSUE THREAD

**Issue by notFoundTheGuy** [Tencent/tdesign-react#24]
![image](https://user-images.githubusercontent.com/36075073/146722823-00521ea6-0778-4522-bc9f-82864abdf4f8.png)

Message类方法，文档中duration是可选的，默认3000，生成的TS声明为必填

**Comment by HQ-Lin** [comment]
收到，这边会改成非必填，下版本一起修复

**Comment by chaishi** [comment]
我记得之前改成非必填了

**Comment by chaishi** [comment]
截图的代码是在哪里看的呀？哪个版本号啊，我看到的代码是下图这样的，可选

![image](https://user-images.githubusercontent.com/11605702/146727546-d87353c2-d466-4f7c-b4d2-10de4bc3c3ba.png)

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-react/blob/develop/src/message/type.ts
仓库最新代码 TS 定义，duration 确实是可选的哦

**Comment by notFoundTheGuy** [comment]
0.15.2
那应该是没更新版本的问题，我更新下
