### ISSUE TITLE
[steps] 请支持下check Icon自定义

### ISSUE THREAD

**Issue by anming-john** [Tencent/tdesign-react#2425]
### 这个功能解决了什么问题

目前 步骤器 steps 的Icon 不符合设计要求， 期望能够自定义， 但发现td 全局配置中并不会支持这个功能， 期望能支持一下
![image](https://github.com/Tencent/tdesign-react/assets/15686326/06a54768-6b27-41fd-b535-341cf8094137)

### 你建议的方案是什么

如上， 期望支持一下

**Comment by uyarn** [comment]
可以支持下

**Comment by Zzongke** [comment]
可以的話，我可以pr！😊

**Comment by anming-john** [comment]
> 可以的話，我可以pr！😊

nice ， 请问什么时候可以上线

**Comment by Zzongke** [comment]
> feat(global-config): add global-config steps feature checkIcon Tencent/tdesign-common#1579

快了🥳

**Comment by Zzongke** [comment]
> > 可以的話，我可以pr！😊
> 
> nice ， 请问什么时候可以上线

快了🥳

**Comment by uyarn** [comment]
supported in 1.2.5 thanks @Zzongke
