### ISSUE TITLE
[Anchor] 组件没有自定义高亮锚点的功能，希望增加该功能

### ISSUE THREAD

**Issue by yangdong6** [Tencent/tdesign-react#2427]
### 这个功能解决了什么问题

锚点对应的内容动态生成场景，初始化界面需要展示锚点对应的内容，锚点无法设置高亮显示

### 你建议的方案是什么

const getCurrentAnchor = () => '#test02';

getCurrentAnchor={getCurrentAnchor}

类似于这样，可以设置高亮的锚点

**Comment by ChuTingzj** [comment]
动态渲染锚点组件就可以了吧

**Comment by yangdong6** [comment]
@ChuTingzj ，具体要怎么做，有demo吗

**Comment by ChuTingzj** [comment]
> @ChuTingzj ，具体要怎么做，有demo吗
我可能一开始误解你的意思了，
这个问题一种方法就是`Anchor`组件提供一个`defaultValue`属性来设置默认激活的锚点
另外一种就是这个问题本质还是一个样式问题，可以在渲染的时候为遍历的第一项设置激活的类名
类似这样
https://codesandbox.io/s/unruffled-estrela-2rks3m?file=/src/App.tsx

**Comment by Zzongke** [comment]
我估計楼主是想說自定義進入頁面哪個錨點高亮的意思吧，也就是進入頁面跳轉到設定的哪個錨點

**Comment by yangdong6** [comment]
是的，因为我们的内容有很多条，如果太多，页面默认只展示某一条，需要对应的该条的锚点高亮，可以点击锚点切换右边内容显示哪一条

**Comment by Zzongke** [comment]
> 是的，因为我们的内容有很多条，如果太多，页面默认只展示某一条，需要对应的该条的锚点高亮，可以点击锚点切换右边内容显示哪一条

其實這個你設置進入頁面就設置query加上hash就好了，這功能組件加上也行，看他們決定吧

**Comment by ontheroad1992** [comment]
好的，正在补充中

**Comment by uyarn** [comment]
supported 1.2.1
