### ISSUE TITLE
[Table]使用ellipsis后，带filter的列的筛选icon出现移动

### ISSUE THREAD

**Issue by Irving1997** [Tencent/tdesign-react#2428]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-c4gdtx?file=/src/demo.jsx

### 重现步骤
在带filter的table的列中，加入ellipsis属性，筛选icon出现移动

### 期望结果
与其他不带ellipsis的header样式保持一致。如
<img width="700" alt="image" src="https://github.com/Tencent/tdesign-react/assets/30365763/658188e2-4ec2-4085-b4ab-30cfd55b2414">

### 实际结果
与其他不带ellipsis的header样式不一致。如
<img width="700" alt="image" src="https://github.com/Tencent/tdesign-react/assets/30365763/b260af51-9b68-4c22-83dd-14aa9524d77f">

| Environment | Info |
|---|---|
| 相关版本 | 1.1.17 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | MacOS（Ventuna13.5）, Chrome（115.0.5790.114） |
| Node版本 |  |

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/aa141bae-48b5-4cfb-8754-ba361b64eb06)
添加這個參數設置為false就行了
