### ISSUE TITLE
react-scripts 5.0.0 会导致 :root中的css全局变量失效

### ISSUE THREAD

**Issue by wangsansi** [Tencent/tdesign-react#243]
例如：
color: var(--td-font-gray-2);
--td-font-gray-2找不到

改成"react-scripts": "^4.0.0",
就可以了

**Comment by yume316** [comment]
可以手动在应用入口js引入公共css解决这个问题
![image](https://user-images.githubusercontent.com/51793080/149510160-107334a5-8d3d-4fbd-93c3-ae48e36a6d00.png)
从官方文档来看。It is a feature. ( 逃

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-ft60v?file=/src/demo.jsx
css variables 与 react-script 版本多少无直接关系，是 CSS4 的标准， 变量未找到是因为没有定义，需要手动全局引入 tdesign 的样式
```
import { Button } from 'tdesign-react';
import 'tdesign-react/es/style/index.css'; // 少量公共样式
```
