### ISSUE TITLE
[taginput] 输入中文时，会被前面的标签遮挡

### ISSUE THREAD

**Issue by tingtingcheng6** [Tencent/tdesign-react#2437]
### tdesign-react 版本

1.2.0

### 重现链接

组件demo页直接输入即可复现

### 重现步骤

先输入一个标签回车，再输入中文，此时拼音被前一个标签遮挡

### 期望结果

输入中文不会被前一个标签遮挡

### 实际结果

输入中文会被前一个标签遮挡

### 框架版本

React

**Comment by Zzongke** [comment]
我看了一下，input不是被前面的標籤遮擋的，是input的輸入框輸入拼音時，input的寬度沒autowidth

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/f7933933-cda9-4598-9665-45c233f04a85)
![image](https://github.com/Tencent/tdesign-react/assets/65376724/9ae18a49-d580-411a-9ff6-247f64f41b3a)
所以添加拼音輸入時更新輸入Input的寬度可以解決！

**Comment by uyarn** [comment]
fixed in 1.2.4
