### ISSUE TITLE
【Cascader 级联选择器】文档指引不正确问题

### ISSUE THREAD

**Issue by sevencai** [Tencent/tdesign-react#2442]
## 文档指引问题

级联文档中的动态加载`demo`示例无法正常表达动态加在内容。

需要将`children: []`，改为 `children: true`才能正确体验到异步加载的效果。

<img width="716" alt="image" src="https://github.com/Tencent/tdesign-react/assets/23190922/afb71b9f-5df3-471e-b639-0f2f2a7bb2c2">

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/781aacf9-9ab7-45f6-a840-fe4ceec524b2)
是的，你說的文檔的Demo有問題，我來修復一下！
