### ISSUE TITLE
[Tree] 叶子节点与非叶子节点的点击事件表现不一致

### ISSUE THREAD

**Issue by FountainShaw** [Tencent/tdesign-react#2444]
### tdesign-react 版本

1.1.17

### 重现链接

https://codesandbox.io/s/6w53wt?file=/src/demo.jsx

### 重现步骤

点击Tree组件中的任意叶子节点和非叶子节点除图表外的地方

### 期望结果

expandOnClickNode = true 时，非叶子节点展开或收起，叶子节点不做反馈
expandOnClickNode = false 时，非叶子节不做反馈，叶子节点不做反馈

### 实际结果

expandOnClickNode = true 时，非叶子节点展开或收起，叶子节点被选中或取消选中
expandOnClickNode = false 时，非叶子节不做反馈，叶子节点选中或取消选中

### 框架版本

react(18.2.0)

### Node版本

v14.18.1

### 补充说明

这个问题是叶子节点与非叶子节点在点击整个节点区域时，同样都是checkbox，但表现出的效果不一致，这会让使用者感到困惑

**Comment by uyarn** [comment]
`expandOnClickNode` 只和展开功能有关 与选中无关；expandOnClickNode本身在1.1.17版本有一些问题 1.3.0修复过了

**Comment by uyarn** [comment]
再补充说明一下 
expandOnClickNode = true 时，非叶子节点展开或收起，叶子节点被选中或取消选中
expandOnClickNode = false 时，非叶子节不做反馈，叶子节点选中或取消选中
是目前预期的结果，叶子节点因为没有子节点了，所以用户点击的目的就是选中它，不存在其他可能；
非叶子节点，用户可能是想选中也可能是展开子节点，所以这里提供的expandOnClickNode配置就是方便具体业务根据实际需要决定点击节点的交互效果
