### ISSUE TITLE
[ColorPicker] 渐变色选择器 修改颜色上方滑杆按钮颜色不变

### ISSUE THREAD

**Issue by whiteHaiyu** [Tencent/tdesign-react#2450]
### tdesign-react 版本

1.2.1

### 重现链接

组件demo页-不同色彩模式的颜色选择器-仅线性渐变模式 即可复现

### 重现步骤

打开弹窗后 直接选择颜色 滑杆上按钮颜色不变；滑动后再选择颜色可以改变
![image](https://github.com/Tencent/tdesign-react/assets/44045961/3912caf2-e88b-46f6-9b1c-cea4d3ddcc0a)

### 期望结果

修改选中颜色，滑杆按钮颜色改变

### 实际结果

直接选择颜色 滑杆上按钮颜色不变；滑动后再选择颜色可以改变

```[tasklist]
### Tasks
```

**Comment by uyarn** [comment]
fixed 1.4.0
