### ISSUE TITLE
[table] 官网可编辑行的表格保存时样式错乱

### ISSUE THREAD

**Issue by vicorn** [Tencent/tdesign-react#2462]
### tdesign-react 版本

1.2.1

### 重现链接

https://tdesign.tencent.com/react/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

![image](https://github.com/Tencent/tdesign-react/assets/30787425/e0ae7c5e-a18d-4aa8-87c9-d183f2368b02)

**Comment by chaishi** [comment]
这个，自己调整一下宽度就好了

**Comment by vicorn** [comment]
> 这个，自己调整一下宽度就好了

啊？这肯定是bug吧，校验时表单突然变宽，vue版并不这样。
