### ISSUE TITLE
[GlobalConfig] 支持动态切换多语言

### ISSUE THREAD

**Issue by duxphp** [Tencent/tdesign-react#2468]
### tdesign-react 版本

最新版

### 重现步骤

使用ConfigProvider后在内部切换多语言配置，并没有热更新，需要刷新页面才会应用新语言

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/a54535d6-d0db-4ae5-8197-e427770745ce)
![image](https://github.com/Tencent/tdesign-react/assets/65376724/427e3265-984c-469b-8cd8-1fd512331294)

source code：
![image](https://github.com/Tencent/tdesign-react/assets/65376724/c04869ee-7beb-4e1b-bc35-442eab4923c7)
![image](https://github.com/Tencent/tdesign-react/assets/65376724/b72d6621-b8cf-4de2-8cbe-a06635d0f097)

bug:
切換語言失敗，因為loadsh/merge導致上一源數據也跟著改變，導致引入的locale/zh_CN裡面的數據頁更正改變了

fix bug:
![image](https://github.com/Tencent/tdesign-react/assets/65376724/a8dfcc43-1ca6-4089-afcb-79e2d56a9176)
深度克隆語言來使用可以解決!!! @

**Comment by uyarn** [comment]
之前可能实现的时候没有考虑切换的场景 是得修复下

**Comment by uyarn** [comment]
supported in 1.2.5
