### ISSUE TITLE
[table] table组件中如果内容是0且设置了ellipsis，当前内容就显示不了

### ISSUE THREAD

**Issue by cllee1214** [Tencent/tdesign-react#2472]
### tdesign 版本

1.1.10

### 重现步骤

1.table中某个cell值为0
2.设置ellipsis = true

**Comment by chaishi** [comment]
应该是判空的原因，我抽空看下。
你看看能不能先转换成字符串 ‘0’ 临时解决这个问题

**Comment by chaishi** [comment]
https://stackblitz.com/edit/react-xcv3ob?file=src%2Fdemo.jsx
看了下最新版本，已经没有这个问题了

<img width="985" alt="image" src="https://github.com/Tencent/tdesign-react/assets/11605702/826653e1-9acd-40d8-b66f-c498d42e5f06">
