### ISSUE TITLE
[Slider] 初始值设为最小值时，label定位错误

### ISSUE THREAD

**Issue by ZYLBless** [Tencent/tdesign-react#2473]
### tdesign-react 版本

1.2.3

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-4thzs8?file=/src/demo.jsx

### 重现步骤

初始value设为min值，或不设置value，hover到滑块上，label出现在页面左上角.
官网第一个示例即可复现。

### 期望结果

初始value设为min值，或不设置value时，label出现在滑块上

### 实际结果

label出现在页面左上角

### 框架版本

React(18.2.0)

### 浏览器版本

Chrome(116.0.5845.110)

### 系统版本

MacOS(13.5)

### Node版本

16.16.0

**Comment by uyarn** [comment]
fixed in 1.2.4
