### ISSUE TITLE
[Descriptions] TD 有计划开发一个类似antd的Descriptions 组件吗？

### ISSUE THREAD

**Issue by anming-john** [Tencent/tdesign-react#2479]
### 这个功能解决了什么问题

参考 ： https://ant-design.antgroup.com/components/descriptions-cn
这个 Descriptions 在很多业务场景上都有用到， 是个不错的组件， 期望td也能支持

### 你建议的方案是什么

期望支持！

**Comment by uyarn** [comment]
有 正在开发

**Comment by anming-john** [comment]
good！ 有计划什么时候上线吗？

**Comment by uyarn** [comment]
> good！ 有计划什么时候上线吗？

下个月吧 已经进行很长时间了 但是UI认领开发的同学一直没有进展 接下来我们会自己接手完成掉

**Comment by uyarn** [comment]
可以参考这个的进度 这个issue先关闭了https://github.com/orgs/Tencent/projects/1/views/31?pane=issue&itemId=13678494
