### ISSUE TITLE
[Timeline 时间轴] Timeline.Item 希望新增点击事件回调

### ISSUE THREAD

**Issue by SnowChasm** [Tencent/tdesign-react#2495]
### 这个功能解决了什么问题

希望在 Timeline.Item 上增加 onClick 回调，用于用户点击时的反馈

### 你建议的方案是什么

增加 onClick 方法导出

**Comment by Zzongke** [comment]
@SnowChasm  自定义内容上面添加图标或者按钮，用户点击反馈是不是好一点？😊

**Comment by SnowChasm** [comment]
> @SnowChasm 自定义内容上面添加图标或者按钮，用户点击反馈是不是好一点？😊

这个其实和需求相关，有时候需要点击整个 item，执行相关逻辑。目前的组件就做不了这个

**Comment by Zzongke** [comment]
> > @SnowChasm 自定义内容上面添加图标或者按钮，用户点击反馈是不是好一点？😊
> 
> 这个其实和需求相关，有时候需要点击整个 item，执行相关逻辑。目前的组件就做不了这个

看大佬讨论一下吧。 @uyarn

**Comment by uyarn** [comment]
supported in 1.3.0
