### ISSUE TITLE
[TreeSelect]不同的父节点具有相同value叶子节点的情况，同时展开父节点时，视图上出现冲突

### ISSUE THREAD

**Issue by Irving1997** [Tencent/tdesign-react#2505]
### 重现链接
https://stackblitz.com/edit/react-y6tl7k?file=src%2Fdemo.jsx

### 重现步骤
1、为不同的父节点配置相同value的子节点
2、同时展开多个父节点时，相同value的子节点被过滤，仅在单个父节点下展示

### 期望结果
能将子节点展示完全

<img width="353" alt="image" src="https://github.com/Tencent/tdesign-react/assets/30365763/739ab929-919b-4879-81de-16194442488f">

### 实际结果
子节点被过滤
<img width="366" alt="image" src="https://github.com/Tencent/tdesign-react/assets/30365763/e0dcc623-0e53-4f6a-9ccc-78c1f30e5e36">

| Environment | Info |
|---|---|
| 相关版本 | 1.2.4 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | Chrome(115.0.5790.114) |
| Node版本 |  |

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/b253a2ef-b372-479c-b690-ee7994791e3c)
我看了一下，data说明了value要设置为唯一值的(key)，希望能帮到你！！！

**Comment by Zzongke** [comment]
@Irving1997 还有什么问题吗？
