### ISSUE TITLE
tdesign的表格自定义 表头 选项列 复选框的内容 有解决办法吗

### ISSUE THREAD

**Issue by yongma16** [Tencent/tdesign-react#2508]
### Discussed in https://github.com/Tencent/tdesign-react/discussions/2506

<div type='discussions-op-text'>

<sup>Originally posted by **yongma16** September 12, 2023</sup>
表格多选 columns: [{ colKey: 'row-select', type: 'multiple' }]
配置{ colKey: 'row-select', type: 'multiple' ,render:()=><>自定义表头无效</>}
配置render无效</div>

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/c5b25793-3cab-4538-abb5-3959ece03247)
![image](https://github.com/Tencent/tdesign-react/assets/65376724/b91a5b68-4bdb-4d85-a953-a56658670212)
![image](https://github.com/Tencent/tdesign-react/assets/65376724/b89c7d2a-3c12-496f-b9b8-58d4659c376a)
复选框的内容应该是过滤的功能，看第三张图那样设置才可以😊

**Comment by yongma16** [comment]
> ![image](https://user-images.githubusercontent.com/65376724/269454851-c5b25793-3cab-4538-abb5-3959ece03247.png) ![image](https://user-images.githubusercontent.com/65376724/269454872-b91a5b68-4bdb-4d85-a953-a56658670212.png) ![image](https://user-images.githubusercontent.com/65376724/269455733-b89c7d2a-3c12-496f-b9b8-58d4659c376a.png) 复选框的内容应该是过滤的功能，看第三张图那样设置才可以😊

跑题了兄弟，你这个filter多选列，我想描述的是{ colKey: 'row-select', type: 'multiple' ,render:()=><>自定义表头无效</>}，row-select这个表格的列选择中render和title不生效

**Comment by yongma16** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/48764359/af2d54de-83bc-43bd-b32a-cc7ec983258f)

**Comment by yongma16** [comment]
https://github.com/Tencent/tdesign-react/issues/2521

**Comment by Zzongke** [comment]
@yongma16 hhh,是我一开始看错了，然后看了发现配置多选和单选默认返回checkbox的，所以你配置title和render都没效果

**Comment by Zzongke** [comment]
> #2521

Repeat，Close.
