### ISSUE TITLE
[table] 使用rowspanAndColspan函数合并单元格功能， 点击table内置的分页按钮切换，合并单元格会出现错乱的情况

### ISSUE THREAD

**Issue by zedwei2** [Tencent/tdesign-react#2513]
### tdesign-react 版本

^1.2.3

### 重现链接

https://stackblitz.com/edit/react-76urqk?file=src%2Fdemo.jsx

### 重现步骤

多次点击table下方 分页数字按钮进行切换页面

### 期望结果

期望合并单元格逻辑按照rowspanAndColspan写的逻辑，显示正常

### 实际结果

table表格会出现合并单元格异常情况
异常图片：![企业微信截图_16947427317583](https://github.com/Tencent/tdesign-react/assets/45986240/607b20f8-7c06-40b3-ac10-15e47d678bd6)

### 框架版本

react(^18.2.0)

### Node版本

V16.15.1

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-react/pull/2514

**Comment by zedwei2** [comment]
我现在看出现问题的概率小了很多(点击十次以上)，似乎还会偶现异常情况。
![image](https://github.com/Tencent/tdesign-react/assets/45986240/66dafa7b-0055-4edc-85c8-a64a1946cb3d)
图里面右下方有table异常的时间点
### 最后还是非常感觉大佬周末抽空帮忙处理我的问题

**Comment by zedwei2** [comment]
> 已修复#2514 
大概什么时候会发布呢？

**Comment by uyarn** [comment]
fixed in 1.2.6
