### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by Roxannej** [Tencent/tdesign-react#2515]
### 这个功能解决了什么问题

官网上的企业微信人满了，github上的二维码是扫不出来的

### 你建议的方案是什么

可以更新下二维码吗

**Comment by uyarn** [comment]
我看下

**Comment by uyarn** [comment]
@Roxannej 你是指哪个二维码？可以扫README这个二维码的 现在分技术栈来管理用户群
