### ISSUE TITLE
[Card] TNode类型定义显示支持函数渲染，但实际无法渲染

### ISSUE THREAD

**Issue by MeetzhDing** [Tencent/tdesign-react#2518]
[Card] TNode类型定义显示支持函数渲染，但实际无法渲染

可能存在大量其他组件也有这种情况，推荐批量检查修复

### tdesign-react 版本

1.2.5

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-2p36qj

### 重现步骤

Card 组件，TNode类型的参数，传递一个 `() => ReactNode`

### 期望结果

对于 `() => ReactNode`，应当执行函数获得结果并渲染。
或者明确类型定义，让 TNode 变成 React.ReactNode

### 实际结果

不能正常渲染，但TypeScript不报错

### 框架版本

React 18.2

### 浏览器版本

Chrome Latest

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/0da01dea-e348-48ae-b008-4e4701098d88)
TNode默认ReactNode，除非声明了TNode<T>才会支持函数渲染，这就要看是否都要支持函数渲染

**Comment by MeetzhDing** [comment]
> ![image](https://user-images.githubusercontent.com/65376724/268900334-0da01dea-e348-48ae-b008-4e4701098d88.png) TNode默认ReactNode，除非声明了TNode才会支持函数渲染，这就要看是否都要支持函数渲染

这里其实我也觉得并不需要全都支持，但是目前的类型检测是否算是失效的？至少是不严谨的。

组件定义上最好是做到，如果不能支持函数渲染，类型就应该报错？

@Zzongke

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/9e43440a-9404-4bd8-99ff-4b4f12a53e6d)
我看了一下你CodeSandBox，你用的是jsx项目，我本地新建了一个tsx的项目，实际是有提示的 @MeetzhDing

**Comment by MeetzhDing** [comment]
@Zzongke OK，那应该是文档默认开启的是jsx项目导致的（推荐改成TypeScript的？或者有两个入口）。

那没有这个问题就可以。issues也可以关了

不过按照整个文档现在的描述来看，绝大多数都还是 TNode，感觉依赖泛型来搞这个类型，在文档上还是有点理解成本的。要能理解 TNode 和 TNode<undefined> 的不同（TNode | TRender 之类的，也许更清晰一点）。

**Comment by Zzongke** [comment]
> @Zzongke OK，那应该是文档默认开启的是jsx项目导致的（推荐改成TypeScript的？或者有两个入口）。
> 
> 那没有这个问题就可以。issues也可以关了
> 
> 不过按照整个文档现在的描述来看，绝大多数都还是 TNode，感觉依赖泛型来搞这个类型，在文档上还是有点理解成本的。要能理解 TNode 和 TNode 的不同（TNode | TRender 之类的，也许更清晰一点）。

泛型是有点一开始不清晰，TNode的旁边有([通用类型定义](https://github.com/Tencent/tdesign-react/blob/develop/src/common.ts))点击跳转查看泛型是什么内容，也还好,希望能帮到你吧！！！😁

**Comment by Zzongke** [comment]
Close.
