### ISSUE TITLE
[SelectInput] select输入搜索的值，无法在关闭面板时清空数据。

### ISSUE THREAD

**Issue by zedwei2** [Tencent/tdesign-react#2527]
### tdesign-react 版本

^1.2.3

### 重现链接

https://stackblitz.com/edit/react-qsubix?file=src%2Fdemo.jsx

### 重现步骤

1.在select输入dadada，点击其他空白区域，关闭面板后（我在切换面板函数哪里执行了  setSelectValue(undefined) 失效）
2.重新点击select 上一次输入的dadada 还会存在。

### 期望结果

关闭面板或其他方式能自动清空掉之前输入的值

### 实际结果

无法通过代码方式清空掉之前输入的值，只能通过点击右侧 x 按钮进行清空。

### 框架版本

react(^18.2.0)

### Node版本

V16.15.1

**Comment by Zzongke** [comment]
@betavs 我想问一下你是想要输入值就显示输入值吗？select选中就显示select的值？

**Comment by Zzongke** [comment]
@betavs 传value值是对应选择select的label，传inputValue才是input的值，这个官网文档写了的，希望能帮助到你😊

**Comment by zedwei2** [comment]
> @betavs 传value值是对应选择select的label，传inputValue才是input的值，这个官网文档写了的，希望能帮助到你😊
这个inputValue使用后，select输入框无法输入，具体效果请看 https://stackblitz.com/edit/react-qsubix?file=src%2Fdemo.jsx

**Comment by zedwei2** [comment]
> @betavs 我想问一下你是想要输入值就显示输入值吗？select选中就显示select的值？

我想输入的时候 通过输入的值进行全量数据的过滤呈现对应内容，现在问题是我输入值后，focus->blur 之后上一次输入的值还存在就会导致体验不佳问题。
select选中显示select值 不进行过滤全量数据操作。

**Comment by Zzongke** [comment]
> > @betavs 我想问一下你是想要输入值就显示输入值吗？select选中就显示select的值？
> 
> 我想输入的时候 通过输入的值进行全量数据的过滤呈现对应内容，现在问题是我输入值后，focus->blur 之后上一次输入的值还存在就会导致体验不佳问题。 select选中显示select值 不进行过滤全量数据操作。

你現在传inputValue的值來实现请求返回搜索的内容展示，然后传value的值来实现select选中的值就好了。希望能帮到你！😊
![image](https://github.com/Tencent/tdesign-react/assets/65376724/acc65206-f513-4ab6-a722-4dfa41efe416)

**Comment by zedwei2** [comment]
> > > @betavs 我想问一下你是想要输入值就显示输入值吗？select选中就显示select的值？
> > 
> > 
> > 我想输入的时候 通过输入的值进行全量数据的过滤呈现对应内容，现在问题是我输入值后，focus->blur 之后上一次输入的值还存在就会导致体验不佳问题。 select选中显示select值 不进行过滤全量数据操作。
> 
> 你現在传inputValue的值來实现请求返回搜索的内容展示，然后传value的值来实现select选中的值就好了。希望能帮到你！😊 ![image](https://user-images.githubusercontent.com/65376724/273421189-acc65206-f513-4ab6-a722-4dfa41efe416.png)

使用此方式能实现我想要的效果 感谢回复！

**Comment by Zzongke** [comment]
@zedwei2 解决问题的话就C关闭一下issue，谢谢😊😊😊
