### ISSUE TITLE
[全局组件] 编译后的语言包缺少繁体中文和俄语

### ISSUE THREAD

**Issue by duxphp** [Tencent/tdesign-react#2541]
### tdesign-react 版本

最新版

### 重现步骤

已声明“ruRUConfig”，但从未读取其值。ts(6133)
找不到模块“tdesign-react/es/locale/ru_RU”或其相应的类型声明

已声明“zhTWConfig”，但从未读取其值。ts(6133)
找不到模块“tdesign-react/es/locale/zh_TW”或其相应的类型声明。

### 期望结果

版本中应该包含这些语言

### 实际结果

围巾不存在

### 框架版本

react

**Comment by Zzongke** [comment]
@duxphp 确实缺少了语言包，我修复一下，感谢！！！

**Comment by uyarn** [comment]
fixed in 1.3.0
