### ISSUE TITLE
[Form] 监听表单项的某个值变化推荐的写法是什么？

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#2546]
### 这个功能解决了什么问题

是通过给 Form 绑定 onValuesChange 来监听事件然后执行一些操作
还是通过 useWatch + useEffect 更合适一点？

### 你建议的方案是什么

如上

**Comment by Zzongke** [comment]
@fangxiezhen 您好，这个完全取决于你自己的需求，要监听某个值实时变化就用useWatch，要监听事件触发的就onValuesChange
