### ISSUE TITLE
[ColorPicker/颜色选择器] 我不知道这个算不算bug，我感觉表现更像性能问题。

### ISSUE THREAD

**Issue by kwooshung** [Tencent/tdesign-react#2562]
### tdesign-react 版本

react 18

### 重现链接

https://tdesign.tencent.com/react/components/color-picker

### 重现步骤

就是在拖动选择颜色的时候，我发现一开始拖动的时候，会有点儿卡，只要卡过之后，页面不刷新，后续的都没问题；奇怪的是弹出框方式的也没问题，而只有第一个案例而且是每次刷新浏览器后第一次拖动的时候。当然我有点儿偷懒了，没有自己在本地做测试，只是在官网上测试了。

**Comment by HaixingOoO** [comment]
暂时没发现问题，先关闭了！！！
