### ISSUE TITLE
[ColorPicker] 样式问题

### ISSUE THREAD

**Issue by baron04** [Tencent/tdesign-react#2567]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-gmhj6r?file=/src/main.jsx

### 重现步骤

在全局样式增加 * { box-sizing: border-box; } 代码，会造成`ColorPicker`组件的系统预设颜色、最近使用颜色样式出现问题。原因是div.t-color-picker__swatches--items没有指定box-sizing，默认是content-box，如果被全局样式影响，就会造成样式不正常。

### 期望结果
1、.t-color-picker__swatches--items 元素指定box-sizing；
2、TDesign组件库内部box-sizing有的是border-box，有的是content-box，建议统一；

### 实际结果
<img width="330" alt="QQ20231021-213110@2x" src="https://github.com/Tencent/tdesign-react/assets/22796808/b56346db-2c92-42f6-8afc-4eba7b0f9751">

| Environment | Info |
|---|---|
| 相关版本 | 1.3.0 |
| 框架版本 / 基础库版本 | React 18 |
| 系统、浏览器 | Mac Chrome |

**Comment by Zzongke** [comment]
感谢 @baron04 您的建议，欢迎PR！！！

**Comment by Zzongke** [comment]
@uyarn ColorPicker要不要调整成border-box呢？

**Comment by uyarn** [comment]
这个issue @carolin913 来跟进

**Comment by uyarn** [comment]
fixed 1.4.2
