### ISSUE TITLE
[QRCode] 希望能够新增二维码组件

### ISSUE THREAD

**Issue by narukeu** [Tencent/tdesign-react#2569]
### 这个功能解决了什么问题

这个组件可以从文本生成二维码图片，我觉得有了这个组件可以大大提升前端开发时的效率。同时由于是组件库自带的二维码组件，所以样式可以和组件库统一，这样构建出来的用户界面会非常自然。

### 你建议的方案是什么

今天试用了 Ant Design 的对应功能发现比较好用，作为 TDesign 的老用户，希望也可以增加这个功能。

**Comment by HaixingOoO** [comment]
@narukeu 您好，重复的issue，所以关闭当前的issue
- #2561
