### ISSUE TITLE
[Table组件] 期望可展开收起的表格中的expandedRow渲染方式支持异步

### ISSUE THREAD

**Issue by codepan** [Tencent/tdesign-react#2571]
### 这个功能解决了什么问题

由于可展开收起的表格中，expandedRow渲染方法中，展开的内容需要调用接口获取数据后做渲染，但目前看文档以及亲测之后感觉不支持异步，业务功能无法实现

### 你建议的方案是什么

expandedRow支持异步

**Comment by Zzongke** [comment]
@codepan 测试了一下，expandedRow写成组件传递来数据获取接口可以实现，已经支持了的。😊

**Comment by Zzongke** [comment]
@codepan  [Demo例子-展开动态加载数据](https://codesandbox.io/s/stoic-monad-wjnkms?file=/src/Demo.js)

**Comment by Zzongke** [comment]
@codepan 您好，解决了您的问题吗？解决了的话麻烦关闭一下issue，谢谢！！！

**Comment by chaishi** [comment]
提问者再无任何回应，理解为问题已解决，issue close
