### ISSUE TITLE
[Select] select组件中tagInputProps属性中excessTagsDisplayType: 'break-line'，设置这个属性之后，仍然换行

### ISSUE THREAD

**Issue by justtoday111** [Tencent/tdesign-react#2574]
### tdesign-react 版本

1.3.0

### 重现链接

https://codesandbox.io/s/fervent-heisenberg-5jtjhw

### 重现步骤

下拉选择多个checkbox,当选择个数宽度超过下拉框宽度，则会换行。

### 期望结果

一行展示，不换行

### 实际结果

会换行

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/f10de5c7-4999-4cdc-bdfa-2e4d6ce4f74d)
@justtoday111 您好，应该传`scroll`

**Comment by Zzongke** [comment]
@justtoday111 您好，解决了你的问题吗？解决了的话麻烦关闭一下issue，谢谢
