### ISSUE TITLE
[Cascader]filterable conflicts with checkStrictly

### ISSUE THREAD

**Issue by Isbutton** [Tencent/tdesign-react#2583]
### 重现链接
https://tdesign.tencent.com/react/components/cascader?tab=demo

https://github.com/Tencent/tdesign-react/assets/17758254/ca91bec5-fa04-485e-bb57-f36103b6da44

### 重现步骤
官网cascader的demo，在打开filterable和checkStrictly的时候，搜索结果无法选中父节点

### 期望结果
搜索后可以选中父节点，也可以选中子节点

### 实际结果
目前点击父节点，无法被选中，而是回退到了上一级级联。

| Environment | Info |
|---|---|
| 相关版本 | 1.3.0 |
| 框架版本 / 基础库版本 | React18.2.0 |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by HaixingOoO** [comment]
@Isbutton 您好，抱歉現在才看到回复你，修复在1.4.3，谢谢！！！
