### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by jameinfeng** [Tencent/tdesign-react#2584]
### tdesign-react 版本

能

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-yy4p9q?file=/src/demo.jsx

### 重现步骤

slider组件max和min字段都设置为1，进度条展示为0
![image](https://github.com/Tencent/tdesign-react/assets/149473343/f893a380-24d7-4d1a-b60a-9564e88ea442)

### 期望结果

进度条为100%

### 实际结果

进度条为0

### 框架版本

react@18.2.0

**Comment by Zzongke** [comment]
@jameinfeng 您好，这个min不能>=max的，这不是bug，感谢提问，issue我就关闭了！！！
