### ISSUE TITLE
[Tabs 选项卡] onChange 方法在激活的选项卡没有发生变化时也会触发

### ISSUE THREAD

**Issue by danchaofan98** [Tencent/tdesign-react#2586]
### tdesign-react 版本

1.3

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-29hd4z?file=/src/demo.jsx

### 重现步骤

重复点击激活的选项卡，也会触发 onChange 事件

### 期望结果

只有当激活的选项卡发生变化时才会触发 onChange 事件，重复点击激活的选项卡时不应该触发该事件

### 实际结果

重复点击激活的选项卡，也会触发 onChange 事件

### 框架版本

React 18

### 浏览器版本

Chrome 120.0.6090.0（正式版本）dev (arm64)

### 系统版本

MacOS(14.0)

### Node版本

Node 18

**Comment by uyarn** [comment]
fixed in 1.3.1
