### ISSUE TITLE
校验表单 不填内容点击提交 页面会往上滑动大概一页的内容

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign-react#260]
https://tdesign.tencent.com/react/components/form
校验表单 不填内容点击提交 页面会往上滑动大概一页的内容

**Comment by HQ-Lin** [comment]
demo 的样式重复问题，表单校验的时候有个滑动到第一个错误项，页面上方有个class与底下的重复导致，调整一下
