### ISSUE TITLE
[Drawer] React 版本 Drawer 在 showInAttachedElement 属性为 true 的情况下， push mode 没有生效

### ISSUE THREAD

**Issue by 4yan** [Tencent/tdesign-react#2607]
### tdesign-react 版本

1.3.1

### 重现链接

https://tdesign.tencent.com/react/components/drawer?tab=demo

### 重现步骤

官方 demo 即可复现

### 框架版本

React

**Comment by HaixingOoO** [comment]
@4yan 你是想表达Drawer 在 showInAttachedElement 属性为 true 的情况下， push mode 没有生效，mode=push没生效是说的内容没有被推开的意思是吗？

**Comment by 4yan** [comment]
@HaixingOoO 是的，我看在vue版本下是有推开的，但react 版本没有做，所以不清楚是bug还是特性

**Comment by HaixingOoO** [comment]
> @HaixingOoO 是的，我看在vue版本下是有推开的，但react 版本没有做，所以不清楚是bug还是特性

OK，感谢您的issue，确实是bug，目前支持的是body元素的push，后续修复！！1

**Comment by uyarn** [comment]
fixed 1.4.0
