### ISSUE TITLE
[Tree] label 属性的 `setData` 无法触发更新

### ISSUE THREAD

**Issue by NWYLZW** [Tencent/tdesign-react#2609]
### tdesign-react 版本

1.3.1

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-kxz6yc?file=%2Fsrc%2Fdemo.jsx%3A64%2C52

### 重现步骤

* 双击结点 label ，聚焦至输入框
* 进行输入，测试 esc, enter 是否能触发
* 点击其他空白处触发 blur

<img width="570" alt="image" src="https://github.com/Tencent/tdesign-react/assets/51358815/1517b4af-880e-402b-8999-1f2dcc831643">

![667e460d81e532bf72f74be4d6b2e4ee](https://github.com/Tencent/tdesign-react/assets/51358815/41293fcb-1f8d-46c2-9a1c-56914ae701f1)

### 期望结果

setData 设置 `isEditing: false` 能正常触发渲染并更新数据

### 实际结果

 blur 存在可能触发更新视图，而按键事件均不可触发更新视图

### 框架版本

React(18.2.0)

### 浏览器版本

Any

### 系统版本

Any

### Node版本

Any

**Comment by NWYLZW** [comment]
当我尝试在 tdesign-react 项目启动的 start 指令中的开发服务上复现时，这居然是无法触发的。

![Export-1700727843943](https://github.com/Tencent/tdesign-react/assets/51358815/a0d2e97c-1a6b-45fa-b436-6ec61d10d785)

文件路径在：`src/tree/_example/base.jsx`
修改内容：
```typescript
export default () => <Tree
  data={items}
  activable
  hover
  transition
  label={(node) => node.data.isEditing
    ? <input
      defaultValue={node.data.label}
      onBlur={e => node.setData({ ...node.data, label: e.target.value, isEditing: false })}
      onClick={e => e.stopPropagation()}
    />
    : <span onDoubleClick={e => {
      e.stopPropagation();
      node.setData({ ...node.data, isEditing: true });
    }}>
      {node.data.label}
    </span>}
/>;
```

**Comment by NWYLZW** [comment]
经过讨论，可能是由于 common submodule 没有更新导致的 tree node class 的数据响应式关系并未关联上导致的 setData 无法触发数据更新。

**Comment by HaixingOoO** [comment]
fixed 1.5.2
