### ISSUE TITLE
react 导航栏只用官方给的代码运行，没有预留横向的padding

### ISSUE THREAD

**Issue by tdesign-helper** [Tencent/tdesign-react#261]
导航栏只用官方给的代码运行，没有预留横向的padding，比较难看，需要手动加入，官方文档中并未给出值

**Comment by xiaosansiji** [comment]
![image](https://user-images.githubusercontent.com/7600149/149906761-46e2bb94-4c20-49b7-bce3-341593723e75.png)
menu 作为容器，最好在 menu 层加 padding，而不是加在 logo 上，否则没有设置 logo 的场景就直接贴边了，不太合理 @LeeJim
