### ISSUE TITLE
[TagInput] 扩展 collapsedItems 的删除功能

### ISSUE THREAD

**Issue by topaz-h** [Tencent/tdesign-react#2625]
### 这个功能解决了什么问题

> 具有删除能力

<img width="699" alt="image" src="https://github.com/Tencent/tdesign-react/assets/54789070/9786f87d-af69-4960-a8e1-2dad7ed7277b">

> 但是不知道封装到内部还是把onClose方法抛出，可以给出建议吗？

### 你建议的方案是什么

1. collapsedItems 参数增加遍历好的 Tag 列表，好处是可以复用 tag、closable、disabled、tagProps 等属性
2. collapsedItems 参数增加 onClose 方法，外部自定义

建议采用哪一种方案呢？如果觉得方案可行，我愿意pr

**Comment by NWYLZW** [comment]
增加遍历好的 tag 列表具体是指？

**Comment by topaz-h** [comment]
<img width="963" alt="image" src="https://github.com/Tencent/tdesign-react/assets/54789070/d3a2b25e-b9cd-4160-9599-bd570020ec36">
在 useTagList 抽离出来，遍历完成后加入到参数内部

**Comment by topaz-h** [comment]
<img width="1131" alt="image" src="https://github.com/Tencent/tdesign-react/assets/54789070/84dfbef0-2b1b-4070-8196-f792876df7d3">

最后大概是这样，我更倾向于把props和onClose当作参数返回

**Comment by uyarn** [comment]
@topaz-h 你好像需要的是这个效果?https://tdesign.tencent.com/vue/components/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%98%E5%8F%A0%E9%80%89%E4%B8%AD%E9%A1%B9%E9%80%89%E6%8B%A9%E5%99%A8
<img width="761" alt="image" src="https://github.com/Tencent/tdesign-react/assets/26377630/464ce410-c469-4289-b45a-b2ac6ff65cc4">

**Comment by topazur** [comment]
<img width="918" alt="image" src="https://github.com/Tencent/tdesign-react/assets/88650465/bfa8df5f-1719-4aad-acc2-2166eaae0c10">
两端不统一，那就按照vue这种方式传递，可以吗？

**Comment by uyarn** [comment]
@topaz-h vue是新增的API 这边接下来会同步跟进

**Comment by uyarn** [comment]
published 1.7.1
