### ISSUE TITLE
[SelectInput] 当页面设置最大高度时，鼠标滚动，会导致页面宽度增加（！！！注意：这里链接鼠标才会有问题）

### ISSUE THREAD

**Issue by justtoday111** [Tencent/tdesign-react#2642]
### tdesign-react 版本

1.4.0

### 重现链接

https://stackblitz.com/edit/stackblitz-starters-8j8ljt?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Fstyle.css,src%2Findex.tsx,public%2Findex.html,package.json&title=React%20Starter

### 重现步骤

滚动页面，页面下拉宽度随着滚动改变

### 期望结果

下拉框宽度与输入框保持一致
![WX20231204-181532@2x](https://github.com/Tencent/tdesign-react/assets/73412601/5c0b7435-049e-44f6-9385-d406554aec9f)

### 实际结果

下拉框宽度会随页面滚动而改变

![WX20231204-181417@2x](https://github.com/Tencent/tdesign-react/assets/73412601/d2768e98-1111-40cd-91a7-7f818205230c)

### Node版本

14.15.0

**Comment by NWYLZW** [comment]
由系统滚动条所占据空间导致的计算错误，已经在修复了。
如果需要先行解决，可以使用 css 暂时将滚动条的宽度设置为 0。

**Comment by uyarn** [comment]
fixed 1.4.1
