### ISSUE TITLE
[table] 在弹窗里超长hover显示不全

### ISSUE THREAD

**Issue by guoqirong** [Tencent/tdesign-react#2657]
### tdesign-react 版本

1.3.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-react/assets/57247313/5f551ec2-2be6-4a91-9d6a-9cc848ffd9b7)
当表格位于弹窗里，文案很长，hover显示不全

### 期望结果

hover能看到全部数据

**Comment by chaishi** [comment]
给 table 加一个属性 `attach='.t-dialog'` ，让浮层都挂载到外层的 Dialog 组件就好了

- `attach='.t-dialog'` 
- `:attach="() => document.querySelector('.t-dialog')"`

**Comment by guoqirong** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/57247313/015194e2-13f8-47c3-aced-ed6d3ce12c2b)
我挂载到body，但实际没生效

**Comment by HaixingOoO** [comment]
> ![image](https://private-user-images.githubusercontent.com/57247313/289496705-015194e2-13f8-47c3-aced-ed6d3ce12c2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODkxMjYsIm5iZiI6MTcwMjI4ODgyNiwicGF0aCI6Ii81NzI0NzMxMy8yODk0OTY3MDUtMDE1MTk0ZTItMTNmOC00N2MzLWFjZWQtZWQ2ZDNjZTEyYzJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEwMDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZTgwZGMwMDAwYzM3OWI0MDgxMDEwMmM1YTczMWJiNGE1ODc1OTYwNWI5YjI3MzdjODE5ODJlMjIxODQ0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1JyhnKgiguSXYjparXcrkZCo_DrnU02K-0UXcTBHzy0) 我挂载到body，但实际没生效

非 Dialog 场景，可以挂载到 body，现在你要挂载在dialog里

**Comment by guoqirong** [comment]
挂dialog也不生效，不管配置什么，都在body里

**Comment by guoqirong** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/57247313/30c3cf64-6091-41b3-b0d5-bd01eccc86d4)
找到隐藏原因，被这个样式给隐藏了

**Comment by HaixingOoO** [comment]
> ![image](https://private-user-images.githubusercontent.com/57247313/289723542-30c3cf64-6091-41b3-b0d5-bd01eccc86d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjM3NjgsIm5iZiI6MTcwMjM2MzQ2OCwicGF0aCI6Ii81NzI0NzMxMy8yODk3MjM1NDItMzBjM2NmNjQtNjA5MS00MWIzLWIwZDUtYmQwMWVjY2M4NmQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA2NDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMGIxNzIyOWMyNGU0ZjY2MDI3OWRkOTc2ZDJmMjI2YTVmNDViNWExYjBjYTljZDcyNzE1MjIwMTg4MjA1NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AKkcnfe4qMUXs1M8GymapDpR04XuQ8JnCWvda5YjG5M) 找到隐藏原因，被这个样式给隐藏了

您好，您现在样式去掉overflow：auto；可以解决这个问题吗？

**Comment by guoqirong** [comment]
是的，去掉这个就正常显示了

**Comment by chaishi** [comment]
看上去没有问题了，issue close
