### ISSUE TITLE
[Tree] 使用时控制台提示错误

### ISSUE THREAD

**Issue by SuperLeven** [Tencent/tdesign-react#2660]
### tdesign-react 版本

1.4.0

### 重现步骤

 <Tree data={treeList} activable hover transition allowFoldNodeOnFilter={true} filter={filterText ? filterByText : undefined} />

### 补充说明

![image](https://github.com/Tencent/tdesign-react/assets/75765099/fbfcd357-90ea-47ea-b383-e13724491301)

**Comment by NWYLZW** [comment]
一、请补充 `filterText` 变量
二、请补充 `filterByText` 变量
三、请补充 `treeList` 变量
四、提供一个可复现的链接用于排查你的问题

**Comment by SuperLeven** [comment]
> 可以复现 @NWYLZW 我来跟进

**Comment by SuperLeven** [comment]
> > 可以复现 @NWYLZW 我来跟进

不会操作，乱点的，没想到新建了一条，重现就好，变量都是官网复制的，名字都没改，辛苦修复了

**Comment by uyarn** [comment]
这个问题是因为初始化storeRef.current导致 暂时不影响功能的使用 我们Tree组件也正在重写 确认了下重写完不会有这个warning

**Comment by HaixingOoO** [comment]
fix 1.5.0
