### ISSUE TITLE
[Cascader]组件在 filter 之后进行选择操作存在异常bug

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#2667]
### tdesign-react 版本

1.4.0

### 重现链接

https://stackblitz.com/edit/react-dq4eq9?file=src%2Fdemo.jsx

### 重现步骤

发现在多选且搜索的情境下，勾选异常
如复现链接，在选择器里输入 “子”， 然后随意勾选，就会发现点击的未必被选中，选中项成了乱七八糟的

**Comment by uyarn** [comment]
fixed 1.4.2

**Comment by gisrp** [comment]
> fixed 1.4.2

今天更新了1.4.2，发现问题仍然存在，是因为还没有发布吗？
参考如下链接，在cascader焦点输入关键字“1”，然后在filter浮动层点击选择选项，仍然无法选中。
https://stackblitz.com/edit/react-mb3ft1?file=package.json
