### ISSUE TITLE
[Cascader] Cascader 组件同时开启 checkStrictly & filterable props，在筛选结果的浮层无法正确选中筛选项

### ISSUE THREAD

**Issue by gisrp** [Tencent/tdesign-react#2683]
### tdesign-react 版本

1.4.1

### 重现链接

[重现链接](https://stackblitz.com/edit/react-mb3ft1?file=src%2Fdemo.jsx)

### 重现步骤

1.输入过滤关键字。
2.在过滤结果的浮层点选结果项，无法选中。

### 期望结果
过滤结果项可以通过点击正确选中

### 实际结果
无法选中

### 框架版本
1.4.1

### 浏览器版本
chrome 版本 120.0.6099.129（正式版本） (arm64)

### 系统版本

macos 14.2.1 (23C71)

### Node版本

--

### 补充说明

--

**Comment by HaixingOoO** [comment]
- https://github.com/Tencent/tdesign-react/issues/2667

目前Cascader组件有过滤的bug，已经解决待发布更新了，你添加checkStrictly(父子节点选中状态不再关联，可各自选中或取消),也就是点击选中失焦就会显示在input内容中了，双击就是可自定义选择其他的内容，还有其他问题吗？

**Comment by gisrp** [comment]
没有其他问题了，谢谢

**Comment by HaixingOoO** [comment]
> 没有其他问题了，谢谢

已经解决问题的话，到时麻烦你自己关闭一下issue，谢谢！！！

**Comment by gisrp** [comment]
今天更新了1.4.2，发现问题仍然存在，是因为还没有发布吗？
参考如下链接，在cascader焦点输入关键字“1”，然后在filter浮动层点击选择选项，仍然无法选中。
https://stackblitz.com/edit/react-mb3ft1?file=package.json

**Comment by HaixingOoO** [comment]
您好，等待更新个新版本，之前修复了多选的，没注意到单选的一个问题，现在修复了
