### ISSUE TITLE
[cascader] : value值需要唯一的(也就是Key唯一)

### ISSUE THREAD

**Issue by duxphp** [Tencent/tdesign-react#2694]
### tdesign-react 版本

18

### 重现步骤

使用load 和全路径模式加载异步省市区数据， 但是 北京市/北京市 无法进行设置 也就是省和市的值都为北京市 则无法再加载下级数据

### 期望结果

使用全路径模式返回的值应该是 ['北京市', '北京市', '东城区']

### 实际结果

实际无法展开二级数据，因为 value 和省的名称冲突了

**Comment by duxphp** [comment]
https://stackblitz.com/edit/react-rveapf?file=src%2Fdemo.jsx

**Comment by HaixingOoO** [comment]
@duxphp 您好，目前`Cascader`的value是唯一的，所以这个issue暂不处理，谢谢！！！
