### ISSUE TITLE
[Pagination] 国际化文本“跳至” 翻译希望能从“jump to”调整为“Jump to”

### ISSUE THREAD

**Issue by rzdong** [Tencent/tdesign-react#2707]
### tdesign-react 版本

1.4.3

### 重现链接

https://tdesign.tencent.com/react/global-configuration#pagination-%E5%88%86%E9%A1%B5

### 重现步骤

国际化翻译，英文翻译的问题

### 期望结果

案例在这里，英文翻译是jump to，但是希望翻译能改为Jump to，首字母大写
https://tdesign.tencent.com/react/global-configuration#pagination-%E5%88%86%E9%A1%B5

### 实际结果

![image](https://github.com/Tencent/tdesign-react/assets/19262880/6d110e6e-f9f1-4368-bd5b-38a5973145a8)

**Comment by HaixingOoO** [comment]
@rzdong 欢迎PR😊！！！

**Comment by uyarn** [comment]
fixed 1.5.1
