### ISSUE TITLE
[Table] 修改table的td固定行高不生效

### ISSUE THREAD

**Issue by About-JayX** [Tencent/tdesign-react#2713]
### tdesign-react 版本

1.4.3

### 重现步骤

修改td的padding后行高仍为自适应撑开表格高度，但是在1.2.7的版本中未发现此问题

**Comment by HaixingOoO** [comment]
麻烦提供个简单的demo我们好排查，谢谢

**Comment by chaishi** [comment]
无可复现问题的代码，且无法理解问题内容。issue close
