### ISSUE TITLE
[ColorPicker] 描述问题的标题

### ISSUE THREAD

**Issue by mysllove** [Tencent/tdesign-react#2715]
### tdesign-react 版本

最新版出现

### 重现步骤

![image](https://github.com/Tencent/tdesign-react/assets/27664778/23b270be-4fd7-4568-b4c4-49cd8e2e7bb5)
直接输入linear-gradient(to right, red, blue)，色值正常，但在面板中转化的色值不对
![image](https://github.com/Tencent/tdesign-react/assets/27664778/dac21883-7165-4470-a4b7-8e9481eaae8a)

### 期望结果

期望色值一致

### 实际结果

面板色值与输入色值不一致

**Comment by HaixingOoO** [comment]
您好，你重复创建issue了，我知道你说的这个bug，但这个没那么快解决，修复了我们会在这个#2304  issue通知你的，这个先Close了，谢谢
