### ISSUE TITLE
[Select] 多选下拉选中滚动的问题

### ISSUE THREAD

**Issue by guoqirong** [Tencent/tdesign-react#2720]
### tdesign-react 版本

1.5.0

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-66f4dt?file=%2Fsrc%2Fdemo.jsx%3A68%2C3

### 重现步骤

多选下拉的问题
选中滚动条底下的选项，会被定位到选中的第一项

### 期望结果

滚动条位置不变

**Comment by HaixingOoO** [comment]
嗯，看到是有问题

**Comment by uyarn** [comment]
fixed 1.5.1
