### ISSUE TITLE
[Cascader] 设置clearable后，点击清除或多次触发onChange事件，并且返回值格式不一致

### ISSUE THREAD

**Issue by 2ue** [Tencent/tdesign-react#2729]
### tdesign-react 版本

1.5.0

### 重现链接

https://stackblitz.com/edit/react-9lffvn?file=src%2Fdemo.jsx

### 重现步骤

设置clearable属性后，点击清除

### 期望结果

onChange只触发一次

### 实际结果

只设置clearable，会触发多次onChange事件，会导致onChange逻辑执行多次
在设置了
```
valueType="full"
showAllLevels
valueMode="onlyLeaf"
```
属性后，会多次触发onChange事件，并且value值格式不一致

### 框架版本

18.2.0

**Comment by HaixingOoO** [comment]
好的，看起来是有多次触发的问题，我们尽快修复！！！

**Comment by HaixingOoO** [comment]
fixed 1.5.2
