### ISSUE TITLE
[Cascader] 级联组件，option 一级的value和二级的value 相同时，此时判断选中逻辑异常

### ISSUE THREAD

**Issue by centuryPark** [Tencent/tdesign-react#2737]
### tdesign-react 版本

1.5.1

### 重现步骤

组件options为[{value: 1, label: '1'}, { value: 2, label: '2', children: [{ value: 1, label: '3' }] }]

```[tasklist]
### Tasks
```

**Comment by HaixingOoO** [comment]
#2694 您好，你的问题和这个issue是一样的问题，`value`值要唯一的
