### ISSUE TITLE
图标显示异常被放大

### ISSUE THREAD

**Issue by li-b-y** [Tencent/tdesign-react#2747]
![截屏2024-02-21 19 28 47](https://github.com/Tencent/tdesign-react/assets/56495230/3e52c343-3b3c-4811-8e3a-1b54db82d9f9)

![截屏2024-02-21 19 30 09](https://github.com/Tencent/tdesign-react/assets/56495230/fd8e0af9-b0ea-4c61-aff9-0677e8f5f5fa)
将scale取消即恢复正常

**Comment by HaixingOoO** [comment]
@li-b-y 您好，可以提供更多信息吗？或者给个CodeSandBox链接

**Comment by li-b-y** [comment]
直接在本地引用下组件库的示例代码即可复现

**Comment by HaixingOoO** [comment]
> 直接在本地引用下组件库的示例代码即可复现

你好，可以提供多点详情信息我好排查嘛，目前我看来是没问题的！

**Comment by NWYLZW** [comment]
所有的图标都会这样？样式是哪个？改的是哪个？默认应该是没有 scale 3 这个属性的。

**Comment by leoskey** [comment]
我不了解 @li-b-y 代码。但是如果使用开发者控制，打开 iPad 模拟，会出现相同的现象。
![Uploading Snipaste_2024-03-22_17-53-05.png…]()

**Comment by HaixingOoO** [comment]
@leoskey 感谢，我们会尽快修复的！！！

**Comment by HaixingOoO** [comment]
@leoskey 您好，chrome上调试mobile/ipad端时，loading出现异常，属于正常现象。
可看这个issue：https://github.com/Tencent/tdesign-vue-next/issues/358
