### ISSUE TITLE
[Dialog] useDialogPosition 绑定了 getClickPosition，多次渲染没有清除，导致性能下降

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#2748]
### tdesign-react 版本

1.5.1

### 重现步骤

该部分代码只添加了事件，但没有清除，导致一直累加，多次渲染后导致性能严重下降。

https://github.com/Tencent/tdesign-react/blob/1718fbef56f3e503a5b34489b1af7d4f9c59aef8/src/dialog/hooks/useDialogPosition.ts#L16C1-L18C4

<img width="881" alt="image" src="https://github.com/Tencent/tdesign-react/assets/37169906/81cf99a2-39fb-4b42-8445-2435aec3fe21">

### 补充说明

下面的 `useEffect` 已经处理了事件绑定，这部分是不是可以删掉？

**Comment by HaixingOoO** [comment]
fixed 1.5.2
