### ISSUE TITLE
[Select 选择器] Select Props 属性中 使用onRemove 事件失效

### ISSUE THREAD

**Issue by zedwei2** [Tencent/tdesign-react#2789]
### tdesign-react 版本

1.5.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-jpz77g?file=/src/demo.jsx

### 重现步骤

1.打开【重现链接】的地址
2.移除第一个select中某一项数据
3.查看控制台打印情况

### 期望结果

可以触发onRemove事件

### 实际结果

无法触发onRemove事件

**Comment by Ali-ovo** [comment]
看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型 
@HaixingOoO   需要改吗 我这边可以提个mr

**Comment by HaixingOoO** [comment]
> 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型 
> 
> @HaixingOoO   需要改吗 我这边可以提个mr

我们已经在修复了，谢谢！！！

**Comment by Ali-ovo** [comment]
> > 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型
> > @HaixingOoO   需要改吗 我这边可以提个mr
> 
> 我们已经在修复了，谢谢！！！

好的

**Comment by HaixingOoO** [comment]
> 好的

欢迎后续更多的参与和贡献！😁

**Comment by uyarn** [comment]
> > > 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型
> > > @HaixingOoO   需要改吗 我这边可以提个mr
> > 
> > 
> > 我们已经在修复了，谢谢！！！
> 
> 好的

@Ali-ovo  才看到 本来是我修复 那你提个PR吧 需要你的热情～

**Comment by Ali-ovo** [comment]
> > > > 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型
> > > > @HaixingOoO   需要改吗 我这边可以提个mr
> > > 
> > > 
> > > 我们已经在修复了，谢谢！！！
> > 
> > 
> > 好的
> 
> @Ali-ovo 才看到 本来是我修复 那你提个PR吧 需要你的热情～

哈哈，感谢 之前我也给 tdesign 做过很多贡献

这个bug看我说的 我想的是 `onRmove` 参数就直接是当前剩下选中的key或者是删除的节点 这样可以吗 
目前是无法按照 定义的 `SelectRemoveContext` 类型 来返回值

或者是我的代码地方理解错了吗？

**Comment by uyarn** [comment]
> > > > > 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型
> > > > > @HaixingOoO   需要改吗 我这边可以提个mr
> > > > 
> > > > 
> > > > 我们已经在修复了，谢谢！！！
> > > 
> > > 
> > > 好的
> > 
> > 
> > @Ali-ovo 才看到 本来是我修复 那你提个PR吧 需要你的热情～
> 
> 哈哈，感谢 之前我也给 tdesign 做过很多贡献
> 
> 这个bug看我说的 我想的是 `onRmove` 的参数是当前剩下选中的key或者是删除的节点 这样可以吗 目前是无法按照 定义的 `SelectRemoveContext` 类型 来返回值
> 
> 或者是我的代码地方理解错了吗？

我理解现在的参数类型是可以满足的 里面的value data都是指这个被删除的选项

**Comment by Ali-ovo** [comment]
> > > > > > 看了一下代码这个改的话 onRmove 事件得改一下类型了，只能传出当前选中的key或者当前删除的节点出来，而不是现在定义的 `SelectRemoveContext` 类型
> > > > > > @HaixingOoO   需要改吗 我这边可以提个mr
> > > > > 
> > > > > 
> > > > > 我们已经在修复了，谢谢！！！
> > > > 
> > > > 
> > > > 好的
> > > 
> > > 
> > > @Ali-ovo 才看到 本来是我修复 那你提个PR吧 需要你的热情～
> > 
> > 
> > 哈哈，感谢 之前我也给 tdesign 做过很多贡献
> > 这个bug看我说的 我想的是 `onRmove` 的参数是当前剩下选中的key或者是删除的节点 这样可以吗 目前是无法按照 定义的 `SelectRemoveContext` 类型 来返回值
> > 或者是我的代码地方理解错了吗？
> 
> 不好意思 忘记回消息了 @Ali-ovo 我理解现在的参数类型是可以满足的 里面的value data都是指这个被删除的选项

好的 这个ts类型貌似一直报错 我该了一版 请review一下

**Comment by uyarn** [comment]
fixed 1.5.4
