### ISSUE TITLE
[Input] 自动聚焦无效

### ISSUE THREAD

**Issue by Evashasha** [Tencent/tdesign-react#2794]
### tdesign-react 版本

latest

### 重现链接

https://react-pzgyyu.stackblitz.io/

### 重现步骤

点击“请选择云解决方案”，下拉框中的输入框未自动聚焦

### 期望结果

能设置下拉框中的输入框自动聚焦

**Comment by HaixingOoO** [comment]
@Evashasha [stackblitz demo](https://stackblitz.com/edit/react-bxcpm8?file=src%2Fdemo.jsx)
