### ISSUE TITLE
[Tabs] Action 区域提供默认样式

### ISSUE THREAD

**Issue by DevQiao** [Tencent/tdesign-react#2806]
### tdesign-react 版本

1.5.3

### 重现链接

https://stackblitz.com/edit/react-subqa3?file=src%2Fdemo.jsx

### 重现步骤

tabs action区域样式不对，且对于 addable 的 Tabs，背景没统一，不美观

### 期望结果

Tabs action 区域上下居中（small size 也一样），背景一致

### 实际结果

![image](https://github.com/Tencent/tdesign-react/assets/10654788/46167691-d58b-4c01-aa81-d12b86516871)

### 框架版本

React 16.14

**Comment by uyarn** [comment]
optimize 1.5.4
