### ISSUE TITLE
[Form/FormItem] 视图问题

### ISSUE THREAD

**Issue by zindler323** [Tencent/tdesign-react#2809]
### tdesign-react 版本

1.5.2

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-k4nx7j?file=%2Fsrc%2Fdemo.jsx%3A90%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltwe0zry00073b6h42s97g2m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltwe0zry00033b6h0fmbz84m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltwe0zry00043b6hftmllbje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltwe0zry00063b6hej0z9qzn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.700805996676735%252C48.299194003323265%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltwe0zry00033b6h0fmbz84m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwe0zry00023b6hnrtsjq2b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdemo.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A90%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A90%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cltwe0zry00033b6h0fmbz84m%2522%252C%2522activeTabId%2522%253A%2522cltwe0zry00023b6hnrtsjq2b%2522%257D%252C%2522cltwe0zry00063b6hej0z9qzn%2522%253A%257B%2522id%2522%253A%2522cltwe0zry00063b6hej0z9qzn%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltwe0zry00043b6hftmllbje%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltwe0zry00043b6hftmllbje%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

访问重现链接，在界面中添加变量，选择类型，选择值，添加变量，选择类型，选择值，一直循环即可出现。

### 补充说明

貌似与FormItem的effect: formMapRef.set  formMapRef.delete相关

**Comment by zindler323** [comment]
> @zindler323 把截图的这个key去掉或者要么你就用id，不要用type当key
> 
> <img alt="截屏2024-03-20 21 38 54" width="524" src="https://private-user-images.githubusercontent.com/65376724/314520654-d48557b6-8586-4639-af1b-6e7203b0f7be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDI3MTAsIm5iZiI6MTcxMDk0MjQxMCwicGF0aCI6Ii82NTM3NjcyNC8zMTQ1MjA2NTQtZDQ4NTU3YjYtODU4Ni00NjM5LWFmMWItNmU3MjAzYjBmN2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEzNDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMzllY2U1YzM5YTU4NTJlZTQ2ODJmYzU3YzEzNjlhZmJlNmQyNzc3ZWIyNDYyYTgwZTkzOTM5YTNkM2ZkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qf9gXAn3zWzpOMHNu3uq32BMa4CCdT5p3gPA3qp5eiA">

您好，key={type}是我不小心引入的另一个问题，我重新修改了下demo，请您再帮忙看下，谢谢

**Comment by zindler323** [comment]
> 你能详细点说明或者给几张图是什么视图问题吗？🤔

您好，我的操作如下：
 
<img width="495" alt="image" src="https://github.com/Tencent/tdesign-react/assets/56532311/f5b05ab7-42f4-481f-85c9-c282bca4a5fd">
<img width="471" alt="image" src="https://github.com/Tencent/tdesign-react/assets/56532311/f9952d2d-7696-4421-856c-c5f0fc9b6078">

**Comment by HaixingOoO** [comment]
ok，我们看看！

**Comment by HaixingOoO** [comment]
fixed 1.7.0
