### ISSUE TITLE
[Image]  属性 referrerpolicy 不生效

### ISSUE THREAD

**Issue by anming-john** [Tencent/tdesign-react#2810]
### tdesign-react 版本

1.4.2

### 重现步骤

从代码中发现， 并不支持传入这个属性
![企业微信截图_369d20ac-e9d0-41c3-b79d-f2c8ebe498b6](https://github.com/Tencent/tdesign-react/assets/15686326/6fbe425c-55a8-4ee8-89f6-ce083e548b73)

代码中

![企业微信截图_c6f6c404-6305-441e-9b2e-37e47d094ffd](https://github.com/Tencent/tdesign-react/assets/15686326/0e8457c5-dff2-4bd8-9c64-01d2304be405)

### 期望结果

希望能支持

### 实际结果

不支持

**Comment by anming-john** [comment]
同理，  ImageViewer  也存在这个问题

**Comment by HaixingOoO** [comment]
> 同理， ImageViewer 也存在这个问题

好的👌

**Comment by NWYLZW** [comment]
> 同理， ImageViewer 也存在这个问题

ImageViewer 在文档中并没有提到支持 referrerpolicy，这个可能需要讨论一下设计，看看参数应该加在哪里。
这个问题暂时只关联 Image 组件吧，如果对 ImageViewer 有添加这个参数的需求，可以另外发一个 feature request issue，我们另外跟进这个问题。
