### ISSUE TITLE
config-provider什么时候对外开放，针对文案去做自定义

### ISSUE THREAD

**Issue by yanima** [Tencent/tdesign-react#282]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chaishi** [comment]
2022 Q1

**Comment by chaishi** [comment]
@yanima 你们现在着急对哪些组件进行文案自定义配置，我们优先支持一下

**Comment by yanima** [comment]
> 
目前需要对DatePicker的那个popup的头部显示格式自定义

**Comment by HQ-Lin** [comment]
目前 config-provider 组件用法已和 vue 框架达成一致，大部分组件的国际化配置已支持，文档会在本周补充一下
组件内部分细节支持配置化能力应该要在 Q1 阶段完成
