### ISSUE TITLE
[EnhancedTable] 树型列表记录当前节点收起展开的状态

### ISSUE THREAD

**Issue by taodream518** [Tencent/tdesign-react#2836]
### tdesign-react 版本

1.5.1

### 重现链接

https://codesandbox.io/p/sandbox/test-8m8x9h?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clup6pdgx00063b6rf9k5ay1x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clup6pdgw00023b6rooeppz51%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clup6pdgw00033b6ry89f9m4t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clup6pdgw00053b6r7m9tmfu8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.62225430018586%252C43.37774569981414%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clup6pdgw00023b6rooeppz51%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clup6pdgw00013b6roe5xemb5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clup6pdgw00023b6rooeppz51%2522%252C%2522activeTabId%2522%253A%2522clup6pdgw00013b6roe5xemb5%2522%257D%252C%2522clup6pdgw00053b6r7m9tmfu8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clup6pdgw00043b6rv7ab5vd8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clup6pdgw00053b6r7m9tmfu8%2522%252C%2522activeTabId%2522%253A%2522clup6pdgw00043b6rv7ab5vd8%2522%257D%252C%2522clup6pdgw00033b6ry89f9m4t%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clup6pdgw00033b6ry89f9m4t%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 期望结果

浏览器刷新后能保持原来的节点状态

### 实际结果

只保持了第一层的节点展开的状态

### Node版本

v16.20.2

**Comment by HaixingOoO** [comment]
fixed 1.7.0
