### ISSUE TITLE
[Tree] 初始化后，切换draggable的值都不生效

### ISSUE THREAD

**Issue by Liao-js** [Tencent/tdesign-react#2837]
### tdesign-react 版本

1.5.5

### 重现链接

https://stackblitz.com/edit/react-ugjsy2-vkutqc?file=src%2Fdemo.jsx

### 期望结果

切换 draggable 的值后，能正常生效

### 实际结果

切换 draggable 的值后，无法正常生效

**Comment by Liao-js** [comment]
这个问题，我会自己提交 PR

**Comment by uyarn** [comment]
fixed 1.6.0
