### ISSUE TITLE
[Select组件] label为0的时候无法显示

### ISSUE THREAD

**Issue by suedar** [Tencent/tdesign-react#2847]
### tdesign-react 版本

1.5.1

### 重现链接
[sandbox 演示](https://codesandbox.io/p/sandbox/select-tdesign-react-y5jj36?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv0batxw00063575647ekzkh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv0batxw00023575eyj6tshf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv0batxw000335759cfn2wjx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv0batxw00053575szz3m1mp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv0batxw00023575eyj6tshf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv0batxv00013575rgfjrguf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clv0batxw00023575eyj6tshf%2522%252C%2522activeTabId%2522%253A%2522clv0batxv00013575rgfjrguf%2522%257D%252C%2522clv0batxw00053575szz3m1mp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv0batxw00043575egsp8dgh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv0batxw00053575szz3m1mp%2522%252C%2522activeTabId%2522%253A%2522clv0batxw00043575egsp8dgh%2522%257D%252C%2522clv0batxw000335759cfn2wjx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv0batxw000335759cfn2wjx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 重现步骤

选择第一项

### 期望结果

显示label为0的项

### 实际结果

选择第一项后label不显示

### 框架版本

React(18.2.43)

**Comment by HaixingOoO** [comment]
![image](https://github.com/Tencent/tdesign-react/assets/65376724/20f0bfb3-1de7-4ab6-b7a5-a933800902c1)
label使用`string`

**Comment by suedar** [comment]
不能这样单纯的处理，有的options是依赖后端返回的，这样很容易出现业务问题，至少应该兼容一下。。。

**Comment by NWYLZW** [comment]
不能假定在使用的用户需要的就是什么，可能是需要隐藏，可能是需要展示文案（文案也是不确定的），万一有的依赖就是不展示呢（可能性比较小）
基于以上的观点，如果我兼容了，问题就不会暴露出来，可能作为一种默认行为被继续使用
其次如果你需要对于 falsy 的特殊兼容支持，这可能是一个比较大的需求，对于单一职责的原子组件来说引入过多复杂度对于组件的维护并不是一件好事
最后由业务向后端要求数据格式的准确性，也是后端应该做到的
所以说约定了 string 的情况下，对于 only string 的支持也是一种合理的措施

**Comment by suedar** [comment]
如果label强制要求是string类型的，使用数字类型应该报warning进行提示
这里的数字类型1是可以显示的，数字类型为0显示不了，是一个非常明显的问题
真正能暴露使用问题的方式是进行warning提示，而不是使用者使用同一类型的数据的时候显示出与其他数据不同的行为
这很容易导致难以预料的业务问题

**Comment by NWYLZW** [comment]
> 如果label强制要求是string类型的，使用数字类型应该报warning进行提示 这里的数字类型1是可以显示的，数字类型为0显示不了，是一个非常明显的问题 真正能暴露使用问题的方式是进行warning提示，而不是使用者使用同一类型的数据的时候显示出与其他数据不同的行为 这很容易导致难以预料的业务问题

首先数字的输入是 ub(undefined behavior)，其次如果你使用的是现代化的编辑起在类型上便会对类型进行检查，并不会遗留问题到生产环境再被发现。

如果你确实觉得组件库需要来对这些 ub 做防御型编程可以提出一个 feature request，关于如何对于 falsy(undefined,null,0,false) 的各种特殊情况下对于数据输入的转化逻辑，这可以被讨论应该如何防御，而且这对于整个系统来说都是有益的。
