### ISSUE TITLE
组件： Dialog

### ISSUE THREAD

**Issue by Evashasha** [Tencent/tdesign-react#2858]
问题描述：
使用Dialog属性confirmLoading无效，未出现loading效果

复现地址：
https://stackblitz.com/edit/react-ojmdnp?file=src%2Fdemo.jsx

**Comment by Evashasha** [comment]
> 👋 @Evashasha，感谢给 TDesign 提出了 issue。 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

期待大佬们快速解决🌹🌹🌹

**Comment by HaixingOoO** [comment]
这个是新功能的，现在是文档放出来了，后续会尽快加上的

**Comment by uyarn** [comment]
supported 1.7.1
