### ISSUE TITLE
Menu组件中点击MenuItem的动效没法关闭吗？

### ISSUE THREAD

**Issue by fengchuiwanli** [Tencent/tdesign-react#287]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LeeJim** [comment]
后面会做个全局动画的开关。

**Comment by fengchuiwanli** [comment]
> 后面会做个自己的开关。

大概多久上呢？能快点儿支持不？

**Comment by fengchuiwanli** [comment]
> 后面会做个全局动画的开关。
大概多久上呢？能快点儿支持不？

**Comment by uyarn** [comment]
> > 后面会做个全局动画的开关。
> > 大概多久上呢？能快点儿支持不？

年后的版本吧 我们确定一下API的命名就可以加上的

**Comment by uyarn** [comment]
预计本周上线

**Comment by uyarn** [comment]
`<ConfigProvider globalConfig={{ animation:{ exclude:['ripple'] } }}></ConfigProvider>`可关闭点击波纹动画
ConfigProvider的文档后续会提供
