### ISSUE TITLE
[HeadMenu] 横版菜单栏在next dev显示正常，但在next start时子菜单会偏移

### ISSUE THREAD

**Issue by neoalvin** [Tencent/tdesign-react#2888]
### tdesign-react 版本

1.7.0

### 重现链接

https://github.com/neoalvin/tdesign-demo

### 重现步骤

next dev下运行：
<img width="635" alt="image" src="https://github.com/Tencent/tdesign-react/assets/15117317/d9d36ac4-2474-4ede-8af0-f9050aaab293">

next start下运行，必现菜单栏偏移：
<img width="768" alt="image" src="https://github.com/Tencent/tdesign-react/assets/15117317/728ea5f0-9f60-4b3b-8d3c-f70e581909f3">

### 期望结果

子菜单正常显示

### 实际结果

子菜单位置偏移

### 框架版本

18

### Node版本

v20.10.0

**Comment by uyarn** [comment]
fixed 1.7.1
