### ISSUE TITLE
[Upload] 当theme:image, draggable:true， uploadFilePercent无效

### ISSUE THREAD

**Issue by Except10n** [Tencent/tdesign-react#2893]
### tdesign-react 版本

1.7.0

### 重现链接

https://stackblitz.com/edit/react-d4fagf?file=src%2Fdemo.jsx

### 重现步骤
![image](https://github.com/Tencent/tdesign-react/assets/1645092/d172f858-ce10-4a74-afc2-43774b013ade)

_No response_

**Comment by Except10n** [comment]
@HaixingOoO 顺便修复下 预览图片加载异常的样式呗

我是直接隐藏了  眼不见为净
```
.@{prefix}-image__error {
    .@{prefix}-space-item + .@{prefix}-space-item {
      display: none;
    }
  }
```

**Comment by HaixingOoO** [comment]
> @HaixingOoO 顺便修复下 预览图片加载异常的样式呗
> 
> 我是直接隐藏了 眼不见为净
> 
> ```
> .@{prefix}-image__error {
>     .@{prefix}-space-item + .@{prefix}-space-item {
>       display: none;
>     }
>   }
> ```

可以的话提供一下图片给我们看看是哪个地方的样式异常，谢谢！！！

**Comment by Except10n** [comment]
<img width="1274" alt="image" src="https://github.com/Tencent/tdesign-react/assets/1645092/ba1ff845-0d49-4cec-bbb4-3b617974086b">


```
.@{prefix}-image__error
.@{prefix}-image__loading
```
