### ISSUE TITLE
[Select] reserveKeyword filterable multiple 属性时，列表搜索功能不符合预期

### ISSUE THREAD

**Issue by qinmaoxing** [Tencent/tdesign-react#2895]
### tdesign-react 版本

1.7.0

### 重现链接

https://stackblitz.com/edit/react-squhyp-dfkfd9?file=src%2Fdemo.jsx

### 重现步骤

1. 输入关键字搜索：**iPhone**
2. 下拉列表中，显示 **iPhone 14**、**iPhone 15** 这两项
3. 选择 **iPhone 14**

### 期望结果

因为使用了 'reserveKeyword={true}' 属性，下拉列表中，用户选中其中一项后，期望下拉列表选择框，仍然保持 **iPhone 14**、**iPhone 15** 这两项过滤，让用户继续选择其它的 **iPhone**，例如 **iPhone 15**

### 实际结果

下拉列表做了一次刷新，把所有选项都显示出来了

### 框架版本

React(18.3.1)

### 浏览器版本

Chrome(124.0.6367.201)

### 系统版本

Window10(22H2)

### Node版本

v18.18.0

### 补充说明

如果把 Select 组件的 value，onChange 属性都去掉，则没有上述问题，效果符合预期；

**Comment by uyarn** [comment]
fixed 1.7.1
