### ISSUE TITLE
[Chheckbox] Checkbox.Group 受控后，onChange 的回调值不对

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#2923]
### tdesign-react 版本

1.7.3

### 重现链接

https://stackblitz.com/edit/react-fq7yh3?file=src%2Fdemo.jsx

### 重现步骤

`Checkbox.Group` 值受控时，回调的结果不正确。
<img width="1591" alt="image" src="https://github.com/Tencent/tdesign-react/assets/37169906/2b85193c-f900-4a52-9603-602d825d6136">

### 期望结果

受控的值与要变化的值进行计算。

### 实际结果

并未正确受控，现在点击后直接存进回调的值数组中了。

**Comment by NWYLZW** [comment]
```ts
const [v, setV] = useState([1])
<A value=v options=[1, 2, 3] onchange={() => {
  console.log(v)
}}/>
```
有三个选项
- [x] 1
- [ ] 2 <- 现在选了它
- [ ] 3
如果按照你说的「受控的值与要变化的值进行计算。」那这里是不是要返回 `1` 呢？
再具体描述一下你的操作步骤和你的预期行为？
