### ISSUE TITLE
[全局特性配置] 自定义类前缀, 在根目录ConfigProvider包括后, 子组件如果重新 ReactDOM.render, 则无法共享ConfigProvider配置

### ISSUE THREAD

**Issue by Gestorz** [Tencent/tdesign-react#2953]
### tdesign-react 版本

>1.2.3

### 期望结果

1.2.3或之前版本, 只需要ConfigProvider在根目录包裹一次即可, 后续版本, 则不行

```[tasklist]
### Tasks
```

**Comment by NWYLZW** [comment]
ConfigProvider 通过 react context provider 提供，如果自行通过操作 dom 破坏了组件上下关系时请自行进行数据同步操作
