### ISSUE TITLE
[Table] pagination 使用三元符并且data为空时，页面会展示之前数据的前十条数据

### ISSUE THREAD

**Issue by jacksonjin** [Tencent/tdesign-react#2957]
### tdesign-react 版本

1.7.5

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-r8ptn6?file=%2Fsrc%2Fdemo.jsx%3A1%2C1-38%2C1

### 重现步骤

重现代码关键是， pagination 是否是三元判断，如果pagination = {total，defaultPageSize, defaultCurrent},就不会出现问题
import React, { useState, useEffect } from "react";
import { Table } from "tdesign-react";

export default function EditableCellTable() {
  const arr = Array.from({ length: 100 }, (_, index) => ({ id: index + 1 }));

  const [data, setData] = useState(arr);

  useEffect(() => {
    setTimeout(() => {
      setData([]);
    }, 5000);
  }, []);
  const columns = [
    {
      title: "id",
      colKey: "id",
    },
  ];
  // 当前示例包含：输入框、单选、多选、日期 等场景
  return (
    <Table
      rowKey="key"
      columns={columns}
      data={data}
      pagination={
        data?.length
          ? {
              defaultPageSize: 10,
              defaultCurrent: 1,
              total: data?.length,
            }
          : null
      }
    />
  );
}

```[tasklist]
### Tasks
```

**Comment by NWYLZW** [comment]
<img width="1920" alt="image" src="https://github.com/Tencent/tdesign-react/assets/51358815/095ab003-7c07-44f1-932e-147296d64869">
sandbox 无法访问（补充 sandbox 后可以重新打开 issue）

看贴出来的代码应该是是按照逻辑预期工作的

**Comment by jacksonjin** [comment]
> <img alt="图像" width="1920" src="https://private-user-images.githubusercontent.com/51358815/341332010-095ab003-7c07-44f1-932e-147296d64869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTE2MTMsIm5iZiI6MTcxODk1MTMxMywicGF0aCI6Ii81MTM1ODgxNS8zNDEzMzIwMTAtMDk1YWIwMDMtN2MwNy00NGYxLTkzMmUtMTQ3Mjk2ZDY0ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2MjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZTExOWZmYmExMmJhOGYyODk3NTlkOGRhNmNkZDk0ZTc2OTIxMDAxYWI4YzFmNTk1OTI5MjBkMThkZGZmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8reJMwF9beHpMV1jComQs5Q-Cso5QqSBi-vKGQB_V9I"> sandbox 无法访问（补充 sandbox 后可以重新打开的问题）
> 看贴士代码应该是按照逻辑预期工作的

现有逻辑是有问题的呀，sandbox  的内容是 贴出来的代码，执行一下下就知道了！

**Comment by HaixingOoO** [comment]
> > <img alt="图像" width="1920" src="https://private-user-images.githubusercontent.com/51358815/341332010-095ab003-7c07-44f1-932e-147296d64869.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTE2MTMsIm5iZiI6MTcxODk1MTMxMywicGF0aCI6Ii81MTM1ODgxNS8zNDEzMzIwMTAtMDk1YWIwMDMtN2MwNy00NGYxLTkzMmUtMTQ3Mjk2ZDY0ODY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2MjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZTExOWZmYmExMmJhOGYyODk3NTlkOGRhNmNkZDk0ZTc2OTIxMDAxYWI4YzFmNTk1OTI5MjBkMThkZGZmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8reJMwF9beHpMV1jComQs5Q-Cso5QqSBi-vKGQB_V9I"> sandbox 无法访问（补充 sandbox 后可以重新打开的问题）
> > 看贴士代码应该是按照逻辑预期工作的
> 
> 现有逻辑是有问题的呀，sandbox 的内容是 贴出来的代码，执行一下下就知道了！

现在是sandbox你给的链接是不是你自己打开可以看，我们打开看不了代码，也就是你设置了私有，没公开仓库，我们访问不了

**Comment by jacksonjin** [comment]
> import React, { useState, useEffect } from "react"; import { Table } from "tdesign-react";
> 
> export default function EditableCellTable() { const arr = Array.from({ length: 100 }, (_, index) => ({ id: index + 1 }));
> 
> const [data, setData] = useState(arr);
> 
> useEffect(() => { setTimeout(() => { setData([]); }, 5000); }, []); const columns = [ { title: "id", colKey: "id", }, ]; // 当前示例包含：输入框、单选、多选、日期 等场景 return ( <Table rowKey="key" columns={columns} data={data} pagination={ data?.length ? { defaultPageSize: 10, defaultCurrent: 1, total: data?.length, } : null } /> ); }

import React, { useState, useEffect } from "react";
import { Table } from "tdesign-react";

export default function EditableCellTable() {
const arr = Array.from({ length: 100 }, (_, index) => ({ id: index + 1 }));

const [data, setData] = useState(arr);

useEffect(() => {
setTimeout(() => {
setData([]);
}, 5000);
}, []);
const columns = [
{
title: "id",
colKey: "id",
},
];
// 当前示例包含：输入框、单选、多选、日期 等场景
return (
<Table
rowKey="key"
columns={columns}
data={data}
pagination={
data?.length
? {
defaultPageSize: 10,
defaultCurrent: 1,
total: data?.length,
}
: null
}
/>
);
}
这个是 sandbox 里边的内容
随便在tdesign的一个官网上打开一个 sandbox ，执行上边的代码就能复现
![image](https://github.com/Tencent/tdesign-react/assets/71485170/1ffd54e9-7f84-4ca3-842b-5f8708fcefbb)
