### ISSUE TITLE
pnpm dev 报错 Could not resolve "../../src/_common/docs/compile"

### ISSUE THREAD

**Issue by zhuba-Ahhh** [Tencent/tdesign-react#2982]
### tdesign-react 版本

1.7.6

### 重现步骤

`pnpm dev`
```
✘ [ERROR] Could not resolve "../../src/_common/docs/compile"
    plugin-tdoc/md-to-react.js:6:46:
      6 │ import { compileUsage, getGitTimestamp } from '../../src/_common/docs/compile';
```

<img width="1087" alt="image" src="https://github.com/Tencent/tdesign-react/assets/84793349/46980122-700d-422b-94a8-bed503bcdda2">

### 期望结果

不报错

### 实际结果

报错

### Node版本

18.20.2

**Comment by NWYLZW** [comment]
submodule 需要初始化，参考一下开发指南
