### ISSUE TITLE
opconfirm组件 找不到父节点发生偏移[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by Smyile** [Tencent/tdesign-react#2983]
### tdesign-react 版本

1.2.6

### 重现步骤

<Popconfirm
            visible={showConfirm[row.vsClass]}
            content={`内容`}
            onCancel={() => {
              setDisableMapSelect(false);
              setMapSelectValue(old => ({ ...old, [row.vsClass]: undefined }));
              setShowConfirm(old => ({ ...old, [row.vsClass]: false }));
            }}
            onConfirm={() => {
              console.log('hello')
            }}
          >
            <AuthorityDecorator>//封装组件嵌套
              <Select
                value={mapSelectValue[row.vsClass]}
                disabled={disableMapSelect}
                options={MERGED_TYPE_LIST.map(e => ({ label: e.label, value: e.name }))}
                onChange={value => {
console.log('hello')
                }}
              />
            </AuthorityDecorator>
          </Popconfirm>
![企业微信截图_270f150c-c7d5-479b-91d1-f51bfad2190c](https://github.com/Tencent/tdesign-react/assets/63196724/49471243-593d-46f5-bff3-78d63a63cfd9)

### 期望结果

希望位置不发生偏移，功能正常。

### 实际结果

位置偏移，删除按钮无法点击

**Comment by Smyile** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HaixingOoO** [comment]
你可以暂时使用`Fragment`来解决这个问题，主要是嵌套的`popup`查找`ref`的问题
```tsx
<Popconfirm>
      <>
         <Select />
      </>
</Popconfirm>
```
