### ISSUE TITLE
[Tabs文档] [可拖拽的选项卡]示例代码有问题

### ISSUE THREAD

**Issue by zindler323** [Tencent/tdesign-react#2988]
### tdesign-react 版本

官网demo版本

### 重现链接

https://tdesign.tencent.com/react/components/tabs#%E5%8F%AF%E6%8B%96%E6%8B%BD%E7%9A%84%E9%80%89%E9%A1%B9%E5%8D%A1

### 重现步骤

`  const onDragSort1 = useCallback(
    () =>
      debounce(({ currentIndex, targetIndex }) => {
        const temp = tabList1[currentIndex];
        tabList1[currentIndex] = tabList1[targetIndex];
        tabList1[targetIndex] = temp;
        setTabList1([...tabList1]);
      }, 500),
    [tabList1],
  );`

### 期望结果

`const [onDragSort1] = useState(() => debounce(({ currentIndex, targetIndex }) => setTabList1((pre) => {
    const newValue = [...pre];
    const temp = newValue[currentIndex];
    newValue[currentIndex] = newValue[targetIndex];
    newValue[targetIndex] = temp;
    return newValue; 
}), 500))`

### 实际结果

1

**Comment by HaixingOoO** [comment]
欢迎PR！！！
不过只需要把 `debounce` 里的函数参数提取给 `useCallback` 就好了
![image](https://github.com/Tencent/tdesign-react/assets/65376724/00cd8fe7-7e37-4f72-bd8f-c73a849bdf8f)

**Comment by zindler323** [comment]
我一开始使用时也省去了debounce，但是发现在相邻两个tab交换时，如果拖动过慢会瞬间交换两次，从而有莫名其妙的一个bug。因此最后我还是使用了debounce

**Comment by HaixingOoO** [comment]
> 我一开始使用时也省去了debounce，但是发现在相邻两个tab交换时，如果拖动过慢会瞬间交换两次，从而有莫名其妙的一个bug。因此最后我还是使用了debounce

看各自喜欢，防抖或者节流，甚至不用也行，因人而异，但是目前demo使用debounce那就继续使用这个好了，然后欢迎PR来修复目前这个demo的bug！！！

**Comment by HaixingOoO** [comment]
> 欢迎PR！！！ 不过只需要把 `debounce` 里的函数参数提取给 `useCallback` 就好了 ![image](https://private-user-images.githubusercontent.com/65376724/347703570-00cd8fe7-7e37-4f72-bd8f-c73a849bdf8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExOTQyNzQsIm5iZiI6MTcyMTE5Mzk3NCwicGF0aCI6Ii82NTM3NjcyNC8zNDc3MDM1NzAtMDBjZDhmZTctN2UzNy00ZjcyLWJkOGYtYzczYTg0OWJkZjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA1MjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZmVkZjlhNzk3NWJmNmVjMzUxZGU3N2Y2NmNiZDExOTI3ZTY3OWFjOWVhYjk2YmNmMDk5OGFjYmI1YjI5MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HtQov8CXbamE3DL-88TlxXQbgohchksb4XR61qhBunc)

之前没仔细看，没看里面防抖执行的情况，把 `useCallback` 改成 `useMemo` 就好了

**Comment by zindler323** [comment]
> 把

事实上还存在个函数缓存失效问题。
对于一个[state, setState]=useState(0)
无论是useCallback(() => setState(state + 1), [state]); 
还是useMemo(() => () => setState(state + 1)，[state]);
调用一次后，依赖项发生变化，缓存变旧，重新生成。

useCallback(() => setState(pre => ...), [])可能好点。

**Comment by NWYLZW** [comment]
不要在这里用防抖吧，内部的拖拽不感知不到排序回调是否执行成功，默认每次结束都会更新一个最新的 index，导致没办法感知到实际的顺序。
但是在这里我理解应该不存在很高频触发的性能问题，所以对这种支持暂时不在计划之类。
