### ISSUE TITLE
[Checkbox文档] 描述错误

### ISSUE THREAD

**Issue by 1379255913** [Tencent/tdesign-react#2993]
### tdesign-react 版本

1.7.6

### 重现链接

https://tdesign.tencent.com/react/components/checkbox

### 重现步骤

受控类多选框描述为“多选框支持 v-model、受控和非受控三种使用方式”，从vue文档中迁移时未改变描述

### 期望结果

描述符合react写法

**Comment by uyarn** [comment]
emmm 这个文档刚好是复用的 只能改common的描述把v-model去掉
