### ISSUE TITLE
[Upload文档] 基础图片上传示例的Stackblitz和CodeSandbox存在问题

### ISSUE THREAD

**Issue by 1379255913** [Tencent/tdesign-react#3004]
### tdesign-react 版本

1.7.7

### 重现链接

https://tdesign.tencent.com/react/components/upload#%E5%9F%BA%E7%A1%80%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0

### 重现步骤

进入文档链接后进入Stackblitz或CodeSandbox

https://stackblitz.com/run?file=src%2Findex.js
![QQ_1721625626618](https://github.com/user-attachments/assets/2e972988-47a7-4ae1-9332-54f0a756da3d)

https://codesandbox.io/p/sandbox/tdesign-react-demo-kqz95n?file=%2Fsrc%2Fdemo.tsx
![QQ_1721625612419](https://github.com/user-attachments/assets/b17e427e-496d-4ba3-8b0a-c8c35af9b37c)

### 期望结果

能正确显示

**Comment by HaixingOoO** [comment]
fixed 1.7.9
