### ISSUE TITLE
[tagInput] 单独设置某个tag的样式

### ISSUE THREAD

**Issue by zqing5621** [Tencent/tdesign-react#3026]
### 这个功能解决了什么问题

对于异常的tag，应该能给出醒目的提示，类似于这种
<img width="249" alt="image" src="https://github.com/user-attachments/assets/0f5bc42c-4a2e-40b3-88fe-19e313c4616b">

### 你建议的方案是什么

tagProps应该是一个方法，入参为value，以便于更精细化的设置tag样式

**Comment by HaixingOoO** [comment]
[taginput valueDisplay](https://tdesign.tencent.com/react/components/tag-input#%E5%8F%AF%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%87%E7%AD%BE%E7%9A%84%E6%A0%87%E7%AD%BE%E8%BE%93%E5%85%A5%E6%A1%86)可以看看自定义显示tag
