### ISSUE TITLE
[popup] 文档中出现异常内容

### ISSUE THREAD

**Issue by suedar** [Tencent/tdesign-react#3036]
### tdesign-react 版本

1.7.8

### 重现链接

https://tdesign.tencent.com/react/components/popup?tab=api

### 重现步骤

<img width="929" alt="企业微信截图_5c0db27f-6ab9-41bb-bfad-f085f705f23f" src="https://github.com/user-attachments/assets/3db21e77-0814-4025-ba28-6cad7f3b76ed">

**Comment by uyarn** [comment]
已修复文档
