### ISSUE TITLE
[ColorPickerPanel] slider move出元素之外，再次move到元素中还能触发mousemove事件

### ISSUE THREAD

**Issue by Jippp** [Tencent/tdesign-react#3041]
### tdesign-react 版本

1.7.9

### 重现链接

https://stackblitz.com/edit/react-lv2q4a-6dgsrz?file=src%2Fdemo.tsx

### 重现步骤

1. 鼠标移动到slider上
2. 按下鼠标 保持不松开 向左或向右移动出slider
3. 鼠标松开，再次将鼠标移动到slider上
4. 没有按下鼠标，但是还能滑动

### 期望结果

上述重现步骤第3、4步，没有按下鼠标，应该不能继续滑动

### 实际结果

上述重现步骤第3、4步，没有按下鼠标，但是还能继续滑动

### 浏览器版本

Chrome(127.0.6533.90)

### 系统版本

Windows 10

### Node版本

v18.20.1

### 补充说明

并没有特定的场景，官网的demo也有相同问题。

**Comment by uyarn** [comment]
fixed 1.8.0, thanks for @Jippp 🌹
