### ISSUE TITLE
[Form] 根据某个字段变化动态展示数据不支持上传组件

### ISSUE THREAD

**Issue by HeXavi8** [Tencent/tdesign-react#3043]
### tdesign-react 版本

1.7.9

### 重现链接

https://stackblitz.com/edit/react-m7ms5q?file=src%2Fdemo.tsx

### 重现步骤

在某些特定场景，修改某个字段值后更新新的字段选项，使用 shouldUpdate 修改 FormItem 的更新逻辑。
当子 FormItem 中组件的数据类型不同，数据变化之后，父FormItem无法切换，报错。
例如切换的子组件一个是 ColorPicker、一个是 Upload 的情况

未上传数据前可以切换
![Screenshot 2024-08-10 at 02 37 24](https://github.com/user-attachments/assets/07e80a5f-cca9-4f6d-a4e5-6958325af6da)

![Screenshot 2024-08-10 at 02 41 46](https://github.com/user-attachments/assets/9498f379-7a9a-4ef2-bb98-f5d17bd56f72)
上传数据
![Screenshot 2024-08-10 at 02 39 27](https://github.com/user-attachments/assets/06e1c23e-3d35-4660-a257-dcb6b74d8af3)
切换后报错
![Screenshot 2024-08-10 at 02 40 32](https://github.com/user-attachments/assets/0b6f5d95-7af9-41f9-bf9a-22df58bb586a)

### 期望结果

希望在某些特定场景，修改某个字段值后更新新的字段选项后，可以兼容不同数据类型的组件切换

**Comment by HaixingOoO** [comment]
你切换的时候给对应的FormItem不同的key来切换，要不React的渲染会认为是同一个元素，所以导致了这个问题
<img width="633" alt="image" src="https://github.com/user-attachments/assets/646e2bea-eadf-4b44-9176-499e39beb332">
