### ISSUE TITLE
[Empty] 默认图片受 TailwindCSS 重置样式影响无法居中，需要加一个强一点的居中约束

### ISSUE THREAD

**Issue by KwokKwok** [Tencent/tdesign-react#3062]
### tdesign-react 版本

 1.8.0

### 重现步骤

在一个安装 tailwind css 的项目中，使用 Empty 组件
因为 svg 会被默认重置为块级元素，导致组件的占位图不居中

### 期望结果

考虑 tailwind 的体量，应该在 Empty 组件的图片容器上加一个更有效的居中样式

### 实际结果

未居中

**Comment by KwokKwok** [comment]
可以通过给 `.t-empty__image` 加上 `display: flex; justify-content: center` 来更好的约束

**Comment by HaixingOoO** [comment]
是的，欢迎PR!!!

**Comment by KwokKwok** [comment]
ok, 我下午处理一下
