### ISSUE TITLE
[Loading] full screen loading can not close in official loading docs

### ISSUE THREAD

**Issue by Ashster** [Tencent/tdesign-react#3082]
### tdesign-react 版本

latest

### 重现链接

https://tdesign.tencent.com/react/components/loading

### 重现步骤

![image](https://github.com/user-attachments/assets/aa69f270-8f0c-41a1-bd1e-e6f3a54cc523)
![image](https://github.com/user-attachments/assets/2b936c93-719b-45a9-bb01-0cd0fba51b8a)

### 期望结果

可以像文档最下面的“服务端渲染”loading 示例一样，支持点击关闭

### 实际结果

loading fullscreen 体验之后关不掉，必须得回退网页

**Comment by uyarn** [comment]
fixed
