### ISSUE TITLE
[Statistic] Statistic 属性 className不起作用

### ISSUE THREAD

**Issue by qinbx** [Tencent/tdesign-react#3088]
### tdesign-react 版本

1.8.1

### 重现链接

https://stackblitz.com/edit/react-pjuthc?file=src%2Fdemo.tsx

### 重现步骤

https://tdesign.tencent.com/react/components/statistic?tab=api 
文档中有 className 属性

`<Statistic title="xxx" className="customClassName" value={82.76} unit="%" trend="decrease" />`
如上中的 `className="customClassName"` 不起使用。

### 期望结果

Statistic组件实例中会出现对应的className

### 实际结果

Statistic组件实例中未添加上对应的className

**Comment by uyarn** [comment]
fixed 1.9.0
