### ISSUE TITLE
[Tooltip]  建议在全局特性配置增加Tooltip组件属性的设置（比如theme属性）

### ISSUE THREAD

**Issue by qinbx** [Tencent/tdesign-react#3103]
### 这个功能解决了什么问题

想设置Tooltip组件的默认theme，在全局特性配置中没看到对应的设置项。
https://tdesign.tencent.com/react/global-configuration?tab=api

### 你建议的方案是什么

建议在全局特性配置增加Tooltip组件属性的设置（比如theme属性）

**Comment by uyarn** [comment]
这个加起来太多了，所有有theme的组件都可以配置theme，维护会很麻烦且目前看来并不是非常必须的。可以考虑在业务里封装一个需要的theme的组件然后每次都调用这个组件的。
如果后面这种需求增加很多我们再考虑增加吧
