### ISSUE TITLE
[Switch] label多于两个字的时，切换多了几次会展示不正常

### ISSUE THREAD

**Issue by suedar** [Tencent/tdesign-react#3123]
### tdesign-react 版本

1.7.8

### 实际结果

代码如下
``` js


  const renderContent = () => {
    if (value) {
      return (
        <DateRangePicker
          format="yyyy-MM-dd HH:mm:ss"
        />
      );
    }

    return <Select options={TimeRangeOptions}></Select>;
  };

  return (
    <div className="time-range-picker">
      <Switch
        size="large"
        label={['范围选择框', '时间选择框']}
        onChange={(v) => {
          setValue(v);
        }}
      />
      {renderContent()}
    </div>
  );

```

https://github.com/user-attachments/assets/3eaf8012-dec1-401e-abbf-57c0df87f480

（请忽略后半部分的toast）

请参考视频，点多几次会展示不正常

**Comment by uyarn** [comment]
这个录屏好像没看出来展示不正常呀

**Comment by suedar** [comment]
> ```js
> 时间选择框
> ```

正常未选中应该显示`时间选择框`的，现在只显示了`选择`

**Comment by uyarn** [comment]
> ```js
>   const renderContent = () => {
>     if (value) {
>       return (
>         <DateRangePicker
>           format="yyyy-MM-dd HH:mm:ss"
>         />
>       );
>     }
> 
>     return <Select options={TimeRangeOptions}></Select>;
>   };
> 
>   return (
>     <div className="time-range-picker">
>       <Switch
>         size="large"
>         label={['范围选择框', '时间选择框']}
>         onChange={(v) => {
>           setValue(v);
>         }}
>       />
>       {renderContent()}
>     </div>
>   );
> ```

懂了 但是我们这边没有复现 https://stackblitz.com/edit/react-lrhfhc-gjmicz?file=src%2Fdemo.tsx 能否在这里复现这个现象 看起来切换是正常的 或者

**Comment by uyarn** [comment]
https://github.com/user-attachments/assets/1392f2bb-bf07-4c3d-8deb-4fd6b7af61ac

**Comment by suedar** [comment]
无法复现了 先close了 以后发现再说～
