### ISSUE TITLE
[Tabs] 激活的选项卡底部横线没有实时跟随选项卡名称的内容的宽度自动变化

### ISSUE THREAD

**Issue by Isbutton** [Tencent/tdesign-react#3132]
### tdesign-react 版本

^1.7.6

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-5sq2fg?file=%2Fsrc%2Fdemo.jsx

https://github.com/user-attachments/assets/bc8efd0b-58e6-4d0e-952f-ff0e805176dd

### 重现步骤

初始化Tabs后，延迟两秒改变激活的选项卡名称。

### 期望结果

激活的选项卡名称宽度变化后，底部横线宽度随之变化。

### 实际结果

激活的选项卡名称宽度变化后，底部横线宽度没有变化。

### 补充说明

看到之前有个相关的issue：https://github.com/Tencent/tdesign-react/issues/1583
已经解决关闭了。但是我这个情况下依旧有问题。

**Comment by uyarn** [comment]
fixed 1.9.2
