### ISSUE TITLE
[Typography] 中英文Ellipsis表现不一致，中文多行 row 属性不生效

### ISSUE THREAD

**Issue by chungguo** [Tencent/tdesign-react#3152]
### 重现链接
https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-jcz38l

### 重现步骤
无需操作

### 期望结果
中英文表现一致

### 实际结果
中文单行显示，英文符合预期

| Environment | Info |
|---|---|
| 相关版本 | 1.9.2 |
| 框架版本 / 基础库版本 | React(18.2.0) |
| 系统、浏览器 | MacOS(15.0.1) Chrome(129.0.6668.101) |
| Node版本 |  |

**Comment by huangchen1031** [comment]
看起来是`Truncate.tsx`里面`getLines`时用了`line.split(' ')`气氛字符串用来计算内容宽度，如果改成`line.split('')`是不是就能兼容汉字了~

**Comment by chungguo** [comment]
> 看起来是`Truncate.tsx`里面`getLines`时用了`line.split(' ')`切分字符串用来计算内容宽度，如果改成`line.split('')`是不是就能兼容汉字了~

这样英文就会被按字母切割，而不是单词，延续Truncate的实现思路的话，需要重新实现分字算法，兼容甚至可能存在的中英文混排

**Comment by HaixingOoO** [comment]
> 看起来是`Truncate.tsx`里面`getLines`时用了`line.split(' ')`切分字符串用来计算内容宽度，如果改成`line.split('')`是不是就能兼容汉字了~

是的，也要join('')，測試過沒問題了

**Comment by huangchen1031** [comment]
> > 看起来是`Truncate.tsx`里面`getLines`时用了`line.split(' ')`切分字符串用来计算内容宽度，如果改成`line.split('')`是不是就能兼容汉字了~
> 
> 这样英文就会被按字母切割，而不是单词，延续Truncate的实现思路的话，需要重新实现分字算法，兼容甚至可能存在的中英文混排

考虑国际化的话不同文字的逻辑还不一样，想想都难搞~

**Comment by huangchen1031** [comment]
> > 看起来是`Truncate.tsx`里面`getLines`时用了`line.split(' ')`切分字符串用来计算内容宽度，如果改成`line.split('')`是不是就能兼容汉字了~
> 
> 是的，也要join('')，測試過沒問題了

大佬666

**Comment by uyarn** [comment]
fixed 1.9.3
