### ISSUE TITLE
[SelectInput] SelectInput的valueDIsplay问题

### ISSUE THREAD

**Issue by chenkang-noob** [Tencent/tdesign-react#3160]
### tdesign-react 版本

1.9.2

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-38gvns

### 重现步骤

在多选的情况下，当SelectInput的value出现一个不在选项内的值时。此时valueDisplay方法中的value参数会表现为对应值的label，而不是对应值的value。不确定这是bug还是feature
<img width="1555" alt="企业微信截图_2eb2caf0-0088-4c1b-bdf3-c61ee235011d" src="https://github.com/user-attachments/assets/8dac1b72-a026-4f4e-8f8d-c28885e56955">

### 期望结果

我直觉上觉得应该是表现为value值的

### 实际结果

我直觉上觉得应该是表现为label值的

**Comment by HaixingOoO** [comment]
你觉得上面选中在options里的，为什么也现实label的值，因为label值是ui显示的内容，value是内部用到的值，所以你看到label才是正常的
