### ISSUE TITLE
[Popup] Popup组件设置popperOptions的offset属性不生效

### ISSUE THREAD

**Issue by 2ue** [Tencent/tdesign-react#3184]
### tdesign-react 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/react-f7oexg?file=src%2Fdemo.tsx

### 重现步骤

鼠标hover到按钮上

### 期望结果

期望按照设置的offset进行偏移

### 实际结果

使用按照设置的offset值便宜

**Comment by ZHUBoer** [comment]
https://popper.js.org/docs/v2/tutorial/#offset
<img width="819" alt="image" src="https://github.com/user-attachments/assets/e8fcd6f8-3f51-4444-8a4c-fd2e53eed378">
但我根据这个配置去写，也没效果。
```
import React from 'react';
import { Button, Popup } from 'tdesign-react';

export default function BasicUsage() {
  return (
    <Popup
      trigger="click"
      popperOptions={{
        // offset: [-40, -100],
        name: 'offset',
        options: {
          offset: [-40, -100], // 设置偏移量
        },
      }}
      showArrow
      content="这是一个弹出框"
    >
      <Button>Hover me</Button>
    </Popup>
  );
}
```

**Comment by HaixingOoO** [comment]
![image](https://github.com/user-attachments/assets/c3dac321-2b88-4d77-aa77-f398e023897e)
![image](https://github.com/user-attachments/assets/8c3f4116-5e29-4625-b651-c1926a27fa10)

@ZHUBoer 你传的值少了，测试没问题的

**Comment by uyarn** [comment]
@HaixingOoO 也许我们应该增加这个类似的demo

**Comment by 2ue** [comment]
> ![image](https://private-user-images.githubusercontent.com/65376724/385122541-c3dac321-2b88-4d77-aa77-f398e023897e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODY2NDIsIm5iZiI6MTczMTQ4NjM0MiwicGF0aCI6Ii82NTM3NjcyNC8zODUxMjI1NDEtYzNkYWMzMjEtMmI4OC00ZDc3LWFhNzctZjM5OGUwMjM4OTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA4MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNGUwNzViZDUwMzFjMmRmMDcxODExMjQ5YzFhMjQ2MTk0ODljNjY3NjZiYWRkMmE2YmFlYTA2NDM1NmI0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bgox9ytVTxmYazB1vZs0OH_uHh1sYLEFCAoSNSuyS9M) ![image](https://private-user-images.githubusercontent.com/65376724/385122486-8c3f4116-5e29-4625-b651-c1926a27fa10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODY2NDIsIm5iZiI6MTczMTQ4NjM0MiwicGF0aCI6Ii82NTM3NjcyNC8zODUxMjI0ODYtOGMzZjQxMTYtNWUyOS00NjI1LWI2NTEtYzE5MjZhMjdmYTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA4MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDJhN2QxYzdjZWMwNzBjNjhhOWRjNjJhM2FiMWI2NGI1MWRiNjZiZmU1ZDc2NGNiYmFkNDNkZTI0MGI1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CPoqQemySPpObB1FOM8_KrRb-TSg-fqlCTDd9KQRzOU)
> 
> @ZHUBoer 你传的值少了，测试没问题的

感谢，按照这个配置OK了
