### ISSUE TITLE
TreeSelect props.treeProps.valueMode no work

### ISSUE THREAD

**Issue by qiaoqiaowang** [Tencent/tdesign-react#3195]
https://codesandbox.io/p/sandbox/tdesign-react-demo-forked-4npd3m?file=%2Fsrc%2Fdemo.tsx%3A52%2C22
单选的时候，valueMode为onlyLeaf，但是还是可以选中父节点

**Comment by uyarn** [comment]
这个API不是说不可以选中，是返回值里面只返回子节点的值 可以参考这个示例 https://tdesign.tencent.com/react/components/tree#%E5%8F%AF%E9%80%89%E6%8B%A9%E7%9A%84%E6%A0%91
打开控制台体验
