### ISSUE TITLE
[Table] Table组件使用filter功能时存在问题

### ISSUE THREAD

**Issue by 2ue** [Tencent/tdesign-react#3196]
### tdesign-react 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/react-lnjtpr?file=src%2Fdemo.tsx

### 重现步骤

Table组件中column启用fiter功能，并且TableProps上绑定了受控filterValue属性，如果绑定的filterValue属性包含了null值则会报错，导致页面白屏，复现步骤：

1、下拉选择随意选择一个平台，然后点击clear图标清除值
2、点击搜索

打断点发现，Select单选组件clear后返回的值数null，导致table组件的useFilter hooks中的isFilterValueExist方法报错，因为其对Object的判断存在问题，其内实现的IsObject方法不能判断出null导致Object.keys(value).length报错。

并且还发现其他问题：如果值为字符串undefined和字符串null会导致误判，误判代码：

```ts
['null', '', 'undefined'].includes(String(value))
```

<img width="814" alt="image" src="https://github.com/user-attachments/assets/36e8a0d8-0f08-42d6-93a2-f073356027fb">

建议优化代码：
``` ts
function isFilterValueExist(value: any) {
  const isArrayTrue = value instanceof Array && value.length;
  const isObject = typeof value === 'object' && !(value instanceof Array);
  const isObjectTrue = isObject && Object.keys(value || {}).length;
  return isArrayTrue || isObjectTrue || ![null, '', undefined].includes(value);
}
```

相关pr：
https://github.com/Tencent/tdesign-react/pull/3197

### 期望结果

期望能正常处理null，字符串null和字符串undefined

### 实际结果

在处理null时会报错

**Comment by uyarn** [comment]
"并且还发现其他问题：如果值为字符串undefined和字符串null会导致误判，误判代码"
看原来的逻辑，是先把value都string一遍 所以是'undefined'和'null' 为什么会是误判呢？

**Comment by uyarn** [comment]
published 1.10.1
