### ISSUE TITLE
Popup 组件 使用 PopupPlugin 给元素配置hover效果时，表现异常

### ISSUE THREAD

**Issue by sevencai** [Tencent/tdesign-react#3220]
如下图所示，在官方提供的demo示例中，使用popupplugin弹出时

若在组件初始化时调用popupplugin，且trigger的类型是hover时，组件表现异常

<img width="1299" alt="image" src="https://github.com/user-attachments/assets/cfbe2a84-4f80-462e-b424-31545080d3ff">

具体异常的点在：

1. 一进入就展示了popup内容
2. hover时，无法展示popup内容

复现地址：https://stackblitz.com/edit/react-o3zkpk?file=src%2Fdemo.tsx,node_modules%2Ftdesign-react%2Fes%2Fpopup%2Findex.d.ts,node_modules%2Ftdesign-react%2Fes%2Fpopup%2FPopupPlugin.d.ts,node_modules%2Ftdesign-react%2Fes%2Fpopup%2Ftype.d.ts

**Comment by uyarn** [comment]
插件形式下trigger这个属性是不起作用的 如果需要在hover时出现 就在mouseenter事件回调使用popupplugin就可以的
