### ISSUE TITLE
[Tooltip] TooltipLite placement="mouse" 模式下，坐标可以计算上 clientY 吗？

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#3225]
### 这个功能解决了什么问题

`mouse` 模式下，只计算了横坐标，没有计算纵坐标，导致 `tooltip` 只能展示在 `node` 的底部，并没有真正的做到模拟 `title` 的效果
<img width="500" alt="Clipboard_Screenshot_1732522843" src="https://github.com/user-attachments/assets/d9e96639-1a5f-4deb-bc26-c53678a95534">

### 你建议的方案是什么

加上 `clientY` 的计算，最好可以加上 `offset` 来控制偏移量

**Comment by uyarn** [comment]
native title 是这个样子 现在是想加clientY 变成什么样子？@moecasts
<img width="803" alt="WeChatWorkScreenshot_2cfd4749-09ae-4be1-a0e0-2894f631d842" src="https://github.com/user-attachments/assets/c2e4676f-10e9-48ea-afec-8f731be4f7ec">

**Comment by moecasts** [comment]
@uyarn 原生的也是有算上 `clientY` 的，是跟在鼠标旁边，而不是 node 旁边
<img width="1314" alt="Clipboard_Screenshot_1733110153" src="https://github.com/user-attachments/assets/331d85b1-9c87-4eb6-9dab-0eecfd77968b">
