### ISSUE TITLE
[Menu] 点击MenuItem区域外的地方，会导致SubMenu收起来

### ISSUE THREAD

**Issue by kajweb** [Tencent/tdesign-react#3237]
### tdesign-react 版本

1.10.0

### 重现链接

https://stackblitz.com/edit/tdesign-241128-menu?file=src%2Fdemo.tsx

### 重现步骤

![image](https://github.com/user-attachments/assets/8ec4eb65-87f8-483a-af93-e24404016b67)

点击MenuItem，会导致SubMenu收起来，必现

### 期望结果

-

### 实际结果

-

### 补充说明

希望能为低版本提供规避方案（如提供全局css）

**Comment by huangchen1031** [comment]
onClick写在了li标签上，需要改到title的div上才能解决

**Comment by uyarn** [comment]
fixed 1.10.2
