### ISSUE TITLE
[全局配置]GlobalConfigProvider的attach 为什么只对Dialog，Select等生效，对于Drawer以及插件类MessagePlugin，DialogPlugin不生效

### ISSUE THREAD

**Issue by EOMHH** [Tencent/tdesign-react#3266]
### tdesign-react 版本

1.10.1

### 重现链接

https://tdesign.tencent.com/react/global-configuration?tab=api

### 重现步骤

使用全局配置 attach
<img width="419" alt="image" src="https://github.com/user-attachments/assets/5733888b-16be-4ef9-9d27-76934d039825">

### 期望结果

Drawer可挂载到全局配置的节点

### 实际结果

Drawer仍然在body上
<img width="399" alt="image" src="https://github.com/user-attachments/assets/38e39014-47a3-4520-b5cb-2f57b47cabd6">

### 框架版本

17.0.1

### 浏览器版本

131.0.6778.86

### 系统版本

14.6.1

### Node版本

15.9.0

**Comment by huangchen1031** [comment]
因为全局的attach只支持了`Dialog`、`ImageViewer`和`Popup`，至于Plugin的用法那就是另一个故事了。。。
@HaixingOoO 大佬看看，`useAttach`是不是在`Portal`里面调的话更通用一些。

**Comment by uyarn** [comment]
drawer会支持attach的全局配置，messagePlugin涉及改动较大，后续再讨论支持

**Comment by uyarn** [comment]
support drawer global attach config 1.10.2
