### ISSUE TITLE
[DatePicker] 高度/对齐问题

### ISSUE THREAD

**Issue by qinbx** [Tencent/tdesign-react#3273]
### tdesign-react 版本

1.10.1

### 重现链接

https://stackblitz.com/edit/react-nobq91da?file=src%2Fdemo.tsx

### 重现步骤

访问重现链接后，可看到日期输入框有垂直方向无法对齐问题，经群里HaixingOoO反馈说是日期框组件里的一个子元素div.t-input__prefix应该去掉。现反馈过来，望解决。

### 期望结果

期望，日期框，可以跟同行的文字、其它日期范围框可垂直对齐。

**Comment by uyarn** [comment]
fixed 1.10.2
