### ISSUE TITLE
Table 组件系列问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#329]
![image](https://user-images.githubusercontent.com/11605702/152086744-2bb2d5e7-4b75-47e3-9e95-88a044dfc131.png)
![image](https://user-images.githubusercontent.com/11605702/152086829-35e86628-731f-4e84-81f6-4ce0a4772b31.png)
![image](https://user-images.githubusercontent.com/11605702/152086860-7314fddb-28dc-4183-8856-9419bd5a0991.png)
![image](https://user-images.githubusercontent.com/11605702/152086889-41c0df5c-9db3-4e68-94b1-76e3a82a4518.png)
![image](https://user-images.githubusercontent.com/11605702/152086933-2dd40ea7-5731-48c0-9c07-f99b28e5497b.png)
![image](https://user-images.githubusercontent.com/11605702/152086981-9f8c581d-2997-4971-8faf-dd85b59d7e5c.png)

**Comment by HQ-Lin** [comment]
@yunfeic 跟进一下
