### ISSUE TITLE
[Form] “字段联动的表单”这里的 CodeSandBox 案例无法打开

### ISSUE THREAD

**Issue by libo1106** [Tencent/tdesign-react#3296]
### tdesign-react 版本

1.10.2

### 重现链接

https://codesandbox.io/p/sandbox/j8vpvp?file=%2Fsrc%2Fdemo.tsx%3A2%2C25

### 重现步骤

https://tdesign.tencent.com/react/components/form#%E5%AD%97%E6%AE%B5%E8%81%94%E5%8A%A8%E7%9A%84%E8%A1%A8%E5%8D%95

这里的两个 demo，都无法打开

<img width="1128" alt="Clipboard_Screenshot_1735022538" src="https://github.com/user-attachments/assets/d6ab9f12-5bf2-43bd-b1d1-a43bc13cfab4" />

### 实际结果

<img width="816" alt="Clipboard_Screenshot_1735022566" src="https://github.com/user-attachments/assets/e6da1e29-8d83-4dd4-82db-7cf0a1d6d1c6" />

**Comment by uyarn** [comment]
已修复
