### ISSUE TITLE
【Table】滚动条样式、固定列错乱

### ISSUE THREAD

**Issue by 2992362310** [Tencent/tdesign-react#334]
问题复现
https://codesandbox.io/s/tdesign-react-demo-forked-5x6gu?file=/src/demo.jsx

**Comment by HQ-Lin** [comment]
![image](https://user-images.githubusercontent.com/24469546/153131326-9f1aace9-6500-4d2b-a95c-2adccf536542.png)
![image](https://user-images.githubusercontent.com/24469546/153131353-118bac32-b957-4cdf-8726-0a40ea4f13d9.png)
横向滚动时漏了多选框那一列

**Comment by HQ-Lin** [comment]
0.25.2 fixed
https://codesandbox.io/s/tdesign-react-demo-forked-z0qncv?file=/src/demo.jsx
