### ISSUE TITLE
使用select组件的multiple多选功能时，如文字较多会使得选项分行

### ISSUE THREAD

**Issue by GrinZero** [Tencent/tdesign-react#337]
使用select组件的multiple多选功能时，如文字较多会使得选项分行。
此处的代码是在select外方固定了长度
![image](https://user-images.githubusercontent.com/70185413/153194429-a8f06520-8eac-48c5-bc77-69e82d0858ee.png)
我不得不思考这是特性还是bug
![image](https://user-images.githubusercontent.com/70185413/153193843-b33bb2ad-ec1c-46cf-a131-e6724edeab97.png)

**Comment by carolin913** [comment]
你好，你说的这个问题是指下面的 +3么，这个是因为你设置了minCollapsedNum，选中超过2个选项，就会以数字形式折叠，还有长度超过设定的400px会换行这也是正常的哈，如果有其他问题可以继续反馈

**Comment by carolin913** [comment]
我试了下这个select在选项中，如果文字过长，会超出外部给定的宽度限制，这里应该是有问题的
![image](https://user-images.githubusercontent.com/2638568/153330506-123195b1-cf2f-4c07-a9cb-c86b9b75701e.png)

**Comment by yangguansen** [comment]
![image](https://user-images.githubusercontent.com/24775952/153331022-6589e91f-d0fa-4cf7-bbde-49f79b6492aa.png)
antdesign超出一行也是会换行的，这里换行是没问题的，如果你想一行显示，那就要提个feature了

**Comment by GrinZero** [comment]
OHHHHH OK
