### ISSUE TITLE
【help】_common下的文件怎么生成？

### ISSUE THREAD

**Issue by yangguansen** [Tencent/tdesign-react#338]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

MAC Google

**Describe the bug**
1.下载代码；
2.npm install
3.npm run dev
报错Failed to resolve import "../_common/style/web/_reset.less" from "../src/style/index.js". Does the file exist?

_common下的文件没有下载下来？这个文件夹里的内容是怎么生成的？

**Comment by HQ-Lin** [comment]
如果你只是 git clone 不加参数的话是需要手动初始化 _common 子仓库的
```bash
git submodule init
git submodule update
```

贡献指南中推荐用 `git clone --recurse-submodules https://github.com/Tencent/tdesign-react.git` 方式是会自动帮你拉取子仓库的代码，具体的可以查看 [贡献文档](https://github.com/Tencent/tdesign-react/blob/develop/CONTRIBUTING.md)

**Comment by yangguansen** [comment]
完善了README文档指引,期望参与issue修复
