### ISSUE TITLE
bug: upload组件theme="image"，并使用requestMethod返回上传失败后，显示为预览图片

### ISSUE THREAD

**Issue by GrinZero** [Tencent/tdesign-react#353]
bug: upload组件theme="image"，并使用requestMethod返回上传失败后，显示为预览图片；

https://codesandbox.io/s/tdesign-react-demo-forked-onz76?file=/src/demo.jsx

**Comment by wookaoer** [comment]
我看下

**Comment by HQ-Lin** [comment]
0.25.0 已修复
