### ISSUE TITLE
【Popup】expandAnimation为true时，可变高度内容展示错误

### ISSUE THREAD

**Issue by Hoofoo-WHU** [Tencent/tdesign-react#355]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**
无关

**Describe the bug**
expandAnimation为true时，弹框不会随内容高度变化且不会出现滚动条

**Additional context**

**Comment by HQ-Lin** [comment]
能不能提供一个 codesanbox 复现链接方便排查

**Comment by Hoofoo-WHU** [comment]
> 能不能提供一个 codesanbox 复现链接方便排查

不好意思，触发路径有点错误，已更新issue，demo如下
https://codesandbox.io/s/tdesign-react-demo-forked-is85c?file=/src/demo.jsx

**Comment by HQ-Lin** [comment]
> 

感谢反馈，确实有问题，我排查下

**Comment by HQ-Lin** [comment]
之前 `popup` 展开动画使用 `maxHeight` 实现需要动态计算内容高度，刚好这两天改成了 `clip-path` 来实现内容就完全有子节点撑开了，我本地最新的代码跑了你的示例是ok的
https://github.com/Tencent/tdesign-react/pull/348

**Comment by HQ-Lin** [comment]
0.25.0 已修复
https://codesandbox.io/s/tdesign-react-demo-forked-zi90x6?file=/src/demo.jsx
