### ISSUE TITLE
Slider 滑块滑动的时候，数字提示框没有随滑块一起改变位置

### ISSUE THREAD

**Issue by xia7187** [Tencent/tdesign-react#369]
### 重现链接
https://tdesign.tencent.com/react/components/slider

### 重现步骤
滑块滑动的时候，数字提示框没有随滑块一起改变位置
<img width="916" alt="image" src="https://user-images.githubusercontent.com/68138709/154643754-1425ea3e-f18e-41d2-8699-a6e555aaca6c.png">

### 期望结果
滑块滑动的时候，数字提示框和滑块一起移动

### 实际结果
滑块滑动的时候，数字提示框没有随滑块一起改变位置

| Environment | Info |
|---|---|
| 相关版本 | 0.25.0 |
| 框架版本 / 基础库版本 | react |
| 系统、浏览器 | macos |
| Node版本 |  |

**Comment by carolin913** [comment]
已复现，感谢反馈，会尽快修复

**Comment by HQ-Lin** [comment]
0.25.2
fixed
