### ISSUE TITLE
[官网] API 文档解析文档，关键词 < 和 >

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#379]
### 重现链接
-

### 重现步骤
<img width="921" alt="wecom-temp-a5efec986be9e31aaf8f5cbab8485391" src="https://user-images.githubusercontent.com/11605702/155141436-3ea75ebc-3173-441f-9908-4e0006c8c4a1.png">

### 期望结果
-

### 实际结果
-

| Environment | Info |
|---|---|
| 相关版本 | 0.25.1 |
| 框架版本 / 基础库版本 | React17 |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
fixed
