### ISSUE TITLE
Dialog组件在移动端的宽度适配问题

### ISSUE THREAD

**Issue by tisou1** [Tencent/tdesign-react#396]
### 重现链接
https://codesandbox.io/s/laughing-hill-mgndu9?file=/src/App.js

### 重现步骤
点击按钮弹出Dialog, 然后拖动减少内置浏览器的宽度,Dialog由于没有适配,宽度会溢出.

### 期望结果
添加宽度小于DIalog默认宽度的适配(如:max-width: calc(100vw - 32px))

### 实际结果
没有max-width属性.

### 补充说明
在做响应式网页的时候遇到.

| Environment | Info |
|---|---|
| 相关版本 | 0.25.2 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/serene-meninsky-zd9cft?file=/src/App.js:0-658
其实你也可以自己去更改 `style` 样式限制 `maxWidth` 展示

我们会讨论下这个需求，因为这个组件库主要是面向 PC 端的，默认的宽度是 540px 一般来说是够用的，如果组件库内置了 `max-width` 会导致有些用户设置 `width` 权重不够高也需要设置 `max-width` 复写，所以可能开放 `style` 给使用者根据具体情况改造会比较合适。
如果要在移动端使用 TDesign 还会有其他组件尺寸适配，后续我们还会推出 `react-mobile`，建议移动端使用那个组件库
