### ISSUE TITLE
【Table 表格】增加 JSX 的写法

### ISSUE THREAD

**Issue by ZZZCNY** [Tencent/tdesign-react#400]
### 这个功能解决了什么问题
更符合 React 习惯，方便理解操纵数据的过程。

### 你建议的方案是什么？
可参考 https://ant.design/components/table-cn/#components-table-demo-jsx

**Comment by chaishi** [comment]
没有看明白这个需求的意思

**Comment by ZZZCNY** [comment]
```js
<Table data={}>
  <Column />
  <Column />
  <Column />
</Table>
```

支持使用上面这种写法，而不是只有：

```js
<Table columns={} data={} />
```

**Comment by HQ-Lin** [comment]
react 因为函数作用域的原因可能 jsx 写法会比 props 配置方式更方便点，这版本会支持下
