### ISSUE TITLE
【Table 表格】API介绍是否缺少部分信息

### ISSUE THREAD

**Issue by ZZZCNY** [Tencent/tdesign-react#403]
![image](https://user-images.githubusercontent.com/59002875/156122566-0ddb0a7a-6476-478f-bea4-7f46e74f1b62.png)

```js
cell(record)
```

`record` 是什么数据呢？API 里没看到，另一个 `row` 有 API 介绍，两者相似吗？

还是说 API 中的 TableRowState 指的不是自定义渲染的 Function 能获取的数据？

**Comment by chaishi** [comment]
就是这些参数
<img width="877" alt="image" src="https://user-images.githubusercontent.com/11605702/156123132-3d3a0dac-70d3-4c19-9918-2f52899b2640.png">

**Comment by ZZZCNY** [comment]
不好意思，我有点瞎🥲
