### ISSUE TITLE
[Form.FormItem]: initialData能否支持Array类型，目前使用下来仅是string | boolean的话有些不太够用

### ISSUE THREAD

**Issue by liuyurong-g** [Tencent/tdesign-react#405]
### 这个功能解决了什么问题
支持自定义组件使用Array类型进行值传递时的defaultValue 设置

### 你建议的方案是什么？
initialData接收多种类型

**Comment by chaishi** [comment]
收到，我们支持一下

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/angular-wquuby?file=src%2Fdemo.jsx
组件代码中是支持的，暴露的type 类型有问题，我们处理下

**Comment by liuyurong-g** [comment]
好的，感谢

**Comment by HQ-Lin** [comment]
0.26.0 fixed
