### ISSUE TITLE
[Table] Firefox下表格样式无法正常渲然

### ISSUE THREAD

**Issue by liuyurong-g** [Tencent/tdesign-react#412]
### 重现链接
https://codesandbox.io/s/vigorous-dawn-plo11w?file=/package.json

### 重现步骤
打开codesandbox即可复现

### 期望结果
保持不同浏览器渲染的一致性

### 实际结果
Chrome能正常渲染，Firefox需要给其中一列添加fixed属性才能渲染出分割线

| Environment | Info |
|---|---|
| 相关版本 | 0.25.2 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | Firefox(97.0.1) |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
chrome:
<img width="962" alt="企业微信截图_bda9800c-219b-4c84-a36f-d803b29fb15e" src="https://user-images.githubusercontent.com/24469546/156304013-c18a7956-5384-4475-bef6-32c6b614b71e.png">

firefox:
<img width="1056" alt="企业微信截图_a9188086-cd42-493f-b7dc-b9cd9c43540b" src="https://user-images.githubusercontent.com/24469546/156304020-f927605b-c11e-435e-b7a9-650186c6d898.png">

火狐的background-clip 渲染有差异。。我们看下怎么兼容
