### ISSUE TITLE
[Input] autocomplete export出来的TS类型是否可以考虑支持其他HTML autocomplete 的属性值

### ISSUE THREAD

**Issue by liuyurong-g** [Tencent/tdesign-react#414]
### 这个功能解决了什么问题
解决因为浏览器文本框已保存历史信息自动回填的问题
实际上现阶段仅靠添加autocomplete="off"并不能完美阻止浏览器的回填，存在需要定义autocomplete='new-password'或其他值的现实需求

### 你建议的方案是什么？
将autocomplete 的类型声明为autocomplete?: string

**Comment by chaishi** [comment]
可以

**Comment by HQ-Lin** [comment]
0.26.0 fixed
