### ISSUE TITLE
[Alert] 添加自定义className之后，原有组件样式会丢失

### ISSUE THREAD

**Issue by liuyurong-g** [Tencent/tdesign-react#424]
### 重现链接
https://codesandbox.io/s/heuristic-tereshkova-cij6hy?file=/src/App.js

### 重现步骤
无特别步骤

### 期望结果
修复问题并能支持外部className

### 实际结果
支持外部className，但会丢失原有样式

| Environment | Info |
|---|---|
| 相关版本 | 0.25.2 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
收到，今日正好发版本会一起处理

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/damp-paper-obtgvw?file=/src/App.js
