### ISSUE TITLE
[Cascader] 级联组件在多选状态下点击后会被关闭

### ISSUE THREAD

**Issue by GrinZero** [Tencent/tdesign-react#428]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-b3n7bk?file=/src/demo.jsx

### 重现步骤
1. 点击任意选项可发现选项重复【新发现问题】，点击父项选择框选定后清除所有选项
2.重新点击级联组件，在子级选择，会发现明明是多选的组件，点击之后却直接关闭了

### 期望结果
1. 多选的情况下，点击子级选项或者父级选项不应该直接关闭

### 实际结果
1. 多选的情况下，点击子级选项或者父级选项后会被直接关闭

### 补充说明
主要是版本兼容问题，希望做一下兼容；

| Environment | Info |
|---|---|
| 相关版本 | 0.26.0 |
| 框架版本 / 基础库版本 | React(16.3.1) |
| 系统、浏览器 | MacOs(12)\Chrome(99.0.4844.51) |
| Node版本 | 17.3.1 |

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-c0g6ks?file=/src/demo.jsx
在 react 17又表现正常。。我们排查下

**Comment by uyarn** [comment]
已在0.27修复

**Comment by GrinZero** [comment]
亲...看了一下，问题仍然存在，这里的重复渲染是一个问题，其次是「会发现明明是多选的组件，点击之后却直接关闭了」https://codesandbox.io/s/tdesign-react-demo-forked-b3n7bk?file=/src/demo.jsx

**Comment by HQ-Lin** [comment]
定位到问题了，react 16 的冒泡阻止方式有问题，今天处理下

**Comment by GrinZero** [comment]
👍 可以的

**Comment by HQ-Lin** [comment]
React 16 及以下都是将事件代理到 document节点的，当触发的时候已经到document了，所以绑定在document上的事件也阻止不了，只能通过阻止兄弟事件触发

React 17是将事件代理到 rootElement 的也就是 `<div id="root" />`，所以正常阻止冒泡就可以了

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/angular-koupzv?file=package.json
0.27.1 fixed
