### ISSUE TITLE
[Layout]使用Layout配合Menu进行布局时，菜单缩放但是Aside没有缩放

### ISSUE THREAD

**Issue by zhuchao666** [Tencent/tdesign-react#439]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-v1wsy5?file=/src/demo.jsx:0-3070

### 重现步骤
选择菜单缩放时，菜单正常缩放但是侧边栏没有进行缩放

### 期望结果
侧边栏应该与菜单同时缩放与展开

### 实际结果
侧边栏没有与菜单同步缩放与展开

| Environment | Info |
|---|---|
| 相关版本 | 0.26.0 |
| 框架版本 / 基础库版本 | React（17.0.2） |
| 系统、浏览器 | MacOS 11.4. chrome 99.0.4844.51 |
| Node版本 |  |

**Comment by zhuchao666** [comment]
我现有的解决方案是通过组件通信在menu放缩与展开时控制aside的宽度，如果说这是你们原本设计的思路的话，能否在Layout组件的case中提出这个方案呢？不然我以为会是bug

**Comment by HQ-Lin** [comment]
emm 从组件角度来说 Aside 与 menu 并无相关联，正常情况下是需要业务在 menu 收起事件中处理 Aside的宽度，组件层面不好去处理的也不应该处理，我在demo中体现一下吧
