### ISSUE TITLE
开发指引走不通

### ISSUE THREAD

**Issue by LisaIsCoding** [Tencent/tdesign-react#448]
### 重现链接
[https://github.com/Tencent/tdesign-react/blob/develop/CONTRIBUTING.md](https://github.com/Tencent/tdesign-react/blob/develop/CONTRIBUTING.md)

### 重现步骤
```shell
git clone --recurse-submodules https://github.com/Tencent/tdesign-react.git
cd tdesign-react
npm i
npm run dev
```

### 期望结果
能运行

### 实际结果
报错
```shell
[plugin:vite:import-analysis] Failed to resolve import "../_common/style/web/_reset.less" from "../src/style/index.js". Does the file exist?
```
> 
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/101237384/157831709-2b9a5c01-6f9d-4114-b511-94bfe8ee1cc7.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.26.0 |
| 框架版本 / 基础库版本 | React |
| 系统、浏览器 | macOS Big Sur 11.6.5, 98.0.4758.109 (Official Build) (x86_64)  |
| Node版本 | 16.13.2 |

**Comment by LisaIsCoding** [comment]
几个小疑问

1. 需要先配置 ssh 吗？
2.

**Comment by LisaIsCoding** [comment]
几个小疑问

1. 需要先配置 ssh 吗
2. 不配置 ssh 的话，是这样吗
    ```shell
    git clone --recurse-submodules https://github.com/Tencent/tdesign-react.git
    cd tdesign-react
    git submodule init
    git submodule update 
    npm i
    npm run dev
    ```
3. 为什么要用 git 子模块呀，我谷歌了一下，很少看到推荐用这个的都觉得用着特麻烦很难用

**Comment by LisaIsCoding** [comment]
> 2. 不配置 ssh 的话，是这样吗
>    ```shell
>    git clone --recurse-submodules https://github.com/Tencent/tdesign-react.git
>    cd tdesign-react
>    git submodule init
>    git submodule update 
>    npm i
>    npm run dev
>    ```

我试着运行【2】，得到：
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/101237384/157831201-cea29e1c-366a-474e-a278-23738e6459c7.png">

**Comment by aouos** [comment]
需要配置 ssh、使用的是 ssh 协议、字模块没有拉取下来运行项目是会报错的，这块用字模块将公共的抽离出去了，其他框架版本组件库公用

**Comment by LisaIsCoding** [comment]
还是不行哎，还差什么前置配置吗？

报错说 `.git can't be found`

> <img width="1309" alt="image" src="https://user-images.githubusercontent.com/101237384/158095509-1c5e38aa-8aee-4fed-85be-943a73528319.png">

但我检查了下是有的

> <img width="1252" alt="image" src="https://user-images.githubusercontent.com/101237384/158095591-8d484045-71a8-410f-8ec7-080a639f59d8.png">

**Comment by HQ-Lin** [comment]
https://docs.github.com/cn/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
设置一下github 的ssh key吧

**Comment by LisaIsCoding** [comment]
解决了，之前配置得有问题。Thx!

**Comment by HQ-Lin** [comment]
我也把 submodule 改成 https 拉取方式吧，好多人不怎么配置 ssh key
