### ISSUE TITLE
[Slider]label如何设置才能动态获取当前value

### ISSUE THREAD

**Issue by looc00** [Tencent/tdesign-react#467]
### tdesign-react 版本

0.26.0

### 重现链接

/

### 重现步骤

![image](https://user-images.githubusercontent.com/100826565/157814299-1ff89bfe-37fa-49be-ac06-ce0f37a52e6b.png)
![image](https://user-images.githubusercontent.com/100826565/157814478-c27c5616-1680-40d9-b25a-be7c313bcd10.png)
希望通过类似这样一个形式动态获取当前value，但是好像不行。
应用场景，希望将数字转化为时间，想用time[value]转换下

### 期望结果

应用场景是希望将数字转化为时间，想用time[value]转换下

### 实际结果

但是value获取不到

### 框架版本

react17.0.2

### 系统版本

win10

**Comment by andyjxli** [comment]
目前 react 是通过字符串替换的 
label={'${value}天'} 通过 ${value} 转换为实际的value
![image](https://user-images.githubusercontent.com/19701675/157817216-71d770fb-98b9-4e3d-8824-fd9904af6364.png)

**Comment by looc00** [comment]
> 目前 react 是通过字符串替换的。 如果不满足业务场景的话，需要支持 function 的话，需要改动一下. label={'${value}天'} 通过 ${value} 转换为实际的value ![image](https://user-images.githubusercontent.com/19701675/157817216-71d770fb-98b9-4e3d-8824-fd9904af6364.png)

目前是times:{0:"0:00" ,1:"0:15" ,2:"0:30"...}，按照现在的字符串替换方式，
![image](https://user-images.githubusercontent.com/100826565/157819639-e81439df-0b73-4de3-90fb-f7dfd99497bd.png)
显示undefined，好像是不行

**Comment by andyjxli** [comment]
> > 目前 react 是通过字符串替换的。 如果不满足业务场景的话，需要支持 function 的话，需要改动一下. label={'${value}天'} 通过 ${value} 转换为实际的value ![image](https://user-images.githubusercontent.com/19701675/157817216-71d770fb-98b9-4e3d-8824-fd9904af6364.png)
> 
> 目前是times:{0:"0:00" ,1:"0:15" ,2:"0:30"...}，按照现在的字符串替换方式， ![image](https://user-images.githubusercontent.com/100826565/157819639-e81439df-0b73-4de3-90fb-f7dfd99497bd.png) 显示undefined，好像是不行

你这个场景确实不支持，需要用函数来替换. @HQ-Lin  你看一下这个场景，如果需要加的话， 我这边改一下

**Comment by HQ-Lin** [comment]
> > 目前 react 是通过字符串替换的。 如果不满足业务场景的话，需要支持 function 的话，需要改动一下. label={'${value}天'} 通过 ${value} 转换为实际的value ![image](https://user-images.githubusercontent.com/19701675/157817216-71d770fb-98b9-4e3d-8824-fd9904af6364.png)
> 
> 目前是times:{0:"0:00" ,1:"0:15" ,2:"0:30"...}，按照现在的字符串替换方式， ![image](https://user-images.githubusercontent.com/100826565/157819639-e81439df-0b73-4de3-90fb-f7dfd99497bd.png) 显示undefined，好像是不行

你这个写法不太对吧？times 里面多了个反斜杠，试试： `label={times[value]}` ？

**Comment by HQ-Lin** [comment]
> 目前 react 是通过字符串替换的。 如果不满足业务场景的话，需要支持 function 的话，需要改动一下. label={'${value}天'} 通过 ${value} 转换为实际的value ![image](https://user-images.githubusercontent.com/19701675/157817216-71d770fb-98b9-4e3d-8824-fd9904af6364.png)

还有， TNode 格式是要支持 function 的
https://github.com/Tencent/tdesign-react/blob/develop/src/common.ts#L8

**Comment by HQ-Lin** [comment]
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/24469546/158748557-3196c6dd-3920-436a-b8b7-49b06ff51631.png">
https://stackblitz.com/edit/angular-dx4vfs?file=src%2Fdemo.jsx

**Comment by looc00** [comment]
> <img alt="image" width="1042" src="https://user-images.githubusercontent.com/24469546/158748557-3196c6dd-3920-436a-b8b7-49b06ff51631.png">
> 
> https://stackblitz.com/edit/angular-dx4vfs?file=src%2Fdemo.jsx

是range模式的不行

**Comment by HQ-Lin** [comment]
0.28.0 已支持 `label={({value, position}) => 'xxx'}`
