### ISSUE TITLE
[Menu] Menu 点击态没法去掉 mask

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#470]
### tdesign-react 版本

0.27.0

### 重现步骤

![image](https://user-images.githubusercontent.com/5036903/157843437-4aa7bab9-ac02-4b0b-86f9-0859176d69c8.png)
按钮点击时飘过的背景色，没有 className ，很难定位，需要非常 hack 的手段，希望能加一下

### 期望结果

有一个具体的 className

**Comment by uyarn** [comment]
是要关闭动画的意思吗？

**Comment by insekkei** [comment]
动画本身挺好的，不过希望能关闭，或者自定义覆盖，所以想看看能不能给那个 div 加个 className ，然后样式权重不要这么高，很难覆盖...

**Comment by uyarn** [comment]
1. 可以关闭 通过ConfigProvider管理；
2. 好 加个className

**Comment by uyarn** [comment]
已经加了class @insekkei `t-ripple` -> `t-ripple__inner` 下个版本带上
