### ISSUE TITLE
表单重置报错

### ISSUE THREAD

**Issue by xucz** [Tencent/tdesign-react#472]
### tdesign-react 版本

0.27.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-hncn9q?file=/src/demo.jsx

### 框架版本

react17

**Comment by HQ-Lin** [comment]
收到，本周处理下

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-2eg2yu

可先给 FormItem 添加 initialData 处理下，后续 upload 组件会做下兼容处理

**Comment by HQ-Lin** [comment]
0.27.1 fixed
