### ISSUE TITLE
[Message] 默认关闭按钮的点击事件没有触发

### ISSUE THREAD

**Issue by y1huachen** [Tencent/tdesign-react#474]
### 重现链接
https://codesandbox.io/embed/nervous-lewin-e19f2y?fontsize=14&hidenavigation=1&theme=dark

### 重现步骤
```
<Message
  duration={0}
  closeBtn={true}
  onCloseBtnClick={() => console.log("无法触发")}
>
  默认关闭按钮测试，closeBtn为【boolean】类型
</Message>
```
绑定的关闭按钮事件不会触发

查看了源代码
路径：
```
https://github.com/Tencent/tdesign-react/blob/develop/src/message/MessageClose.tsx
```
<img width="755" alt="wecom-temp-36b513b331c64a9da4fde2517b9f46c8" src="https://user-images.githubusercontent.com/44855904/158026733-cf88ebac-5115-4acb-80a9-8ec1b3aa409c.png">
此处对于默认的关闭按钮没有加上关闭按钮事件？

### 期望结果
绑定的关闭按钮事件在点击关闭按钮时正常触发

### 实际结果
绑定的关闭按钮事件在点击关闭按钮时没有触发

| Environment | Info |
|---|---|
| 相关版本 | 0.27.0 |
| 框架版本 / 基础库版本 | React 17.0.2 |
| 系统、浏览器 | MacOS |
| Node版本 |  |

**Comment by kenzyyang** [comment]
收到。

**Comment by HQ-Lin** [comment]
0.27.1 fixed
