### ISSUE TITLE
[Anchor] AnchorItem className 传入之后搞丢了原本的 组件内部 className

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#495]
### tdesign-react 版本

0.27.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-qiviyh

### 重现步骤

![image](https://user-images.githubusercontent.com/5036903/158577786-11f5d9bb-5383-4700-84bc-f6bff06416fe.png)
<img width="953" alt="image" src="https://user-images.githubusercontent.com/5036903/158577819-b32661dd-cce1-404c-aeed-3b91f66a4aee.png">

### 期望结果

同时有两个 className ：t-anchor__item 和我传入的

### 实际结果

只剩下了我传入的

### 框架版本

React

**Comment by HQ-Lin** [comment]
0.28.0 fixed
