### ISSUE TITLE
[Slider] 禁用状态仍然可以拖动

### ISSUE THREAD

**Issue by aouos** [Tencent/tdesign-react#497]
### tdesign-react 版本

0.27.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-7j2mrx?file=/src/demo.jsx

### 重现步骤

引用 `Slider` 组件，设置 `disabled` 属性

### 期望结果

禁用状态不可拖动

### 实际结果

禁用状态可以拖动

### 框架版本

React(17.0.2)

**Comment by andyjxli** [comment]
收到，我看看

**Comment by HQ-Lin** [comment]
0.28.0 fixed
