### ISSUE TITLE
[table] table本地排序，如果排序数据里有0，反复排序后table内会增加多个重复数据

### ISSUE THREAD

**Issue by haishancai** [Tencent/tdesign-react#500]
### tdesign-react 版本

0.25.2

### 重现链接

https://codesandbox.io/s/stoic-lalande-d3bef5?file=/src/App.js

### 重现步骤

详细见重现链接

### 期望结果

多次点击排序按钮，不会出现重复的无用的行

### 实际结果

多次点击排序按钮，出现重复的无用的行

### 框架版本

React

### Node版本

v12.22.3

**Comment by HQ-Lin** [comment]
0.28.0 fixed
