### ISSUE TITLE
[Form] formRef.current.submit 调用时必须传一个事件不然会报错

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#509]
### tdesign-react 版本

0.27.0

### 重现步骤

`<Dialog
          header="媒体注册"
          visible={isVisible}
          onConfirm={handleConfirm}
          onClose={() => { setIsVisible(false) }}
          >...

const handleConfirm = async (e) => {
   // 这里不传个 e 会报错
    const result = await form.current.submit(e);

}
`

![image](https://user-images.githubusercontent.com/5036903/158982398-48dedc5f-67c8-4bb8-a0b2-d2a5adb8a734.png)

### 期望结果

submit 可以没有参数

### 实际结果

需要传一个 e

**Comment by HQ-Lin** [comment]
收到，这里的e我改成可选的并且兼容判断下

**Comment by HQ-Lin** [comment]
0.28.0 fixed
