### ISSUE TITLE
[Select] Option子组件配合自定义keys使用异常

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-react#511]
### tdesign-react 版本

0.28.0

### 重现步骤

用户反馈 via kiddxu
```jsx
<Select placeholder="请选择" keys={keys} value={partition?.partitionId} onChange={onPartitionChange}>
{partitionOpts.map(({ label, value }, index) => (
     <Option key={index} customValue={index} label={label} value={value} />
))}
</Select>
```

<img width="666" alt="wecom-temp-518c112b2c085b62dafcffea564545e9" src="https://user-images.githubusercontent.com/26377630/159016495-5c89ea51-cc14-416a-95c1-e88b016fab3c.png">

### 期望结果

正常使用

### 实际结果

使用异常

### 框架版本

React

### 浏览器版本

any

### 系统版本

any

### Node版本

any

**Comment by HQ-Lin** [comment]
0.29.0 fixed
