### ISSUE TITLE
[Checkbox] checkbox 高度有问题，导致 Form 垂直不能居中

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#519]
### tdesign-react 版本

0.27.0

### 重现步骤

![image](https://user-images.githubusercontent.com/5036903/159217659-22c38e8b-54cf-4443-8770-fa7585be3ea6.png)

### 期望结果

label 和 checkbox 垂直居中

### 实际结果

不居中

### 框架版本

React

**Comment by HQ-Lin** [comment]
0.29.0 fixed
