### ISSUE TITLE
[cascader] Cascader multiple 模式时容错不够，value undefined 时会崩溃

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#520]
### tdesign-react 版本

0.28.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lp0gj7

### 重现步骤

Cascader multiple 
点击选择框，就会崩溃

### 期望结果

正常打开弹层

### 实际结果

崩溃

### 框架版本

react

**Comment by HQ-Lin** [comment]
0.30.0 fixed
