### ISSUE TITLE
[Select] 有一个小的 margin left 导致对不齐

### ISSUE THREAD

**Issue by insekkei** [Tencent/tdesign-react#524]
### tdesign-react 版本

0.28.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-xehpi1

### 重现步骤

![image](https://user-images.githubusercontent.com/5036903/159455896-ca7fa40f-a6fe-4660-9a37-4ad727254e53.png)

### 期望结果

能对齐

### 框架版本

React

**Comment by uyarn** [comment]
重构成select-input时样式遗漏处理了 这个样式本来是给multiple下 和tag增加一定距离方便输入使用的

**Comment by HQ-Lin** [comment]
0.29.0 fixed
