### ISSUE TITLE
[treeSelect] 折叠功能失效

### ISSUE THREAD

**Issue by LinJieLinLin** [Tencent/tdesign-react#525]
### tdesign-react 版本

0.28.0

### 重现链接

https://0_28_0-tdesign-react.surge.sh/react/components/tree-select?tab=demo

### 重现步骤

点开任意treeSelect demo,点折叠图标

### 期望结果

根据用户点击折叠图标，数据折叠或展开

### 实际结果

默认一直展开，没有折叠

### 框架版本

react 16.12.0

### 浏览器版本

Edge99.0.1150.46

### 系统版本

window

### 补充说明

官方demo就有这个问题，可对比0.21.0版本

**Comment by HQ-Lin** [comment]
0.29.0 fixed
