### ISSUE TITLE
[Upload] Method不能修改请求方法，beforeUpload不能更新header

### ISSUE THREAD

**Issue by wangsansi** [Tencent/tdesign-react#526]
### tdesign-react 版本

0.27.2

### 重现步骤

1. 修改了method='PUT'，实际请求还是POST
```
<Upload
     headers={{
         'Authorization': auth,
         'x-cos-security-token': token
     }}
     beforeUpload={(file)=>getAuth(file)}
     method="PUT"
     action="http://frogla-1253445332.cos.ap-shanghai.myqcloud.com/"
     theme="image"
     tips="允许选择多张图片文件上传，最多只能上传 3 张图片"
     accept="image/*"
     multiple
     max={3}
 />
```
2. beforeUpload中调用setAuth和setToken，修改header中的auth和token，发请求的时候头部仍然没有。
```
const [auth, setAuth] = useState('');
const [token, setToken] = useState('');
function getAuth(file){
        let Key = 'ticket/' + file.name
        let parma = {
            Method: 'PUT',
            Pathname: '/'+Key
        }
        return new Promise((resolve,reject)=>{
            api.post('/api/v1/cos/authorization',parma).then((res)=>{
                let {data} = res   
                setAuth(data.Authorization)
                setToken(data.SecurityToken)
                resolve(true)
            },(err)=>{
                console.log('获取auth错误')
                reject(true)
            })
        })
    }
```
<img width="810" alt="image" src="https://user-images.githubusercontent.com/25080434/159482786-7f985cf3-63bf-475b-9aeb-530adbf311ff.png">

### 期望结果

method能够改变请求方法，beforeUpload中能够更新header

### 实际结果

method始终为post，beforeUpload中修改header没有更新

### 框架版本

react(17.0.2)

### 浏览器版本

Chrome(版本 98.0.4758.80)

### 系统版本

MacOS(11.0.1)

**Comment by teal-front** [comment]
@wangsansi beforeUpload要更新真正上传请求里的头部吗？
那需求在requestMethod方法里去更新。

**Comment by wangsansi** [comment]
@teal-front 是的，修改真正上传请求头，那如果用了requestMethod是不是就不能用action上传了？需要自己上传？

**Comment by teal-front** [comment]
> @teal-front 是的，修改真正上传请求头，那如果用了requestMethod是不是就不能用action上传了？需要自己上传？

恩，得自己上传了。

**Comment by wangsansi** [comment]
@teal-front 嗯 谢谢 那请求方法不能改变这个问题，请你们再看一下吧

**Comment by HQ-Lin** [comment]
0.29.0 已支持
