### ISSUE TITLE
[Select] onSearch触发时机有误

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-react#555]
### tdesign-react 版本

0.29.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-wr64bx?file=/src/demo.jsx

### 重现步骤

focus在Select 此时没有输入内容的情况下 不应该调用onSearch的回调 
进行搜索 选中其中一个值后 再focus在Select 此时没有搜索 由于继续调用了onSearch的回调 导致以当前value入参执行onSearch 返回了错误的内容；
考虑问题出现的原因是使用SelectInput重构之后 每次focus都会调用onInputChange 进而触发了onSearch
<img width="572" alt="image" src="https://user-images.githubusercontent.com/26377630/160745215-ec585edb-51b8-4532-b6b7-c1ebf2c96076.png">

### 期望结果

focus在Select 没有输入内容的情况下 不调用了onSearch的回调 

### 实际结果

focus在Select 没有输入内容的情况下 调用了onSearch

### 框架版本

React

**Comment by HQ-Lin** [comment]
0.30.0 fixed
