### ISSUE TITLE
[Tooltip] 添加了duration 属性后，初次渲染会闪现tooltip

### ISSUE THREAD

**Issue by leeenx** [Tencent/tdesign-react#557]
### tdesign-react 版本

0.29.0

### 重现链接

https://stackblitz.com/edit/angular-79jdpl?file=src%2Fdemo.jsx

### 重现步骤

`<Tooltip content="文字提示仅展示文本内容" duration={100}>
      <Button variant="outline">默认文字提示</Button>
    </Tooltip>`
此代码即可重现。

### 期望结果

添加了 duration 属性也不应该有闪现BUG

### 实际结果

添加了duration 属性，提示文字会在页面首次渲染时闪现

### 框架版本

React17.0.2

### 浏览器版本

99.0.4844.51

### 系统版本

MacOS(10.15.7)

### Node版本

10.16.0

### 补充说明

另外添加了 duration 后，在nextjs框架下会有以下告警：「Warning: Expected server HTML to contain a matching <div> in <div>」

**Comment by uyarn** [comment]
fixed 0.30.0

**Comment by Reilkay** [comment]
当前版本依然有这个问题，增加duration属性后在初次渲染时会出现，去除后恢复正常。
"tdesign-react": "^1.7.7"

**Comment by HaixingOoO** [comment]
> 当前版本依然有这个问题，增加duration属性后在初次渲染时会出现，去除后恢复正常。 "tdesign-react": "^1.7.7"

![image](https://github.com/user-attachments/assets/8f326ca4-77bc-4692-9f10-92ff24de20f3)
`duration` 就是首次渲染会出现的

**Comment by Reilkay** [comment]
> > 当前版本依然有这个问题，增加duration属性后在初次渲染时会出现，去除后恢复正常。 "tdesign-react": "^1.7.7"
> 
> ![image](https://private-user-images.githubusercontent.com/65376724/355688761-8f326ca4-77bc-4692-9f10-92ff24de20f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTAzNTYsIm5iZiI6MTcyMzAxMDA1NiwicGF0aCI6Ii82NTM3NjcyNC8zNTU2ODg3NjEtOGYzMjZjYTQtNzdiYy00NjkyLTlmMTAtOTJmZjI0ZGUyMGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA1NTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MGJkYzZiYTdlY2UyMGFmZTk1YTkzODExYjJkMjNmMzgxZmRjZjk0ZjlhYTRhNTZkMTUyN2Y0NzEyNGRkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MkT3ZqNQyRQq-sBMAvLpXSpuJWXCsTixuOEyhxfiPj4) `duration` 就是首次渲染会出现的

如果初次渲染时不需要显示就无法设置Tooltip的显示时长吗？

**Comment by HaixingOoO** [comment]
> 如果初次渲染时不需要显示就无法设置Tooltip的显示时长吗？

你可以使用delay，传一个数组进去(比如：delay={[0,5000] as any}),第一个是appearDelay，第二个是exitDelay，目前可能会提示类型有问题，会在下个版本加上类型就不会警告了，你先给个 `any`

**Comment by Reilkay** [comment]
> > 如果初次渲染时不需要显示就无法设置Tooltip的显示时长吗？
> 
> 你可以使用delay，传一个数组进去(比如：delay={[0,5000] as any}),第一个是appearDelay，第二个是exitDelay，目前可能会提示类型有问题，会在下个版本加上类型就不会警告了，你先给个 `any`

你好，我在增加了`delay={[0,5000] as any}` 之后，组件变为五秒后显示，看起来第二个参数才是显示延迟？但在我改为`delay={[500, 0] as any}` 后，组件在触发时立即出现，但不会自动被销毁，只会在点击其他地方时才会消失。请问这是什么问题？

**Comment by HaixingOoO** [comment]
不好意思，之前看了delay是被tooltip包裹着的元素触发有的属性，你要是外部元素控制tooltip的显示时间(duration),你可以新建个issue，是希望挂载时可控制tooltip是否显示🤔
