### ISSUE TITLE
[Menu] 默认展开属性不生效

### ISSUE THREAD

**Issue by zhuchao666** [Tencent/tdesign-react#558]
### tdesign-react 版本

0.29.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-8yhq76?file=/src/demo.jsx

### 重现步骤

给Menu传递defaultExpanded属性，值为subMenu的value数组，但是菜单栏并没有默认展开

### 期望结果

菜单栏应该根据defaultExpanded中的值将subMenu进行默认展开

### 框架版本

React（17.0.2）

### 浏览器版本

99.0.4844.83

### 系统版本

MacOS（11.4）

### Node版本

node V16.14.0

**Comment by andyjxli** [comment]
这里的问题在于同时设置了 defaultExpanded 和 expanded 造成了冲突。
如果是自定义受控组件应该是直接传入 expanded，同时设置 expanded = 默认值。如下：

const [active, setActive] = useState("1-1");
  const [collapsed, setCollapsed] = useState(false);
  // 设置初始值就行
  const [expands, setExpands] = useState(["1", "2", "2-1"]);

  return (
    <Fragment>
      <Menu
        value={active}
        // defaultExpanded={["1", "2", "2-1"]}
        collapsed={collapsed}
        expandMutex={false}
        expanded={expands}
        onExpand={(values) => setExpands(values)}
        onChange={(v) => setActive(v)}
        operations={
          <ViewListIcon
            className="t-menu__operations-icon"
            onClick={() => setCollapsed(!collapsed)}
          />
        }

**Comment by zhuchao666** [comment]
好的了解，谢谢告知
