### ISSUE TITLE
DatePicker(日期选择器)弹窗收回时位置不对

### ISSUE THREAD

**Issue by justjavac** [Tencent/tdesign-react#56]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62

url: https://tdesign.tencent.com/react/components/date-picker

https://user-images.githubusercontent.com/359395/147207816-ac63c290-bc02-4319-9b53-43afe699dbc2.mp4

**Comment by HQ-Lin** [comment]
感谢反馈，popup 展开时位置判断有点问题，本周内处理

**Comment by andyjxli** [comment]
fixed by: https://github.com/Tencent/tdesign-react/pull/76

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-react/releases/tag/0.22.0 fixed
