### ISSUE TITLE
[InputNumber] 支持label

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-react#565]
### 这个功能解决了什么问题

 <img width="265" alt="image" src="https://user-images.githubusercontent.com/35833812/161022780-def6aac5-3058-453f-8d1c-839e7eb5548a.png">

### 你建议的方案是什么

希望inputNumber支持label和suffix

**Comment by HQ-Lin** [comment]
这个感觉用 Input 组件会比较合适
