### ISSUE TITLE
[面包屑] separator 设置不起作用

### ISSUE THREAD

**Issue by 2992362310** [Tencent/tdesign-react#568]
### tdesign-react 版本

0.30.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-i93ns4

### 重现步骤

<img width="1104" alt="wecom-temp-a06a59892ddba3f9e7bacee8ccb5e92c" src="https://user-images.githubusercontent.com/43593232/161246136-5d77649c-10e1-484b-8195-2b4ef8f31619.png">

### 框架版本

react

**Comment by HQ-Lin** [comment]
0.30.2 fixed
