### ISSUE TITLE
[Table] 触发排序后，无法正确获取当前页码（onSortChange里）

### ISSUE THREAD

**Issue by haishancai** [Tencent/tdesign-react#569]
### tdesign-react 版本

0.30.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-pq1uv8?file=/src/demo.jsx

### 重现步骤

1、先翻到第2页
2、排序
3、onSortChange里的current值还是1

### 期望结果

期望是2

### 实际结果

是1

### 框架版本

React

**Comment by carolin913** [comment]
该问题需要自己在业务中对pagenation的状态做维护，table中没有包括分页的state
