### ISSUE TITLE
[Slider] 动态设置value值很大时会出现浏览器卡死

### ISSUE THREAD

**Issue by haishancai** [Tencent/tdesign-react#570]
### tdesign-react 版本

0.30.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-o9qy8y?file=/src/demo.jsx

### 重现步骤

1、动态设置value很大，出现浏览器卡死
useEffect(() => {
    setRange([267, 786456]);
    setRangeValue([300, 10000]);
  }, []);

### 期望结果

正常渲染

### 实际结果

![Uploading 企业微信截图_7fedd8e7-ee0f-479d-a6a4-1023f7b3639f.png…]()

### 框架版本

React

**Comment by andyjxli** [comment]
@haishancai 这个问题是因为 step 默认为 1 导致的。尝试设置一个步长来解决一下呢？
我想了一下，我们不太好设置其他默认步长或动态计算，会导致其他业务场景不适合

**Comment by haishancai** [comment]
@andyjxli 看了下antd组件不设置的时候是自动计算了step的，其他业务场景是不是能要求用户设置下step，与卡死相比，性能问题似乎更加严重，这个卡死可能会直接导致用户弃用这个组件

**Comment by HQ-Lin** [comment]
看了一下性能问题出现在 `accAdd` 函数针对浮点数的加法计算，这版本优化一下

**Comment by HQ-Lin** [comment]
0.31.0 fixed
