### ISSUE TITLE
[Table] 无法兼容自定义数据类型

### ISSUE THREAD

**Issue by muyanmie** [Tencent/tdesign-react#577]
### tdesign-react 版本

"tdesign-react": "0.23.0"

### 重现步骤

用如下方法使用table组件
`<Table data={data} columns={columns} rowKey="id"></Table>`

其中我的columns的类型定义为`PrimaryTableCol<ListItem>[]
`
在此定义下，table入参会报错`不能将类型“TableRowData”分配给类型“ListItem”`

其中我的ListItem定义为
```
export interface ListItem {
  id: string;
  name: string;
  code: STATUS;
}
```

为什么我在规定columns时不使用原本的TableRowData定义呢？
因为我需要对row元素做一些处理，而我的处理函数需要规定入参类型，使用TableRowData会将我的元素类型都变成any，导致我不得不在使用时还需要强行转换一次类型

(例如如下的使用
```
const columns: PrimaryTableCol<TableRowData>[] = [
    {
      colKey: 'name',
      title: '名称',
      cell({ row }) {
        return <ClientIcon name={row.cnName} icon={row.avatar} />;
      },
    },
    {
      colKey: 'code',
      title: '状态',
      cell({ row }) {
        return MAPPING[row.code as STATUS];  // 这里需要强制转换一下
      },
    },
  ];
```

### 期望结果

期望TableRowData的定义能更加宽泛，能够成功兼容用户的自定义类型
如果对用户自定义类型有规范，明确标注出规则

### 实际结果

出现不兼容

### 框架版本

"react": "16.13.1"

### 浏览器版本

Chrome(100.0.4896.60)

### 系统版本

macOS Monterey 12.3

### Node版本

v14.16.1

**Comment by HQ-Lin** [comment]
0.32.0 fixed
