### ISSUE TITLE
[Upload] draggable/multiple/theme="custom"属性同时存在时组件不渲染

### ISSUE THREAD

**Issue by liuyizhou** [Tencent/tdesign-react#578]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-tqkjhk?file=/src/demo.tsx

### 重现步骤
1.draggable/multiple/theme="custom"属性同时存在时组件不渲染
2. customDraggerRender 没有声明在d.ts中

可以在链接中重现

### 期望结果
1.组件正常渲染
2.ts环境下不报类型错误

### 实际结果
1.组件不渲染
2.ts环境报错

| Environment | Info |
|---|---|
| 相关版本 | 0.30.1 |
| 框架版本 / 基础库版本 | React 17 |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
0.31.1 fixed
