### ISSUE TITLE
[Upload] 多图片上传时defaultFiles造成上传进度错误

### ISSUE THREAD

**Issue by liuyizhou** [Tencent/tdesign-react#584]
### tdesign-react 版本

0.30.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-m8ptud?file=/src/demo.jsx

### 重现步骤

图片上传时，当传入defaultFiles，后续的图片的上传进度会显示NaN%

<img width="441" alt="企业微信截图_6a5c9143-80f6-4b22-b153-2c02e3c487a8" src="https://user-images.githubusercontent.com/8944820/162357418-e34b11ba-a13f-4f44-9193-8353078e4b81.png">

### 期望结果

上传进度正常显示

### 实际结果

上传进度显示NaN%

**Comment by yaogengzhu** [comment]
我尝试解决下

**Comment by HQ-Lin** [comment]
0.30.2 fixed
