### ISSUE TITLE
Menu组件颜色问题

### ISSUE THREAD

**Issue by xucz** [Tencent/tdesign-react#595]
### tdesign-react 版本

0.30.1

### 重现步骤

t-menu__logo 

light 主题，底部边框颜色为固定值： border-bottom-color:  #f0f0f0;

dark 主题，底部边框为： border-bottom-color: var(--td-gray-color-10);

### 期望结果

light、dark 主题，border-bottom-color 都从css变量中取，这样外部组件颜色可以也取相同的css变量，可以做到颜色统一

### 框架版本

react17

**Comment by HQ-Lin** [comment]
感谢指出问题，这里的token使用错了
应该要用分割线的 token：--td-component-stroke

我们调整下
<img width="551" alt="wecom-temp-0345813b7ddcbd106fd62e70e24bb0d0" src="https://user-images.githubusercontent.com/24469546/163136362-7010db3e-003e-42ec-b641-a3fec2c929d4.png">

**Comment by HQ-Lin** [comment]
0.31.0 fixed
