### ISSUE TITLE
[Menu] 样式问题

### ISSUE THREAD

**Issue by ZhaoRB** [Tencent/tdesign-react#598]
### tdesign-react 版本

0.30.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-v8vo3x

### 重现步骤

1. 多层subMenu嵌套出现圆点
2. 添加 href 属性后 icon 和菜单项内容的间距变小

![image](https://user-images.githubusercontent.com/42922769/162881731-1aafc9a0-b5a2-479d-83cd-e1b1ed13373d.png)

3. expandType: 'popup' 没有内容的时候依然弹出无内容的空白框

**Comment by HQ-Lin** [comment]
0.31.0 fixed
