### ISSUE TITLE
[Table] height和maxHeight，传入字符串无效

### ISSUE THREAD

**Issue by looc00** [Tencent/tdesign-react#603]
### tdesign-react 版本

0.30.2

### 重现步骤

Table height maxHeight 只有传number有用，string无效

### 框架版本

react(17.0.2)

**Comment by carolin913** [comment]
@looc00 这里验证了下，如果传入数字或字符串是可以的，但是不能带px，比如400或者'400'这样，目前api文档里的说明有误，下个版本会更新文档。

**Comment by looc00** [comment]
> @looc00 这里验证了下，如果传入数字或字符串是可以的，但是不能带px，比如400或者'400'这样，目前api文档里的说明有误，下个版本会更新文档。

百分比也不行

**Comment by carolin913** [comment]
百分比要生效得看继承于哪个父元素，目前table的层级比较复杂，需要你自己去设置父级高度才好继承，所以不建议用百分比，带px这种我们会支持下，下一版本会支持

**Comment by HQ-Lin** [comment]
0.31.0 fixed
