### ISSUE TITLE
[Cascader 级联选择器] 自定义选中值模式,valueMode属性不生效。

### ISSUE THREAD

**Issue by ltsok** [Tencent/tdesign-react#621]
### tdesign-react 版本

^0.28.0

### 重现链接

https://stackblitz.com/edit/angular-kgmpu1-1tjcam?file=src%2Fdemo.jsx

### 重现步骤

import React, { useState } from 'react';
import { Cascader } from 'tdesign-react';

export default function Example() {
  const [value1, setValue1] = useState([]);
  const [value2, setValue2] = useState([]);
  const [value3, setValue3] = useState([]);
  const options = [
    {
      label: '选项一',
      value: '1',
      children: [
        {
          label: '子选项一',
          value: '1.1',
        },
        {
          label: '子选项二',
          value: '1.2',
        },
        {
          label: '子选项三',
          value: '1.3',
        },
      ],
    },
    {
      label: '选项二',
      value: '2',
      children: [
        {
          label: '子选项一',
          value: '2.1',
        },
        {
          label: '子选项二',
          value: '2.2',
        },
      ],
    },
  ];

  const itemStyle = {
    marginTop: '16px',
  };

  const onChange1 = (value) => {
    console.log('value', value);
    setValue1(value);
  };

  const onChange2 = (value) => {
    console.log('value', value);
    setValue2(value);
  };

  const onChange3 = (value) => {
    console.log('value', value);
    setValue3(value);
  };

  return (
    <div className="tdesign-demo-block-column">
      <Cascader
        style={itemStyle}
        options={options}
        value={value1}
        onChange={onChange1}
        multiple
        valueMode="onlyLeaf"
      />
      <Cascader
        style={itemStyle}
        options={options}
        value={value2}
        onChange={onChange2}
        multiple
        valueMode="parentFirst"
      />
      <Cascader
        style={itemStyle}
        options={options}
        value={value3}
        onChange={onChange3}
        multiple
        valueMode="all"
      />
    </div>
  );
}

### 期望结果

![image](https://user-images.githubusercontent.com/34325236/163310487-4da79458-2026-443e-a540-c5a3cb35aa5b.png)
valueMode='all'时；输出['1', '1.3']

### 实际结果

['1.3']

### 框架版本

react(17.x)

### 浏览器版本

Chrome(100.0.4896.88)

### 系统版本

MacOs(11.4)

### Node版本

Node(14.7.0)

### 补充说明

无

**Comment by jsonz1993** [comment]
@ltsok 看了下demo好像逻辑没什么问题
你选了子选项三，所以只有 1.3，这时候选项一是半选中状态，不应该被输出
