### ISSUE TITLE
[Cascader] filterable 模式下，展示状态异常

### ISSUE THREAD

**Issue by jsonz1993** [Tencent/tdesign-react#622]
### tdesign-react 版本

0.30.2

### 重现链接

https://stackblitz.com/edit/angular-991jun?file=src/demo.jsx

### 重现步骤

![Kapture 2022-04-14 at 13 09 47](https://user-images.githubusercontent.com/11730463/163317822-4fcccd94-1b2e-4a06-9ca4-85d7316cced3.gif)
点击已选值

### 期望结果

正常展示

### 框架版本

React(0.30.2)

**Comment by HQ-Lin** [comment]
0.31.0 fixed
