### ISSUE TITLE
[Code] 错别字修正

### ISSUE THREAD

**Issue by HQ-Lin** [Tencent/tdesign-react#625]
### tdesign-react 版本

0.30.2

### 重现步骤

https://github.com/Tencent/tdesign-react/runs/5686876657?check_suite_focus=true

<img width="430" alt="image" src="https://user-images.githubusercontent.com/24469546/163325404-981f6cce-afe4-48d8-97bc-fb8c9378422d.png">

这个 ci 列出了一系列不合理的代码命名，诚招壮士帮忙修复下

**Comment by jsonz1993** [comment]
本地修了一些，但是没提pr，存在几个问题
1. 大部分错误位于 example 和 test ，或者是局部变量，影响比较小
2. 有一些是className的命名，这些改动可能会导致部分用户覆盖样式出现问题，比如 原本用户给 t-cascader--noraml 写了个加粗，现在 className 变成 t-cascader--normal会不生效。
3. js/tree 中 actived, activable 等找不到一个更合适的词代替，虽然确实没有这单词，但是一看能理解...
4. 关于 less 文件中，一些十六进制表示的颜色，比如 #ba431b， typos 会识别成拼写错误，这块暂时没有什么好的办法处理(指的是在pr中如果加入 typos 检查)。
5. 忽略了 CHANGELOG.md 
6. 对文件的修改只做了简单的校验

具体可看

https://github.com/jsonz1993/tdesign-react/commit/d9dbd6d24c3f4c142a91caf0e64774f431ec1305

https://github.com/jsonz1993/tdesign-common/commit/ad5968dafbea47077697f2bf0aacdfaa1273ef39

**Comment by uyarn** [comment]
less文件可以忽略检查 我在.github的CI上加一下忽略吧

**Comment by jsonz1993** [comment]
> less文件可以忽略检查 我在.github的CI上加一下忽略吧

存量解决的话，确实可以忽略less文件的检查
增量代码 className 在 jsx 里面也会用到所以可以避免，如果是一些 less variable 拼写错误就没办法识别了（存量存在这种情况）

**Comment by jsonz1993** [comment]
> less文件可以忽略检查 我在.github的CI上加一下忽略吧

typos 1.7版本修复 十六进制颜色值的问题了
