### ISSUE TITLE
[popup] 弹层占用区域问题

### ISSUE THREAD

**Issue by nia3y** [Tencent/tdesign-react#632]
### tdesign-react 版本

latest

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-6k8qiw?file=/src/index.css

### 重现步骤

![image](https://user-images.githubusercontent.com/44686955/163382506-90e75924-603e-4a2f-84da-fcb89bb4b3c5.png)

弹层组件的范围存在问题，点击红色区域不能关闭弹层。
style、className 挂载的位置是否也不对？应该和 t-popup 同级吧，不应该放在 t-popup-content 内

### 期望结果

点击红色区域可以正常关闭

### 实际结果

点击红色区域不能关闭弹层

### 框架版本

latest

### 浏览器版本

chrome latest

**Comment by HQ-Lin** [comment]
1.这里应该优化掉底部多余的空间，但是trigger 与 popupContent 之间还是需要有占位的效果，否则在hover模式中鼠标从trigger移动到popup过程中就会消失
<img width="150" alt="image" src="https://user-images.githubusercontent.com/24469546/163529379-db001e1a-fa6d-4a00-a060-aaf7ef9bffcd.png">

2. Popup 本身也是有div节点的，你把它当成普通div来看的话className和style挂载是合理的，需要挂载到popupContent的话可以通过 `overlayClassName`、`overlayStyle` 去控制
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/24469546/163530244-9e9ad419-b149-48bb-947c-9597cb1a0c33.png">

**Comment by nia3y** [comment]
ok，了解
