### ISSUE TITLE
[Icon] tdesign-icons-react 对 React v18+ 的支持

### ISSUE THREAD

**Issue by hijiangtao** [Tencent/tdesign-react#634]
### 这个功能解决了什么问题

现有 tdesign-icons-react 标明的 peerDependencies 依赖不支持 React v18+ 版本的代码，安装时会报错，涉及代码如下：

```
"peerDependencies": {
    "react": "^16.0.0 || ^17.0.0",
    "react-dom": "^16.0.0 || ^17.0.0"
  },
```

### 你建议的方案是什么

+ ^18.0.0

**Comment by uyarn** [comment]
tdesign-icons-react@0.0.10 https://www.npmjs.com/package/tdesign-icons-react/v/0.0.10
