### ISSUE TITLE
[Table]The state in onSelectChange is always the initialized value

### ISSUE THREAD

**Issue by tianjidiaobao** [Tencent/tdesign-react#638]
The state in onSelectChange is always the initialized value

codesandbox:https://codesandbox.io/s/tdesign-react-demo-forked-egr8jz?file=/src/demo.jsx\

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/26198425/163537843-cc0e3c79-15af-4d85-929b-a1499112df0a.png">

Maybe the problem is because：
https://github.com/Tencent/tdesign-react/blob/60f36d4cd8e448fe140a1c1390e1eca81b14b2b6/src/table/primary/useSelect.tsx#L27

**Comment by HQ-Lin** [comment]
近期 table 在重构，这周review完会跟随版本一起发布修复众多问题
