### ISSUE TITLE
[table] 数据源在useEffect中初始化，表格行拖拽后，无法正常展示数据

### ISSUE THREAD

**Issue by ltsok** [Tencent/tdesign-react#650]
### tdesign-react 版本

0.31.0

### 重现链接

https://stackblitz.com/edit/angular-uray9x-xojs7r?file=src%2Fdemo.jsx

### 重现步骤

按重现链接代码，拖拽后，表格展示数据消失
![image](https://user-images.githubusercontent.com/34325236/163786541-e2f6a6d2-1ea5-498b-a037-ecf3a903a996.png)
![image](https://user-images.githubusercontent.com/34325236/163786586-ebd74096-598a-4b71-a0b0-176baf027157.png)

**Comment by uyarn** [comment]
顺便说一句 这个demo比较建议TabPanel是通过Tab的子组件获得的 依赖非顶级暴露的组件是不可靠的 
const { TabPanel } = Tabs;

**Comment by uyarn** [comment]
我又看了一下你这个场景 你这个问题其实是闭包问题吧 onDragSort刚开始赋值的时候的data形成了闭包 可以用ref处理一下 
https://stackblitz.com/edit/angular-uray9x-tr9uoz?file=src%2Fdemo.jsx 
或者你希望这个onDrag再回调什么参数？

**Comment by HQ-Lin** [comment]
0.32.0 fixed

**Comment by ltsok** [comment]
收到
