### ISSUE TITLE
[Table] BaseTableCol 的 className 支持传入函数

### ISSUE THREAD

**Issue by liuyizhou** [Tencent/tdesign-react#652]
### tdesign-react 版本

0.30.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-ngqut9?file=/src/demo.jsx

### 重现步骤

columns={[
        {
          align: "center",
          width: 100,
          minWidth: 100,
          className: () => {
            return "xxx";
          },
          ellipsis: true,
          colKey: "index",
        },

### 期望结果

class="xxx"

### 实际结果

class="() => {
        return "xxx";
      }"

**Comment by HQ-Lin** [comment]
0.32.0 fixed
