### ISSUE TITLE
[Select]  valueType="object" 无法正常移除已选项

### ISSUE THREAD

**Issue by zousandian** [Tencent/tdesign-react#654]
### tdesign-react 版本

v0.27-0.31

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-gq7zmx?file=/src/demo.jsx

### 重现步骤

Select 组件设置  valueType="object" 选择几个选项 ，点击选项删除按钮或者按退格键

### 期望结果

可以正常移除已选项

### 实际结果

无法正常移除已选项

### 框架版本

React 16

**Comment by HQ-Lin** [comment]
0.32.0 fixed
