### ISSUE TITLE
[Select] valueDisplay 取值在多选+可搜索过滤情况下，当已有选项后再次输入字符串会展示错误引用对象赋值

### ISSUE THREAD

**Issue by hijiangtao** [Tencent/tdesign-react#661]
### tdesign-react 版本

0.30.2

### 重现链接

https://codesandbox.io/s/multiple-select-with-search-show-nullish-item-2h87pz?file=/src/demo.jsx

### 重现步骤

Select 组件打开如下功能后，自定义 Option 以及 valueDisplay 存在此问题

1. showSearch
2. multiple

具体代码见 codesandbox

### 期望结果

选中内容应该在 valueDisplay 中正常传递

### 实际结果

在示例中可以输入任意字符串，然后等待 search 的回调结果，选中其中一项，此后，重新点击输入框，输入任意字符，存在概率会出现空 tag 现象，随着字符串的输入增多，该现象可能会消失，又恢复正常的展示（即展示已选中的内容 tag）

以本 codesandbox 为例，实际选中时传递 item 应该是 

```
{
    tid: "100141230238",
    t_name: "WO测试1",
    birthday: "2021-07-02",
    profession: ["导演"],
    pic_url: ""
  }
```

效果如下

<img width="253" alt="image" src="https://user-images.githubusercontent.com/4990015/164374546-bab3c598-5f84-471f-9d71-786f49dfad72.png">

但在展示为空（空 tag）时，传递的是错误的引用地址：

```
[object Object]
```

valueDisplay 传入的对象内容如下：

<img width="743" alt="image" src="https://user-images.githubusercontent.com/4990015/164374829-4d7821e9-0791-4665-9f52-35fd4f07904b.png">

效果如下

<img width="261" alt="image" src="https://user-images.githubusercontent.com/4990015/164374607-aa1dba72-3898-4da3-a864-ac1e674f89df.png">

怀疑是组件内部 ref 引用错误导致（selectedLabel），但随着 search 字符串输入，后续有概率可以恢复正常

### 框架版本

React v17.0.2

**Comment by hijiangtao** [comment]
不知道是不是这里处理的问题，供参考 https://github.com/Tencent/tdesign-react/blob/6860d0130c13d60a18d1054178ed3ac226b0218e/src/select/base/Select.tsx#L97-L102

**Comment by HQ-Lin** [comment]
0.32.0 fixed
