### ISSUE TITLE
[Table] pagination变化时pageSize失效

### ISSUE THREAD

**Issue by liuyizhou** [Tencent/tdesign-react#666]
### tdesign-react 版本

0.31.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-bwkbpr?file=/src/demo.jsx

### 重现步骤

pageSize设置为20，state条件判断是否传入pagination配置对象

### 期望结果

每页20条

### 实际结果

每页10条

**Comment by HQ-Lin** [comment]
0.32.0 fixed
