### ISSUE TITLE
TimePicker 时间选择器 确定选择时间不生效

### ISSUE THREAD

**Issue by harrylu99** [Tencent/tdesign-react#67]
**Describe Framework**

- [ ] tdesign-vue
- [ ] tdesign-vue-next
- [x] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

Chrome 96.0

**Describe the bug**
TimePicker 时间选择器 下拉框后不做任何动作，有时间被选中，但是点击确定不生效，本页没有默认时间的都有这个问题
[Link](https://tdesign.tencent.com/react/components/time-picker#%E6%97%B6%E5%88%86%E7%A7%92%E9%80%89%E6%8B%A9%E5%99%A8)

https://user-images.githubusercontent.com/40201365/147338299-4ed4d90a-7adb-44cc-a104-5ab65c674936.mp4

**Comment by fzhange** [comment]
@harrylu99 hi 你这个tdesign-react的版本是多少呢？ 
另外上传的这个视频，好像没内容。

**Comment by harrylu99** [comment]
> @harrylu99 hi 你这个tdesign-react的版本是多少呢？ 另外上传的这个视频，好像没内容。

[是官网的例子啦](https://tdesign.tencent.com/react/components/time-picker)

https://user-images.githubusercontent.com/40201365/147338064-7e918ffe-cc96-45b2-bd4c-3f2d0a8a539e.mp4

**Comment by harrylu99** [comment]
> @harrylu99 hi 你这个tdesign-react的版本是多少呢？ 另外上传的这个视频，好像没内容。

是官网的例子啦 https://tdesign.tencent.com/react/components/time-picker

https://user-images.githubusercontent.com/40201365/147338419-cacc0f04-7da6-4884-8530-427f6c8a89a7.mp4

**Comment by yaogengzhu** [comment]
> > @harrylu99 hi 你这个tdesign-react的版本是多少呢？ 另外上传的这个视频，好像没内容。
> 
> 是官网的例子啦 https://tdesign.tencent.com/react/components/time-picker
> 
> 时分秒选择器， 时分选择器，自定义步长时间选择器，十二小时制时间选择器和时间区间选择器 这几个下拉后会有默认的选中时间，但是这时候点确认却不生效
> 
>  timepickertdesign1.mp4
看了下代码，从代码上来说，确实只是一个关闭的动作！选择时间是通过滚动时间来触发的～ 这应该属于一个设计层面的问题，看官方是否需要支持confirm支持选择时间。

**Comment by uyarn** [comment]
0.22.0 fixed. thanks for @yaogengzhu
