### ISSUE TITLE
[ConfigProvider] ConfigProvider globalConfig的很多参数都是必填，可改为选填

### ISSUE THREAD

**Issue by chizhiyiheng** [Tencent/tdesign-react#670]
### tdesign-react 版本

0.30.2

**Comment by uyarn** [comment]
麻烦升级到0.31+的版本 已经改成partial了

**Comment by uyarn** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/26377630/164619422-a7c5cfae-c8f7-4e92-a694-ac375054131b.png">
