### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-react#677]
交互稿已确定，可以认领

【三期组件-时间轴】
https://codesign.qq.com/s/2nL6jgkLqmjpJXV/YDgGjYDmYKZwEVQ/inspect
访问密码：OLZL

**Comment by HQ-Lin** [comment]
已招募到开发者：@Yilun-Sun
待设计稿完成后确定 API 后就启动开发，后续有人员变动会同步更新在此 ISSUE 中

**Comment by southorange1228** [comment]
我来负责跟进开发~

**Comment by southorange1228** [comment]
https://github.com/Tencent/tdesign-react/pull/1156

**Comment by HQ-Lin** [comment]
0.40.0 已支持
