### ISSUE TITLE
[Menu] 能否在组件内部做个自适应呢？

### ISSUE THREAD

**Issue by HenryLee0** [Tencent/tdesign-react#679]
### 这个功能解决了什么问题

no message

### 你建议的方案是什么

是否会考虑：当浏览器可视化区域的宽度达到一个minWidth时 可以自动收起打开状态的Menu菜单？
![image](https://user-images.githubusercontent.com/93959131/164974257-c4fe0bf1-3a1c-4dc7-9ca6-5ff159524de5.png)

**Comment by HQ-Lin** [comment]
1.作为组件来说，外层容器什么样是不在组件逻辑范围之内的，是不是可视范围内对于组件来说是无法感知的，甚至有可能运行环境都不是在web，那还要适配各种环境下可视区域的判断逻辑，不合理
2.Menu 的展开收齐是受控属性，如果做到了自动切换那又违背了受控的原则，会导致别的用户觉得奇怪明明自己没有要求折叠却失控了，还需要用户再去理解自适应的优先级比用户的代码还要高，也不合理
3.页面响应式本身就是业务开发会遇到的，万一有的用户又希望永远不变呢？所以做了也会有用户觉得不合理
