### ISSUE TITLE
Cascader组件选中异常

### ISSUE THREAD

**Issue by myLazyProgrammer** [Tencent/tdesign-react#68]
**Describe Framework**

- [ ] tdesign-vue
- [ ] tdesign-vue-next
- [x] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**

chrome  96.0.4664.110
macos Catalina 10.15.7

**Describe the bug**
官方文档 https://tdesign.tencent.com/react/components/cascader?tab=demo#%E6%96%87%E6%9C%AC%E8%BF%87%E9%95%BF%E6%97%B6%E7%9A%84%E5%B1%95%E7%A4%BA
选中选项二过长的那一列时 有概率导致选项二过短的一列无法选中
![image](https://user-images.githubusercontent.com/28853627/147308184-dfac0c8b-5224-4cc7-a506-f1d15dc036c1.png)

**Additional context**

**Comment by myLazyProgrammer** [comment]
看起来是被 tooltip 遮挡了

**Comment by pengYYYYY** [comment]
我们排查一下喔

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-react/releases/tag/0.23.0 fixed
