### ISSUE TITLE
[Table] 新版table列属性设置ellipsis: true后，鼠标hover浮层不消失

### ISSUE THREAD

**Issue by haishancai** [Tencent/tdesign-react#687]
### tdesign-react 版本

0.32.1

### 期望结果

鼠标移开popup浮层消失

### 实际结果

<img width="782" alt="wecom-temp-c7e9d7d1e19f39d60bc3e1d1706b9ad1" src="https://user-images.githubusercontent.com/5885699/165063904-1273337d-5b34-4133-84b5-a024fd07f7e3.png">

### 框架版本

React

**Comment by chaishi** [comment]
没有复现问题的代码，难以处理，辛苦提供 demo 后，再 reopen issue

**Comment by uyarn** [comment]
<img width="1180" alt="wecom-temp-9c1467359b89094b5694091a50585cdc" src="https://user-images.githubusercontent.com/26377630/167247489-d9ef5ffc-9fa5-4730-811b-e2cc88df4b0e.png">

**Comment by uyarn** [comment]
reconfirm..

**Comment by chaishi** [comment]
咋复现这个问题呢，如果长时间没有回复，issue 将被关闭
