### ISSUE TITLE
[Textarea] 文本字符没统一

### ISSUE THREAD

**Issue by HenryLee0** [Tencent/tdesign-react#689]
### tdesign-react 版本

0.32.1

### 补充说明

<img width="2072" alt="image" src="https://user-images.githubusercontent.com/93959131/165073375-eff1a1ff-0677-46e9-ad9b-8528360f87a3.png">

**Comment by HQ-Lin** [comment]
这个问题就有意思了。。
其实你 devtool 上看到的是 chrome 浏览器预设的字体，而最后渲染在dom节点上是页面设定的字体，官网页面用的是 `PingFangSC-Regular` 字体，但是chrome 的控制台不是这个字体，可能是 `monospace `?（因为试了下很接近）
所以这里不会去预设 textarea 的字体，否则他在safary浏览器下你又要提个issue说字体对不上了
你可以打开safary 看一下其实他们是同一个字体也就是 `PingFangSC-Regular`
