### ISSUE TITLE
[Dialog] 组件样式优化

### ISSUE THREAD

**Issue by HQ-Lin** [Tencent/tdesign-react#692]
### 这个功能解决了什么问题

当前Dialog 是通过transform 做动画和位移的，transform 属性会导致浏览器创建一个 layer 层从而使内部子节点的 fixed 属性定位失效

### 你建议的方案是什么

需要调整 css 布局为使用 top left 属性来控制定位，移除 transform

**Comment by huoyuhao** [comment]
认领[Dialog] 组件样式优化
