### ISSUE TITLE
[table] 拖拽功能无效

### ISSUE THREAD

**Issue by yuchenfang** [Tencent/tdesign-react#693]
### tdesign-react 版本

0.32.1

### 重现链接

https://git.woa.com/biz-ria/xunda/xunda-crm-web/blob/dev/src/pages/Buz/dealer/order/index.tsx

### 重现步骤

https://car-test.retail.qq.com/buz/dealer/order

### 期望结果

拖拽能够拖拽

### 实际结果

拖拽无效

### 框架版本

react(0.32.1)

### Node版本

14.17.0

**Comment by uyarn** [comment]
用户代码问题 已沟通
