### ISSUE TITLE
Table 组件固定表头时列内容无法对齐

### ISSUE THREAD

**Issue by jzhangdev** [Tencent/tdesign-react#70]
**Describe Framework**

- [ ] tdesign-vue
- [ ] tdesign-vue-next
- [x] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
All browsers.

**Describe the bug**
在设置 `maxHeight` 属性后，若内容总高度小于 `maxHeight` 的值，表头中的列和内容中的列无法对齐。

**Additional context**
https://codesandbox.io/s/tdesign-react-demo-forked-jqse1?file=/src/demo.jsx

**Comment by jzhangdev** [comment]
是否可以考虑根据 table body 的内容是否溢出来决定 table header 是否增加 `padding-right` ？

**Comment by Ezreal09** [comment]
大家是不是都太闲了，重复造这种轮子

**Comment by chaishi** [comment]
@Ezreal09  

对啊，就是发现 TX 内部好多这种轮子，数不清楚了。一个部门一个轮子，自己搞。

后来老板看不下去了，大家一起搞一个吧，别都自己搞了，然后就出现这个轮子了

**Comment by uyarn** [comment]
@yunfeic

**Comment by uyarn** [comment]
0.22.0 fixed
