### ISSUE TITLE
table前端分页bug

### ISSUE THREAD

**Issue by yuchenfang** [Tencent/tdesign-react#711]
### tdesign-react 版本

0.32.1

### 重现步骤

table 前端分页
比如一共有100条数据
第一页会把所有数据加载出来。
第二页会展示正确数量的数据，
再切回第一页，数据数量又正常了

**Comment by uyarn** [comment]
贴下代码

**Comment by yuchenfang** [comment]
<Table
            loading={dataLoading}
            data={data || []}
            columns={columns}
            rowKey={rowKey}
            verticalAlign="top"
            hover={true}
            pagination={{
              defaultCurrent: 1,
              defaultPageSize: 5,
              total: pagination.total,
              showJumper: true,
              onChange(pageInfo) {
                console.log(pageInfo, 'onChange pageInfo');
              },
              onCurrentChange(current, pageInfo) {
                console.log(current, 'onCurrentChange current');
                console.log(pageInfo, 'onCurrentChange pageInfo');
              },
              onPageSizeChange(size, pageInfo) {
                console.log(size, 'onPageSizeChange size');
                console.log(pageInfo, 'onPageSizeChange pageInfo');
              },
            }}
          ></Table>

**Comment by yuchenfang** [comment]
`<Table
            loading={dataLoading}
            data={data || []}
            columns={columns}
            rowKey={rowKey}
            verticalAlign="top"
            hover={true}
            pagination={{
              defaultCurrent: 1,
              defaultPageSize: 5,
              total: pagination.total,
              showJumper: true,
              onChange(pageInfo) {
                console.log(pageInfo, 'onChange pageInfo');
              },
              onCurrentChange(current, pageInfo) {
                console.log(current, 'onCurrentChange current');
                console.log(pageInfo, 'onCurrentChange pageInfo');
              },
              onPageSizeChange(size, pageInfo) {
                console.log(size, 'onPageSizeChange size');
                console.log(pageInfo, 'onPageSizeChange pageInfo');
              },
            }}
          ></Table>`

**Comment by chaishi** [comment]
我来处理下分页的问题

**Comment by uyarn** [comment]
fixed in 0.34.0
