### ISSUE TITLE
[Dialog] 文档描述更新

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#713]
### tdesign-react 版本

vn

### 重现步骤

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/11605702/165886052-b7b42850-7643-4264-bba6-38094d80f0bf.png">

**Comment by Davont** [comment]
React Class 组件, 使用 ref 尝试 this.$dialog 示例:
https://codesandbox.io/s/tdesign-react-demo-forked-l7ztqh?file=/src/demo.jsx

**Comment by HQ-Lin** [comment]
这里不要把跟框架语法糖相关的文案放到common啊，之前是vue自己维护的，怎么搬过去都没有review下
https://github.com/Tencent/tdesign-common/blob/develop/docs/web/api/dialog.md#%E6%8F%92%E4%BB%B6%E5%87%BD%E6%95%B0%E5%BC%8F%E8%B0%83%E7%94%A8

**Comment by Davont** [comment]
已提 PR, 由于需要更改 Common 仓库内的公共描述，故更改地方会涉及其他仓库，PR 列表如下：
tdesign-react: https://github.com/Tencent/tdesign-react/pull/736
tdesign-common: https://github.com/Tencent/tdesign-common/pull/449
tdesign-vue: https://github.com/Tencent/tdesign-vue/pull/849
tdesign-vue-next: https://github.com/Tencent/tdesign-vue-next/pull/727

> 其中 vue 相关的更改，文案不变（vue插件和函数调用都涉及），只更改 md 引用方式。
