### ISSUE TITLE
[Table] 迁移 Vue2 的功能：拖拽调整列宽 和 表尾吸底

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#715]
### tdesign-react 版本

最新版本

### 重现步骤
1. Table 表尾吸底（含横向滚动条吸底）
https://github.com/Tencent/tdesign-vue/pull/810

2. Table 拖拽调整列宽
https://github.com/Tencent/tdesign-vue/pull/757

3. 缺陷处理
https://github.com/Tencent/tdesign-vue/pull/860

4. 拖拽修复
https://github.com/Tencent/tdesign-vue/pull/870

**Comment by chaishi** [comment]
@uyarn 处理中

**Comment by uyarn** [comment]
- [ ]  Table：可筛选输入框梅输入一次或删除一次字符都会失去输入框的焦点

**Comment by chaishi** [comment]
> * [ ]   Table：可筛选输入框梅输入一次或删除一次字符都会失去输入框的焦点

官网最新 table ，不没有这个问题了

**Comment by chaishi** [comment]
拖拽调整列宽，resolved in https://github.com/Tencent/tdesign-react/pull/902
