### ISSUE TITLE
未添加header属性，Card组件布局错误

### ISSUE THREAD

**Issue by xucz** [Tencent/tdesign-react#723]
### tdesign-react 版本

0.32.2

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-yhjrr1?file=/src/demo.jsx

### 期望结果

未添加header属性，Card的布局显示正确

### 实际结果

未添加header属性，Card的布局显示错误

### 框架版本

react17

**Comment by uyarn** [comment]
fixed in 0.32.3
