### ISSUE TITLE
请问一下，表单怎样实现提交的数据是内嵌的对象？比如 {  a: { b: { c: 1 }}}

### ISSUE THREAD

**Issue by Ryqsky** [Tencent/tdesign-react#725]
### 这个功能解决了什么问题

请问一下，表单怎样实现提交的数据是内嵌的对象？
比如 {  a: { b: { c: 1 }}}

我发现 FormItem name="a.b.c" 不行，name=['a', 'b', 'c'] 也不行

### 你建议的方案是什么

支持 {  a: { b: { c: 1 }}}

**Comment by HQ-Lin** [comment]
目前确实是不支持整理成嵌套的数据结构，但应该要支持一下
这版本我处理下吧，支持用数组的方式 `name=['a', 'b', 'c'] `

**Comment by HQ-Lin** [comment]
https://tdesign.tencent.com/react/components/form#%E5%A4%8D%E6%9D%82%E5%B5%8C%E5%A5%97%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E8%A1%A8%E5%8D%95
0.33.2 已支持
