### ISSUE TITLE
[InputNumber]无法输入0.01-0.09

### ISSUE THREAD

**Issue by shryzhang** [Tencent/tdesign-react#727]
### tdesign-react 版本

0.32.2

### 重现链接

https://tdesign.tencent.com/react/components/input-number

### 重现步骤

示例中，输入0.01-0.09，即可复现

### 期望结果

能够输入0.01-0.09

### 实际结果

无法输入0.01-0.09

### 框架版本

React(17.x)

**Comment by fnll** [comment]
看起来是因为`internalInputValue`这个状态是组件内用于储存输入框展示的，它是`string | number` 类型。但是在输入时会调用`strToNumber`尝试把输入数字，所以 0.0 这样的输入就直接被转化成0然后展示到输入框里了

**Comment by HQ-Lin** [comment]
0.32.3 fixed
