### ISSUE TITLE
发现一个文档错误，暗黑模式下，不是给body添加属性，而是html

### ISSUE THREAD

**Issue by vastwu** [Tencent/tdesign-react#73]
![image](https://user-images.githubusercontent.com/3717980/147317845-5fe3a386-9801-4972-9f2f-5decf3cf262a.png)

下面代码写的是正确的

**Comment by chaishi** [comment]
@xiaosansiji 跟进中

**Comment by HQ-Lin** [comment]
感谢反馈，线上已修复
https://tdesign.tencent.com/react/components/dark-mode
