### ISSUE TITLE
[Upload] 设置defaultFiles后未展示内容

### ISSUE THREAD

**Issue by muyanmie** [Tencent/tdesign-react#734]
### tdesign-react 版本

"tdesign-react": "0.32.3-alpha.1"

### 重现链接

https://codesandbox.io/s/nice-shadow-kk3p43?file=/src/index.tsx:78-85

### 重现步骤

打开链接即可复现

### 期望结果

展示给出的默认图片

### 实际结果

没展示

**Comment by uyarn** [comment]
表单组件放在Form里 value(files)会被表单拦截 需要把初始值放在表单里
参考 https://codesandbox.io/s/9n2ve9?file=/src/demo.jsx

**Comment by HQ-Lin** [comment]
https://codesandbox.io/s/inspiring-vaughan-k0tbfk?file=/src/App.tsx
被 `formItem` 包裹的组件会劫持里面的受控属性，要改成 `initialData`
