### ISSUE TITLE
[Select] 已勾选的值，禁用没有生效

### ISSUE THREAD

**Issue by jacksonjin** [Tencent/tdesign-react#740]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/71485170/167357202-5f10b56e-67a4-4498-b4cc-4c2fb3a29fce.png)

### 你建议的方案是什么

暂时没有解决方案

**Comment by PBK-B** [comment]
关于这个 issue 我了解后，注意到 @uyarn 曾经有一个 commit 导致该问题 https://github.com/Tencent/tdesign-react/commit/7b2ebfb8071f9dd0769971a5fa0cd1e1650200cb 这里还原改动是否会涉及什么问题呢？

**Comment by PBK-B** [comment]
@jacksonjin 你是否想要实现部分选项默认选中且对用户禁用？类似下图需求？
![截屏2022-05-13 下午8 40 24](https://user-images.githubusercontent.com/39079814/168286782-63234012-6192-4f8a-a32a-8dd72dae9fb2.png)

**Comment by PBK-B** [comment]
> 关于这个 issue 我了解后，注意到 @uyarn 曾经有一个 commit 导致该问题 [7b2ebfb](https://github.com/Tencent/tdesign-react/commit/7b2ebfb8071f9dd0769971a5fa0cd1e1650200cb) 这里还原改动是否会涉及什么问题呢？

> @uyarn 我尝试修复并进行了相关逻辑的实现，可能对您的 commit 产生了一些颠覆性的改变，麻烦 Review ，没问题之后我将提交 PR。
相关逻辑 commit: https://github.com/PBK-B/tdesign-react/commit/dc67274788f95d65790c304ab49695fdbfa6b833
相关示例 commit: https://github.com/PBK-B/tdesign-react/commit/6bd828517e80bdcdbe65ae98ca58c0492d35eed2

**Comment by uyarn** [comment]
> > 关于这个 issue 我了解后，注意到 @uyarn 曾经有一个 commit 导致该问题 [7b2ebfb](https://github.com/Tencent/tdesign-react/commit/7b2ebfb8071f9dd0769971a5fa0cd1e1650200cb) 这里还原改动是否会涉及什么问题呢？
> 
> > @uyarn 我尝试修复并进行了相关逻辑的实现，可能对您的 commit 产生了一些颠覆性的改变，麻烦 Review ，没问题之后我将提交 PR。
> > 相关逻辑 commit: [PBK-B@dc67274](https://github.com/PBK-B/tdesign-react/commit/dc67274788f95d65790c304ab49695fdbfa6b833)
> > 相关示例 commit: [PBK-B@6bd8285](https://github.com/PBK-B/tdesign-react/commit/6bd828517e80bdcdbe65ae98ca58c0492d35eed2)

我看看

**Comment by HQ-Lin** [comment]
0.34.4 fixed
