### ISSUE TITLE
[Slider] TS 类型错误

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-react#743]
### tdesign-react 版本

0.32.1

### 重现步骤

<img width="894" alt="image" src="https://user-images.githubusercontent.com/35833812/167404404-e7f94db7-83fa-4113-a374-9f324f05a128.png">

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/35833812/167404630-71c44ee2-4e81-489a-9a13-fb32be327668.png">

### 期望结果

inputNumberProps 的类型应为 `InputNumberProps | boolean`

**Comment by andyjxli** [comment]
感谢，我们看下～

**Comment by HQ-Lin** [comment]
0.33.2 fixed
