### ISSUE TITLE
[Input]  样式优化

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-react#750]
### tdesign-react 版本

0.32.1

### 常规态

<img width="509" alt="image" src="https://user-images.githubusercontent.com/35833812/167620360-a0c928c3-ced7-4dbb-a5da-3382e7d5ce41.png">

### 选中态

<img width="541" alt="image" src="https://user-images.githubusercontent.com/35833812/167620226-19e64140-5660-43dc-945b-5fc3ac378be1.png">

### 常规态

<img width="634" alt="image" src="https://user-images.githubusercontent.com/35833812/167620500-6535e5e5-c14f-4842-9d73-d6bc16d2a0d1.png">

### 选中态

<img width="665" alt="image" src="https://user-images.githubusercontent.com/35833812/167620136-acd3ab03-27a8-488a-839d-950fd9a0d84c.png">

问题1: t-input__inner 元素高度占满
问题2: 选中态颜色文字应该为白

**Comment by HQ-Lin** [comment]
我记得设计稿是要有上下padding的，应该是实现的时候漏了
