### ISSUE TITLE
[Table] 同步 Vue 侧功能，支持自定义树形结构图标；支持隐藏排序文本提示

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-react#751]
### 这个功能解决了什么问题

https://github.com/Tencent/tdesign-vue/pull/863
https://github.com/Tencent/tdesign-vue-next/pull/746

参考 Vue3 的代码实现，开发 React

### 你建议的方案是什么

-

**Comment by uyarn** [comment]
- [ ]  Table：可筛选输入框梅输入一次或删除一次字符都会失去输入框的焦点

**Comment by uyarn** [comment]
合并issue跟进 https://github.com/Tencent/tdesign-react/issues/715

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/842

**Comment by HQ-Lin** [comment]
0.35.0 fixed
