### ISSUE TITLE
[Affix] 优化占位节点的创建方式

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#760]
### 这个功能解决了什么问题
之前的展位节点是通过 react dom 操作生成，在频繁的操作会重复开启 affixed，触发多次渲染。新的方式，是通过原生创建占位节点，减少 render 次数

### 你建议的方案是什么？
用 dom 去创建一个节点，在根据状态，插入和删除节点

**Comment by ontheroad1992** [comment]
#759

**Comment by HQ-Lin** [comment]
0.33.2 fixed
