### ISSUE TITLE
[input-number] 能否给`直接输入/增加/删除`添加事件？

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#771]
### 这个功能解决了什么问题

埋点时需要区分是直接输入的还是点击按钮改变的数值。

### 你建议的方案是什么

1. 在 `onChange` 时，顺便返回触发源。
2. 单独开 `onInput`, `onStepIncrease`, `onStepReduce` 接口。

**Comment by chaishi** [comment]
`onInput` 是什么事件，什么时机触发的？

**Comment by chaishi** [comment]
`onStepIncrease` 和 `onStepReduce` 略长，
建议直接使用 `onReduce` 和 `onIncrease`

**Comment by chaishi** [comment]
如果能拿到数据，`onChange` 可以补充上输入的原始数据

**Comment by chaishi** [comment]
`onChange` 事件，已经有参数可以区分 change 的变化来源，应该可以满足 `onStepIncrease ` 和 `onStepReduce `的场景

<img width="845" alt="image" src="https://user-images.githubusercontent.com/11605702/168549381-22920be7-0d9f-4d17-8df4-b0ffdd6aa747.png">

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/react-v2ywmb?file=src%2Fdemo.jsx
可以看下这个demo

**Comment by chaishi** [comment]
比较好奇，需要 `onInput` 输入事件的原因是？

**Comment by moecasts** [comment]
> 比较好奇，需要 `onInput` 输入事件的原因是？

埋点需要区分是直接输入还是点击按钮。

看了下 @HQ-Lin 的例子发现 `onChange` 已经能区分了，`onInput` 也实现了。

谢谢各位大佬解答～
