### ISSUE TITLE
New tabs style

### ISSUE THREAD

**Issue by JokerQyou** [Tencent/tdesign-react#78]
**Is your feature request related to a problem? Please describe.**

No it's not related to a problem.

**Describe the solution you'd like**

It would be nice to have the tab header styled like the tab switch on documentation page:
![image](https://user-images.githubusercontent.com/1465267/147341692-06376277-aedf-4092-9062-6eba0461c7cb.png)

Maybe it could be to add another theme called `switcher` so one would use it like this:

```jsx
      <Tabs placement={'top'} size={'medium'} theme={'switcher'} disabled={false}>
        <TabPanel value={'1'} label={'1'}>
          <div style={{ margin: 20 }}>这是一个Tabs</div>
        </TabPanel>
        <TabPanel value={'2'} label={<div>2</div>}>
          <div style={{ margin: 20 }}>这是一个Tabs</div>
        </TabPanel>
      </Tabs>
```

**Describe alternatives you've considered**

Currently no alternatives. Maybe someone could pull some CSS tricks to achieve similar styling.

**Additional context**

No additional context.

**Comment by chaishi** [comment]
you mean this one ?
https://tdesign.tencent.com/react/components/radio
![image](https://user-images.githubusercontent.com/11605702/147343490-d6bf7c3a-1eae-4d85-be77-0da231bd1568.png)

**Comment by JokerQyou** [comment]
Yeah the styling is pretty similar. But I think that is a tab group instead of a radio group, am I missing something?

**Comment by chaishi** [comment]
I'll tell our designers about radio or tabs.

May I know where you're from?
If you're Chinese ,  we can communicate with 中文

My  Enlish is pool.

**Comment by chaishi** [comment]
or.... If you can reading Chinese,  just like I can reading Enlish.

You can speak English continue, and I  speak Chinese

**Comment by chaishi** [comment]
It can be tab header styled in some situations, also it can be a radio group in another situations.

**Comment by JokerQyou** [comment]
可以用中文，哈哈，只是我不清楚这个项目的语言偏好，就用英文提了。

**Comment by chaishi** [comment]
不过英文有个好处，国际友人方便看。就是得暴露我书面英文垃圾的缺点，哈哈

**Comment by HQ-Lin** [comment]
跟设计师讨论了这个，Tabs 主要还涉及到新增与删除的逻辑，这类样式不太好承载这些交互，所以还需等待下设计侧的规划
