### ISSUE TITLE
[Table] onDragSort 函数无法访问最新的 data 数组

### ISSUE THREAD

**Issue by hurry07** [Tencent/tdesign-react#784]
### tdesign-react 版本

0.33.2

### 重现步骤

const Detail = (props: Props) => {
  const { detail } = props;
  console.log('onLoad', detail);
...

  function onSort() {
    console.log(detail); // 这里的数组永远是 [], 即便外层改变, 也不会改变.
  }

  return (
    <Card
      title='包装明细'
      bordered
      header
      className={Style.detail}
      actions={<Button icon={<AddIcon/>} onClick={onAdd}>添加</Button>}
    >
      <Table
        data={detail}
        rowKey='id'
        tableLayout='auto'
        hover
        dragSort={'row-handler'}
        onDragSort={onSort}
        className={Style.detailRow}
        size={'small'}
        columns={createColumns()}
      />
    </Card>
  );

**Comment by chaishi** [comment]
辛苦提供最新版本，可以复现问题的 Demo 之后，再 reopen 当前 issue 

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/11605702/169661854-36d89db3-2eb1-43c9-95cb-ef3752849f44.png">
