### ISSUE TITLE
[Dialog] DialogPlugin调用时confirmBtn传入TButtonProps不生效

### ISSUE THREAD

**Issue by ArthurYung** [Tencent/tdesign-react#797]
### tdesign-react 版本

tdesign-react@0.34.1

### 重现链接

https://tdesign.tencent.com/react/components/dialog#%E5%87%BD%E6%95%B0%E5%BC%8F%E8%B0%83%E7%94%A8

### 重现步骤

官方文档示例中
```ts
  const onAlert = () => {
    const alertDia = DialogPlugin.alert({
      header: 'Dialog-Alert-Plugin',
      body: 'Notice: Your balance is going to be empty.',
      confirmBtn: {
        content: 'Got it!',
        variant: 'base',
        theme: 'danger',
      },
      onConfirm: ({ e }) => {
        console.log('confirm e: ', e);
        alertDia.hide();
      },
      onClose: ({ e, trigger }) => {
        console.log('close e: ', e);
        console.log('trigger: ', trigger);
        alertDia.hide();
      },
    });
  };
```
confirmBtn无法设置弹窗按钮

### 期望结果

props能对Dialog按钮自定义设置

### 实际结果

无法设置弹窗按钮
<img width="555" alt="image" src="https://user-images.githubusercontent.com/29910365/170184497-168f4e38-1b71-4d36-a767-7df7ea7db0f5.png">

### 框架版本

React 16

**Comment by HQ-Lin** [comment]
考虑到react编写jsx更方便一些所以一开始实现的时候没有支持，近期也完善一下这个逻辑

**Comment by uyarn** [comment]
fixed in 0.34.3

**Comment by HQ-Lin** [comment]
0.34.4 fixed
