### ISSUE TITLE
[Select] 当 multiple 为 true 的时候，筛选(filter)功能无法关闭

### ISSUE THREAD

**Issue by skytt** [Tencent/tdesign-react#801]
### tdesign-react 版本

0.34.3

### 重现链接

https://stackblitz.com/edit/react-epqa4c?file=src%2Fdemo.jsx

### 重现步骤

设置 Select 组件的 multiple 属性为 true，并更改 filterable 的值为 false，观察组件

### 期望结果

当 multiple 为 true，且 filterable 为 false 的时候，组件支持多选，且不能搜索输入

### 实际结果

当 multiple 为 true，且 filterable 为 false 的时候，仍然支持搜索

### 补充说明

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/7420660/170222719-2ef46256-23af-4093-a5c2-56e1a593f8f2.png">

**Comment by HQ-Lin** [comment]
0.34.4 fixed
