### ISSUE TITLE
[loading] 函数方式中 ts 中限制了传入 style、classname 的设置

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#803]
### tdesign-react 版本

0.33.2

### 实际结果

![image](https://user-images.githubusercontent.com/29194619/170441210-7b79f74b-47ba-478b-9139-aea1e32791d3.png)

### 补充说明

![image](https://user-images.githubusercontent.com/29194619/170441415-7bef2534-cf3a-4e74-91be-930e635e415e.png)
TdLoadingProps 不包含 style、classname

**Comment by HQ-Lin** [comment]
0.34.4 fixed
