### ISSUE TITLE
[Skeleton] 非 loading 状态下，多余的 div 影响样式的计算与继承

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#805]
### tdesign-react 版本

0.33.2

### 期望结果

![image](https://user-images.githubusercontent.com/29194619/170460925-aa3b8d42-339f-4233-bfdd-ea98d7927c83.png)
<img width="277" alt="image" src="https://user-images.githubusercontent.com/29194619/170460995-2bfeb7f9-6b83-413d-a41f-e1e48cc95300.png">
![image](https://user-images.githubusercontent.com/29194619/170461091-7e4f66b7-2acb-42e8-a49f-e9ada153f829.png)
这是有效的

### 实际结果

<img width="294" alt="image" src="https://user-images.githubusercontent.com/29194619/170461246-e83f72d4-04ae-4a97-aa2f-b1a75add5ceb.png">
<img width="363" alt="image" src="https://user-images.githubusercontent.com/29194619/170461312-23f20fd4-6c70-4a8f-a5c7-b0ed037bd364.png">
![image](https://user-images.githubusercontent.com/29194619/170461351-29cd3cad-f1e2-44bc-acfb-d8affbaf1a2b.png)

### 补充说明

非 loading 状态下，多余的 div 影响了样式的继承与计算，去掉多余的div应该就可以了

**Comment by ontheroad1992** [comment]
#808

**Comment by HQ-Lin** [comment]
0.34.4 fixed
