### ISSUE TITLE
windows 开发环境运行报错

### ISSUE THREAD

**Issue by psaren** [Tencent/tdesign-react#809]
### mac可以正常运行！

windows 10 运行报错
-  develop 分支
- yarn
- yarn dev

![image](https://user-images.githubusercontent.com/18643034/170520944-ab8faf8b-a108-4721-8ee0-be0b26a44936.png)

**Comment by HQ-Lin** [comment]
在windows 下完整路径的 \ 被vite解析时候丢失了。。我排查下看看
