### ISSUE TITLE
[Table] 树形结构的表格切换页面后点击展开会报错

### ISSUE THREAD

**Issue by HaoyuGu** [Tencent/tdesign-react#816]
### tdesign-react 版本

0.34.3

### 重现链接

https://codesandbox.io/s/2me5lj?file=/src/demo.jsx

### 重现步骤

切换页面后点击“展开/收起可见行”会报错
![image](https://user-images.githubusercontent.com/55372943/170907607-95b95c3a-64b6-481c-bc9c-3ee062ae4b2e.png)

**Comment by chaishi** [comment]
亲爱的，这不是一个问题。

<img width="523" alt="image" src="https://user-images.githubusercontent.com/11605702/172042782-a842be05-ff90-4429-9841-d4ef4a6a1a01.png">

Demo 里面，“展开/收起可见行” 控制的 id 是写死的固定 id，当切换分页的时候。id 完全换成了另外一波数据，之前写死的固定 id 自然不存在了，也就自然报错了。
