### ISSUE TITLE
[Upload] 设置 autoUpload={false}  后，上传错误图片，再上传正确图片，报错信息不消失

### ISSUE THREAD

**Issue by chizhiyiheng** [Tencent/tdesign-react#819]
### tdesign-react 版本

0.34.4-alpha.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-wgo4pd?file=/src/demo.jsx

### 重现步骤

1.  上传一张比较大的图片，报错：图片超过xx M
2. 上传一张大小范围内的正确图片，刚才的报错信息不消失

  const sizeLimit: SizeLimitObj = { size: 2, unit: 'MB', message: '图片大小不能超过 2 MB' };

<Upload
          sizeLimit={sizeLimit}
          tips="上传文件大小在 2M 以内，建议图片尺寸为 88px * 88px"
          accept="image/*"
          theme="image"
          autoUpload={false}
          showUploadProgress={false}
        />

### 期望结果

报错信息消失

### 实际结果

报错信息没消失

**Comment by HQ-Lin** [comment]
0.34.4 fixed
