### ISSUE TITLE
[TagInput ] 中文输入法输入英文然后直接回车会生成标签然后输入的英文也落在输入框里了

### ISSUE THREAD

**Issue by sameenzm** [Tencent/tdesign-react#820]
### tdesign-react 版本

0.32.2

### 重现步骤

中文输入法输入英文然后直接回车会生成标签然后输入的英文也落在输入框里了：
<img width="493" alt="image" src="https://user-images.githubusercontent.com/17029105/170961051-05d1f5b1-0117-4880-b5e2-d6790f592db9.png">

<img width="436" alt="image" src="https://user-images.githubusercontent.com/17029105/170960215-fb472fb9-5b6f-4c12-8896-fe367453d9eb.png">

### 期望结果

只留下标签
<img width="328" alt="image" src="https://user-images.githubusercontent.com/17029105/170960378-77e054f1-069b-4253-bfc0-557ca49661f4.png">

### 框架版本

React(17.0.2)

### 浏览器版本

Chrome(101.0.4951.64)

### 系统版本

MacOS(11.3.1 )

### Node版本

v14.18.2

**Comment by HQ-Lin** [comment]
0.34.4 fixed
