### ISSUE TITLE
[PrimaryTable] rowKey 属性支持函数制定，或者数组指定

### ISSUE THREAD

**Issue by genyuMPj** [Tencent/tdesign-react#825]
### 这个功能解决了什么问题

table 的数据源中可能不存在唯一标识的key，而rowKey 是在
![image](https://user-images.githubusercontent.com/50562327/171121613-29fdae5b-e6bf-45fa-b3f5-b4b0d2dfdfb0.png)
row 中查找，导致无法定义唯一标识的rowKey。
因此，需要支持rowKey 可以是函数或者数组配置

### 你建议的方案是什么

方案1：
支持 函数定义rowKey
`rowKey = (row) => {
return  String(row.key1) + String(row.key12);
}`
方案2： 
支持数组定义rowKey
rowKey: [key1, key2]
按照key1 和key2 查找， 然后拼接起来作为唯一标识

**Comment by chaishi** [comment]
合理需求，倾向支持函数

**Comment by chaishi** [comment]
经过再三思考，组件内部决定不支持这个特性。原因：每一行的唯一标识在组件内部的上百处使用到，每一次获取，每一次渲染都去计算一波，不划算。

建议，在外面先对数据进行初始化，提前组合好一个唯一标识。`data = data.map(row => ({ ...t, id: row.key1 + row.key2 }))`
组件外部处理，一行代码的事情，一次遍历一次计算的事情。
