### ISSUE TITLE
select 组件 禁用状态下还能选择！

### ISSUE THREAD

**Issue by yaogengzhu** [Tencent/tdesign-react#84]
**Describe Framework**

- [x] tdesign-react

Add browser version here

**Describe the bug**
select 禁止选择状态还能继续操作

![image](https://user-images.githubusercontent.com/42566669/147386851-388f4844-8305-4033-8f0b-fce2480ae0c4.png)

**Comment by uyarn** [comment]
0.22.0 fixed . thanks for @yaogengzhu
