### ISSUE TITLE
[Table] expandedRow 被调用两次

### ISSUE THREAD

**Issue by liwl23** [Tencent/tdesign-react#841]
### tdesign-react 版本

0.34.4

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-13v81r

### 重现步骤

1.  查看demo.jsx的第57行，确保其为

```JavaScript
  const expandedRow = ({ row }) => {
    console.log(row);
    return (
      <div className="more-detail">
        <p className="title">
          <b>集群名称:</b>
        </p>
        <p className="content">{row.instance}</p>
        <br />
        <p className="title">
          <b>管理员:</b>
        </p>
        <p className="content">{row.owner}</p>
        <br />
        <p className="title">
          <b>描述:</b>
        </p>
        <p className="content">{row.description}</p>
      </div>
    );
  };
```

2. 清空console；
3. 点击展开按钮；
4. 查看console的输出。

### 期望结果

58行的log输出一次，即expandedRow被调用了一次。

### 实际结果

58行的log输出两次，即expandedRow被调用了两次。

### 框架版本

React(18.2.0)

### 浏览器版本

Edge(102.0.1245.30)

### 系统版本

Window

**Comment by liwl23** [comment]
另外，还有个问题。
1. 在上面的链接里面，把表格拉倒最右边
2. 展开**最后一行**，然后再收起来。
然后可以发现表格最后面多了一列。
上述代码直接来自官方的[示例代码](https://tdesign.tencent.com/react/components/table#%E5%8F%AF%E5%B1%95%E5%BC%80%E5%92%8C%E6%94%B6%E8%B5%B7%E7%9A%84%E8%A1%A8%E6%A0%BC)，唯一的修改在于158行的"bordered"。

**Comment by chaishi** [comment]
`expandedRow` 是渲染 DOM 的函数，被调用两次多是因为有多类数据发生了变化。
比如 `expandedRow` 渲染 DOM 依赖 data 和 expandedKeys，当这两个数据都发生变化时，自然会执行两次 `expandedRow`。

没有明白一个渲染执行 2 次，会有什么问题

**Comment by liwl23** [comment]
把代码简化了一下，可以看[这个](https://codesandbox.io/s/tdesign-react-demo-forked-e7bfob?file=/src/demo.jsx)。
在上述代码中，data是固定的，展开某一行*仅仅*会改变expandedKey，但是展开任意一行都会令expandedRow调用两次。

只是不明白，为什么渲染一次需要调expandedRow两次。

**Comment by liwl23** [comment]
另外还有另一个问题，对于(这里)[https://codesandbox.io/s/tdesign-react-demo-forked-e7bfob?file=/src/demo.jsx]的第二行。把它收起之后的页面显示有问题。
1. 最初的表格中有两行两列，如下图：
![](https://github.com/liwl23/pictures/raw/main/%E5%88%9D%E5%A7%8B%E7%8A%B6%E6%80%81.png)
2. 把它展开之后没什么问题：
![](https://github.com/liwl23/pictures/raw/main/%E5%B1%95%E5%BC%80.png)

2. 但是把它收起来就会发现，最右侧似乎多了一列？：
![](https://github.com/liwl23/pictures/raw/main/%E5%86%8D%E6%94%B6%E8%B5%B7.png)

**Comment by chaishi** [comment]
多出来的“那一列”问题已经明白哈，不用再单独描述。

那其实不是多出来的列，只是多出来一条右边线。下周处理
