### ISSUE TITLE
[EnhancedTable] 表格树组件默认展开时视图渲染错乱 ，急！！！

### ISSUE THREAD

**Issue by Alex-is-coding** [Tencent/tdesign-react#845]
### tdesign-react 版本

最新版本可复现

### 重现链接

https://stackblitz.com/edit/react-bc1mey-vjedvk?file=src%2Fdemo.jsx

### 重现步骤

默认展开表格树，见示例 [EnhancedTable](https://stackblitz.com/edit/react-bc1mey-vjedvk?file=src%2Fdemo.jsx)

### 期望结果

默认展开树正常显示

### 实际结果

默认展开树 第一级不显示

**Comment by chaishi** [comment]
默认展开的功能好像还没有发布呀

**Comment by chaishi** [comment]
提供的链接，如下图所示，哪里乱了啊，看不懂问题。着急的话，要先把问题描述清楚呀，不然也帮不上

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/11605702/172122908-4340ee65-f9fc-4b16-a3a1-849bfa29b917.png">

**Comment by chaishi** [comment]
请使用最新版本：0.34.5-alpha.1
