### ISSUE TITLE
【MenuItem】onClick事件处理，选中状态禁止点击

### ISSUE THREAD

**Issue by leosxie** [Tencent/tdesign-react#847]
### 重现链接
https://codesandbox.io/s/6f7nyy?file=/src/demo.jsx

### 重现步骤
选中的菜单，点击，无响应

### 期望结果
期望选中的菜单点击也能有响应

### 实际结果
选中的菜单点击无响应

| Environment | Info |
|---|---|
| 相关版本 | 0.34.4 |
| 框架版本 / 基础库版本 | React |
| 系统、浏览器 | 无 |
| Node版本 | 无 |

**Comment by HQ-Lin** [comment]
0.35.0 fixed
