### ISSUE TITLE
使用 React@18 createRoot Mode 来启动 APP 时，会默认校验表单

### ISSUE THREAD

**Issue by feibinyang** [Tencent/tdesign-react#850]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-u95let

### 重现步骤
用 chrome 打开链接即可看到

### 期望结果
默认不校验

### 实际结果
默认校验

### 补充说明
当使用 ReactDOM.render 函数启动时，就不会默认校验

| Environment | Info |
|---|---|
| 相关版本 | 0.34.4 |
| 框架版本 / 基础库版本 | React@18.1.0 |
| 系统、浏览器 | Chrome  101.0.4951.64 |
| Node版本 |  |

**Comment by HQ-Lin** [comment]
React 18 在开发模式严格模式下会执行两次 useEffect ，我看看怎么处理好点
https://www.techiediaries.com/react-18-useeffect/

**Comment by HQ-Lin** [comment]
https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors

**Comment by HQ-Lin** [comment]
逻辑已调整为不依赖初始化判断来跳过首次数据变化触发校验，之后在 React 18 下也不会渲染时校验了
https://github.com/Tencent/tdesign-react/pull/1076

**Comment by HQ-Lin** [comment]
0.37.0 fixed
