### ISSUE TITLE
【StepItem】value not work

### ISSUE THREAD

**Issue by zousandian** [Tencent/tdesign-react#852]
<img width="1138" alt="企业微信截图_199c0a5c-7176-4021-a261-33d05d6dded1" src="https://user-images.githubusercontent.com/6047274/172513434-561faac8-461d-4bcc-be06-dcad750842fe.png">
当 StepItem 是动态拼装的，需要手动设置步骤标识。
v0.33.2 之前， `<StepItem value={2}></StemItem>` 是可以正常显示的，现在显示 NaN 了。
<img width="56" alt="image" src="https://user-images.githubusercontent.com/6047274/172514113-27ce66fd-5fd9-4c77-9092-49b90a4d3de9.png">

v0.33.2 开始，要改成 `<StepItem index={2}></StemItem>`才能正常显示标识。是否符合预期？
<img width="49" alt="image" src="https://user-images.githubusercontent.com/6047274/172514193-22849954-b9f8-41c6-9350-d32155df1c6f.png">

相关代码：
https://github.com/Tencent/tdesign-react/blob/7e39b5b50c3cc891c2ccbb89ed7ed18bde4e606f/src/steps/StepItem.tsx#L42

**Comment by HQ-Lin** [comment]
能否提供个在线demo 方便调试问题

**Comment by zousandian** [comment]
> Reference

https://codesandbox.io/s/tdesign-react-demo-forked-lews4b

**Comment by HQ-Lin** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/24469546/172582345-ba778f54-6d65-4164-a7e1-ba47cb2f0031.png">

https://codesandbox.io/s/tdesign-react-demo-forked-0r936g?file=/src/demo.jsx

自定义的组件编写不规范没有透传相关props，调整下就好了
