### ISSUE TITLE
[Upload] accept属性赋值时，image/svg 不能选择svg文件。.svg才可以选择

### ISSUE THREAD

**Issue by chizhiyiheng** [Tencent/tdesign-react#853]
### tdesign-react 版本

^0.34.4

### 重现步骤

<Upload
          sizeLimit={sizeLimit}
          tips="上传文件大小在 2M 以内，建议图片尺寸为 88px * 88px"
          accept="image/png, image/svg, image/jpeg, image/jpg"
          theme="image"
          autoUpload={false}
          showUploadProgress={false}
        />
无法选择svg文件。改成accept="image/png, .svg, image/jpeg, image/jpg"后可以选svg文件

### 期望结果

 accept="image/png, image/svg, image/jpeg, image/jpg" 这样也可以选择svg文件

**Comment by HQ-Lin** [comment]
W3C 规范中要求的是 image/svg+xml，改成这个就好了
https://www.w3.org/TR/SVG/mimereg.html

https://stackblitz.com/edit/react-2yvpyb?file=src%2Fdemo.jsx
