### ISSUE TITLE
[input-number] 点击减少按钮时触发两次 onChange

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#854]
### tdesign-react 版本

tdesign-react

### 重现链接

https://codesandbox.io/s/nkhqjy?file=/src/demo.jsx

### 重现步骤

第二次后点击减少按钮，onChange 触发发两次。
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/37169906/172558521-3f48b37e-661b-49cf-8c88-ae010dccbe29.png">

### 期望结果

每次减少只触发一次 onChange

### 实际结果

每次减少触发了两次 onChange

**Comment by HQ-Lin** [comment]
0.35.0 fixed
