### ISSUE TITLE
[Drawer] 取消按钮 文案更改无效

### ISSUE THREAD

**Issue by yuchenfang** [Tencent/tdesign-react#855]
### tdesign-react 版本

0.33.2

### 重现链接

https://git.woa.com/biz-ria/xunda/xunda-crm-web/blob/feat/1.4.1/src/pages/Buz/manufacturer/components/edit.tsx

### 重现步骤

190行，最终展现始终都是 取消，  另一个按钮则能够匹配文案

### 框架版本

react(0.33.2)

### Node版本

14.17.0

**Comment by yuchenfang** [comment]
业务代码问题，抱歉

**Comment by yuchenfang** [comment]
还是有问题，cancelBtn   和onCancel   好像都没生效

**Comment by HQ-Lin** [comment]
cancelBtn 和 confirmBtn 字符串支持有点问题，这周处理下，可以先用 jsx 处理下
```
cancelBtn={<Button>取消</Button>}
```

**Comment by HQ-Lin** [comment]
0.35.0 fixed
