### ISSUE TITLE
bug: drawer 收起的样式有问题

### ISSUE THREAD

**Issue by mortalYoung** [Tencent/tdesign-react#86]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

- browser: Chrome
- tdesign-react: 官网版本

**Describe the bug**

复现地址：https://tdesign.tencent.com/react/components/drawer?tab=demo#%E4%B8%8D%E5%90%8C%E4%BD%8D%E7%BD%AE%E7%9A%84%E6%8A%BD%E5%B1%89

把 `placement` 改成 `top` 后，drawer 的收起显然没有其他位置流畅，有一个先关闭蒙层再收起抽屉的过程

**Additional context**

**Comment by HQ-Lin** [comment]
drawer 从上到下缺少了 transform 的动画效果，这边补一下

**Comment by HQ-Lin** [comment]
https://github.com/Tencent/tdesign-common/pull/60/files fixed

**Comment by uyarn** [comment]
fixed 0.22.0
