### ISSUE TITLE
[upload] 选中.flv格式文件后返回的文件类型（type字段）为空

### ISSUE THREAD

**Issue by tengcaifeng** [Tencent/tdesign-react#861]
### tdesign-react 版本

0.34.4

### 补充说明

选中.mp4, .avi等文件是有正确返回文件类型值的

**Comment by wookaoer** [comment]
> ♥️ 有劳 @wookaoer @teal-front @carolin913 尽快确认问题。 确认有效后将下一步计划和可能需要的时间回复给 @tengcaifeng 。

收到，我尽快处理

**Comment by HQ-Lin** [comment]
https://stackoverflow.com/questions/65165897/html-input-element-type-file-flv-file-not-a-valid-mime-file
看起来是浏览器没办法识别 flv 的mime-type
