### ISSUE TITLE
[EnhancedTable] 表格树组件使用table.current.setData()方法加进去的数据，子节点的padding值没有了 Bug

### ISSUE THREAD

**Issue by Alex-is-coding** [Tencent/tdesign-react#865]
### tdesign-react 版本

最新版本可复现

### 重现步骤

![wecom-temp-a13b94d691870fd97ae894ef4ed33b26](https://user-images.githubusercontent.com/49911480/172984408-4f8ec721-d10d-47fe-9138-dd880016ce73.png)

EnhancedTable 表格树组件使用table.current.setData()方法加进去的数据，子节点的padding值没有了 

### 期望结果

EnhancedTable 表格树组件使用table.current.setData()方法加进去的数据，子节点样式显示正常

### 框架版本

"tdesign-react": "^0.34.5-alpha.3"

**Comment by chaishi** [comment]
下次提 issue，记得提供下代码，至少数据给一下
