### ISSUE TITLE
Skeleton组件使用时ts报错：'Skeleton' cannot be used as a JSX component

### ISSUE THREAD

**Issue by CuzyouZQL** [Tencent/tdesign-react#874]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-pch5c5?file=/src/demo.tsx

### 重现步骤
开启ts检查时出现'Skeleton' cannot be used as a JSX component

### 期望结果
没有出现ts报错

### 实际结果
使用时出现了ts报错

| Environment | Info |
|---|---|
| 相关版本 | 0.35.0 |
| 框架版本 / 基础库版本 | react17.0.16 |
| 系统、浏览器 | macOs |
| Node版本 |  |

**Comment by uyarn** [comment]
fixed in 0.35.1
