### ISSUE TITLE
[Anchor]组件类型修改

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#880]
### tdesign-react 版本

0.35.0

### 重现步骤

<img width="1379" alt="企业微信截图_b111c2e7-c0ee-4baf-ab96-06702853c4a9" src="https://user-images.githubusercontent.com/32590310/173484658-75c8fcfd-74ab-4ca3-9212-ef7f3106c452.png">

### 期望结果

`affixProps`的`children`属性应该去掉

**Comment by ontheroad1992** [comment]
这个错误已经定位到了，谢谢你的帮助

**Comment by southorange1228** [comment]
这个改法有问题吧...`Affix`本身这个chilren应该是必填的？只是在`Anchor`组件中这个属性不是必须的。准确来说应该是去掉的？应该被Omit掉？
@uyarn
