### ISSUE TITLE
[Table] Table支持列宽度调整

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#884]
### 这个功能解决了什么问题

https://tea-design.github.io/component/table/%E5%88%97%E5%AE%BD%E5%BA%A6%E8%B0%83%E6%95%B4

### 你建议的方案是什么

表格支持列宽度调整

**Comment by chaishi** [comment]
Vue2 已经支持，React 在路上了

**Comment by chaishi** [comment]
issue 重复，请关注 https://github.com/Tencent/tdesign-react/issues/715

关闭重复 issue

**Comment by chaishi** [comment]
拖拽调整列宽，resolved in https://github.com/Tencent/tdesign-react/pull/902
