### ISSUE TITLE
[Table] 表尾吸底不生效

### ISSUE THREAD

**Issue by southorange1228** [Tencent/tdesign-react#885]
### tdesign-react 版本

0.35.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-eodg63?file=/src/demo.jsx

### 期望结果

表尾吸底生效。
不知道是不是我写的代码有问题。
看了下源码 并没有对`TFoot`使用`Affix`包裹
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/32590310/173723055-245879ea-7320-4b9e-bad5-c72f6007905f.png">

代码中也没有此属性的引用。
<img width="357" alt="image" src="https://user-images.githubusercontent.com/32590310/173723167-020d1ed2-159f-4942-98b1-46a5ba18f038.png">

**Comment by southorange1228** [comment]
#715 开发中？

**Comment by chaishi** [comment]
对，开发中，请关注 #715
当前 issue 重复，关闭

**Comment by chaishi** [comment]
feature resolved in https://github.com/Tencent/tdesign-react/pull/902
