### ISSUE TITLE
[Table] 数据为空时，自定的 empty 无法撑开表格

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-react#886]
### tdesign-react 版本

0.35.0

### 重现链接

https://stackblitz.com/edit/react-5qlve5?file=src%2Fdemo.jsx

### 重现步骤

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/29194619/173729127-a6edb101-2fda-4a0d-af52-57749ff3eea1.png">

**Comment by chaishi** [comment]
不明白无法撑开表格是什么意思，都自定义 empty 了，高度不是完全可以自己定的么

**Comment by chaishi** [comment]
不明白，是希望调整表格高度，还是调整空元素高度。
如果是为了撑开表格，则属于方式不对，并不能使用空元素来让表格的高度变高。请更为使用 `<t-table height={400} />`

**Comment by ontheroad1992** [comment]
> 不明白，是希望调整表格高度，还是调整空元素高度。
> 
> 示例代码里面，既写了 `<t-table maxHeight={fixedTopAndBottomRows ? 500 : 300} />` 又写了 `empty={<div style={{ height: '400px' }}>空</div>}`，所以，你是想表格高度为 300？400？还是 500？表格懵了，我也懵了
> 
> 如果想要使用 `empty` 撑开表格高度，两个选择：1. maxHeight 的值设置的大于 empty 元素高度；2. 删除代码中的 `maxHeight` 属性

拜托，你去世纪尝试下可以吗？就就简单跟着我上面的红色标记区域去看一下，就知道了额，自定义的 empty 被一个 t-table__empty 节点包裹着了，他的 css 样式写死了高度，下级节点无法撑开
也麻烦你，既然要给解决方案，就给一个 demo, 不要臆想代码，浪费时间

**Comment by HQ-Lin** [comment]
这里的问题是想说 `t-table__empty` 样式限制了高度导致了内部元素希望变得更大或更小的时候没办法实现吧
