### ISSUE TITLE
[Upload] 传入files删除图片后无法上传图片

### ISSUE THREAD

**Issue by liuyizhou** [Tencent/tdesign-react#898]
### tdesign-react 版本

0.35.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-gepy1i?file=/src/demo.jsx

### 重现步骤

组件传入files，删除图片后，beforeUpload api不生效

### 期望结果

删除后正常触发上传

### 实际结果

无法继续上传

### 框架版本

react 17.0

### 补充说明

需要传入files的受控场景

**Comment by teal-front** [comment]
![image](https://user-images.githubusercontent.com/5626638/174212572-ef931c9f-4fa0-4fee-800d-946410acdb09.png)

加上onChange就可以了。

**Comment by liuyizhou** [comment]
已解决
