### ISSUE TITLE
Pagination 组件 mouseOver 状态有闪烁

### ISSUE THREAD

**Issue by mortalYoung** [Tencent/tdesign-react#90]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

Add browser version here
- browser: Chrome
- version: 官网版本

**Describe the bug**
- 鼠标 mouseOver 到 Pagination 组件的 __number--more 的时候，在该 li 上来回移动的时候，该 li 不断闪烁。

官网版本稳定复现 https://tdesign.tencent.com/react/components/pagination#%E5%B0%91%E9%87%8F%E9%A1%B5%E9%9D%A2

**Comment by HQ-Lin** [comment]
收到，今日处理下

**Comment by andyjxli** [comment]
fixed: https://github.com/Tencent/tdesign-react/pull/92

**Comment by uyarn** [comment]
fixed 0.22.0
