### ISSUE TITLE
Message  close 关闭无响应

### ISSUE THREAD

**Issue by yaogengzhu** [Tencent/tdesign-react#91]
**Describe Framework**

- [x] tdesign-react

**Describe Environment**

**Describe the bug**
Message close 点击关闭，无响应！

**Additional context**

![image](https://user-images.githubusercontent.com/42566669/147408890-432d5ea6-d556-4f46-b4b7-6517dd0c5dee.png)

**Comment by HQ-Lin** [comment]
当前 demo 仅用来展示 message 组件的 ui 状态，所以没有处理 close 关闭事件
