### ISSUE TITLE
[Dialog] 内嵌input框不能输入中文

### ISSUE THREAD

**Issue by fatWill** [Tencent/tdesign-react#910]
### tdesign-react 版本

最新版本

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-83tqn4?file=/src/demo.jsx:237-261

### 重现步骤

直接在input框输入，不能输入中文

### 框架版本

React

**Comment by southorange1228** [comment]
非`Dialog`组件问题，`input`元素本身的问题。
https://segmentfault.com/a/1190000039802807
@fatWill
