### ISSUE TITLE
优化暗黑模式下 demo 背景色

### ISSUE THREAD

**Issue by ZZZCNY** [Tencent/tdesign-react#912]
### tdesign-react 版本

0.35.1

### 重现步骤

分页控件建议左右留 `8px` 的空白

![image](https://user-images.githubusercontent.com/59002875/174692926-e993fd15-ad08-45ef-9fc9-fd9214929809.png)

**Comment by chaishi** [comment]
我之前也提过这个，后来没消息了

**Comment by ZZZCNY** [comment]
我认为并不只是暗黑模式下的问题，只不过刚好在浅色模式下背景色相同，所以你们认为没问题。
![image](https://user-images.githubusercontent.com/59002875/176996775-ce2a6da4-a4f5-4548-8af7-67f98331890b.png)

**Comment by ZZZCNY** [comment]
建议将 `#app > td-doc-layout > td-doc-content > div:nth-child(3) > div.tdesign-demo-wrapper.tdesign-demo-item--table-base.tdesign-demo-item--table > td-doc-demo > div.tdesign-demo-item__body` 的 `background-color` 改为 `#242424`，显示效果将与浅色模式相同。
![image](https://user-images.githubusercontent.com/59002875/176997054-f3762212-9cc8-40f0-a1f9-28d7a74812d8.png)

**Comment by uyarn** [comment]
> 建议将 `#app > td-doc-layout > td-doc-content > div:nth-child(3) > div.tdesign-demo-wrapper.tdesign-demo-item--table-base.tdesign-demo-item--table > td-doc-demo > div.tdesign-demo-item__body` 的 `background-color` 改为 `#242424`，显示效果将与浅色模式相同。 ![image](https://user-images.githubusercontent.com/59002875/176997054-f3762212-9cc8-40f0-a1f9-28d7a74812d8.png)

@ZZZCNY 确实是demo的Body bg color的问题 我们调整一下

**Comment by Wen1kang** [comment]
设计这里其实原来是有留左右16px的间距，在设计稿也是如此，但是考虑到使用场景，这里定义了固定数值的margin会导致组件在其他地方使用不够灵活，建议自己在div下设置个左右16px或者8px的padding哦，这样会好些，设置死会比较不灵活

**Comment by ZZZCNY** [comment]
> 设计这里其实原来是有留左右16px的间距，在设计稿也是如此，但是考虑到使用场景，这里定义了固定数值的margin会导致组件在其他地方使用不够灵活，建议自己在div下设置个左右16px或者8px的padding哦，这样会好些，设置死会比较不灵活

主要是你们的demo有点丑，把bg color改下就好

**Comment by chaishi** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/11605702/179215454-046b98a4-a5e7-4024-b8b5-e2893f9a6034.png">

可能不仅仅是 暗黑模式的问题，在普通的卡片模式，也会存在贴边的问题
