### ISSUE TITLE
[Select] 支持展开下拉框时，点击输入框位置可以收起下拉框

### ISSUE THREAD

**Issue by feibinyang** [Tencent/tdesign-react#919]
### 这个功能解决了什么问题

目前 tdesign Select 组件在下拉框展开时，不支持点击输入框收起下拉框（只支持选中选项或者 blur 时才收起），我司设计师倾向于点击输入框也可以收起下拉框，希望官方可以提供这个能力。

另外我看了 antd 的交互，他们是支持的。https://ant.design/components/select/

### 你建议的方案是什么

点击输入框可以展开下拉框，再点击输入框可以收起下拉框。

**Comment by chaishi** [comment]
不支持，交互如此
