### ISSUE TITLE
[TagInput/Select] 能否自动换行

### ISSUE THREAD

**Issue by zousandian** [Tencent/tdesign-react#926]
### 这个功能解决了什么问题

当需要输入较多选项时，例如员工选择器需要输入较多员工时，单行体验较差
<img width="896" alt="image" src="https://user-images.githubusercontent.com/6047274/175238488-bbaf27ae-9e85-4552-9f44-8eed123c06a0.png">

### 你建议的方案是什么

支持自动换行显示

**Comment by chaishi** [comment]
#### 辛苦看下文档，可以换行

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11605702/175239526-e8cbefa6-5488-4c77-84fa-d298fa2dbdf0.png">

**Comment by chaishi** [comment]
后面会改成默认换行
