### ISSUE TITLE
Component about Button, the text on the button is invisible about ghost

### ISSUE THREAD

**Issue by makerhou** [Tencent/tdesign-react#944]
![image](https://user-images.githubusercontent.com/22055477/175452013-9dee2c77-44f4-4b65-9c18-e4f0db8e53af.png)

**Comment by chaishi** [comment]
copy that

**Comment by HQ-Lin** [comment]
ghost 本意是希望按钮背景色置为透明，但是这里由于文字颜色与底色都是白色导致了文字看不见，我们讨论下看看要怎么优化

**Comment by Wen1kang** [comment]
We will fix the bug with ghost button demo background color.
