### ISSUE TITLE
[Table] 合并单元格功能搭配翻页功能时表格显示混乱

### ISSUE THREAD

**Issue by GrinZero** [Tencent/tdesign-react#966]
### 重现链接
https://codesandbox.io/s/tdesign-react-demo-forked-ss2lgi?file=/src/demo.jsx

### 重现步骤
1. 翻页前，console区已经开始报错`TDesign Table Error: rowKey is wrong, can not get unique identifier of row. `，同时表格渲染了两次
2. 翻页后，单元格异常合并。

### 期望结果
单元格正常合并，无奇怪的报错

### 实际结果
单元格异常合并，显示异常

### 补充说明
同时rowspanAndColspan的可用性并不是很高，期待可以自动合并

| Environment | Info |
|---|---|
| 相关版本 | 0.35.1 |
| 框架版本 / 基础库版本 | React(17.0.2) |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by GrinZero** [comment]
同时表格呈现了两个-->同时表格呈现了两轮调用rowspanAndColspan

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1028

https://user-images.githubusercontent.com/11605702/176993815-26408023-74be-4776-9191-802bb30ea2b3.mov

**Comment by GrinZero** [comment]
那啥，修好了？我看视频第二页仍没合并单元格来着

**Comment by HQ-Lin** [comment]
0.36.2 fixed
