### ISSUE TITLE
[textarea] 组件定义maxrows没有生效，得输入部分focus的时候才会展开

### ISSUE THREAD

**Issue by booyangcc** [Tencent/tdesign-react#968]
### tdesign-react 版本

16

**Comment by HQ-Lin** [comment]
https://stackblitz.com/edit/react-16nniq?file=src%2Fdemo.jsx
没有复现你说的问题，能否给个demo看看

`maxRows` 意思是最多展示几行，当文字行数超过后会出现滚动条，如果你希望一开始就展示几行，应该使用 `minRows`

**Comment by booyangcc** [comment]
> 

minrows和maxrows均设置20试试看

**Comment by carolin913** [comment]
直接设置rows即可，原生属性，已解决

**Comment by HQ-Lin** [comment]
> https://stackblitz.com/edit/react-16nniq?file=src%2Fdemo.jsx 没有复现你说的问题，能否给个demo看看
> 
> `maxRows` 意思是最多展示几行，当文字行数超过后会出现滚动条，如果你希望一开始就展示几行，应该使用 `minRows`

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/24469546/177086707-2f7f2985-990a-4181-b95b-5e362c11069e.png">
都设置20那也是按照 minrows来展示依然没有你说的问题
