### ISSUE TITLE
能否支持sass样式引用

### ISSUE THREAD

**Issue by kemistep** [Tencent/tdesign-react#969]
### 这个功能解决了什么问题

默认使用的sass，但是模板是less，可以提供sass样式吗？

### 你建议的方案是什么

提供选择，避免过多依赖；

**Comment by HQ-Lin** [comment]
暂时没有这个规划，考虑到维护和开发成本只使用 less 工具开发样式就足够了没必要把 sass、stylus 都搞一遍
后续甚至可能把 less 工具移除，完全使用 css variable + postcss后处理器来开发管理样式文件

**Comment by kemistep** [comment]
> 暂时没有这个规划，考虑到维护和开发成本只使用 less 工具开发样式就足够了没必要把 sass、stylus 都搞一遍 后续甚至可能把 less 工具移除，完全使用 css variable + postcss后处理器来开发管理样式文件

那也挺好的，纯原生的最好了，安装依赖太多了，还容易出问题；
