### ISSUE TITLE
[slider] inputNumberProps 能否支持传入theme

### ISSUE THREAD

**Issue by dufemeng** [Tencent/tdesign-react#970]
### 这个功能解决了什么问题

 inputNumberProps 支持传入theme

### 你建议的方案是什么

<img width="588" alt="截屏2022-06-25 15 18 10" src="https://user-images.githubusercontent.com/10006784/175763076-95e72277-33f9-4c1a-ae1b-a9e69b2c100d.png">

**Comment by HQ-Lin** [comment]
目前来看 column 主题在 slider 组件中应该是最美观的才对，为何还会想改成别的主题
由于设计稿只提供了一种形态，所以这边组件实现的时候也没有把这个设置开放出去

**Comment by dufemeng** [comment]
> 目前来看 column 主题在 slider 组件中应该是最美观的才对，为何还会想改成别的主题 由于设计稿只提供了一种形态，所以这边组件实现的时候也没有把这个设置开放出去

<img width="351" alt="截屏2022-06-27 17 13 43" src="https://user-images.githubusercontent.com/10006784/175904606-8b8f5b36-1211-4203-8989-b4e132fa7f1f.png">
设计稿是长这个样子

**Comment by southorange1228** [comment]
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/32590310/175908088-53ddb1e1-1128-41fc-a56f-bbca7381c133.png">
这个无法满足吗？
