### ISSUE TITLE
[Form表单] number 校验规则不生效

### ISSUE THREAD

**Issue by tyanbiao** [Tencent/tdesign-react#971]
### tdesign-react 版本

0.35.1

### 重现链接

https://stackblitz.com/edit/react-urdptp?file=src/demo.jsx

### 重现步骤

按照文档为 FormItem 设置校验规则 `{ number: true, message: '年龄必须是数字', type: 'error'}`，输入非数字内容不会提示错误

```TypeScript
        <FormItem
          label="年龄"
          name="age"
          initialData={35}
          rules={[
            { required: true, message: '年龄必填', type: 'error' },
            { number: true, message: '年龄必须是数字', type: 'error' },
            { min: 0, message: '年龄不能小于0', type: 'error' },
          ]}
        >
          <Input />
        </FormItem>
```

### 期望结果

输入非数字类型提示错误

### 实际结果

非数字内容能通过校验，未提示错误
![image](https://user-images.githubusercontent.com/19632522/175763965-2f3d94e0-fb38-4e4e-9f8e-6871c9efd779.png)

### 框架版本

React(17.0.2)

### 浏览器版本

Microsoft Edge Version 102.0.1245.44 (Official build) (64-bit)

### 系统版本

Windows 10

### Node版本

v16.13.1

**Comment by HQ-Lin** [comment]
确实有问题，今天发版本一起修复

**Comment by HQ-Lin** [comment]
0.36.0 fixed

**Comment by HQ-Lin** [comment]
这里这么改还是会有问题，input返回的都是字符串哪怕你输入的是阿拉伯数字
但是又有场景是类似于qq号这种需要比较数字字符串长度
所以如果要比较数字大小的，还是自己写validator去比较一下
在0.37.1版本会改回去

**Comment by HQ-Lin** [comment]
> 似乎文档还没有更新，看了一下，不知道应该从哪里给文档提 Issue 🤔
> 
> https://tdesign.tencent.com/react/components/form?tab=api#formrule
> 
> <img alt="屏幕截图 2022-07-20 165513" width="585" src="https://user-images.githubusercontent.com/19632522/179941722-16309663-edbc-4ee1-b960-2a5ed6f4bf75.png">

文档没有问题啊，input输入的值返回的都是string，只是你以为你输入的是number而已，如果你自己封装一个 CustomInput 强转成number在给到 form表单，我也可以自动转成校验数字大小
