### ISSUE TITLE
[Table] 表格排序点击多次会报错，TypeError Cannot read properties of null (reading 'getBoundingClientRect')

### ISSUE THREAD

**Issue by yancekang** [Tencent/tdesign-react#986]
### tdesign-react 版本

0.35.1

### 重现链接

https://codesandbox.io/s/suspicious-sunset-wrd7tt?file=/src/App.tsx

### 框架版本

React 18

### Node版本

14.15.1

**Comment by uyarn** [comment]
这个问题应该是修复了 今天的0.35.2版本会发布 如果着急用 可以先用0.35.2-alpha.9 或者i tdesgin-react@alpha

**Comment by HQ-Lin** [comment]
0.36.0 fixed

**Comment by yancekang** [comment]
感谢
