### ISSUE TITLE
[upload] draggable 时无法定义theme='custom'

### ISSUE THREAD

**Issue by dufemeng** [Tencent/tdesign-react#991]
### 这个功能解决了什么问题

希望draggable时也可以定义theme='custom'

### 你建议的方案是什么

无

**Comment by chaishi** [comment]
自定义上传应该支持拖拽上传的

<img width="494" alt="image" src="https://user-images.githubusercontent.com/11605702/177566506-30216b28-311f-4edf-bf7e-305d5d217527.png">
