### ISSUE TITLE
[Table]编辑功能使用到的 react 版本问题

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#993]
### tdesign-react 版本

0.36.0

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lsjk22

### 重现步骤

table 的可编辑功能，当 react 和 react-dom 版本低于 17.0.0 时，就会出现“点击单元格使其变为可操作的组件时，再次点击立即取消了编辑状态”这个问题。

### 期望结果

期望能够支持低版本的 react 这个功能， 或者说在文档中详细说明要求的版本最低为多少

**Comment by chaishi** [comment]
我们支持低版本 React

**Comment by HQ-Lin** [comment]
0.36.2 fixed

**Comment by chaishi** [comment]
https://codesandbox.io/s/tdesign-react-demo-forked-rrkk0e


https://user-images.githubusercontent.com/11605702/177103008-38a73662-24ef-4a9e-9926-2b0c2122dcc9.mov
