### ISSUE TITLE
[Table]可编辑功能，数据更新迟一步，第二次修改不更新

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#994]
### tdesign-react 版本

0.36.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-lsjk22

### 重现步骤

select 单元格， 第一次修改是正常的，但是第二次修改就会出现数据不更新的情况

### 期望结果

修复 bug

### 框架版本

react@17.0.2

**Comment by chaishi** [comment]
可编辑功能，都是直接透传数据和参数的，组件内部没有维护任何数据状态。

辛苦检查下自己的数据

**Comment by fangxiezhen** [comment]
> 可编辑功能，都是直接透传数据和参数的，组件内部没有维护任何数据状态。
> 
> 辛苦检查下自己的数据

官网的例子就能复现这个问题，也辛苦看下这是否是合理的

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1028

https://user-images.githubusercontent.com/11605702/176995323-30bc401d-13cb-4604-bf10-925a71438242.mov

**Comment by HQ-Lin** [comment]
0.36.2 fixed
