### ISSUE TITLE
[Table] 编辑功能的 edit 配置期望增加 api 获取行数据

### ISSUE THREAD

**Issue by fangxiezhen** [Tencent/tdesign-react#995]
### 这个功能解决了什么问题

期望能在 edit 配置中增加获取该行数据的渠道
使用场景例如：行有两个 select 框，后者框的选项依赖于前者的选择项，但是现有的 api，无法在 edit 配置中获取到该行，所以无法进行判断

### 你建议的方案是什么

可以把 edit 配置由 object，兼容增加出 （context）=> edit 。
或者有更好的方式来帮助实现单元格之间的联动效果。
期待回复

**Comment by chaishi** [comment]
> 现有的 api，无法在 edit 配置中获取到该行，所以无法进行判断

截图中，不是有每次变化的行数据 和 rowIndex 么。是否尝试过

<img width="850" alt="image" src="https://user-images.githubusercontent.com/11605702/176088683-af5030d5-cb1c-4cd5-8054-a51e85119d8d.png">

**Comment by chaishi** [comment]
需求整体描述有点抽象，看不太明白，不知如何支持

**Comment by fangxiezhen** [comment]
> 需求整体描述有点抽象，看不太明白，不知如何支持

例如，
![image](https://user-images.githubusercontent.com/77480903/176109778-c21c7c96-d150-4e59-8418-03c17c8bda02.png)
而这两个 select 的 options 都是通过 edit 配置的 props 传入的，现有的 api 的情况下，我该如何灵活控制 props 传入的 options 呢？

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1028

事件 `onEdited` 参数已经包含当前 行的全部数据，即 `newData`，如下图所示。因此，不再新增获取行数据的 API。
<img width="429" alt="image" src="https://user-images.githubusercontent.com/11605702/176997300-b30da72d-7433-4d0f-8f9c-59260803b2c6.png">

**Comment by chaishi** [comment]
对于需求中提到的，Select 组件之间的联动，在 https://github.com/Tencent/tdesign-react/pull/1028 中已支持，待发布。

示例代码，如下：

<img width="815" alt="image" src="https://user-images.githubusercontent.com/11605702/176997343-0a80e86f-b706-43e2-a980-95016f2beef1.png">

**Comment by HQ-Lin** [comment]
0.36.2 fixed
