### ISSUE TITLE
[Table] 树形表格数据，父子节点关联选中缺少半选状态

### ISSUE THREAD

**Issue by lazybonee** [Tencent/tdesign-react#996]
### tdesign-react 版本

0.36.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-wn83mg?file=/src/demo.jsx

### 重现步骤

1.切换至父子关联选中模式
2.选中所有子节点

### 期望结果

父节点关联选中

### 实际结果

父节点并未勾选

### 框架版本

17.0.2

### 浏览器版本

Chorme(102.0.5005.115)

### 系统版本

MacOs

**Comment by chaishi** [comment]
关于父子关联选中，场景较为复杂，有以下几种业务场景：

- 1. 所有的行选中都只选中 叶子结点，不计入父节点
- 2. 所有行选中，无论是叶子结点，还是父节点，都需记入选中
- 3. 子节点全部选中时，是否直接替换为 父节点，或是直接保留全部子节点

类似于 Tree 组件的 valueType / valueMode 等功能。情况较多，需要专门找个时间集中处理。

**Comment by chaishi** [comment]
再次看这个问题，着实看不懂问题到底是什么。

就说选中 BUG，但是没有描述具体是个什么 BUG，太抽象了。需更多描述信息，否则无法处理。

**Comment by chaishi** [comment]
除了 中层节点的半选状态 没有开发，实在是看不出来什么问题。

https://user-images.githubusercontent.com/11605702/177005892-b99e6c4c-74e4-4186-b4bf-f07d8791e497.mov

**Comment by lazybonee** [comment]
![1656775207(1)](https://user-images.githubusercontent.com/11715201/177006515-a15f53fd-02b5-4737-b18d-8f1c41476733.png)
先全部勾选子节点的JQTEST10-JQTEST410，其父节点JQTest0没有做到自动关联选中。正常来说所有子节点被选中，那么就表示父节点也应该显示被选中状态。

**Comment by lazybonee** [comment]
> ![1656775207(1)](https://user-images.githubusercontent.com/11715201/177006515-a15f53fd-02b5-4737-b18d-8f1c41476733.png) 先全部勾选子节点的JQTEST10-JQTEST410，其父节点JQTest0没有做到自动关联选中。正常来说所有子节点被选中，那么就表示父节点也应该显示被选中状态。

**Comment by lazybonee** [comment]
> > ![1656775207(1)](https://user-images.githubusercontent.com/11715201/177006515-a15f53fd-02b5-4737-b18d-8f1c41476733.png) 先全部勾选子节点的JQTEST10-JQTEST410，其父节点JQTest0没有做到自动关联选中。正常来说所有子节点被选中，那么就表示父节点也应该显示被选中状态。



> 再次看这个问题，着实看不懂问题到底是什么。
> 
> 就说选中 BUG，但是没有描述具体是个什么 BUG，太抽象了。需更多描述信息，否则无法处理。

**Comment by chaishi** [comment]
[resolved in https://github.com/Tencent/tdesign-vue/pull/1115](https://github.com/Tencent/tdesign-react/pull/1028)

半选状态已支持，待发布

https://user-images.githubusercontent.com/11605702/177024719-29fdd088-3c6d-4fd1-88f8-dd8a82f2992c.mov

**Comment by chaishi** [comment]
问题已沟通清楚，移除中间信息，方便后续查问题

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue/pull/1115

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1142

**Comment by HQ-Lin** [comment]
0.36.2 fixed
