### ISSUE TITLE
[Table] 树形数据表格，选中子节点时，会导致父节点自动折叠

### ISSUE THREAD

**Issue by lazybonee** [Tencent/tdesign-react#999]
### tdesign-react 版本

0.36.1

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-hqtl77?file=/src/demo.jsx

### 重现步骤

![image](https://user-images.githubusercontent.com/11715201/176133163-9ebeb868-d873-4b0d-9186-9256c2bd7f41.png)
如图选中 子节点

### 期望结果

父节点保持展开

### 实际结果

![image](https://user-images.githubusercontent.com/11715201/176133298-fc409264-0618-46a9-a9f5-dd619bbdeea5.png)
父节点自动折叠

### 框架版本

React(17.0.2)

### 浏览器版本

Chorme(102.0.5005.115)

### 系统版本

MacOs

**Comment by chaishi** [comment]
印象中，这个问题在 Vue 中处理过，我迁过来

**Comment by chaishi** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/11605702/176990830-aa67d524-2fc5-4392-a0b5-60fa25884950.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-react/pull/1028

https://user-images.githubusercontent.com/11605702/176993067-26709f7d-44e7-47ad-88c8-87d84b06cbb7.mov

**Comment by HQ-Lin** [comment]
0.36.2 fixed
